### ISSUE TITLE
Sugerencia aumento del limite de cuentas por ip

### ISSUE THREAD

**Issue by Nepo23** [MithrandirCraft/MithrandirCraft#100]
Bueno abro este ticket para sugerir un aumento en el limite de 3 cuentas por ip a 5 cuentas por ip, esto significa una modificacion el la Norma 13, que puede ser resultado de una medida grave o mederada.

Motivos:
1) Regularmente los jugadores son solo un individuo por ip, pero hay familias, personas desadas o no desadas que les prestas internet  ya sea un cuarto que compartes con amigos, o con estudiantes, y esto sumar que todos juegan minecraft, mismo servidor, esto genera conflicto ala hora de jugar devido a la normativa, por lo que sugiero un aumento en la ip por cuenta para que tus compañeros y tu puedan jugar tranquilamente y disfrutar de las hermosas guerras XD.

2) Es claro que el mapa no es ahora, lo suficientemente grande, para mantenerte fuera de las areas de grifeos( Petamientos, Destruccion) de tu faccion, porlo que mantener una faccion alejado de que te rrompan tu patio intentando de entrar, es dificil,  como estrategia se puede mantener dos facciones para, ya sea cuidar equilibradamente tus cosas, para distraer a tus enemigos devido a que no sabe en cual faccion tienes los recursos buenos, y sin fin de estrategias que se te pueden ocurrir para controlar la situacion.

3) No por menos importante, devido a que es un problema poco citado y poco comunicado, pero no es falta mencionarlo si por alguna razon olvidaste tu contraseña y ya superaste el limite no podras jugar, o mas aun te banearan tu cuenta nueva o anterior devido a que estas comentiendo una falta grave o moderada ala normativa del servidor, solucion tener 1 cuenta por si las dudas.

Agradesco su tiempo por leeer mi sugerencia y espero una respuesta afirmativa o negativa pero de igual manera manifestando sus motivos.

Se aseptan comentarios positivos y negativos a esta sugerencia pero con el devido respeto que se merece gracias...

**Comment by BlackBeemo** [comment]
ticket duplicado, lo mueves tu o lo muevo yo?

**Comment by MithrandirCraft** [comment]
Nepo, si has seguido mis comentarios en el chat interno, sabrás que soy mas bien partidario de ser permisivo con la norma 13.

Lo que no podemos tolerar son las cantidades de registros exageradas... Pero seguiremos hablándolo por el medio habitual.

En cuanto al caso de las familias que juegan juntas, te hago saber que pueden acceder simultaneamente hasta 5 nombres a MithrandirCraft. Esto es información que no debería ser pública, o por lo menos no debería animar a nadie a multicuentear con más de 3 cuentas (No permitido).
