### ISSUE TITLE
Propuestas

### ISSUE THREAD

**Issue by xLebet** [MithrandirCraft/MithrandirCraft#101]
1- Incorporación de KOTH (King Of The Hill) (Rey de la colina)
Me gustaría proponerlo como un evento semanal, en el cuál las facciónes vayan a capturar el KOTH para así poder conseguir riquezas, yo pienso que esto fomentaría el pvp y daría un toque de competitividad al juego, no lo propuse antes por que sabía que sería un camping total del KOTH, pero ahora que todos empezamos de 0, sería una buena idea, a continuación dejo unos videos para que te des una idea de como es el KOTH https://www.youtube.com/watch?v=8C7ArjohY6A ahí se puede apreciar como es un KOTH, el objetivo es mantenerte en la zona roja cierto tiempo sin que te saquen de ahí para poder ganar el KOTH, como puedes ver es un servidor grande, por lo tanto pueden hacer KOTH's casi a diario, pero como somos menos yo por eso propongo que sea un evento semanal, https://www.youtube.com/watch?v=Sa-8T_w4kZk al principio podemos ver como una facción va a pelear por el KOTH, en el minuto 3:00 puedes ver como van a pelear contra otra facción, prefiero que lo veas y me digas que piensas,

2-Nuevas Maneras de conseguir esmeraldas.
Ahora que todos somos nuevos, pienso que conseguir esmeraldas a base de otros minerales, sería una manera de poder hacer un poco de ''inflación'' y daría otra alternativa a las cabezas de mobs

**Comment by MithrandirCraft** [comment]
Me gusta tu idea de KOTH. La valoraré. Quizá me permita hacer cosas interesantes para el servidor, además de las que ya hay planeadas.

**Comment by MithrandirCraft** [comment]
Tu segunda propuesta ya no me convence tanto. Creo que los jefes deberían dar más esmeraldas, cuando lo hagan habrá una inflación más merecida, por supuesto todavía queda trabajo en ese ámbito.

**Comment by BlackBeemo** [comment]
la propuesta de lebet combinado con un jefe que este ocupando el castillo ese lo aria aun mejor

**Comment by MithrandirCraft** [comment]
Se puede acomplejar bastante :)

**Comment by JessyelXD** [comment]
Salas de PvP por niveles serían los mismos mapas pero los más expertos no podrían atacar a los principiantes

o sino también podría ser que fuera como un faccion que puedas administrar quien está en esa sala 

También que al pvp todos tuviéramos la misma condición o kits de PvP por que las espadas que prenden fuego son malas con un golpe te mata que todos tuviéramos las mismas armas que en mi opinión es bastante injusto que un jugador experto (Con armas encantadas) mate a un jugador de dos golpes y el novato tenga que dar mas de 10 golpes es injusto...

**Comment by MithrandirCraft** [comment]
@JessyelXD Deberías abrir un ticket para ti mismo para comentar tu asunto.

En todo caso, he llegado a la conclusión de que no voy a aplicar tu sugerencia.

Realizar dicho sistema sería demasiado costoso temporalmente y complejo, requeriría un nivel de mantenimiento y trabajo que simplemente no creo valer la pena para su aplicación.

Las salas de PvP en MithrandirCraft estan destinadas a ser utilizadas con el equipamiento obtenido en Factions, y nada más. Son de libre acceso.

**Comment by JessyelXD** [comment]
que se pueda hacer un seguda (home) como /sethome2 y /home2
igual que el /sethome normal para poder tener dos casa espablesidas

**Comment by MithrandirCraft** [comment]
@JessyelXD Temas borrados, Abre un ticket individual y separado para cada una de tus sugerencias porfavor.

**Comment by SimplyAcke** [comment]
Este post no puede caer, la idea de lebet es buenísima (por mi parte) pero no sólo un KotH semanal si no un KotH final. Podríamos también hacer que cada x tiempo se cambie de mapa por ejemplo 3 meses o 5. Para dar las mismas oportunidades a todos los jugadores que llegan nuevos. El KotH final tiene como objetivo dar una ventaja a la facción ganadora para el siguiente mapa. Suele contener armaduras y espadas completas, bloques etc... Es algo interesante para fomentar el pvp y animar un poco a las factions a que crezcan con un motivo.

**Comment by krazlas1** [comment]
Creo que esta idea debería de ser evaluada, se ha quedado en el olvido y tiene mucho potencial.

**Comment by MithrandirCraft** [comment]
No ha quedado en el olvido :P Solo estoy estudiando la forma mas eficiente de implementar esto.

El ticket sigue abierto. Todas las ideas de Lebet acabarán siendo implementadas, un ejemplo: Los duelos.

**Comment by MithrandirCraft** [comment]
Implementado.
