### ISSUE TITLE
Insultos|Friend

### ISSUE THREAD

**Issue by gamemaker26** [MithrandirCraft/MithrandirCraft#102]
Pruebas de la denuncia:
![2015-10-02_17 02 55](https://cloud.githubusercontent.com/assets/14942575/10249954/71de7d14-6928-11e5-8a38-4f9620e07817.png)

**Comment by MithrandirCraft** [comment]
Esta persona no sabe comportarse. Le hemos aplicado un ban permanente de IP, por este y otros motivos.

También nos ocuparemos de limpiar sus cuentas.
