### ISSUE TITLE
Espadas/arcos con descripciones personalizadas la tienda   

### ISSUE THREAD

**Issue by sadow2811** [MithrandirCraft/MithrandirCraft#103]
esta idea me surgió tras ver que cuando una espada de la orden o del votante sale en el chat la descripción de la misma figura con ella y es algo curioso, muchos de los jugadores veteranos del servidor solemos tener una espada especial en nuestro corazón :3 así que mi propuesta seria poder comprar en la tienda del servidor una espada con una descripción personalizada o incluso con un color de nombre distinto al resto, en mi opinión creo que gustaría bastante a la comunidad ademas de no ser muy difícil usar un comando que genere una descripción tanto en espadas como en arcos y aun mejor, no requeriría de ningún plugin extra para el servidor. atentamente Sadow2811 ^_^

**Comment by MithrandirCraft** [comment]
Esta idea la he leído anteriormente. Fuiste tu quien lo sugirió?

El problema es que al utilizar el sistema de Enjin para la tienda, no estoy muy seguro que podamos incluír un imput por parte del jugador, para confirmar que mensaje quiere en su espada.

Además, a no ser que el color sea distinto de morado, quizá sería posible con esto burlar algunos de los intercambios que tenemos previstos y que requerirían el intercambio de armas con "Lore" > mensajes.

Lo valoraré, quizá pueda aplicarse, pero no prometo nada.

**Comment by sadow2811** [comment]
si, lo sugerí en el antiguo foro hace algunos meses, pero no estuve muy pendiente de las respuestas y opiniones y quise reabrir el tema esta vez estando mas atento.

**Comment by MithrandirCraft** [comment]
Lo siento, pero con descripciones custom sería posible burlar algunos intercambios. (Entra en conflicto con la configuración del servidor.)
