### ISSUE TITLE
Los templos marinos no se han generado. (¿Has visto algun templo marino? ¡Dinoslo!)

### ISSUE THREAD

**Issue by alucardjhon** [MithrandirCraft/MithrandirCraft#104]
hola buena tardes: 
me comunico para reportar o preguntar si los templos de mar estan en fallas o lo quitaron a beneficio...
espero su respuesta... me encanta el server "pase lo q le pase seguire" jejej nos vemos

**Comment by MithrandirCraft** [comment]
Puede que los archivos NBT relacionados con la generación de estructuras de templos marinos estuviesen corruptos.

He eliminado el archivo para que vuelva a generarse, pero es bastante probable que los templos que deban aparecer no lo hagan si las chunks donde aparecerían ya han sido cargadas.

Si alguien ve algún templo marino, que lo comunique aquí.

**Comment by alucardjhon** [comment]
buenas tardes;
me comunico para reportar que decide averiguar y encontre un templo de mar  ala mitad, lo verifico  farmex 
bueno, nos vemos

**Comment by MithrandirCraft** [comment]
Ya veo.
Lo mas provable es que ese templo se haya generado a medias, ya que alguien estuvo cerca de él.

Las chunks que fueron cargadas antes de mis ajustes quizá no hayan podido aplicar la información sobre templos marinos. Pero las chunks intactas si, por lo cuál, en las chunks que nunca cargaron si apareció una sección de un templo, mientras que en la sección renderizada no.

Esto podría explicar tu el suceso del "Medio Templo".

En cualquier caso, sigan buscando mas templos por favor. No creo que todos los templos se hayan generado con mal funciones como esa.

**Comment by MithrandirCraft** [comment]
Tema solucionado.
