### ISSUE TITLE
Reporte  por Banear sin Pruebas

### ISSUE THREAD

**Issue by alucardjhon** [MithrandirCraft/MithrandirCraft#105]
Buenas Tardes: 
Me presento Soy: Alucard
Le comunico mi reporte sobre un baneo no correspondido a un integrante de mi Faction
Nombre de Faction: Arcoiris
Nombre del jugador baneado: Gatiko
Nombre del jugador a reportar: Nadelina
Fecha: 2015-10-02 21:18:41	
Sección de /rules: Por uso de xray a un jugador
Comentarios adicionales y detalles:
como muestra la imagen 01: 
![gatiko pikando 01](https://cloud.githubusercontent.com/assets/14955811/10265059/0763cd3e-69f7-11e5-864a-3b7fc08c8634.jpg)

*El jugador gatiko esta picando dentro del Faction de Arcoiris y no en minas. 
*Esos minerales fueron picados con toke de seda en mas 7 horas de esfuerzo y tiempo en el bioma de "Extreme hills"
*Los jugadores q picaron cada mineral con toke de seda, para picarlo despues fueron:  Alucard,Johanna,Wolfdark,Luna.

imagen 02: Lugar donde fuimos a pikar
![lugar donde fuimos a pikar](https://cloud.githubusercontent.com/assets/14955811/10265118/058f121e-69f9-11e5-8a98-72189793759d.jpg)

imagen 03: Lugar donde pusimos una base de la mina
![lugar donde pusimos una base de la mina](https://cloud.githubusercontent.com/assets/14955811/10265126/819d262a-69f9-11e5-924d-fa83a8887a3e.jpg)

...espero que haya entendido y resuelva esta injusticia, 
Puede restablecerle la cuenta del jugador gatiko... 
"tuvo que crearse otra cuenta a un despues de ser baneado para seguir en el server" :)  
espero su respuesta y solucion al respecto

**Comment by MithrandirCraft** [comment]
Buenas noches.

Muchas veces no nos fijamos en la actividad del jugador, sino tan solo en la cantidad de vetas que mina.

Nos hemos fijado en que uno o varios jugadores de la facción tienen indicios de estar usando xrays.
Tal como se establece en la normativa, en ocasiones facciones enteras pueden ser penalizadas por la actividad de individuos específicos.

Voy a dejar algo claro: En vuestra facción, una o más personas están haciendo trampas, y eso lo tenemos muy claro. Quizá creáis que esa persona esté limpia, o no os comuniquéis demasiado entre vosotros, pero el asunto es que cuando hay un xrayer, otros miembros de la facción pueden pagar el precio, y eso es responsabilidad de todos y cada uno de los miembros.

Los tramposos no deben ser tolerados.

Al realizar esta técnica, en la cuál un jugador mina todas las vetas, estáis cargando la responsabilidad de los xrays a otra persona. En este caso, al ser de la misma facción, la consideramos un cómplice, y carga con todo el peso de las consecuencias.

**Comment by alucardjhon** [comment]
hola; entonces es ilegal pikar tantas vetas unidas? aunqe esten guardadas porque eso fue lo q hicimos...juntamos las vetas o blokes de minerales de tanto tiempo para que despues lo piquemos con seguridad? en nuestra faction jeje

**Comment by alucardjhon** [comment]
la gente q usa xray no se molesta x estar mas  de 7 horas con esfuerzo pikando solo debe pikar donde supuestamente estan los minerales... en my factions no usamos ese programa xq somos muy unidos en confiar ya que sabemos que si uno usa eso puede joder a la faccion

**Comment by alucardjhon** [comment]
en ningun momento el jugador gatiko fue a minar con alucar y johanna y luna y wolfdark... solo entro normal y le pedimos q nos pike como a cualquiera los minerales xq nos salia el mensaje del limite, eso por eso q le envie una foto donde el jugador gatiko picaba los minerales dentro la faccion

**Comment by alucardjhon** [comment]
yo he estado mas de 9 veces q jugue de cero en el server y he pikado mas del trilpe q esto... me salian ese cartel del limite aun asi nunca me dijieron nada xq lo hacia legal y bonito con tiempo y esfuerzo jeje
my officer johanna dice ¿q cual es el limite de pikar x dia los minerales para no causar indicios de ilegales?

**Comment by alucardjhon** [comment]
solo espero que se solucione este error ya q no se cometio falta ni se uso xray ya q lo desmuestra la imagen con fecha y pruebas al respecto... subire mas fotos si es necesario para aclarar su dudas ,
gracias x la respuesta lo saluda alucard/johanna de la faccion arcoiris ...

**Comment by alucardjhon** [comment]
entonces como indica usted que el mod nadelina lo baneo al jugador gatiko x usar xray, y tan solo estaba pikando los minerales en la faccion arcoiris. puff espero su respuesta... no tengo problema en decir o mostrar fotos para q no haya injusticias en my faccion atte..

**Comment by BlackBeemo** [comment]
Porqué esta ban gatiko?

El día mismo del incidente decidí resetear la herramienta para detectar xrayers. Pocos minutos después estos dos usuarios Wolfdark,Luna les salta el limitador. Horas después de esto vuelvo a comprobar las estadísticas y tenían unos valores de minado muy sospechosos.

Nos pueden contar las historias que quiera pero se exactamente como como están distribuidas las menas de esmeraldas en 
extreme hills y nadie puede conseguir tantas cantidades como Wolfdark,Luna en un tiempo récord como ese.

La razón de todo este alboroto no viene de lo sucedido estos últimos días, esto es un cumulo de indicios durante varios meses. Johana era una de los usuarios con mas cuentas del servidor antes del reset solo superado por una persona, por ese entonces no baneabamos ni eliminábamos a multicuentas.

El día en que johanna decidió crearse una casa nueva os desplazasteis un grupo de personas a una área cercana a mi casa, durante esos días empezaron a aparecer túneles característicos de un xrayer 
pero por ese entonces yo no tenia rango mod y no tenia las herramientas suficientes para actuar.

Alguien de vosotros tiene xray y uno esta pagando las consecuencias por ello, si no quieren ensuciar reputaciones de otros usuarios no usen hacks.

**Comment by alucardjhon** [comment]
hola blackbeemo estos dos jugadores eran alucard y johanna jeje puede ir al "BIOMA EXTREME HILLS+" y puedes comprobar el lugar esta lleno de minerales mucho mas de esmeraldas jejej

**Comment by alucardjhon** [comment]
tus indicios fallan cuando una persona pikan mas de lo normal aunque se haya pasado horas y horas pikando tuneles recto como dejamos ese lugar trantando de buscar minerales o esmeraldas... yo solo reporte sobre el baneo injusto del jugador gatico...

**Comment by alucardjhon** [comment]
yo como jugador en el server he vivido y jugado mas de 9 veces de zero y he pikado con esfuerzo y tiempo mas del triple de esto y no tuve problema de ninguno mod o mith xq siempre decia q lohacia "legal y bonito"

**Comment by alucardjhon** [comment]
solo pikabamos en el piso 4 11 16 como indica wikipedia para conseguir esmeraldas diamantes minerales... el "bioma extreme hills+" la mayoria sabe q esta lleno de minerales mas de normal eso deberia saberlo recuerde q ahy dos extreme hills uno normal y uno con mas minerales jajaj y con esa info fuimos a minar...

**Comment by alucardjhon** [comment]
en ningun momento estuvo gatiko minado o pikando con nosotros solo le dijimos q entre a la facccion y que nos ayude a pikar los minerales juntados jajaj y al final notamos q usted lo baneo x indicios invalidos
