### ISSUE TITLE
falta de respeto que un mod banee sin pruebas y solo con indicios 

### ISSUE THREAD

**Issue by alucardjhon** [MithrandirCraft/MithrandirCraft#106]
hola blackkbeemo o nadelina saludos ... 

hola blackbeemo estos dos jugadores eran alucard y johanna jeje puede ir al "BIOMA EXTREME HILLS+" y puedes comprobar el lugar esta lleno de minerales mucho mas de esmeraldas jejej

tus indicios fallan cuando una persona pikan mas de lo normal aunque se haya pasado horas y horas pikando tuneles recto como dejamos ese lugar trantando de buscar minerales o esmeraldas... yo solo reporte sobre el baneo injusto del jugador gatico...

yo como jugador en el server he vivido y jugado mas de 9 veces de zero y he pikado con esfuerzo y tiempo mas del triple de esto y no tuve problema de ninguno mod o mith xq siempre decia q lohacia "legal y bonito"

solo pikabamos en el piso 4 11 16 como indica wikipedia para conseguir esmeraldas diamantes minerales... el "bioma extreme hills+" la mayoria sabe q esta lleno de minerales mas de normal eso deberia saberlo recuerde q ahy dos extreme hills uno normal y uno con mas minerales jajaj y con esa info fuimos a minar...

en ningun momento estuvo gatiko minado o pikando con nosotros solo le dijimos q entre a la facccion y que nos ayude a pikar los minerales juntados jajaj y al final notamos q usted lo baneo x indicios invalidos

wofdark era alucard
luna era johanna
jaja tus indicios fallan  saludos y recuerda q el mapa es igual al de antes 

si tu herramienta indica q yo pike mas del triple de veta de lo norma es porque se como minar recuerda q no soy nuevo estoy hace 10 meses jugando y tengo experiencias en minar sin usas cosas ilegales q no me interesa... saludos nadelina o mith espero su respuesta

**Comment by alucardjhon** [comment]
yo espero respuesta solo del señor admin mith...

**Comment by sadow2811** [comment]
el administrador es eficaz pero no creo que te responda en 20 minutos a las 2 de la mañana XD dale al menos 24 horas. respecto a tu problema el sistema no se suele equivocar puesto que también cuenta el promedio de piedra (si no lo han cambiado) y de esa forma se puede saber fácilmente si se a usado xray o no, también podría ayudar a tu inocencia enseñarle el lugar donde minaste, aveces por la forma de las galerías se ve claramente si se usaron hacks o no, si son túneles rectos y simétricos o si van directamente hacia las menas.

**Comment by alucardjhon** [comment]
jaja le dare tiempo pero q no lo cierren este ticket asi  nomas sin causa sabiendo q tengo la razon y esta equivocada nadelina jeje

**Comment by MithrandirCraft** [comment]
@alucardjhon Porsupuesto que tienes razón. Pero parece que todavía no has entendido nuestro razonamiento. Lo voy a intentar simplificar al máximo:

1. No es necesario proporcionar pruebas a los jugadores afectados (Aunque si nos basamos en "pruebas") para realizar una expulsión. Realizamos nuestras expulsiones siempre y cuando creamos que los indicios apuntan a una violación de la normativa. El/Los jugadores afectados podrán siempre debatir su expulsión en este sistema de tickets.

2. En tu facción, uno o mas miembros están usando xrays (lo sepáis o no todos), y allí es donde la habéis cagado por el simple hecho de permanecer en esa facción corrupta, da igual que no conozcáis a los integrantes. En el momento que "gatiko" minó esos diamantes no hizo ningún cuestionamiento sobre su procedencia, y se puso a minarlos todos él, se llevó las ostias el solo.

El hecho de minar tantas vetas y con tan poca piedra registrada, en si ya causa 2 reacciones. Primeramente, hace que nuestras estadisticas se disparen y muestren rates de minería muy exagerados. 0 piedras minadas y más de 120 diamantes, por ello no aconsejamos farmear, o minar todas las vetas de un grupo para evitar meterse en problemas. Y segundamente, valorar de donde proceden esas vetas minadas, en este caso, minadas por otros miembros que muestran indicios de haber estado usando xrays.

Deacuerdo. Y ahora pensarás, que importa eso? Gatiko es inocente! Pues parcialmente si, Gatiko es inocente, pero pertenece a una facción donde hay miembros (indefinidos) que están usando xrays, como tal, voluntario o involuntariamente esta siendo complice. Y al haberse llevado él todas las vetas extraídas ilegalmente, se lleva toda la culpa en esta situación. 

La alternativa es expulsar a todos menos a gatiko, después de habernos mostrado que ciertamente, se ha llevado toda la culpa injustamente al minar todas las vetas de otros jugadores malintencionados. Pero creo que lo mejor que podéis hacer es esperar a que termine su expulsión.
