### ISSUE TITLE
prueba de como se encuentra minerales sin usar tales programas ilegales 

### ISSUE THREAD

**Issue by alucardjhon** [MithrandirCraft/MithrandirCraft#107]
Buenos Dias
soy Alucard:
ME COMUNICO SOLAMENTE AL SEÑOR ADMIN MITH:
Me costara entender, hasta saber cada detalle para aclarar y no manchar my Nombre o de los integrante de la Faccion... 
"sabado 3 octubre x la tarde  " seria ayer 
Bueno  esta vez fui al lugar donde picamos y volvimos apicar pero solo la piedra del lugar han estado todos de la faction arcoiris ayudando q no se necesita xray si puede ir al bioma dicho, Hicimos que FARMEX  un mod lo verificara en vivo y directo lo viera,pikara y vio q el lugar estaba llenos de minerales mas de lo normal subire fotos para dicha prueba, espero que no se emocione como otros, ya que asi esta ese bioma muy concentrado de minerales no es culpa de nosotros ni de ustedes es el bioma jajaj mega minerales hay
![2015-10-04_01 47 20](https://cloud.githubusercontent.com/assets/14955811/10267773/68a6acb0-6a79-11e5-955f-c46f00373a2b.png)

![2015-10-04_01 48 42](https://cloud.githubusercontent.com/assets/14955811/10267775/73e48886-6a79-11e5-830c-4dc1b65bd5f9.png)

![2015-10-04_01 50 15](https://cloud.githubusercontent.com/assets/14955811/10267776/76f47b62-6a79-11e5-880c-66e3f6c6d51a.png)

![2015-10-04_01 51 13](https://cloud.githubusercontent.com/assets/14955811/10267777/7a1c59b8-6a79-11e5-86b9-c1e8f077d505.png)

![2015-10-04_01 52 06](https://cloud.githubusercontent.com/assets/14955811/10267778/7bcd86ec-6a79-11e5-9078-b1ca473f2677.png)

![2015-10-04_01 53 40](https://cloud.githubusercontent.com/assets/14955811/10267779/7ecf7d46-6a79-11e5-8203-4a08da789aa8.png)

![2015-10-04_01 54 46](https://cloud.githubusercontent.com/assets/14955811/10267780/81609c34-6a79-11e5-8f02-c837530ed13a.png)

y por ultimo tema me podria dar los nombres de my faccion que insinuan que usan xrays o programas ilegales... para darle su respuesta al respecto... gracias espero su respuesta saludos

**Comment by BlackBeemo** [comment]
Ustedes ganan, le retiro el ban a gatiko por falta de pruebas.
