### ISSUE TITLE
"Proxy detectado" falso positivo (¿Tienes este problema? Reportalo aquí, te intentaremos ayudar!)

### ISSUE THREAD

**Issue by aaronagullo** [MithrandirCraft/MithrandirCraft#108]
Me aparece esto: https://i.gyazo.com/0328e6e44489c39877a4b1fd97d5f6f0.png
 ¿Qué hago?

**Comment by MithrandirCraft** [comment]
Oh no.

Bueno la mejor solución es conseguir entrar con una IP distinta, lee las faq's en este enlace:
www.mithrandircraft.es/faq

Si no consigues solucionarlo dimelo.

**Comment by aaronagullo** [comment]
Nada, no me deja.

**Comment by MithrandirCraft** [comment]
Me sorprende que habiendo cambiado de IP no lo hayas podido solucionar.
El problema es con tu IP. Estará alistada en alguna de estas 3 páginas como "IP insegura", si consigues que la desalisten (por petición), dejarás de tener problemas para acceder:

    http://www.shroomery.org/
    http://www.stopforumspam.com/ 
    http://yasb.intuxication.org/

Si no consigues acceder a nuestro servidor, tengo una posible una solución puntual que te permitirá entrar al servidor, el problema es que solo te permitirá acceder con uno o varios nombres que tu determines. (Si quieres te los añado en lista blanca para que con esos nombres no tengas problemas para acceder.)

En todo caso, este tema me gustaría revisarlo mas a fondo... ya que nunca he entrado muy minuciosamente en este error.

**Comment by aaronagullo** [comment]
Aquí http://www.stopforumspam.com/  aparece mi IP marcada como SPAM. Por lo que se ve he heredado la IP de alguien que hacía spam. Ya me he puesto en contacto para que me retiren de la lista, aviso por aquí cuando me retiren de la lista.

**Comment by MithrandirCraft** [comment]
Genial, esa es la mejor opción :) Vigila no sea que estés alistado en alguna página.

Si tardan mucho en desbloquearte podemos poner tu nombre de usuario en lista blanca.

**Comment by FearMagix** [comment]
hola tengo ese mismo problema y encontre mi ip enlistada pero no tengo idea de como hacer para que la quiten de la lista
ayudenme porfa este es mi servidor favorito

**Comment by MithrandirCraft** [comment]
@FearMagix En que pagina estas alistado? Ten en cuenta que puedes evadir esta situación cambiando de IP.

**Comment by FearMagix** [comment]
y como hago para cambiar mi ip

**Comment by MithrandirCraft** [comment]
Prueba esto: http://www.taringa.net/post/hazlo-tu-mismo/15605925/Como-cambiar-la-IP-Facil-CMD.html

**Comment by FearMagix** [comment]
ya lo intente varias veces pero no me funciona
no tienes otra forma

**Comment by MithrandirCraft** [comment]
@FearMagix Si tenemos otra forma, pero es menos eficaz y más puntual. Consiste en otorgar acceso a tu nombre con la IP que utilizas. Sin embargo, no podrás acceder con mas nombres excepto ese mientras sigas usando tu IP. Por ello, la mejor solución es que consigas cambiar tu IP.

Si llamas a tu operadora es bastante provable que lo hagan por ti, puedes indicarles que tienes problemas porque tu IP esta marcada como insegura en páginas de IP's malignas.

Recuerda que este filtro existe por una razón importante, tienes toda la info en las FAQ's

**Comment by FearMagix** [comment]
si por favor aun que solo use ese nombre

**Comment by MithrandirCraft** [comment]
He colocado a "FearMagix" en una lista blanca de acceso. Ahora en teoría no deberías tener problemas con ese nombre para entrar a MithrandirCraft.

Pero como ya he dicho, siempre que intentes entrar con cualquier otro nombre y estés usando la misma IP que ahora, no podrás entrar.

Con FearMagix no debería haber problema pero. Procura cambiar tu IP o seguirás teniendo problemas.

Si eres de sudamerica: És bastante común que las IP's sudamericanas estén marcadas como IP's malignas, por alguna razón.

**Comment by FearMagix** [comment]
Mith e encontrado una cosa sobre mi ip que me dice esto 

Tu conexión NO pasa por un proxy caché. 

aque se refiere con eso

**Comment by MithrandirCraft** [comment]
https://es.wikipedia.org/wiki/Proxy

Resumidamente, usar un proxy significa utilizar una conexión ajena para obtener acceso a un servicio.

Por lo tanto, no estas usando un proxy según ese mensaje.

A pesar de ello, el problema por el cuál no puedes entrar a MithrandirCraft no es este, sino que simplemente tu IP ha sido declarada maliciosa en una de las páginas web que te he mostrado. Y por ello tienes problemas para entrar.

**Comment by MithrandirCraft** [comment]
Todavía no puedes entrar? Te puse en una whitelist especial.

**Comment by FearMagix** [comment]
aun no me deja entrar porque e buscado mi ip pero me aparece otro correo y otro nombre de usuario pero es de mi pais 

sera que erede su ip

**Comment by FearMagix** [comment]
ya pude resolver el problema y ya puedo entrar

**Comment by MithrandirCraft** [comment]
@FearMagix Me alegra mucho leer eso :) Espero que no te vuelva a ocurrir.

Como lo has arreglado?

**Comment by FearMagix** [comment]
utilise el programa Hotspot Shield y esa fue la solucion

**Comment by vampiredrem** [comment]
HOLA :) como soluciono los problemas de proxy, ya hice todo lo comentado arriba :/

**Comment by vampiredrem** [comment]
Tengo problemas con lo de proxy, e echo todo lo que estaba en el ticket cambiar la ip verificar si esta en una lista negra, lo de reiniciar, apague mi note, borre el server y lo puse otra vez ya no se que mas hacer aun sale el mensaje de proxy detectado, antes del ultimo mantenimiento de varias horas podía entrar sin ningún problema, desde que el server esta en ON nuevamente ya no puedo entrar.
 gracias de antemano.

**Comment by MithrandirCraft** [comment]
@vampiredrem

Ahora mismo me temo que no puedo hacer nada inmediato para ayudarte... Tenemos que incorporar un sistema de "lista blanca" eficaz para aquellos casos puntuales que tenéis falsos positivos.

Le echaré un vistazo ahora, en cualquier caso, deja aquí tu nombre de usuario y intentaré garantizarle acceso (Si lo consigo, te lo indicaré aquí de inmediato.)

Lo que está claro es que, si consigues cambiar tu IP, podrás acceder al servidor. El problema es que tu IP es considerada "maligna" por ciertas páginas.

**Comment by vampiredrem** [comment]
Pero como maligna si antes podía entrar cuando quería :/ .. mi Nick es ( VampiRe ) quizás ya no podre jugar mas :/

**Comment by MithrandirCraft** [comment]
@vampiredrem Si no eres capaz de cambiar tu IP externa manualmente, quizá puedas llamar a tu proveedor de internet para solicitarles un cambio.

**Comment by vampiredrem** [comment]
okey tengo 11 años no entiendo algunas cosas pero si hice todas las opciones que dio a los otros jugadores.

**Comment by vampiredrem** [comment]
El problema es completamente en tu server e probado con mas de 15 otros y en todos me dejan entrar, desde el mantenimiento esto cambio. ojala puedas hacer que pueda entrar otra vez, esperare tu respuesta :) .
gracias de antemano

**Comment by MithrandirCraft** [comment]
@vampiredrem Por supuesto que el problema es en MithrandirCraft. Utilizamos un filtro bastante exigente que detiene bots, comparando las IP's de los usuarios con listados de IP's maliciosas.

Todo esto está explicado en las faq's

**Comment by MithrandirCraft** [comment]
@vampiredrem Voy a necesitar tu IP para permitir acceso.

Puedes enviarnosla a: mithrandircraft@hotmail.es
En el caso de que te importe darla públicamente aquí (Nunca lo recomendaría, pero puedes hacerlo.)

**Comment by vampiredrem** [comment]
Ya esta echo avísame si te a llegado por favor :)

**Comment by MithrandirCraft** [comment]
@vampiredrem Listo, intenta entrar ahora.

**Comment by vampiredrem** [comment]
Ya ingrese :D ... ojala perdure no como ayer, gracias Mith fuiste de gran ayuda ! :)
