### ISSUE TITLE
LA GRAN DISCULPA POR USO DE HACKS (xXxDarkSoulxXx)

### ISSUE THREAD

**Issue by TheWildeRrNess** [MithrandirCraft/MithrandirCraft#109]
Les pido PERDÓN por uso de hacks en el servidor, el uso de hacks se provoca porque siempre que te petan tu fac pierdes todo y necesitas mas para recuperarte pero reconosco que esta muy mal el uso de hacks

**Comment by TheWildeRrNess** [comment]
Nadelina dame mis pantalones vitales >:v pls

**Comment by BlackBeemo** [comment]
El staff de mithrandircraft discutira lo sucedido con tu amigo, pronto tendran una respuesta.

**Comment by TheWildeRrNess** [comment]
ok gracias pero dame mis pantalones pls <:v

**Comment by MithrandirCraft** [comment]
Saludos. Parece que la cuenta que detallas en el titulo no se encuentra baneada.
Aceptamos tus disculpas, y por tu iniciativa podríamos haber reducido tu tiempo de expulsión si fuese existente.

Procura leer y interiorizar la normativa: www.mithrandircraft.es/normas
