### ISSUE TITLE
No puedo logearme, atrapado en un portal del nether

### ISSUE THREAD

**Issue by xJedax** [MithrandirCraft/MithrandirCraft#117]
Me quedé bloqueado en un portal del Nether, me tuve que desconectar. Ahora estoy atrapado en un portal del nether y no puedo logearme ni hacer nada. Mi nombre en el servidor es Jeda

**Comment by MithrandirCraft** [comment]
Porfavor, indica tus coordenadas.

**Comment by xJedax** [comment]
-32,004 / 70 / -317,685   en el nether

**Comment by xJedax** [comment]
-32,004 / 70 / -317,685  en el nether

Date: Sun, 25 Oct 2015 11:33:59 -0700

**Comment by MithrandirCraft** [comment]
Creo que podrías haber salido de allí tu mismo, rompiendo las paredes, pero hemos destruido el portal para ti :)
