### ISSUE TITLE
Broken leashrange + MM - Spawner connection

### ISSUE THREAD

**Issue by alucardjhon** [MithrandirCraft/MithrandirCraft#118]
buenas tardes:
soy alucard, Officer01 de la faction: INFINITY

le comunico al mith que solucione, al parecer el maestro boss, esta fuera de su domo... 
ajaja, lo vi en el pueblo, y le lleve a pasear...

bañando, paseando al maestro boss jaja
![banando paseando al maestro jaja](https://cloud.githubusercontent.com/assets/14955811/10756481/163965f0-7c83-11e5-8e4f-00634621c88c.png)

**Comment by MithrandirCraft** [comment]
Nop, es un nuevo bug. Tiene que haber un bug nuevo cada temporada.
