### ISSUE TITLE
Sugerencias para los rangos vip's

### ISSUE THREAD

**Issue by RoronoaOwlerCity** [MithrandirCraft/MithrandirCraft#12]
Saludos Mith.
Este ticket es nada más para un sugerencia, que se me ha animado sin querer dañar la política del servidor, sólo como una posible idea para mejorar los ingresos al servidor y contar más o menos el porque hago esta sugerencia. Podemos observar, como es obvio, que en el servidor solo hay dos rangos para los donantes, y bueno, yo veía 2 donantes del rango VIP en los últimos meses y 1 con rango VIP + (Nepo_23 y Jshacks) y (Thraiin) respectivamente.
Entonces mi sugerencia es que, no se remuevan estos rangos, sino que se agregue más variedad para los jugadores con ganas de donar al servidor, mi experiencia en otros servidores y las diversas opiniones que he observado es que a la gente les gustan los "Kits"  entonces, sino es mucha complicación, porque consto de ignorancia de si es complicado poner más rango vip's, entonces, si no es muy difícil  (porque no quiero proponer algo complicado y ese tipo de cosas) pienso que se podrían agregar más rangos, diversos rangos, que llamen la atención de las personas (no es que esto no los hagan, pero hay diversos gustos). Entonces, el porque que sugiero esto, es porque veo que la media está subiendo, ahora por las tardes en mi país veo hasta 30 players, y esperemos siga subiendo, entonces entre más jugadores hay, más posibles donantes para que haya más fondos para el servidor. 
Mi propuesta es que haya estos rangos ya implementados , y otros rangos como digamos...Kit hierro, que sea una armadura de hierro encantada y comida  y herramientas de hierro. O kit diamante...una armadura de diamante y sus herramientas y así, lo que se ocurra...kit protección4...una armadura protección 4, comandos especiales (lo que ya hay en los otros rangos), que se les recargue cada día, o 2 días, 3 días, etc y cosas que consideres tú de acuerdo a los precios....Claro, no es mi intención proponer algo que sea demasiado ventajoso para un donante y que los novatos salgan afectados, algo sencillo pero a la vez llamativo  (como digo, no quiero ofender ¿no? solo decir que hay diversos gustos). 
Nunca he sido muy a fin a cualquier tipo de ventaja de esta manera, no es mi intención proponer algo que sea para beneficiarme yo mismo, me gusta conseguirme lo mio o pedirle a Lebet de sus chest o:! xd no,no, pero...me parece que hay gente que les gustan los rangos de este estilo y están dispuestas a donar y ahora con más players me parece que vendrían bien más rangos de donantes de ser posible. 
PSDT: No sé si esto está en contra de tu política a las aspiraciones de los rangos de donantes, pero de ser así, espero no sea una sugerencia que parezca destructiva, es con el fin de aportar una pequeña idea ^^

**Comment by RoronoaOwlerCity** [comment]
Ehm, se me ha ocurrido algo, podría ser retocados o implementados a manera de la jugabilidad del servidor, a eso me refiero con los boss y mobs que no se encuentran en otros servidores...Podría ser algo así como que los kit's , no sean tanto a lo survival y eso así de simple como yo te lo sugería en la primer publicación, sino que lo que se me ocurre es que pueden ser kit's derivados de los jefes del servidor, exceptuando aquellos que sean demasiado buenos, digamos.
"/Kit vital" que podría ser , (lo digo como ejemplo: Espada de la orden y armadura de diamante encantada con protección 1  y que al usuario le de 2 o 3 corazones más) 
Algo así se me ocurre u otros encantamientos, a criterio eso. Porque hay que también que reconocer, por lo menos a mí me gustan mucho los jefes y un kit que sea algo parecido al modelo aventura del servidor. 
Saludos.

**Comment by MithrandirCraft** [comment]
Cada jefe suele incorporar ya su propio "set" de armas o armaduras.

Falta incorporar información en la web acerca de estas armas, pero no tengo intención de que sean de fácil obtención.

No creo que este tipo de armas sean apropiadas para entregar a rangos vip.

En hunger games y próximamente skywars también se entregarán kits seleccionables de donación, pero no creo que sea buen momento para hacer esto, ya que hunger games no se llena todavía, y skywars necesita tiempo para funcionar de forma estable.
