### ISSUE TITLE
Lenguaje inapropiado jugador vegetagamer9

### ISSUE THREAD

**Issue by xJedax** [MithrandirCraft/MithrandirCraft#120]
Reportador: Jeda

Jugador reportado: vegetagamer9

Fecha: 30/10/2015  16:50 aprox.

Lenguaje ofensivo e inapropiado.
![vegetagamer9 2](https://cloud.githubusercontent.com/assets/15312847/10850834/f877fa20-7f27-11e5-9602-9a632e85962b.jpg)
![vegetagamer9 3](https://cloud.githubusercontent.com/assets/15312847/10850836/f87dbb36-7f27-11e5-8d01-ba47c831a3de.jpg)
![vegetagamer 9 1](https://cloud.githubusercontent.com/assets/15312847/10850835/f87bd6ea-7f27-11e5-8671-6154080a7898.jpg)

**Comment by MithrandirCraft** [comment]
Buenas tardes.

Hemos aplicado una expulsión (corta) al jugador. Esperamos que con esto aprenda la lección.

Para futuras situaciones en las que recibas insultos, recurre al comando /ignore
