### ISSUE TITLE
Los moderadores y el entorno de juego. ¿Disponen de ventajas? (Aclaración oficial)

### ISSUE THREAD

**Issue by xJedax** [MithrandirCraft/MithrandirCraft#121]
reportdor: Jeda

Reportado: rafaelox24

fecha: 1 nov 2015 4:23

me estaba bombardeando la fac entre mucha gente y segun el moderador rafaelox24 el cogia el tnt del creativo. Esto hacen los mod?

![rafaelo](https://cloud.githubusercontent.com/assets/15312847/10867083/82f10b6e-8050-11e5-9c93-22343423b89b.jpg)

**Comment by MithrandirCraft** [comment]
![screenshot_1](https://cloud.githubusercontent.com/assets/6623704/10868889/44f37106-809d-11e5-9f8e-a12ae7dd7ebf.png)

Esta es una sección de la MOTD que recibes cada vez que entras a MithrandirCraft.

Te lo aclaro: Los moderadores son también jugadores ofensivos, esto significa que a pesar de ejercer sus obligaciones de moderación, puedes encontrartelos en el mundo de Factions como jugadores normales ofensivos.
En ningún caso un moderador tendrá ventajas sobre los demás jugadores en ninguna situación durante el juego. Eso incluye "Creativo", un modo de juego que NO necesitan y del cuál NO disponen para ejercer sus obligaciones de moderación.

Puedes confiar en un moderador para: 
   -Comentarle y Reportarle actividades contrarias a la normativa. 
   -Solicitar contacto con administración (Aunque en estos casos tu mejor opción es abrir un ticket)
   -Comentarle asuntos técnicos sobre el servidor.

No confíes nunca en un moderador (A no ser que te lleves bien con él):
   - Durante tu experiencia de juego en Factions
   - Durante tu experiencia de juego en Survival
   - Durante tu experiencia de juego en el mundo de eventos (Salas PVP, Jefes, Pueblo...)

Asi que recuerda: Los moderadores nunca tendrán ventaja sobre los demás jugadores, son también jugadores normales, y puedes confiar en ellos para realizar reportes (A ser posible no durante un asalto xD)

En cualquier caso, vamos a modificar la motd para que quede más claro lo que te acabo de explicar.

**Comment by MithrandirCraft** [comment]
Reabro este ticket para cualquier otra persona que se formule la misma duda.
