### ISSUE TITLE
vip+   "Al morir solo perderás un 50% de tus items"

### ISSUE THREAD

**Issue by BlackBeemo** [MithrandirCraft/MithrandirCraft#122]
Al morir solo perderás un 50% de tus items.

Eso es lo que pone en la descripción del vip+ en la tienda oficial. He muerto en survival y perdí todo, el 100% del inventario y cuando mueres en factions pierdes el 20% de tu inventario.
El rango que tengo es vip+.

**Comment by MithrandirCraft** [comment]
Gracias por reportar esto. Pregunté varias veces en el equipo interno si los % de drop se aplicaban correctamente... al menos ahora se que no xD

Le echaré un vistazo.

**Comment by MithrandirCraft** [comment]
He hecho unos ajustes, Ahora a las 6 hay un restart, aver que tal.

He pasado todos los rates de drop a 30% seas vip o vip+

Para jugadores normales, el rate debería ser ahora de 5%

En survival pierdes todo porque en un principio nadie debería poder robar tus drops. Si esto no es así, porfavor notificamelo.

Mejoraré la descripción de esta función en los rangos, indicando que los efectos se producen unicamente en Factions.
