### ISSUE TITLE
sethome en survival

### ISSUE THREAD

**Issue by BlackBeemo** [MithrandirCraft/MithrandirCraft#123]
- Comando /sethome (Establecer una home privada para luego teleportarte con /home, la home se establece en las coordenadas donde te encuentres)

Los de rango vip+ disponen del comando sethome pero se solapa con el sethome de survival. Esto significa que si juegas en survival solo tienes el sethome de survival y tu ventaja como rango vip+ en ese aspecto se anula. 

No hay sethome vip+ en survival.

**Comment by MithrandirCraft** [comment]
Lee el apartado especial azúl dedicado a HOMES (Sección azúl marino derecha) en /warp comandos

Dime si eso te ayuda a resolver este problema de homes. Hay una jerarquía y un orden que debes seguir si quieres sacar el máximo partido de tus homes disponibles.

Se que es un poco cutre, pero es la mejor forma que tenemos por el momento de otorgar la cantidad de homes pertinentes.

**Comment by BlackBeemo** [comment]
en el apartado ese pone que en survival puedo tener 2 homes, es eso cierto o lo interprete mal, si es cierto solo puedo tener un home en survival

**Comment by MithrandirCraft** [comment]
Si, es cierto. He modificado los carteles, quizá ahora sea mas clara la explicación.

Haz lo siguiente y no podrás fallar:

<nombre de la home> = coloca tu nombre para la home SIN UTILIZAR NUMEROS, SOLO LETRAS!

1. Utiliza /delhome <nombre de la home> para eliminar todas las homes que tengas hechas.
2. Ve a Survival
3. Utiliza /sethome <nombre de la home>
4. Cambia de lugar (Aún en Survival) y utiliza /sethome <nombre de la home>, esta vez un nombre distinto
5. Utiliza /home <nombre de la home> prueba primero una, y luego la otra, verás como funciona.
