### ISSUE TITLE
Recuperación por email (No recibes tu mail? Reportalo aqui.)

### ISSUE THREAD

**Issue by BlackBeemo** [MithrandirCraft/MithrandirCraft#124]
Solicite el cambio de contraseña por email, no me llego la nueva contraseña y ahora no puedo entrar.

**Comment by MithrandirCraft** [comment]
Que nadie utilize este sistema. Esta completamente roto. Si alguien lo ha usado por error deberá reportarlo en este ticket para que lo solucionemos.

Estamos trabajando para arreglar este error.

**Comment by MithrandirCraft** [comment]
Arreglado
