### ISSUE TITLE
no funciona el aldeano de venta de  cabeza

### ISSUE THREAD

**Issue by alucardjhon** [MithrandirCraft/MithrandirCraft#125]
hola... buenas tardes
me comunico.. que el aldeano de la venta araña cueva. no me vende esmeraldas...
![tiket no funciona la venta de cabeza de cueva](https://cloud.githubusercontent.com/assets/14955811/10992141/ed1080b6-8441-11e5-89a0-4499c331295f.png)

he intentado las sugerencias y nada...
espero su respuesta

**Comment by BlackBeemo** [comment]
Las pusiste en la pared y luego las quitaste con puño/agua/pico/tnt?

**Comment by MithrandirCraft** [comment]
Prueba colocar tu cabeza en el suelo (Colocada no tirada) de Factions.

Luego recoge la cabeza minandola. Esto debería desbugear tu cabeza de araña de cueva.

**Comment by MithrandirCraft** [comment]
Dinos si te funciona :)

**Comment by MithrandirCraft** [comment]
Comentario de @alucardjhon:

Buenas Tardes:
Me comunico: sobre aldeano de vendedor de cabezas de araña cueva
Hola, he intentado, las sugerencias, aun no esta en funcionamiento normal, 
Hoy lo verifico la MOD Deidei... y no hubo solucion uff. 
espero su respuesta 
Saludos, Alucard de INFINITY

**Comment by MithrandirCraft** [comment]
@alucardjhon te estaré buscando en el juego, quiero ver esas cabezas.
