### ISSUE TITLE
aldeano, vendedor de cabeza, sin funcionar 

### ISSUE THREAD

**Issue by alucardjhon** [MithrandirCraft/MithrandirCraft#126]
Buenas Tardes:
Me comunico: sobre aldeano de vendedor de cabezas de araña cueva
Hola, he intentado, las sugerencias, aun no esta en funcionamiento normal, 
Hoy lo verifico la MOD Deidei... y no hubo solucion uff. 
espero su respuesta 
Saludos, Alucard de INFINITY

**Comment by MithrandirCraft** [comment]
Movido al ticket original https://github.com/MithrandirCraft/MithrandirCraft/issues/125
