### ISSUE TITLE
error al iniciar 

### ISSUE THREAD

**Issue by alucardjhon** [MithrandirCraft/MithrandirCraft#127]
buenas tardes, 
me sale al iniciar este error
![1111](https://cloud.githubusercontent.com/assets/14955811/11026579/dc598bd2-868a-11e5-892a-7bdc402fd561.png)

error with reg_msg translation; please contact the admin for verify or update translation

espero su respuesta, uff

**Comment by MithrandirCraft** [comment]
Solucionado.
