### ISSUE TITLE
Recuperación de cosas

### ISSUE THREAD

**Issue by witchrd** [MithrandirCraft/MithrandirCraft#128]
Hola mith necesito comunicarle que cuando yo estava jugando normal me desconecte y me volvi a conectar , cuando me desconecte y me conecte no estavan mis cosas y no solo eso se me aparecieron el kit de novato y quiero recuperar mis cosas TODAS , por eso necesito que me ayude porque consegui esas cosas con esmero espero que me responda este problema.

                                                                                                             -Att:Mythicalmidget

**Comment by witchrd** [comment]
Espero que me ayude.

**Comment by witchrd** [comment]
Estoy en la cuenta de mi hermana porq no se como funciona esta cosa xD

**Comment by BlackBeemo** [comment]
Entra con el nombre de usuario Witchrd y luego witchrd alomejor te equivocaste en la primera letra

**Comment by MithrandirCraft** [comment]
@witchrd probaste lo que te indicó Beemo?

**Comment by witchrd** [comment]
Les explico , yo no soy witch dr soy la hermana no se como crearme una de estas cositas y me meti con esta xDD , mith hay mucho lag en el server

**Comment by MithrandirCraft** [comment]
@witchrd 1 ticket por reporte, y 1 cuenta por usuario porfavor.

Cierro ticket, si lo desean, pueden abrir otro, pero para 1 solo tema, y proporcionando los detalles siguiendo esta plantilla: https://github.com/MithrandirCraft/MithrandirCraft
