### ISSUE TITLE
Me desconecte en survival y cuando regrese los objetos de factions fueron sustituidos pos los de survival

### ISSUE THREAD

**Issue by TheWildeRrNess** [MithrandirCraft/MithrandirCraft#129]
Mis objetos de factions se perdieron al desconectarme en survival , cuando regrese a factions tenia los objetos de survival. Me gustaría que recuperaran mis objetos que yo consideraba de mucho valor. Espero su respuesta equipo de administración de MithrandirCraft.

**Comment by HOLASOYUNHUMANO** [comment]
A mi tambien me paso lo mismo Tambien me gustaria recuperar mis cosas

**Comment by MithrandirCraft** [comment]
Hemos arreglado este error.

Tengo varias preguntas, si las respondéis, me estaréis ayudando a solucionar futuros problemas similares:

- Os fijasteis si vuestro bug de inventario ocurría cada vez que os deslogueabais? Si es asi, requeríais cerrar el cliente para que se produjese el error, o bastaba con usar /logout?

- Podeis aportar mas detalles sobre cuando creeis que se produce este bug? Por ejemplo, es posible que solo se haya producido al desloguear durante un reinicio, o justamente por un reinicio? Pasaron muchas horas desde que os desconectasteis hasta que regresasteis y comporbasteis el error?

En cualquier caso, para que pueda hacerme una idea de lo que quereis que os reestablezca, necesitaría imagenes que confirmen lo que llevabais en el inventario.

**Comment by HOLASOYUNHUMANO** [comment]
Pues a mi me paso cuando en survival puse /warp pvp y me paso
y pues imagenes no tengo lo unico bueno que tenia era una espada de diamante al full es lo unico que quiero

**Comment by MithrandirCraft** [comment]
@HOLASOYUNHUMANO En que mundo?

**Comment by HOLASOYUNHUMANO** [comment]
Se me paso el inventario del surv a factions

**Comment by KawaiiGNE** [comment]
Hola, las cosas de survival que tenia en KawaiiGNE me han aparecido en factios, he probado a desloguear y reloguear pero el bug no me desaparece, he perdido todo lo que tenia equipado en factions y eran cosas de bastante valor, hay alguna forma de que pueda recuperarlas?¿

**Comment by MithrandirCraft** [comment]
@KawaiiGNE 

El error debería estar arreglado desde hace unas 22 horas.

Cuando te ha ocurrido esto?

**Comment by UnicorniaxD** [comment]
Holaas! He muerto en survival y las cosas de survival las tengo en fac. Y al kawai le ocurrio esto sobres las 15:30 14:00. Estaba yo con el en ese momento.

**Comment by MithrandirCraft** [comment]
Los jugadores afectados deberían proporcionar estos datos:

- Hora y día de desconexión aproximada (anterior a la producción del error)
- Hora y día de conexión (momento en el que se produjo el switch de inventarios)
- Sintomas exactos.

**Comment by HOLASOYUNHUMANO** [comment]
A mi me paso en el mismo dia que escribi, pero me pueden devolver mis espada es lo unico que quiero :c

**Comment by TheWildeRrNess** [comment]
MithrandirCraft no me acuerdo de la hora exacta pero se que fue ase 2 Días, solo quiero saber si es posible que me devuelvan mis cosas.

**Comment by TheWildeRrNess** [comment]
:-1:

**Comment by TheWildeRrNess** [comment]
:-1:

**Comment by MithrandirCraft** [comment]
@TheWildeRrNess Este error se produjo hace 2 días, y ya debería estar arreglado, por lo tanto tu caso tiene bastante sentido, aún así, hacer spam no te va a ayudar nada.

Los jugadores afectados que deseen una compensación pueden recibirla (En factions), además de reestablecer su inventario de survival en el lugar pertinente, si proporcionan los siguientes datos ordenadamente:

- Nombre de jugador
- Localización del inventario de Survival (En Factions ya que ha sido trasladado por error)
- Descripción de las perdidas en Factions

Y cumplen las siguientes condiciones:

- Estar conectados y contestar mi mensaje administrativo entre las 16:00, y las 21:00h (Horario Peninsular Español y del servidor.) todos los días, hasta el Viernes de esta semana, cuando este ticket será cerrado definitivamente si no se vuelve a producir este error.

**Comment by HOLASOYUNHUMANO** [comment]
Como asi que localizacion del inventario de survival?

**Comment by MithrandirCraft** [comment]
@HOLASOYUNHUMANO Necesito saber a donde ha ido a parar vuestro inventario de Survival en Factions. Habeis tocado el inventario cuando se os jodió? Lo habeis guardado en alguna parte? Eso necesito saber, y si lo habeis puesto en un cofre de factions, indicar donde se encuentra todo.

**Comment by HOLASOYUNHUMANO** [comment]
Nombre:HOLASOYUNHUMANO
Localizacion:No he movido el inventario ni he tocado nada
Perdidas:Comida Y espada de diamante al Full

**Comment by HOLASOYUNHUMANO** [comment]
Mith!! Me sigue pasando

**Comment by HOLASOYUNHUMANO** [comment]
Ahora me paso al revez y perdi mis cosas en survival que es eso!

**Comment by MithrandirCraft** [comment]
@HOLASOYUNHUMANO Lo normal es que se traslade el inventario de Survival  a Factions, y sobreescriba el inventario de Factions...

Sin embargo, soy incapaz de reproducirlo, podrías decirme si te ocurre siempre que sigues determinadas acciones? O si es algo aleatorio?

**Comment by HOLASOYUNHUMANO** [comment]
Me ocurre siempre que me desconecto y me vuelvo a conectar pero creo que es por lo del principio que te mandan a loguearte a otro lado

**Comment by MithrandirCraft** [comment]
@HOLASOYUNHUMANO Ya no mandamos a la gente a un mundo distinto al desloguear, por lo tanto no tiene sentido que aún pierdas algo.

**Comment by MithrandirCraft** [comment]
@HOLASOYUNHUMANO Puedes reproducir el error que te hace perder el inventario actualmente?

**Comment by HOLASOYUNHUMANO** [comment]
Ok lo intentare

**Comment by HOLASOYUNHUMANO** [comment]
Mith Me volvio a pasar cuando puse ./warp pvp tengo las cosas del surv

**Comment by MithrandirCraft** [comment]
Ahora mismo?

**Comment by MithrandirCraft** [comment]
Este problema ha sido parcheado con un metodo temporal, nos desharemos del error completamente mas adelante.
