### ISSUE TITLE
Perdida de cosas por el lag.

### ISSUE THREAD

**Issue by Pabloxlive** [MithrandirCraft/MithrandirCraft#13]
Hola buenas,me paso por aqui para intentar reclamar algo que he perdido por el lag:
Estaba picando obsidiana durante 1 h,viene un poco de lag en el server,la gente se queja y eso,pero yo seguia picando,siguen pegando lagazos,hasta que consigo picar 1 bloque mas,en ese bloque,se buguea y me meto dentro,luego paso a la lava de abajo y muero,no es por no poner agua,porque siempre para picar ponia agua.
Si no llevase nada de importancia me daria igual,pero esque perdi 13 diamantes,y 2 stacks de obsidiana...Mira los logs y todo eso para que veas que lo que te digo es verdad,porque me parece injusto que lleve picando 1 h y muera por el lag...

Gracias.
Nombre en el juego: Necro_AATB
Fecha del bug: 07/01/2015
Hora aprox: 14:15 (Hora canaria)

**Comment by MithrandirCraft** [comment]
Saludos

El lag que han experimentado los jugadores durante los días 5 y 6 de este mes, se debe a un exceso de memoria en disco. 

El servidor tenía problemas para encontrar más memoria (ya se encontraba al límite), el proceso para guardar más datos en la memoria causó lag de procesos.

Estos problemas de memoria se deben a la ausencia de fondos para pagar una expansión. Tendríamos fondos si recibiesemos una mínima cantidad de donaciones.

En cualquier caso, hemos retirado parte de las instalaciones del servidor, para reducir el consumo, consecuentemente el problema con el lag debería estar resuelto.

**Comment by Pabloxlive** [comment]
Okey,pero las cosas que he perdido no las vas a devolver? :/
