### ISSUE TITLE
Servidor caido..

### ISSUE THREAD

**Issue by RoninPy** [MithrandirCraft/MithrandirCraft#130]
Veo que desde hace varias horas no hay respuesta del servidor, hasta que hora estará de mantenimiento? Gracias.

**Comment by MithrandirCraft** [comment]
Hola, hemos dejado algo de información sobre lo que ocurre en la pagina de FB. Deberíamos estar ON para hoy por la noche o mañana por la mañana.

Agradecemos tu paciencia :)
