### ISSUE TITLE
Moderador abusivo

### ISSUE THREAD

**Issue by KawaiiGNE** [MithrandirCraft/MithrandirCraft#131]
Hola, tengo un problema con un moderador que, por lo visto, se enfada cuando es derrotado y abusa de su condición para banear.
Mi nombre es KawaiiGNE, y el moderador que me ha baneado de manera injusta (afirma el uso de hacks cuando las razones de su derrota son obvias: poción de fuerza)
Quiero saber 2 cosas, que hacer para evitar que un moderador abuse de su poder sobre ti y como demostrarlo. 
![prueba](https://cloud.githubusercontent.com/assets/15872506/11329068/9947d2f6-9196-11e5-9942-374cd9b467dd.png)

En el caso de que hubiese pruebas acerca del uso de hacks de combate por mi parte estaría conforme con el ban, pero en este caso el administrador solo aplico un ban por una rabieta

**Comment by MithrandirCraft** [comment]
Buenas tardes.

Esta es una situación que se produce de vez en cuando, y tiende a involucrar a un jugador y un moderador concretos en cada ocasión...

Yo mismo elijo cuidadosamente a todos los integrantes del equipo de moderación, y confío en su criterio para realizar expulsiones.

Si has sido expulsad@, es porque el moderador en cuestión ha tenido que ver alguna acción ALTAMENTE sospechosa en tu comportamiento o forma de pelear.
Rafaelox ha muerto unas 227 veces en combate, si de verdad no fuese capaz de controlarse tras una derrota (Que además intuyo, ha debido ser en una sala de pvp donde no existe gran riesgo.) ya habría baneado a unas 227 personas injustificadamente.

Cuando se realiza una expulsión, la única justificación que recibirás será el motivo de la expulsión. Nunca vamos a proporcionarte ninguna "prueba" de ello.
Si algo me hace creer aún más en la decisión que ha tomado rafaelox, es el hecho de que estarías dispuesta a aceptar tu castigo si te proporcionasemos algun tipo de prueba, tu misma estas metiendo la pata delatandote.

Porfavor:
 - Juega Legal y lee la normativa /rules.
 - Has sido avisad@ una vez, no vuelvas a caer en lo mismo.

Si deseas añadir alguna cosa reabre este ticket.

**Comment by UnicorniaxD** [comment]
1.Lo que yo diga a nadie le va a importar. 2.pero como buena clienta que soy ya que nosotros DONAMOS al Server, no nos merecemos este trato porque ese chico no usa nada de hacks ni mucho  el problema esta en que no puedes jugar en pvp porque si lo haces bien es por que uSAS hacks?No se han parado a pensar que puede llegar alguien que lo haga mejor que tu? volveremos  a echar partidas grabaremos nuestras pantallas y callaremos  por el trato tan cordial que estamos recibiendo sin motivos, porque hasta a mi me duele la impotencia de saber que a el le gusta pelear y no puede jugar pvp por que lo banean y lo mejor de todo es que nadie se pone en su lugar , prefieren creer a un MOD que se ofende de que llegue alguien que juegue mejor que el. La próxima vez que hable por algún sitio será demostrando  pruebas de esta injusticia POR VIDEOS grabando las pantallas de las partidas y de lo que hacemos en minecraft.

**Comment by Catadolfa** [comment]
Yo la verdad, preferiria que se le de la oportunidad a KawaiiGNE de mostrar su inocencia através de un streaming donde el desde su pantalla nos enseña como hace el PVP. Yo no me pongo especialmente del lado de nadie pero opino que sería lo mas justo como amiga de KawaiiGNE y de Rafaelox24.

**Comment by Catadolfa** [comment]
Si el caso es que KawaiiGNE termina siendo inocente me imagino que nuestra facción se merece una disculpa, especialmente después de lo que pasó durante el torneo en el que nos acusaban a TODOS de llevar KillAura, por otro lado, no obligo nada a nadie, yo no soy MOD o Admin para tomar decisiones, solo doy la sugerencia para resolver el problema de forma justa en caso de que estén ambas partes de acuerdo.

**Comment by UnicorniaxD** [comment]
Es lo que yo quiero tambien un streaming, que le dejen demostrarle. O que nos dejen demostrar y responder a todos esos comentarios en el video con tantas acusaciones.

**Comment by Catadolfa** [comment]
Yo la verdad no quiero responder a ningun comentario de video ni acusaciones mas, me da igual lo que pasó en ese torneo, de que fue un poco injusto contra nosotros lo fue, pero no hicieron nada en contra de las reglas.

**Comment by rafaelox24** [comment]
E peleado con el varias veces y siempre todo bien, pero las en las 2 ultimas ocasiones tenia un Aimbot muy evidente, no es por que me maten que baneo ya que si fuera por ese banearia a 227 personas jaja.

**Comment by UnicorniaxD** [comment]
Pues mendez, perdona que te diga, ves fantasmas donde no los hay ;) se va a comprobar todo esto y veremos donde esta el segun tu el "aimbot"

**Comment by Ivanovic24** [comment]
La verdad, no sé si usais hacks o mod, autoclicks, macros o lo que sea, pero aparte de que tu te has delatado en el primer mensaje, como bien a dicho nuestro admin Mithrandir, este moderador te ha visto actuar de manera sospechosa, y este usuario lleva años de experiencia en pvp al igual que yo, y a visto a hackers, guarros y jugadores de todos los tipos.

Que doneis por el servidor no significa que podais incumplir las normas o hacer lo que os de la gana, donar solo os da el privilegio de tener varios comandos y magias mas.
Si has donado y se te coje con hacks o cualquier otra cosa, irás baneado el mismo tiempo que si no fueras vip. Eso no quita que no sigais donando, por que ayuda muchisimo al servidor.
Es el primer aviso, solo piensa bien lo que haces, el segundo aviso no sera 1 dia nada mas...

**Comment by KawaiiGNE** [comment]
Pero si a mi me da igual que me echeis en caso de que tengais razon y use hacks, a mi me daria lo mismo, pero no los uso, hasta he abierto un twitch para cerrar boquitas cuando hago pvp http://www.twitch.tv/kbrav0 pero no te preocupes ivanovic, tu puedes seguir haciendo lo que quieras por que ser mod si significa poder hacer lo que quieras, como llamar a los jugadores "una panda de mongolos" en un chat de uso unico para moderadores.
[https://www.youtube.com/watch?v=DkQiIvMhIP8 minuto 6:28]

**Comment by BlackBeemo** [comment]
Estáis haciendo lo que hacéis siempre, se os acusa de hacks, os banean con pruebas evidentes y en respuesta abren un ticket diciendo
que el moderador es un corrupto y lo a echo por rabieta.

Esto de vosotros no es nada nuevo simplemente que asta el momento nunca habíais abierto un ticket. Las TRES ultimas veces estuvimos observando vuestras estadísticas de minado durante semanas y en las TRES veces que se os baneao FUE EL ADMIN PERSONALMENTE A VER COMO MINABAN. Que hicieron después del ban esas veces? admitieron que usan xary? NO! Se crearon cuentas para insultarme cada vez que hablaba por el chat, muy maduro de su parte.

Lleváis hace mucho tiempo el en grupo de usuarios maleducados y tramposos sin señal ninguna de rectificación ni arrepentimiento y esperan de nosotros que les demos un trato mas educado porque son donadores? 

De mi parte no van a recibir nada, sois usuarios tramposos dispuestos a liarla mas, de este tipo de jugadores en este server hemos tenido unos cuantos y están todos baneados.

Grava los vídeos que quieras porque los vas a necesitar.

**Comment by Catadolfa** [comment]
Perdona informarte BlackBeemo, la verdad nose quien eres pero que YO esté al tanto nadie de mi fac ha creado en ningún momento una cuenta para insultarte. Por lo que estás diciendo me imagino que eres Nadelina y si estoy en lo cierto pues lo siento si en algún momento alguien de mi "grupo de usuarios maleducados y tramposos" te ha ofendido con su silencio. Lo único que hicimos, bueno, que hice yo fue poner carteles por el spawn, sí, insultandote, porque cometiste una injusticia. Aquél dia que me metiste en la carcel durante un mes cuando MIS estadisticas de minar independientemente de las estadisticas del resto de mi fac no saltaban la alarmita esa que vosotros teneis cuando alguien usa el xRay, se lo preguntamos a MortisBlack. Como ya sabrás el xRay lo han quitado, sip, debo admitir que usabamos xRay al principio PERO si ya no va el xRay y ya no podemos usarlo deberiais de dejar de ver fantasmas donde no los hay. 
En segundo lugar, hemos abierto este ticket para hablar de otro baneo injusto que es el de los aimbots de Kevin, hemos estado intentando demostrar pruebas y nose si por orgullo o por el simple facto de no os importa lo que hagan los usuarios del servidor, las habéis rechazado continuamente y habéis traído a cuento un tema que ya está cerrado hace meses, pues ya van meses que el xRay está deshabilitado en este servidor.

Lo único por lo que yo puedo pedir perdón y a la vez no deberia es por todo lo que se ha estado liando ultimamente en los chats del servidor. Yo estoy totalmente en contra de estas peleas, pero la distancia me impide atarle las manos a los de mi fac y además, ellos tienen el derecho a decir lo que quieran a quien quiera, mientras mantengan el respeto y no violen las reglas de este server.

**Comment by Catadolfa** [comment]
Añadiendo a lo de recibir un poco mas de respeto. Tú como WebMaster de este servidor, ya que fuiste elegida por Mithrandir, deberias mantener el respeto a los usuarios, independientemente de lo que hayan echo o hayan dejado de hacer. Yo a pesar de todos los baneos y peleas y problemas que tengais con Kevin y Tatiana, sigo haciendo buenas relaciones con todas las personas de este servidor sin desrespetar, humillar o mirar abajo a ningún usuario y si en algún momento lo he echo pido disculpas públicamente en este ticket.
