### ISSUE TITLE
el unregister no funciona

### ISSUE THREAD

**Issue by alucardjhon** [MithrandirCraft/MithrandirCraft#132]
hola,buenas tardes

el comando de "/unregister paswoord" no funciona? pa dichas cuentas pufff... espero su respuesta

saludos...

**Comment by MithrandirCraft** [comment]
Algunos comandos relacionados con el sistema de contraseñas pueden tener problemas de permisos.

Gracias por comunicarnos esto, lo arreglaremos :)

**Comment by MithrandirCraft** [comment]
Reabre este ticket si estoy equivocado pero creo que ya debería estar arreglado.
Y sinó, en el siguiente restart (6 P.M)
