### ISSUE TITLE
el captcha no funciona? para iniciar 

### ISSUE THREAD

**Issue by alucardjhon** [MithrandirCraft/MithrandirCraft#133]
buenas tardes:
me comunico al mith que le envie por mail, el problema a resolver de las cuentas...

![Uploading no funciona el captcha.png…]()
![Uploading no funciona el captcha.png…]()

**Comment by MithrandirCraft** [comment]
Si, faltan permisos para varias cosas xD los estoy incorporando todos. Estará arreglado en breve.
