### ISSUE TITLE
falla de la regeracion del mapa en my fac

### ISSUE THREAD

**Issue by darksessho** [MithrandirCraft/MithrandirCraft#134]
buenas tardes, 
ser lider sessho  de gamers

reporto, la perdidas de my spawner de esqeleto y zombie, de my claim...
espero q puedan resolver esto :/ 
tambien parte de la casa claimada fue roto x la regeneracion :(

mys saludos.

**Comment by MithrandirCraft** [comment]
El sistema solo regenera chunks no reclamadas. Si ves que hay irregularidades en la regeneración, es porque no reclamaste bien tu terreno.

Indicame las coordenadas de la chunk afectada (x y z, coordenadas de bloques interiores, no de chunk).

**Comment by darksessho** [comment]
mys buenas tardes:Ser sessho lider de gamers
le indicare las coordenadas por medio de mail porque, es arriesgado por reporte, indicando my ubicacion...---------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------------Date: Fri, 27 Nov 2015 07:21:20 -0800

**Comment by sadow2811** [comment]
en verdad solo te arriesgas a que esa ubicación se convierta en un cráter XD
