### ISSUE TITLE
Intercambio de cabezas

### ISSUE THREAD

**Issue by Deideando** [MithrandirCraft/MithrandirCraft#135]
Los aldeanos del primer piso (Esqueleto, Zombie, Creeper y Wither esqueleto) No dan la opción de tradeo. 
![captura de pantalla 2015-11-28 a las 1 11 40 p m](https://cloud.githubusercontent.com/assets/16061845/11453502/32617ebc-95d2-11e5-9a7f-04a2aa6fb005.png)

**Comment by MithrandirCraft** [comment]
Han sido desactivados por razón de seguridad.

Hay un error con las ID's de este tipo de cabezas.

**Comment by MithrandirCraft** [comment]
Arreglado.
