### ISSUE TITLE
Recuperar Cuenta

### ISSUE THREAD

**Issue by xXandrescolXx** [MithrandirCraft/MithrandirCraft#136]
Buenas noches

En el dia de hoy se han logeado con mi cuenta de xX_andrescol_Xx en el servidor de MithrandirCraft y han cambiado la contraseña, ademas es una cuenta VIP y tambien cuando me registre no pude poner mi correo

Como puedo recuperar mi cuenta?

**Comment by Catadolfa** [comment]
Tengo pruebas y al culpable, dejo aquí pantallazos. 
![screenshot_1](https://cloud.githubusercontent.com/assets/15986291/11605328/9caf1d54-9aca-11e5-990b-eecca04d39d2.png)
![screenshot_2](https://cloud.githubusercontent.com/assets/15986291/11605329/9cb3a69e-9aca-11e5-8f75-80693d01a2eb.png)

**Comment by MithrandirCraft** [comment]
No es posible acceder a una cuenta ajena en circunstancias normales, algo ha tenido que ocurrir para que descubriesen tu contraseña o tu cuenta estuviese desregistrada / accesible en determinado momento.

Puedes dar algún detalle mas? Es posible que te hayan engañado para que visites otro servidor? Existe un metodo de robo de cuentas que consiste en atraer a gente a un servidor, y de esta forma tomar control de su sesión.

En MithrandirCraft recomendamos no visitar servidores sospechosos. MithrandirCraft es un servidor seguro, donde tus datos, IP, privacidad, y contraseña nunca serán comprometidos o proporcionados a terceros.

Estamos trabajando para proporcionar un arreglo con el sistema de recuperación de cuenta por e-mail, esto debería ayudar a solucionar casos de robo de sesión en el futuro.

Por el momento, para reestablecer tu cuenta, vas a tener que enviarnos un e-mail a mithrandircraft@hotmail.es proporcionando tu nombre de usuario y e-mail registrado. Si no tienes un email registrado con tu cuenta será mejor que nos proporciones algún dato importante sobre la donación que realizaste para tu rango (eso debería ser suficiente). Lo hablaremos por correo :)

**Comment by xXandrescolXx** [comment]
Listo Mith, muchas gracias, te acabo de enviar la información por correo
