### ISSUE TITLE
Preguntas sobre el servidor

### ISSUE THREAD

**Issue by Catadolfa** [MithrandirCraft/MithrandirCraft#137]
Preguntas para el servidor

1. ¿La administración (MOD, ADMIN, PB) del servidor tiene acceso a los chats de factions, o conversaciones privadas de los usuarios?
2. ¿Qué tipos de problemas se pueden reportar en este foro? (Bugs, hacks, sugerencias?)
3. ¿Cómo funciona el spawn y respawn de los jefes del servidor? (Explicación detallada)
4. ¿El servidor posee algún servidor de teamspeak, raidcall, u otro programa donde la llamada por voz sea posible entre los usuarios?
5. ¿Se pueden reportar los problemas directamente a los moderadores conectados en el servidor o es mas recomendado abrir un ticket cuando sucede algún problema?
6. ¿Cuando se abre un ticket los moderadores pueden tomar acción y decisión en el problema que se presenta en el ticket o solo los administradores pueden tomar acción sobre los casos presentados desde github?
7. Una vez un usuario ha sido baneado por mas de X meses su cuenta se quita del registro de cuentas y tiene que ser registrada otra vez para quedar utilizable, esto lleva a varias preguntas. 
7.1. ¿Los objetos de esa cuenta quedan utilizables despues de volver a registrarse?
7.2. ¿Otras personas se pueden registrar con el mismo nombre de usuario?
8. ¿Se implementarán nuevos jefes menos poderosos para los usuarios nuevos que no poseen armas y armaduras decentes para luchar contra los actuales?

Espero no ofender a nadie con mi curiosidad, pero son preguntas que me han surgido desde que empecé en este servidor. No tengo preferencia sobre la gente que puede responder, mientras la información sea de fiar.

**Comment by MithrandirCraft** [comment]
Hola, buenas noches. Todas tus respuestas:

1. Si, solo administración
2. Todos los detalles en este README: https://github.com/MithrandirCraft/MithrandirCraft
3. www.mithrandircraft.es/jefes (No voy a dar ninguna explicación detallada, porque el sistema aún esta muy bugoso.)
4. Teníamos un canal de Team Speak, pero no entraba nadie, por desuso decidimos cerrarlo. Pero podemos abrir otro si hay suficientes peticiones.
5. Si hablas con un moderador primero, es bastante provable que si no puede solucionarlo el/ella te envíen aquí. Sin embargo, todos los moderadores terminan comunicandose con Administración, por lo que nos acaba llegando tu información.
6. Una pregunta interesante... Por lo general, te sorprenderá saber que las decisiones en gran parte de las ocasiones no las toma una sola persona, sino que se tiende a hablar en el chat interno de staff para tomar cursos de acción. Cualquier persona puede intervenir en una conversación en un Ticket de MithrandirCraft, no solo Staff's.
7. Cuando un jugador permanece más de 1 año sin conectarse por cualquier motivo (Incluso una expulsión), su nombre es desregistrado y todos sus datos son eliminados. Sin embargo, pueden quedar algunos resquicios de su presencia como estadisticas.
8. Si. Es uno de los aspectos del servidor donde queremos profundizar mas. Y de hecho los primeros jefes nuevos que empezamos a desarrollar iban orientados para jugadores menos experimentados :)

Si tienes mas preguntas estaré encantado de responderlas (Si tengo tiempo claro.)

**Comment by MithrandirCraft** [comment]
Reabre este ticket si quieres añadir algo.

**Comment by Catadolfa** [comment]
Muchas gracias.
