### ISSUE TITLE
Intercambios con objetos dropeados por jefes (Bugeado de nuevo)

### ISSUE THREAD

**Issue by AndresGatoXD** [MithrandirCraft/MithrandirCraft#138]
Buenos Días. Tengo este problema:
En Intercambios Especiales (warp pueblo), para ser mas preciso no he podido canjear/comprar el Spawner de Zombi y el de Spider. Tengo los requisitos y "dinero" para comprar tal objeto, pero el aldeano no me da lo que quisiera comprar.

**Comment by MithrandirCraft** [comment]
Un bug que ya habiamos arreglado, y ha vuelto.

Lo volveremos a arreglar.

**Comment by MithrandirCraft** [comment]
Paso el hilo oficial a: #178
