### ISSUE TITLE
Discusión

### ISSUE THREAD

**Issue by Catadolfa** [MithrandirCraft/MithrandirCraft#139]
Me gustaría que las peleas entre MODs VS Insidious parasen de una vez. No es un ambiente agradable y a mi me da mucha vergüenza que todo el servidor se piense que usamos hacks porque estas peleas se hacen publicas. Esto no es un problema que nos incumbe solo a nosotros los de las peleitas pero tambien al entorno. Jugadores que se acostumbran a un entorno donde predominan los insultos y las indirectas crea un ambiente horrible. En mi opinión todos tenemos derecho a defendernos mientras lo hagamos de la manera correcta y con educación. Muchas veces se dicen cosas por el chat dirigidas de nuestra fac a los mods y viceversa. Independientemente de quien empieza, nadie sale ganando pues las peleas siguen y siguen. Indirectas como "alguien de cierta fac que estoy viendo va a ser baneado pronto" sobran. Se pueden resolver los problemas hablando como gente normal. Gracias.

**Comment by Catadolfa** [comment]
Mi recomendaciones para resolver esto son las siguientes:

- Abre un github para discutir estas cosas con gente especifica
- Intentar crear un filtro de chat donde personas especificas pueden hablar

No intento oprimir los derechos de expresión de nadie, pero hay cosas que se merecen un lugar para ser discutidas.

**Comment by MithrandirCraft** [comment]
Hola. Soy Mithrandir.

Personalmente no tengo mucha idea de cual es la situación de la que estás hablando, me ocupo de los aspectos técnicos del servidor , moderar el servidor es trabajo de los moderadores (Yo ya tengo suficiente xD).

-Procura cooperar con la resolución de cualquier asunto relacionado con el servidor que te pidan los moderadores.
-Lee la normativa /rules y cumplela: www.mithrandircraft.es/normas (Es obligatorio para jugar en MithrandirCraft)

Dejaré este ticket abierto 5 días, por si algún staff quiere hacer algun comentario.

**Comment by BlackBeemo** [comment]
Yo cuando voy a banear a alguien mando una advertencia al afectado dándole la oportunidad de rectificar. Lo suelo hacer de forma publica
y una de las menores preocupaciones que tendría que tener esa persona es su reputación. De todas las advertencias que mando suelo recibir un "que te follen" en toda la cara y el afectado continua saltándose las normas resultando en un "que te follen a ti y pa hackaban".

Un amonestación publica no se debería de tomar a la ligera, si en tu entorno se encuentran jackers tu también puedes verte afectado por ellos. Por esa razón algunos mods deciden hacerlo de forma publica para proteger al resto de usuarios de posibles injusticias.

Posibles injusticias:
	- Encontrarte un jacker con un palito y que te mate tu yendo full diamante.
	- Que un miembro de tu fac sea un "experto minando" y al día siguiente el admin tenga que intervenir borrando todo lo que hay en esa facción.
	- Que la gente dude de la legitimidad de tus habilidades por tener a varias personas en tu fac baneadas por jacks.

Recuerda que aquéllos que usan jacks les importa una puta mierda que eso pueda afectar a sus amigos. Es necesario una cierta dosis de egoísmo para andar por un server fardando de recursos y habilidades.

**Comment by Catadolfa** [comment]
BlackBeemo, gracias por contestar, veo que te has centrado más en la cita que he utilizado en respuesta a mi comentario. En respuesta a lo que tú me dices, como referí anteriormente hay lugares donde las cosas pueden ser habladas. Si tú quieres darle un aviso a un jugador para que elimine sus "hacks" puedes decirselo utilizando el comando /w y no haciendolo un problema público; no lo dejas caer como una indirecta en el chat y lo peor, vacilando al jugador como lo que sucedió aquél dia. Pero eso da igual, perdonado. Al igual que he cogido esa cita, tambien podría coger otras como cuando nos llamaron "noobs" por usar pociones en pvp y cuando nos defendimos, ya que no tenemos ninguna confianza con las personas que nos llamaron noob, la respuesta de esa persona fue llamarnos "personas sin dignidad, no dispuestas a superarnos". Tambien se podría agarrar el ejemplo donde un publicista del servidor durante el torneo de server vs admin llamó "mongolos" a los usuarios conectados. 
Reitero tambien que he abierto esta discusión para hablar sobre peleas en el servidor y no sobre quien usa hacks y quien no usa hacks. Está claro y admitido que hemos usado xRay en mi fac, casi tan claro como el facto de que el xRay en este servidor ya no es utilizable. Del kill aura no haré comentarios, yo no se como va eso, no tengo ni idea de como se juzga. Desde mi punto de vista ellos no lo utilizan, ni lo han utilizado y confio en la palabra de ellos, igual como vosotros decís que ellos sí utilizan kill aura y confiais en lo que se dice entre vosotros.

Posible injusticia:

- Un jugador necesita pruebas para acusar a otro de haber utilizado un hack. Un moderador no, y cuando llega el momento de juzgar el caso se tiene que confiar en la palabra de los moderadores, pero no se confía en la palabra de los jugadores. Lo justo sería que los moderadores tambien tuvieran que hacer capturas de pantalla o videos para hacer un ban, así los jugadores acusados no podrían negar las irreputables pruebas. Vosotros afirmais que hablais unos con otros, sois tantos moderadores en el servidor, e incluso hay dos administradores que pueden entrar de forma invisible a tu facción y espiarte y ninguno de vosotros puede conseguir una prueba antes de hacer un ban apropiado? Espero que esto se tome en consideración. Eso es todo lo que tengo que decir sobre los hacks y los bans en este servidor, pero mi opinión es irrelevante, vosotros haréis lo que querrais y yo lo respetaré.

**Comment by MithrandirCraft** [comment]
@Catadolfa

Yo personalmente intento tomar las decisiones mas justas. Nuestra comunidad no es muy grande, y entre las personas que se ofrecen para formar parte de staff, las que elijo son siempre las que creo mas inteligentes y maduras.

No considero que un moderador deba proporcionar pruebas para realizar su acción. Lo que si considero es que debería tener la madurez suficiente como para procesar su acción antes de realizarla. Es curioso, porque no es la primera vez que escucho que debería ser necesario proporcionar pruebas por nuestro lado, sin embargo, yo lo encuentro innecesario y relentizador para un proceso de expulsión.

**Comment by Catadolfa** [comment]
Es simplemente una diferencia de opiniones, yo lo veo como lo mas justo, especialmente siendo una comunidad pequeña. Pero como dije anteriormente, lo respetaré, pues yo no hago las reglas. Gracias mith

**Comment by BlackBeemo** [comment]
> veo que te has centrado más en la cita que he utilizado en respuesta a mi comentario

No tengo problema en citar linea por linea

> En respuesta a lo que tú me dices, como referí anteriormente hay lugares donde las cosas pueden ser habladas.

Si, esos lugares son donde el moderador considere apropiado.

> Si tú quieres darle un aviso a un jugador para que elimine sus "hacks" puedes decirselo utilizando el comando /w

Ya te respondí de porque lo digo públicamente lee mi comentario anterior. Y no me da la gana darle un trato privilegiado a una persona que no sigue las normas.

> y no haciendolo un problema público

Te preocupan cosas que no deberían y no se transforma en un problema publico porque yo lo mencione en /all en mi pais se llama transparencia.

> no lo dejas caer como una indirecta en el chat y lo peor, vacilando al jugador como lo que sucedió aquél dia

Recuérdame que paso aquel día no tengo tan buena memoria, podrías poner exactamente la fecha y lo que os dije?

> Pero eso da igual, perdonado.

No pedí en ningún momento que me perdonaras, pero no pasa nada te perdono.

> Al igual que he cogido esa cita, tambien podría coger otras como cuando nos llamaron "noobs" por usar pociones en pvp

Existe un código de honor no escrito que la mayoría de personas que hacen pvp (player vs player) conocen a la perfección menos tu. La cosa es que si alguien te reta a un pvp en este servidor uno no se espera que dicha persona aparezca con dos escuderos y pociones. Podrías avisarle en plan "olle que me traigo a dos personas a un 1 vs 1 y un inventario de pociones" entonces alomejor la otra persona no te dirá noob.

> ya que no tenemos ninguna confianza con las personas que nos llamaron noob, la respuesta de esa persona fue llamarnos "personas sin dignidad, no dispuestas a superarnos".

bueno pues eso que decía:

1.- Aceptar el reto
2.- No traerse a un escudero (en tu caso supongo que son 2 o 3)
3.- Acordar el tipo de indumentaria
4.- go!

Son salas pvp en las que no se pierde nada, no pasa absolutamente nada porque alguien te mate allí. Y esta mal visto que una persona con armadura de diamante prot 4 acose a uno que no lleva ni ropa interior.

> Tambien se podría agarrar el ejemplo donde un publicista del servidor durante el torneo de server vs admin llamó "mongolos" a los usuarios conectados.

Sip, quizás no tendría que haber usado esa palabra porque la culpa de lo sucedido fue del mongolo del admin. Otra palabra como incautos abría sido mas acertada. A y no fue a los usuarios conectados como tu bien pretendes dar a entender fue a un grupo de personas que bloqueaban una placa de presión para teletransportarse.


> Reitero tambien que he abierto esta discusión para hablar sobre peleas en el servidor

La verdad es que en el titulo solo pone "Discusion" y sobre el primer comentario veo que te molesta que un mod mande indirectas antes de banear a alguien.

 > y no sobre quien usa hacks y quien no usa hacks.

No veo ningún comentario en este ticket mio ni de mith señalando a alguien.


> Está claro y admitido que hemos usado xRay en mi fac, 

Clarísimo, múltiples bans en pocos meses.

>casi tan claro como el facto de que el xRay en este servidor ya no es utilizable.

Eso ya no esta tan claro, el que ahora mithrandircarft tenga oreofuscator no quiere decir que algunos individuos tengan otros métodos ilegítimos para encontrar menas.

> Del kill aura no haré comentarios, yo no se como va eso, no tengo ni idea de como se juzga.

kill aura: digamos que es como un campo en el que cualquier individuo que se acerque sera automáticamente dañado por el usuario del jack (aun estando de espaldas) y no confundir con aimbot.

> Desde mi punto de vista ellos no lo utilizan, ni lo han utilizado y confio en la palabra de ellos

Estas acusando a moderadores de que no tienen ni idea de lo que hacen sin tu ni siquiera saber con certeza de que ellos no usan hacks?

> igual como vosotros decís que ellos sí utilizan kill aura y confiais en lo que se dice entre vosotros.

Así no funcionan los moderadores, si fuese por tu criterio abría muchísimas mas personas baneadas. Presupones que nuestras decisiones son basadas en la fe y la magia nosotros solo creemos en la magia(solo mith).

Cuando un moderador banea a alguien sobretodo si es un ban de meses el jugador en cuestión a sido chequeado por prácticamente todos los moderadores que son activos en pvp, eso quiere decir que durante semanas el jacker se a trabado en pvps contra mods y han visto claras señales de que usa hacks.

> Un jugador necesita pruebas para acusar a otro de haber utilizado un hack. Un moderador no, y cuando llega el momento de juzgar el caso se tiene que confiar en la palabra de los moderadores, pero no se confía en la palabra de los jugadores.

Y es como funciona en cualquier otro lado, si en algún server no se sigue esta formula es porque deben de tener como 9000 mods y prefieren no tener un server vació.

El rango de moderador en mithrandircarft no se compra con cupos de descuento, son personas seleccionadas por mith a las que el considera de confianza. Para que veas lo difícil que es entrar en el rango mod, desde principios de verano solo a entrado un moderador nuevo y teniendo la capacidad de banear como máximo de un día. Unos cuantos meses verdad?

> Lo justo sería que los moderadores tambien tuvieran que hacer capturas de pantalla o videos para hacer un ban, así los jugadores acusados no podrían negar las irreputables pruebas.

Eso es justamente lo que no tendrían que hacer. Se les otorga un rango y confianza no es necesario nada mas para banear. El tener que demostrar constantemente con pruebas irrefutables el baneo de una persona es algo tedioso.

Esto de que se exija a los moderadores que demuestren sus bans no es nada nuevo anteriormente otros BANEADOS lo han echo. Saben que todo juega a su favor saben que disimulan muy bien el hack y que lo utilizan lo justo para no levantar sospechas y SABEN que probablemente el ban este basado en pequeños deslices que han tenido durante las semanas que han sido observados.

> Vosotros afirmais que hablais unos con otros, sois tantos moderadores en el servidor, e incluso hay dos administradores que pueden entrar de forma invisible a tu facción y espiarte y ninguno de vosotros puede conseguir una prueba antes de hacer un ban apropiado?

No estamos obligados a presentar ningún tipo de prueba al baneado por lo dicho en la citación anterior. 
Es mas yo ni puedo grabar mis partidas porque tengo un ordenador que da pena y en el hipotético caso de que consiga subir el vídeo a internet se verían pixels, seria como ver minecraft en 2D.

Que conveniente seria para los acusados que yo no pueda demostrar nada por falta de recursos, verdad?

> Espero que esto se tome en consideración. Eso es todo lo que tengo que decir sobre los hacks y los bans en este servidor, pero mi opinión es irrelevante, vosotros haréis lo que querrais y yo lo respetaré.

ok

**Comment by KawaiiGNE** [comment]
KawaiiGNE presente, a mi ya se me ha expulsado por "aimbot" en cualquiera de los casos ahora siempre que juego en pvp grabo todo lo que hago para poder defenderme, ya que no me queda otra, mi palabra no vale en contra de lo que me digan los mods, espero que las capturas en video valgan al menos, también en caso de ser necesario puedo stremear si me lo piden, ya que no subo todos los vídeos que grabo al entrar en pvp.

**Comment by Catadolfa** [comment]
No Kevin, no vale la pena porque claramente la confianza otorgada por el administrador a los moderadores vale mas que cualquier prueba física que tú poseas, tu palabra no vale nada y mereces ser tratado como basura porque has incumplido las normas. Arde en el infierno, pues estás en insquisicióncraft y la palabra de aquellos que no posean una placa tras su nombre no debe ser tomada en cuenta pues son simplemente basura de clase media. Tambien sé jugar al sarcasmo Don Beemo.

**Comment by UnicorniaxD** [comment]
Nadelina con todo el cariño y con todo el respeto al servidor. Acaso no te das cuenta que de lo que nos quejamos es por el bien del servidor? Entrar al server y que lo primero que lees sea.. HACKS ..Se crear un """ambiente un tanto desmotivador"",<- (me dije la gente que intento atraer al server pero se largan) por que gracias a que vosotros los MOD usais la palabra hacks para todo, ahora todo el mundo la usa. Pero adelante, hagan lo que quieran. Yo paso de comentar mas.Quieres seguir diciendome hacks? sin problema te doy mis datos me lo comentas en faceebook,vlog etc etc pero el resto de la gente que juega al servidor no tiene que pagar ni leer cosas que no se tendria que estar permitido decir.

**Comment by Ivanovic24** [comment]
La palabra de todos cuenta, si fueramos inquisicioncraft, hubierais recibido ya la pena de muerte

**Comment by MithrandirCraft** [comment]
Los peores hacks serán erradicados eventualmente, os lo puedo garantizar.

En ese momento, dejarán de producirse estas paranoias, pero por el momento, confió en el criterio de mis moderadores. 
Si creéis que podéis hacerlo mejor, podéis aplicar vosotros mismos para Moderación, si no os gusta el sistema, y queréis que todos los moderadores proporcionen pruebas a aquellos expulsados que lo soliciten (Porque supongo que creéis que merecen mas atención y perdida de tiempo con sus casos), podéis cambiar el sistema desde dentro, y ser vosotros los primeros en aplicar esta metodología: Expulsion - Reclamación - Justificación detallada.

Me gustaría tener en cuenta los puntos de vista, ideas y aportaciones de todos aquellos que tengan algun tipo de voluntad de aportación hacia el servidor, pero no dispongo de tanto tiempo, y no es mi función mas importante como Administrador. Pero como me gusta decir, si creeis en vuestros ideales, seguid el proceso adecuado y formareis parte de "la inquisición" que supongo consideráis tan cerrada, para cambiarla vosotros mismos.

**Comment by Nepo23** [comment]
Lo mismo que te dije Generalizando, los mod´s.
No hay peleas, es claro mencionar que la reputacion, el historial es tomando en cuenta a la hora de tomar deciciones y de como observamos las pruebas.
No tendriamos que desmostrar con pruebas fisicas, es buena tu opinion y la respeto, pero por cada ban tendriamos que llenar con las pruebas, todo un foro para esa persona, dejando de lado que si mostramos las pruebas con mas razon se haria publico, o si en este caso decidieramos que solo las observaran ciertas personas, queda obsoleto mostrar pruebas ya que el mismo jugador sabe por que lo han baneado. 
Solo le dariamos un intento penoso por rescatarse, si que seria penoso.
Luego al punto que quieres llegar es como tu mencionaste democracia, pero como jugador estas sujeto a normas del servidor, eres un jugador que te ha gustado el servidor y quieres seguir jugando. Pero como todo estas sujeto a normas, reglas y nosotros ya damos por hecho que has aseptado estas normas, y que aseptaras las consecuencias de tus acciones. 
Si es vrd que toda la fac queda en duda, y es claro como has iniciado refireindote a mod's, son tus compañeros es muy dificil que no sepas como juegan y que tan respetuosos son.
De mi parte creo que es necesario mas un acercamiento verbal y demostrarles que puede ser muy divertido jugar cumpliendo las normas y ser menos paranoicos XD.

**Comment by Catadolfa** [comment]
Cuando digo que se necesitan pruebas, no digo que se necesite llenar todo un formulario, digo que es bueno tener una prueba fisica para que cuando el jugador entre con otra cuenta y diga "oye, por que me has baneado si soy inocente", tú puedas respaldar tu ban con tu prueba. Es que los mods no son humanos y no cometen errores? Confio en que mith elige a sus moderadores cautelosamente, pero tambien confio en que cualquier humano puede cometer errores.

**Comment by Catadolfa** [comment]
Pero la verdad no quiero discutir mas este ticket, he intentado parar peleas sin sentido y esa mala fama que se va creando entre la gente que yo quiero y se me ha escupido y retregado en la cara la palabra hacks incontables veces. Simplemente no me conectaré mas al server porque con gente tan repelente se me quitan las ganas.

**Comment by BlackBeemo** [comment]
> es bueno tener una prueba fisica

En el caso de xrays se delatan ellos mismos y los bans los suele efectuar un admin o se hacen a petición de uno.

Luego están los flipados que solo entrar al server se ponen a minar y en 5 minutos tienen 100 diamantes. Tu realmente crees que alguien jugando solo en un server nuevo es capaz  de minar mas diamantes que piedra? Mi respuesta es obviamente no y se le banea, pero claro según tu eso es muy injusto, necesitaría pruebas y como no tenemos freecam pues el chico tan feliz con su paja mental asta que un admin se tenga que encargar de el.

En el caso de jacks o se graba o no hay prueba no hay mas misterio y enseñarle el vídeo al chico es otro paso. Si alguien me obliga a llegar tan lejos solo para que no me toque las narices lo baneo 99 años.

Esto ultimo equivaldría a rellenar un formulario(lo de los 99 años no lo otro).

> "oye, por que me has baneado si soy inocente"

Lo primero que hacen todos es aferrarse a su presunta inocencia, lo tienen muy bien aprendido de las películas. Tu fac a echo exactamente eso en anteriores ocasiones. La señorita Tianna fue baneada por mi. Su gran capacidad de deducción le hizo pensar que la banee y que no tenia pruebas lo único que ella no sabia es que un admin la estaba observando un buen rato. 
También esta el legendario caso de Galletitas, en su primer ban abrió un ticket rajando, después del reset se le perdono, estuvimos unas semanas intentando pillarlo infraganti nos tenia bien mareados a todos(son de los que saben usa el jack bien), asta que el legendario admin con gafas de sol lo pillo farmeando con el aimbot activado, al chico no se le ocurrió otra cosa que fardar de sus 100 niveles en el chat publico. 
Así es como caen todos, el que usa jacks o xray suele tener un ego enorme, es tan grande que terminan por autobaneandose.Banhammer debería permitir el autoban, nos quitaría mucho trabajo.

Lo que vengo a decir es que si no hay incentivos de admitir su pecado no lo aran, nunca lo hacen a excepción de cuando se van del server, entonces si que pavonean de lo fácil que era usar jacks en este server y empiezan a rajar y rajar asta que se dan cuenta de que los tengo en ignore.

> Es que los mods no son humanos y no cometen errores?

Si, cometemos errores y rectificamos.

Si, cometemo errores y rectifico(ya he desbaneadoa por mala decisión). Hubo un caso en el que nadie nunca había dado la nota con los jacks y fueron siempre muy educados tanto en el chat interno y en el sistema de tickets, los termine desbaneando.

> Pero la verdad no quiero discutir mas este ticket, he intentado parar peleas sin sentido y esa mala fama que se va creando entre la gente que yo quiero y se me ha escupido y retregado en la cara la palabra hacks incontables veces. Simplemente no me conectaré mas al server porque con gente tan repelente se me quitan las ganas.

Cada uno es responsable de su propia fama si andas con gente que usa jacks es tu decisión, acepta las consecuencias.

**Comment by MithrandirCraft** [comment]
@Catadolfa El factor humano no debería condicionarte, si alguna vez deseas ignorar a alguien (Incluso a un staff, aunque no sería recomendable) Puedes utilizar el comando /ignore <jugador>

No deberías sentirte intimidado por algun staff si ese es el caso, puesto que puedes venir aquí en cualquier momento a reportar cualquier caso de abuso (Pero asegurate de proporcionar pruebas).

Puedes jugar en MithrandirCraft con total libertad, todo el mundo es bienvenido siempre y cuando respete la normativa.

Desde el entorno de staff, nunca se dará un trato distinto a nadie, incluso si ha tenido un mal historial en el pasado. Juega legal y responsablemente.

Disculpa cualquier grosería que haya podido decir Beemo, no esta muy involucrado últimamente en asuntos de juego, pero sin embargo, cree bastante en nuestro sistema de aplicación de castigos actual, y además le gusta pegar bastanta caña en los comentarios xD
