### ISSUE TITLE
Mithrandir - UnBan

### ISSUE THREAD

**Issue by lukrr** [MithrandirCraft/MithrandirCraft#140]
Holas.

Soy lukrr, el chico que le quito la cuenta a andrescol, queria venir a hablar de eso, mire, yo no suelo hacer ese tipo de cosas, pero llegue a odiar tanto a los jugadores Hurtorema y Pepapig, los cuales pertenecen a una fac de 5 o 6 players, lo que se me hace imposible para mi poder luchar solo contra 5 juntos, por lo tanto, veia que en pvp no podia porque eran muchos, y se me dio por quitarle la cuenta a un amigo de ellos, para intentar desde esa cuenta llegar hacia ellos y destruirlos, queria pedir perdon, puedo devolverle las cosas a andres, esque me gusta el server, pasaba varias horas jugando en el, y no quisiera que me den ban, fue un error mio y lo se, quisiera poder volver a jugar y que no vuelva a pasar lo de intento de robo de cuenta, porfavor.
Otra cosa, esa fac me acusa de KillAura, pueden revisarme si es necesario, siempre me decian hacker pero nunca me querian revisar, lo digo para que dejen de decirme hacker, si es que puedo volver al sv.
Ademas mi ip cambia cada 12 horas, podria entrar con otra cuenta cada 12 horas, pero prefiero arreglar las cosas e usar mi username original antes que ser un infiltrado.

Saludos Mithrandir.

**Comment by BlackBeemo** [comment]
Supongo que el admin se a tenido que calentar la cabeza para averiguar quien fue el que le robo la cuenta a ese chico, a tenido que invertir un tiempo en ti y tu caprichito para arreglar el tema y tu en ese tiempo ni te molestaste en devolver la cuenta.

No mendigues perdón cuando no as echo absolutamente nada para merecerlo.

**Comment by MithrandirCraft** [comment]
Redime tu expulsion: http://www.mithrandircraft.enjin.com/#desban-190376

Paga el daño que has hecho.

**Comment by lukrr** [comment]
Man no voy a pagar 20 dolares por un desbaneo, e leido otros que son hackers, piden perdon y les desbanean, le puedo devolver las cosas pero quiero mi cuenta.

**Comment by Ivanovic24** [comment]
No es lo mismo ser hacker que robar una cuenta. Siendo hacker perjudicas a un usuario en el momento, es mas grave robar la cuenta a un usuario especifico, ademas investigarte y pillarte conlleva unos gastos y esfuerzos.
O contribuyes economicamente al servidor para ser desbaneado, o afronta las consecuencias

**Comment by xLebet** [comment]
Lukrr, hace varios dias, me atreveria decir que hace 1 semana te encontre entrando con cuentas de otros usarios, y te lo adverti, ahora tienes que cumplir el castigo.

**Comment by lukrr** [comment]
Otros usuarios? solo intente con uno
