### ISSUE TITLE
Mithrandir - Propuesta

### ISSUE THREAD

**Issue by lukrr** [MithrandirCraft/MithrandirCraft#141]
Buenas

Aqui lukrr, por si me quitan el ban les traigo propuestas, 1) me gustaria que en /warp pvp, en las zonas donde no hay drop y no se permiten perlas ni magia, que tmb no se te rompa la armadura, ya que para que quieres luchar ahi, si te rompes la armadura nomas y no ganas nada a cambio, ademas, hay vips y mods, que se reparan la armadura, mientras q los users normales no pueden, y ello lleva a q la mayoria de los q van a warp pvp son mods, vips, o amigos de vips a los cuales los pueden reparar.
Por ejemplo, a mi me gusta el pvp, pero todos pasan en /warp pvp, asi que nunca puedo luchar contra otras personas que tengas cosas op como yo, y no voy a /warp pvp por el unico motivo de que se me daña la armadura y tengo que conseguir 32 lvls para reparar 200 aprox de cada parte de mi armadura, quiero reparar mi armadura y paso tooodo el dia consiguendo niveles.

2) Ya saben que si tienes 1 arma muy op, no le puedes cambiar el nombre, meterles nuevos enchants, o repararla, porque te aparece "Muy Caro", yo conozco de un plugin, no recuerdo el nombre, pero lo usaba en un server de un amigo, el cual por lo q recuerdo quitaba eso, por lo tanto solo costaba nivel y mineral, y no te aparecia "Muy Caro".

3) Otro plugin llamado "NameTagEdit" hace que cuando apretas "TAB" aparece el nombre de cada jugador, esto es normal, pero a los MODS, ADMINS, etc, puedes modificarlo para que les aparezca "(MOD) "name", (ADMIN) "name", etc, para que los jugadores sepan si hay mods o no, ya que actualmente apretas TAB y no aparece quienes tienen rango, estos plugins los conozco y se usarlos porque los tenia anteriormente en mi sv, el cual ahora esta cerrado, si no sabes bien usarlo te puedo hechar una mano.

Saludos
lukrr

**Comment by MithrandirCraft** [comment]
Buenas tardes.

La verdad, hay que tener unas bolas bien grandes para atreverse a dar sugerencias tras ser expulsado por el administrador principal. Pero igualmente contestaré a tus comentarios ya que por lo menos te dirijes con propiedad.

1.Por lo general, las sugerencias que tendemos a recibir ya han pasado previamente por mi cabeza, y incluso he llegado a contestarlas anteriormente. En cuanto a la durabilidad de las armaduras en pvp, he llegado a la conclusión de que eliminar el desgaste de durabilidad en esas salas, no es una prioridad. (Sin embargo, siempre lo he tenido en cuenta como una posibilidad)
Siento tener que monetizar tanto, pero el servidor no se paga solo. Yo puedo seguir manteniendo este servidor por pura voluntad, pero a cambio, espero que si los jugadores quieren estar al nivel estandard, aporten su grano de arena para obtener un rango que les facilite mas las cosas (Y aún así no lo considero un desbalanceo excesivo comparado con otros servidores donde las ofertas desbalancean el juego completamente).

2.No se de que estas hablando, pero por lo visto, y comenzando por na Normativa del servidor, puedo intuír que desconoces bastantes aspectos de MithrandirCraft. Uno de los ambitos en los que mas estamos trabajando es en el sistema de jefes, que en el futuro proporcionará muchos mas recursos para quienes derroten a los jefes que estamos desarrollando. Esto debería facilitar la obtención de experiencia, y también aflojaría tu asunto #1. Como ves, el balanceo del servidor es un proceso que nunca termina.

3. No nos gusta saturar el servidor de utilidades, las mantenemos al mínimo. En esta ocasion me limito a decir simplemente que NO.

att. __Mithrandir__
Juega legal, lee la normativa: www.mithrandircraft.es/normas
