### ISSUE TITLE
Punisher y zombi oscuro

### ISSUE THREAD

**Issue by GaaZ** [MithrandirCraft/MithrandirCraft#142]
Una cantidad extraordinaria de punishers y zombis oscuros de acumulan en donde no deben, al parecer, lo hacen debido a la presencia de los aldeanos vendedores, aqui las imagenes

![2015-12-07_15 08 02](https://cloud.githubusercontent.com/assets/16198137/11641445/4e1b97d8-9d06-11e5-93ae-6055e9c29fcb.png)
![2015-12-07_15 11 08](https://cloud.githubusercontent.com/assets/16198137/11641451/548b2110-9d06-11e5-9aab-a9445a9c6717.png)
![2015-12-07_15 11 18](https://cloud.githubusercontent.com/assets/16198137/11641452/55115b90-9d06-11e5-9a12-8938d811b38a.png)
![2015-12-07_15 23 37](https://cloud.githubusercontent.com/assets/16198137/11641455/566d21b8-9d06-11e5-9952-d82510575e5c.png)
![2015-12-07_15 38 23](https://cloud.githubusercontent.com/assets/16198137/11641468/5f04be3a-9d06-11e5-9dc2-5f1169053178.png)
![2015-12-07_15 38 28](https://cloud.githubusercontent.com/assets/16198137/11641469/616e7594-9d06-11e5-84ad-75de7353d4b4.png)

**Comment by MithrandirCraft** [comment]
Ya estaba al corriente de esto. Son 2 bugs en 1.

Para empezar, no debería haber tantos zombies, y no deberían perseguir a los aldeanos xD

**Comment by MithrandirCraft** [comment]
Para el primer error, tendré que arreglar el bug de duplicaciones.
Para el segundo error tendré que reprogramarles la AI.

**Comment by GaaZ** [comment]
demasiado tarde, ya me aproveché de todos ellos xD.Pero volverán a spawnearse

**Comment by MithrandirCraft** [comment]
Mereces un ban.

**Comment by MithrandirCraft** [comment]
Vale, voy a cerrar este ticket, la AI debería estar arreglada, que es lo importante.

Las duplicaciones se arreglarán mas adelante. Reabre este ticket si se siguen comportando como imbeciles.

**Comment by GaaZ** [comment]
Reabro debido a que los mobs se han vuelto aún más imbéciles xd 

![2015-12-07_21 24 38](https://cloud.githubusercontent.com/assets/16198137/11646216/bc606016-9d29-11e5-9114-88479ed0f433.png)
![2015-12-07_21 25 03](https://cloud.githubusercontent.com/assets/16198137/11646217/bf0376d2-9d29-11e5-9049-6f7eff4954e6.png)

**Comment by MithrandirCraft** [comment]
Ok, yo creo que esto todavía se esta produciendo porque los mobs clonicos pierden su AI.
Y por ello se ponen a atacar a los NPC's...

Dejaremos este ticket abierto hasta que lo haya solucionado :) La clave está en detener esas duplicaciones.

**Comment by GabbGabb** [comment]
xD
Yo vi un tercer bug, en este caso con los Punisher.
pero en mi caso, este estaba dentro de la tienda, y andando en dirección a la trampilla, en cuanto la abrí, el Punisher salió disparado, se estampó contra la pared, y desapareció. La atravesó? Se desintegró? Regresó al Futuro con Doc & Marty? O viajó al limbo? pero como sea, ese Punisher ya no estaba ahí.
![2015-12-03_02 08 30](https://cloud.githubusercontent.com/assets/12144547/11769076/6872f828-a1df-11e5-8c6a-fca993d63639.png)
Aquí estoy yo, con mi amigo Punisher, extorsionando a Novo para que nos dé cosas.
En cuanto le abrí esa trampilla... no debí abrirla... fue muy triste xD

**Comment by MithrandirCraft** [comment]
![screenshot_1](https://cloud.githubusercontent.com/assets/6623704/11791461/76c857e8-a2a1-11e5-8738-1d820c42ff3a.png)

**Comment by MithrandirCraft** [comment]
Parcheado.
