### ISSUE TITLE
Problema con la generación de estructuras durante limpiezas de mapa (Defectos e invasividad)

### ISSUE THREAD

**Issue by darksessho** [MithrandirCraft/MithrandirCraft#143]
hola buenas tardes
soy darksessho
Me comunico para reportar, templos de mar eliminados, despues de la regeneracion que tuvo factions..

espero su respuesta, mys saludos server mithrandircraft....

**Comment by MithrandirCraft** [comment]
Buenas tardes :)

Ocurre tambien otro problema relacionado con las estructuras al regenerar el mapa, y es que algunas estructuras como minas tienden a invadir los terrenos reclamados, destruyendolos.
Por ello, hasta que no solucionemos este problema, no podrá haber otra limpieza de ningun mapa.

Tengo una pregunta para ti:

- Es posible que el terreno cercano al templo haya sido reclamado por alguien? Un reclamo podría haber hecho que se preserve la zona sin regenerar, generandose una sección de templo únicamente en wilderness o terreno sin reclamar (en caso de Survival).

-----------------------------------
Es posible que tomemos una de estas 2 acciones ante esta situación:

- Prescindir de estructuras globalmente, eso incluye prescindir de templos, minas, pueblos... (No es una solución muy agradable... pero alomejor sea nuestra única opción.)

- Procesar la generación de estructuras de forma que respeten los terrenos reclamados al regenerarse, y se generen plenamente sin errores.

**Comment by darksessho** [comment]
buenas tardes my forma de vista era:
En siglos pasados tenia my casa en templos, claimeado... pero una regeneracion hizo desaparecer el templo, al igual que spawner, el consejo mas aprovechable seria construir una casa fuera de los biomas templos, minas, aldeas, para no tener perdidas...Saludos, seguire averiguando sobre templos

**Comment by darksessho** [comment]
buenas tardes:
me comunico para saber cuando estara arreglado este bug?

saludos. como sugerencia podrian vender esponjas, mientras =)

**Comment by MithrandirCraft** [comment]
Esponjas ya disponibles en venta, en la misma tienda donde se compran.

He eliminado los datos de estructuras relacionados con templos marinos, veamos si eso ayuda a que se generen bien.
