### ISSUE TITLE
Linkear Survival con Factions_nether

### ISSUE THREAD

**Issue by AndresGatoXD** [MithrandirCraft/MithrandirCraft#144]
Mith, acaso no se puede ir al Nether en survival? lo he intentado pero no pude ir.

(Editado por __Mithrandir__)

**Comment by MithrandirCraft** [comment]
No, no es posible ir al nether desde Survival. Tenemos una aclaración sobre ello en las faq's del servidor: www.mithrandircraft.es/faq

Sin embargo (y no prometo nada), pensaré en algun metodo eficaz para que los portales lleven al nether, teniendo en cuenta que seguramente no compartirá el inventario de Survival.

En cuanto al aldeano de las tierras hechizadas, efectivamente, no sirve de nada tener tierras hechizadas sin tener un intercambiador :P Arreglado!

**Comment by MithrandirCraft** [comment]
No conectaremos los portales, y no generaremos un nether para survival.

Sin embargo, comprendemos que Survival es un mundo muy aislado, y terminaremos haciendo algo al respeto, pero ten en cuenta que el modo principal es Factions.
