### ISSUE TITLE
Cerebrales locos

### ISSUE THREAD

**Issue by GaaZ** [MithrandirCraft/MithrandirCraft#145]
Los cerebrales suelen disparar a la nada de vez en cuando.
![2015-12-10_12 38 50](https://cloud.githubusercontent.com/assets/16198137/11727189/896cedb8-9f50-11e5-812d-2b79a1980bea.png)
![2015-12-10_12 39 00](https://cloud.githubusercontent.com/assets/16198137/11727191/8b082ed0-9f50-11e5-8621-bf0f0d699904.png)
![2015-12-10_12 39 24](https://cloud.githubusercontent.com/assets/16198137/11727192/8f20abaa-9f50-11e5-9e2a-aefb24c0d99b.png)

A no ser que eso sea normal, no me molestaré con tener que atacarlos así xd

**Comment by GabbGabb** [comment]
No disparan a la nada,  pero a veces ocurre, que debido a la acumulación de Cerebrales, estos acaben disparandose entre ellos, generando un enfrentamiento entre dos o mas Cerebrales, esto añadiendo lo de su molesto retroceso, hace que algunos Cerebrales queden bugeados, como cuando el rey zombie caía al piso de abajo, pues el Cerebral bugeado igual, y por eso es posible que acaben disparando al suelo, o al techo como retardeds xD

**Comment by MithrandirCraft** [comment]
Ok, esto podría estar arreglado mañana a partir de las 6 A.M, hora española.

**Comment by MithrandirCraft** [comment]
Nope. Aún estoy trabajando en ello.

**Comment by ZertahhLoL** [comment]
Para que dejen de bugearse no se podría aumentar la resistencia a el empuje de los celebrales?

A su ves esto conllevaría a que estén muy rotos y haya que nerfearles un poco la vida o el daño.

**Comment by MithrandirCraft** [comment]
¿Esto sigue ocurriendo? La verdad es que es un comportamiento vanilla, pero quizá podamos parchearlo nosotros, por eso sigue abierto desde hace tanto tiempo (No lo consideramos prioritario).

**Comment by MithrandirCraft** [comment]
Cierro este ticket, que ya lleva demasiado tiempo abierto. Lo voy a considerar pulido de jefes, puesto que no es demasiado grave.
