### ISSUE TITLE
El maestro dando lecciones

### ISSUE THREAD

**Issue by GaaZ** [MithrandirCraft/MithrandirCraft#146]
Esta vez el maestro sí se pasó de la raya xD
![2015-12-10_13 23 18](https://cloud.githubusercontent.com/assets/16198137/11727341/5499687c-9f51-11e5-939f-7b9fd41d77be.png)
![2015-12-10_13 23 47](https://cloud.githubusercontent.com/assets/16198137/11727343/56fe4dd0-9f51-11e5-8db6-a7aae50c536b.png)
![2015-12-10_13 27 50](https://cloud.githubusercontent.com/assets/16198137/11727346/59b674a8-9f51-11e5-9b14-96b5bee1ea6d.png)
![2015-12-10_13 28 06](https://cloud.githubusercontent.com/assets/16198137/11727348/5a5826e0-9f51-11e5-80f0-99cb6b3ef3e4.png)

**Comment by AndresGatoXD** [comment]
LOL medio server contra el Maestro xD

Ademas, hay veces que las personas se mueren y aparecen en el Spawn (normal) pero el Maestro lo sige y se va hasta alli. es rencoroso xD
![2015-12-08_08 15 30](https://cloud.githubusercontent.com/assets/16181320/11741236/57856678-9fd6-11e5-8f77-37564f17afac.png)

**Comment by MithrandirCraft** [comment]
Bueno, al menos estas experiencias hacen que la gente se de cuenta de que existen los jefes xD seguro que les parecerá una experiencia memorable y original :)

**Comment by GabbGabb** [comment]
Voto por un jefe invencible que vaya por el spawn, pueblo, eventos etc a sus anchas. Haciendo publicidad, y atacando a todo ser que le desafie xD

**Comment by MithrandirCraft** [comment]
Confirmen que esto esta arreglado.

**Comment by MithrandirCraft** [comment]
Voy a tomar este error por "Feature", ya que no lo considero demasiado grave, y le da cierta profundidad a la batalla.

El problema parece ser que el jefe tarda más de lo que debería en regresar a su spawn al exceder el maximo radio de movimiento. Pero eventualmente acaba volviendo.

Esto otorga mas profundidad a la batalla, ya que permite al jefe alcanzar jugadores fuera del radio durante un rato.
