### ISSUE TITLE
Cobardes en PVP

### ISSUE THREAD

**Issue by AndresGatoXD** [MithrandirCraft/MithrandirCraft#147]
Ya estoy harto de esta gente que se aprovecha de la "linea segura", pueden provocar ellos PVP pero no nosotros y sacan ventaja.

![2015-12-12_06 32 30](https://cloud.githubusercontent.com/assets/16181320/11761282/da275efa-a09a-11e5-818e-2c75844bc609.png)

**Comment by MithrandirCraft** [comment]
Creo que entiendo lo que quieres decir.

Ya hemos cubierto a los cobardes que se esconden por allí dentro al iniciar un pvp, pero nos faltaría detener esos flechazos verdad? Sería solo cuestión de rediseñar esa sala.
