### ISSUE TITLE
/sethome en eventos

### ISSUE THREAD

**Issue by Catadolfa** [MithrandirCraft/MithrandirCraft#148]
Aun sigue el bug del sethome en eventos para los vip+
![screenshot_2](https://cloud.githubusercontent.com/assets/15986291/11763702/d9c526b6-a0e2-11e5-9771-cfd5399c305b.png)
![screenshot_3](https://cloud.githubusercontent.com/assets/15986291/11763701/d9c435a8-a0e2-11e5-8f40-7f0caab9f607.png)

**Comment by MithrandirCraft** [comment]
Arreglado. Las homes de pvp-event serán retiradas.
