### ISSUE TITLE
Los minijefes curando

### ISSUE THREAD

**Issue by Catadolfa** [MithrandirCraft/MithrandirCraft#149]
No estoy segura si esto es un bug, pero me imagino que sí. Los minijefes como Escuderos, Espiritus del fuego (vulcano), Zombi escarlata, Zombi esmeralda y Zombi cobalto (rey zombi) en vez de hacerme daño me curan. Nose si soy la única o hay otros jugadores que se encuentran con el mismo tipo de bug.

**Comment by MithrandirCraft** [comment]
Confirma que esto esta arreglado.

**Comment by Catadolfa** [comment]
No, el bug no está solucionado. Si prefieres susurrame cuando me veas online para que yo pueda enseñartelo y tú puedas hacer pruebas.

**Comment by MithrandirCraft** [comment]
@Catadolfa No puedo reproducirlo. Podrías indicarme con que mobs te ocurre?

**Comment by Catadolfa** [comment]
Escuderos, Espiritus del fuego , Zombi escarlata, Zombi esmeralda y Zombi cobalto

**Comment by Catadolfa** [comment]
Me encuentro ahora mismo en Torre Eliptica, y voy a hacer algunas pruebas para ver si se trata de los mobs o de la armadura. Creo que es la armadura de irrompibilidad 4 lo que está bugueado

**Comment by Catadolfa** [comment]
He echo unas pruebas y se ve que los mobs te curan en relación a la protección que tengas. Por ejemplo si vas con una armadura de diamante p4 te curarán 3 corazones con cada golpe, si vas con armadura de hierro te curarán 1 corazón cada 2 golpes, si no llevas armadura te harán daño.

**Comment by Catadolfa** [comment]
Algun progreso?

**Comment by MithrandirCraft** [comment]
Estoy intentando reproducir esto con las armaduras que tu dices. Parece que esta vez si está arreglado, confirmamelo.

**Comment by MithrandirCraft** [comment]
Vuelvo a cerrar, comenta si estamos en las mismas xD o encuentras otra forma de reproducirlo.
