### ISSUE TITLE
desaparicion de objetos

### ISSUE THREAD

**Issue by supercool55** [MithrandirCraft/MithrandirCraft#15]
Debido a no poder minear por el lag mi faccion peritas obtuvo sus recursos mediante el sistema propuesto por el juego, el sistema esmeraldas, nos esforzamos mucho haciendo lo que debido al lag era lo menos complicado para nosotros. Matar infinidad de bichos para obtener cabezas para vender y sacar estas tan preciadas esmeraldas, las cuales empleamos en obtener productos tales como una pareja de spawmers de cada animal para poder reproducirlos, así como los nuevos soportes para armaduras que desaparecieron con nuestras armaduras de diamantes mejoradas puestas, ademas de nuestros caballos con las monturas y armaduras, solo quedó uno al cual aún no le habíamos comprado aún la armadura. Hecho en falta alguna cosa más pero eso ya no sabría cuantificarlo.
Nos gustaría poder recuperar los objetos que se borraron por falta de memoria del servidor si esto fuese posible ya que nos costo innumerables horas de juego.

Un saludo, atentamente Supercool55.

**Comment by MithrandirCraft** [comment]
Por lo visto todas estas perdidas pueden compensarse con esmeraldas.

Te devolveré unas cuantas.

**Comment by supercool55** [comment]
Ya las he recibido, muchas gracias como poco pareces una persona lógica y razonable. Lamento mi impetuosidad en el juego pero trata de entender el palo de perder lo perdido tras todo el esfuerzo.

Un saludo y muchas gracias de nuevo, supercool55
