### ISSUE TITLE
Coordenadas de deslogueo/logueo incorrespondidas

### ISSUE THREAD

**Issue by PokeFury** [MithrandirCraft/MithrandirCraft#150]
Hola, quiero reportar un bug... el bug consiste que cuando te desconectas en un lugar apareces en otro. por favor arreglenlo

**Comment by MithrandirCraft** [comment]
Porfavor, procura mejorar tu ortografía de cara a futuros reportes.

Por suerte, he conseguido comprender lo que me intentas decir, pero no podría haber tanta suerte mas adelante si no te esfuerzas un poco mas xD

Estoy al tanto de este error, y lo estoy arreglando :)

**Comment by PokeFury** [comment]
Ya ya, es que me acabo de levantar u.u pero grac

**Comment by MithrandirCraft** [comment]
Arreglado. Reabran este ticket si se vuelve a producir.
