### ISSUE TITLE
Cuando me conecto no aparezco en el ultimo punto de desconexion, aparezco en un punto que en mi vida visite.

### ISSUE THREAD

**Issue by JuaniTortitah** [MithrandirCraft/MithrandirCraft#152]
Es un bug, me han dicho eso los admines, quisiera saber si se puede arreglar, gracias.

**Comment by MithrandirCraft** [comment]
https://github.com/MithrandirCraft/MithrandirCraft/issues/150

**Comment by JuaniTortitah** [comment]
Bueno, gracias Mithradin, espero el arreglo :).

**Comment by MithrandirCraft** [comment]
Reabro, sigue habiendo unos problemas con esto.

**Comment by MithrandirCraft** [comment]
He purgado las posiciones bloqueadas de todos los usuarios. Alguien sigue experimentando este error?

**Comment by Ivanovic24** [comment]
Si yo

**Comment by MithrandirCraft** [comment]
@Ivanovic24 Llevas 2 días y 11 horas sin conectarte. Como puedes decir tan a la ligera que sigues experimentando este error?

**Comment by MithrandirCraft** [comment]
Lo doy por solucionado, gracias por la extensa operación.
