### ISSUE TITLE
Mithrandir - UnBan

### ISSUE THREAD

**Issue by lukrr** [MithrandirCraft/MithrandirCraft#153]
Mithrandir, ya pls pueden desbanearme? ya llevo bastante tiempo sin jugar en el sv, ya aprendi la leccion T_T no sean malos dejenmen volver...

lukrr

**Comment by MithrandirCraft** [comment]
Buenas tardes

En correspondencia con el nombre de usuario que utilizas en GitHub:
"lukrr" fue expulsado por infligir la norma 11. Una norma cuya violación se considera de nivel 'A' Grave.

Es responsabilidad de los jugadores leer la normativa en www.mithrandircraft.es/normas o /rules (ingame). Los jugadores que no respeten la normativa deberán asumir las consecuencias o redimir su expulsión mediante una aportación económica al servidor.

**Comment by lukrr** [comment]
Pues claro, cuando me baneraon vi que otro puso aqui que pedia perdon por usar hack, y lo desbanearon como si nada, claro, como el afecta a todos los del server usando hack lo desbanean, mientras que yo solo afecte al que le robe la cuenta, pues claro, a mi me banean permanentemente, logica.

**Comment by Ivanovic24** [comment]
A un hacker se le puede esquivar dentro del juego, simplemente evitandolo y ademas es mas facil de pillar.
Robar una cuenta no es tan facil de descubrir, ademas de que puede afectar gravemente al jugador perjudicado.
Asume tus consecuencias.

**Comment by lukrr** [comment]
Evitar? claro, si te viene a robar la fac? te vas y dejas que te robe todo? al tio al que le saque la cuenta le devolvi la mitad de las cosas, porfavor, no creo que el/los hackers te devuelvan las cosas luego de matarte, ademas no siempre se sabe si alguien es hack, puede no usar killaura pero si usar wall para ver cofres, facs, etc.

**Comment by lukrr** [comment]
Solo quiero volver a jugar en el sv con mi cuenta Original, y no hare mas eso de robar cuentas, SOLO QUIERO JUGAR.

**Comment by Catadolfa** [comment]
Eh, si tan bueno eres devuelveme la P4 que me robaste cuando me pediste que te hiciera tp desde la cuenta de Andres. O devuelve las p4 a todos los que has matado usando tu kill aura, que diga, tus fabulosas habilidades de artes marciales megaop que has aprendido de Kung Fu Panda.

**Comment by lukrr** [comment]
Ja, me banean y queres que te devuelva la P4, que te den, y todavia dice killaura jaja

**Comment by Catadolfa** [comment]
Solo lo decía para mostrarte que no solo has afectado al jugador de la cuenta que has entrado. Ademas, para que quieres que te dejen volver si tienes tu cuenta de Jason? :3

**Comment by lukrr** [comment]
Porque no quiero usar otras cuentas, y si hablas de otras cuentas, tengo Jason, MrBuilder, MCbuilder, entre otras, con las q puedo publicar ips de otros svrs para que algun q otro jugador entre a otro sv a probarlo, tal vez le guste mas q este c:
