### ISSUE TITLE
 Mantenimiento, duracion indefinida del server mmm que sucedera

### ISSUE THREAD

**Issue by darksessho** [MithrandirCraft/MithrandirCraft#154]
hola buenas tardes:

me comunico para saber cuanto duraria el mantenimiento, que efectos o consecuencias, habra pasado... me gustaria saber un informe de habra alguna modificacion, mejoras, arreglo de bug

**Comment by MithrandirCraft** [comment]
facebook.com/Mithrandircraft

Toda la información diaria sobre el servidor puedes leerla siempre en este grupo de Facebook.
