### ISSUE TITLE
Ender Chest troll :C

### ISSUE THREAD

**Issue by FlowerSwag** [MithrandirCraft/MithrandirCraft#156]
me ayudas mith? compre la version gratis del vip (osea que no la compre realmente) y puse cosas en las 2 barritas extra del ender chest, pero a los 2 dias  cuando se me fue el vip las cosas de el ender chest se abian ido, me gustaria que me debolbieran mis cosas.

**Comment by MithrandirCraft** [comment]
No pueden desaparecer. Lo que si puede ocurrir es que cuando abras el cofre, el contenido de esas 2 barras caiga encima tuyo.
