### ISSUE TITLE
Quiero Un Ban

### ISSUE THREAD

**Issue by vegetagamer9** [MithrandirCraft/MithrandirCraft#158]
Reconozco que MithrandirCraft es un gran server y no se porque me baneron me dice que publicidad abusiva el caso es que he comprobado mi dirección ip y todo eso y no entraron con mi cuenta sino que con mi portátil yo no fui sólo quiero que me digan que día hice tal cosa y miraré una cosa :/ esperó que den un ban

**Comment by vegetagamer9** [comment]
Perdón es UnBan

**Comment by vegetagamer9** [comment]
Que día y que hora

**Comment by MithrandirCraft** [comment]
Buenas tardes. Basandome en la expulsion relacionada con el usuario "vegetagamer9" realizada el 20 de Noviembre a las 27:57 con el motivo "Publicidad reiterada".

Creo recordar que el nombre fue expulsado de forma permanente por estar publicitando otros servidores.

Es responsabilidad de la persona que crea la cuenta, todo lo que ocurra en dicha cuenta. Si no fuiste tu quien estaba usando la cuenta "vegetagamer9" en ese momento, sigues siendo responsable de lo que haya ocurrido en ella.

Puedes redimir la expulsión de cualquier usuario mediante este enlace:
http://www.mithrandircraft.enjin.com/#desban-190376

Lee la normativa: www.mithrandircraft.es/normas y juega legal.
