### ISSUE TITLE
Cuenta robada.

### ISSUE THREAD

**Issue by Catadolfa** [MithrandirCraft/MithrandirCraft#159]
Alguien ha intentado acceder mi cuenta probando varias contraseñas, sin éxito alguno. Sin embargo, alguien ha conseguido acceder a la cuenta de mi hermano, le ha cambiado la contraseña a su cuenta y le ha puesto mi skin.

**Comment by Catadolfa** [comment]
La cuenta es AndreMorenoPais. Yo hago el reporte porque el solo tiene 6 años.

**Comment by MithrandirCraft** [comment]
Hemos arreglado el sistema de recuperación de contraseñas. Por lo tanto, si tu hermano ha registrado un email con su cuenta, no tendrá problema en reestablecer su contraseña.

La seguridad y complejidad de la contraseña que establezcais, o el acceso a vuestras sesiones abiertas es responsabilidad vuestra.

Nosotros ponemos la seguridad interna y encriptación de las contraseñas, para que nadie, incluso nosotros no podamos leerlas. Y tambien proporcionamos consejos de seguridad que llevan ya un tiempo en el foro (Aunque no se utilize mucho).

**Comment by lukrr** [comment]
xD
