### ISSUE TITLE
reporte de fallo en tiendas

### ISSUE THREAD

**Issue by supercool55** [MithrandirCraft/MithrandirCraft#16]
No me deja comprar en las tiendas ni a mi ni a nadie de mi facción.

Un saludo y gracias, Supercool55

**Comment by MithrandirCraft** [comment]
Grácias por reportar esto, lo revisaré.

**Comment by supercool55** [comment]
Recibido y gracias

**Comment by supercool55** [comment]
hice lo que me dijiste y sigue sin funcionar mi tienda :(
A ver si puedes echarle un vistazo.

Gracias, un saludo supercool55

**Comment by supercool55** [comment]
Ah por si te sirve de algo a mi no me deja comprar en ninguna tienda puesta por otro jugado, con lo que pienso que el problema es de mi perfil o algo

**Comment by MithrandirCraft** [comment]
Lo investiragé.

**Comment by MithrandirCraft** [comment]
Soy incapaz de reproducir tu problema, con una cuenta normal.

Debo indicar, que realizar compras en tu propia tienda no está permitido (bloqueo de seguridad), pero realizar compras en cualquier otra tienda si debería ser posible.

Si sigues teniendo esto problema, y no es demasiado pedir, agradecería que grabes el error con las tiendas detalladamente, y pasarme un enlace a tu video.
