### ISSUE TITLE
Las palabras Bonitas de Zozap hacia a mi. Miercoles 17:33

### ISSUE THREAD

**Issue by UnicorniaxD** [MithrandirCraft/MithrandirCraft#160]
<a href="http://es.tinypic.com?ref=10fq784" target="_blank"><img src="http://i65.tinypic.com/10fq784.jpg" border="0" alt="Image and video hosting by TinyPic"></a>

**Comment by MithrandirCraft** [comment]
Utiliza /ignore si alguien te molesta. 
No parece un caso de demasiado serio de acoso, sino mas bien una especie de niñada por parte de ese jugador, y sin duda, no carece de un incentivo por tu parte para alimentar su actitud.

**Comment by UnicorniaxD** [comment]
Injusto pero no problema :) Pero me parece denigrande que permitan ese vocabulario así cuando juegan niños de todas las edades.

Pero! Tu server tus normas.
