### ISSUE TITLE
Denigrante tener gente así de PB de un Servidor.

### ISSUE THREAD

**Issue by UnicorniaxD** [MithrandirCraft/MithrandirCraft#161]
Todos los días nos acusan de hacker, hasta a mi que no juego pvp ._. (tengo pantallazos que no pondré para no perder mas el tiempo).

Hoy,  entra Toby_ juega contra kraz1234 un pvp y lo banean 6 meses por hacker, ok!
Aqui teneis lo que se llama una prueba de verdad de un hacker elegido PB por el equipo  de Mithandicraft. 
Buen trabajo. 
https://www.youtube.com/watch?v=QYSiQWGQOqo&feature=youtu.be
Minuto: 5:00

Nosotros siempre tenemos pruebas de  según los Mods somos "hacker" y no la tienen  en cuenta.
Nos acusan de Hacker y nos dicen "no os preocupes, sin motivos no hay bang" Todos los días.
Matas a uno en un pvp y te banean 6 meses  por hacker por la Face y te tienes que aguantar por que son las palabras sagradas de los MODS  Elegidos cuidadosamente por el equipo de MithrandiCraft.
Pues ten cuidado con las palabras de tus MODS y PB por que mas Hacker que ellos no hay nadie y si eso esta permitido para ellos creo que lo justo seria, que  para la gente del Servidor tambien.
Nada mas que decir.

**Comment by MithrandirCraft** [comment]
Si no hay nada mas que decir, por mi parte tampoco tengo mucho que decir.

Cierro el ticket entonces, porque no termino de ver tu punto.

**Comment by KawaiiGNE** [comment]
Te dan prueba de comportamiento abusivo de jugadores que tienen un alto rango en el servidor, jugadores que según tu son de fiar por que han sido elegidos por los administradores del server, un jugador como kraz, en el cual se ve claramente que lleva una velocidad excesiva en el vídeo mientras va agachado en pvp, un jugador que al empezar en el server iba llamando pendeja a la gente, un jugador que empieza a insultar y meterse con otros jugadores en el servidor donde es publicista, hace lo que le da la gana. 

![lo mas divertido es que es publicista]
(https://cloud.githubusercontent.com/assets/15872506/12072242/65854f12-b0d5-11e5-8269-457697cea641.png)

**Comment by xLebet** [comment]
Aquí se puede ver que es solo un bug visual y no afecta en la jugabilidad
https://www.youtube.com/watch?v=NryoR6n1IJY
https://www.youtube.com/watch?v=8S_A5hD3O4k

**Comment by UnicorniaxD** [comment]
Si, todo es un bug. A uno lo ven volar y es un bug, al otro lo ven correr agachado y pelear  y es otro bug. A uno que juega pvp (toby) solo una partida, no les ven hacer nada ni correr agachando ni volar ni aimbot ni nada y lo banean 6 meses, logica? Ninguna. Le pasamos todo esto a otros Admines y jugadores de otros server y estan asi ._."""" En este server se acepta todo eso en gente que lleva mas de tres años y eso es lo que nos dan a entender y no voy a comentar mas porque nada tiene sentido, ya que son las reglas del server y ahi no puedo hacer nada.

**Comment by xLebet** [comment]
Cabe mencionar que yo banee la primera cuenta de toby (pepapig) y fue por un CLARO uso de hacks,
esta acusación que estás haciendo es falsa, y mira que me tome el tiempo de ver detalladamente el video.
