### ISSUE TITLE
Publicista del servidor utilizando deliberadamente hacks, y hostigando contra otros jugadores

### ISSUE THREAD

**Issue by KawaiiGNE** [MithrandirCraft/MithrandirCraft#162]
Hola, vengo aquí donde se hacen los "reportes serios" para quejarme de que uno de los publicistas del servidor utiliza hacks. https://youtu.be/QYSiQWGQOqo?t=306 
Se le puede observar con una velocidad tremenda yendo agachado.
La cuestión es la siguiente, el moderador que fue capaz de banear por 6 meses a un jugador por que el creía que llevaba hacks, sin ni siquiera ser capaz de confirmarlo. Por que no fue capaz de sancionar de la misma manera al publicista que estaba usando hacks de manera deliberada?

También les dejo con una imagen previa donde se muestra el típico comportamiento del mismo publicista.
![lo mas divertido es que es publicista](https://cloud.githubusercontent.com/assets/15872506/12072317/1cc9a4e0-b0d9-11e5-8385-c75db016f075.png)

Me gustaría añadir que solo pido justicia, en este servidor que me demuestra cada día mas como he desperdiciado dinero en el vip.

**Comment by MithrandirCraft** [comment]
Gracias por abrir un ticket para este asunto, es lo que debiste hacer desde el comienzo.

Esto son acusaciones directas hacia un PB. Ten en cuenta que un publicista no tiene ninguna función de moderación en el servidor, sin embargo, cualquier cosa que pueda ver puede ser comunicada a un moderador, y desde allí valorarse una acción.

Hablaré directamente con krazlas ya que le tenemos entre staff. Analizaré este caso y veré si es necesario tomar alguna medida.

Si es cierto que se ve algo sospechosa esa velocidad agachado, por lo demás no veo ningún problema con el resto del pvp.

Si queréis señalar algun detalle del video estaré encantado de analizarlo.

**Comment by MithrandirCraft** [comment]
Me comentan que en esa escena krazlas llevaba los efectos de una poción de velocidad II, sin embargo, debido a la calidad del video y el pack de texturas que utilizas no puedo terminar de verlo con claridad...

Sin duda si llevaba una poción de velocidad, parece bastante normal, a parte de que superar la velocidad máxima agachado no debería ser posible.

Krazlas es un jugador que lleva ya más de 3 años jugando en MithrandirCraft, no le veo capaz de ponerse a usar hacks...

Hay algo mas que deba ver en el video? Sin duda el lenguaje no es muy adecuado, pero la naturaleza de Factions tiende a llevar a todos a utilizar este tipo de lenguaje de vez en cuando, y estoy seguro de que tu y tu facción no sois la excepción verdad?

**Comment by KawaiiGNE** [comment]
en el vídeo se ve como me duran los efectos de poción de velocidad 2 y corriendo de pie, voy casi a la misma velocidad que el agachado, no vale la pena comentar que no vi efectos de poción de velocidad en el en ese momento ya que no puedo aportar pruebas pero yo si que la llevaba y agachado, con poción de velocidad 2 voy mucho mas despacio que de pie sin correr, sin poción de velocidad.

**Comment by MithrandirCraft** [comment]
Si es asi, parece un hack bastante especifico. Combinado con el hecho de que no veo nada sustancialmente desbalanceante durante el pvp, no puedo llegar a la conclusion de que se estén usando hacks en esta situación.

**Comment by KawaiiGNE** [comment]
Aqui dejo un video demostrando que la velocidad de kraz era muy superior a la normal que puede tenerse agachado mientras se usa una pocion de velocidad 2 https://www.youtube.com/watch?v=pRZHFacGFww

De esta manera intento demostrar que kraz no ha obtenido la velocidad tan alta por medios dentro del juego, si no por algo que esta fuera del juego.

**Comment by MithrandirCraft** [comment]
Puedes ponerle nombre a ese hack? Puedes probarlo tu mismo en el servidor?

**Comment by UnicorniaxD** [comment]
Pues si no es hacks que nos diga como lo hizo para hacerlo nosotros :p

**Comment by Catadolfa** [comment]
Soy un gato

**Comment by KawaiiGNE** [comment]
osea que si veo alguien usar hacks, pero no se que hack es, no le pasa nada, se va impune de la situación? y en cambio un moderador ve a toby_ jugar sin que pase nada ni haga nada, y le echa durante 6 meses sin aviso previo?

Consideras esto justo?

**Comment by UnicorniaxD** [comment]
Mira kawai, que no te la calientes mas hijo mio!

**Comment by MithrandirCraft** [comment]
@KawaiiGNE En absoluto, lo has tomado como una demanda, pero solo era una pregunta. 
Si tienes idea de que hack se podría tratar, puedes comentarnoslo para ayudar con su futura prevención.

De hecho voy a trabajar en unos nuevos sistemas para la prevención de hacks de combate, para reducir situaciones como esta.

----------------------------------------
Voy a borrar los comentarios impertinentes de este ticket, y advierto ahora que si veo alguna chorrada mas por aquí quedaréis bloqueados permanentemente de este sistema de tickets.
Algunas cosas que veo por aquí las encuentro de muy mala educación, tenéis suerte de mi paciencia.

**Comment by UnicorniaxD** [comment]
Mejor preguntale al kraz directamente que es en vez de preguntarnos a nosotros, desde luego potis no son

**Comment by KawaiiGNE** [comment]
Yo de momento ya tengo claras las cosas, si eres publicista o mod, puedes usar hacks y salir impune, pero si por embargo no le caes bien a estos, a la mínima, aun que no uses hacks ni hagas nada, ya estas baneado por larga temporada.

Yo no he venido a quejarme de que me maten con hacks, yo he venido a pedir el mismo trato, si se supone que la justicia es tratar a todo el mundo de la misma manera, no lo estoy viendo aquí.

**Comment by MithrandirCraft** [comment]
@UnicorniaxD Como ya he dicho, hablaré con krazlas cuando se encuentre disponible.

Asi que acordamos esto:

- No hay indicios de uso de hacks de combate.
- Hay posibles indicios de uso de hacks de velocidad.
- Se ha producido un caso de lenguaje inadecuado reiterado por parte de un publicista.

**Comment by MithrandirCraft** [comment]
@KawaiiGNE Te parece suficiente lo que he acordado ya?

**Comment by KawaiiGNE** [comment]
Se habló a caso con toby_?
Se le dio una razón, pruebas o motivo para banearlo 6 meses?
Solo estuvo unos minutos en pvp.

No, con toby_ se actuó al instante con un ban de 6 meses y aun estoy esperando a conocer la razón de esto.

![kraz amenaza](https://cloud.githubusercontent.com/assets/15872506/12072571/35be4238-b0e5-11e5-8e2f-5e15ae4c3cd3.png)

Luego tengo que aguantar que me amenace con bans y que los moderadores lo cumplan, no, no estoy contento con solo hablar con el acerca de sus hacks, yo quiero que se discuta que pasa con todos los moderadores y mi fac, por que yo he acabado grabando todo lo que hago cuando entro a pvp por si me meten un ban sin motivo igual que han hecho con toby_, yo busco poder jugar en mi servidor sabiendo que a los que usen hacks se les banea y a los que no hagan uso de estos no.

**Comment by MithrandirCraft** [comment]
Claro, es comprensivo que te sientas así. Por eso el comportamiento de mis staff es algo que me preocupa. Y de lo que hablo con ellos constantemente para formarlos.

Sin embargo, ten en cuenta que la expulsión de ese jugador no la realizó krazlas, sino Zirix según el registro.

Si Zirix realizó esa expulsón, es porque estaba convencido de la razón que estableció junto con la expulsión.

**Comment by MithrandirCraft** [comment]
En cuanto a "las pruebas" no es necesario que un moderador proporcione pruebas, no me cansará nunca repetir esto. La filosofía de este servidor no es proporcionar pruebas a quienes no juegan legalmente, sino tomar medidas en el momento que se valora internamente que el jugador incumple alguna norma.

**Comment by KawaiiGNE** [comment]
Pero, toby_ juega legalmente, y lo he visto jugar siempre sin que pase nada, lo que pasa es que tienen mal perder algunos de los miembros del staff.

Soy el primero que quiere ver ban a todos aquellos que usen hacks en el pvp, lo unico que veo es como cada dia tengo que soportar ver como los miembros del staff empiezan a meterse con nosotros de alguna manera, los miembros de la fac insidious se defienden de estos pero no empiezan.

De todos modos me gustaria añadir que vale que no haya pruebas pero a toby_ no le dio tiempo a hacer nada minimamente sospechoso para recibir un ban de 6 meses.

**Comment by KawaiiGNE** [comment]
Añadiré tambien que en el servidor suele haber lags bastante altos, que pueden dificultar la visión de hacks, y necesitan ser vistos durante mas tiempo que unos minutos para hacer un ban de 6 meses al instante.

**Comment by MithrandirCraft** [comment]
@KawaiiGNE Como siempre tiendo a decir en los casos que no se defienden por el propio usuario... toby_ debería abrir su propio ticket debatiendo su expulsion si tiene algo que decir.

Por otro lado, ya que mencionas la mala fama que tienes entre mi equipo de staff, he de decir que parece bastante justificada, considerando los siguientes puntos que puedo apreciar yo mismo, y de los cuales necesitais ser conscientes y procurar corregir:

- Falta de educación evidente al abrir estos tickets por vuestro grupo.
- Falta de educación en el servidor. Apreciable por varios de mis staff, y por mi mismo cuando os 
  veo hablar por el chat del servidor.
- El caso puntual de @UnicorniaxD, que personalmente me parece una autentica fantasmada de 
  presentarse para Publicismo, y abandonar repentinamente sin dejarme una explicación.

**Comment by UnicorniaxD** [comment]
Fantasmada... Quieres saber por que me salí? Pues te lo cuento.
Me salí porque estaba cansada de leer comentarios acerca de mi Fac, que en ese momento me sentía agobiada por todo lo que ponía, que parecen pequeñas cosas pero a mi me molestaban y tenia pensado hasta de irme del server por como me sentía en ese momento. Yo la ilusión que tenia en ayudar era grande y aun así siempre ando votando y publicando por sitios. No te dije nada porque pensé que no le darías importancia, mas o menos le dije a mortis que me iba a salir porque iba a dejar de jugar y ya esta. Pero si te molesto lo siento.

**Comment by MithrandirCraft** [comment]
@UnicorniaxD 
Confiaba en que precisamente al entrar en el staff podrías airear un poco el asunto turbio con tu facción, pero no dijiste ni una palabra.

Desde mi perspectiva, al abandonar sin explicación quedaste muy mal. Por eso lo considero tu acción una fantasmada. Es la imagen que le has dado al administrador principal.

**Comment by tobyi** [comment]
El motivo de mi ban fue injusto, banearon al jugador a los 10 minutos que había entrado al server y yo no entiendo la razón de porque fue eso

**Comment by MithrandirCraft** [comment]
@tobyi Abre un ticket porfavor. Parece que estás hablando de una 3ra persona, y intuyo que esa no es tu intención xD

**Comment by UnicorniaxD** [comment]
Yo quería entrar para ser PB no para calmar las aguas. Pero quedar mal por el motivo por cual lo hice, merece la pena pues no me sentía bien ahí y si yo se que al entrar leo todo eso no me habría ni apuntado a nada. Yo entiendo tu postura porque me pongo desde tu punto, entiende tu la mía. Para calmar, no tenia que entrar ya que siempre intento llevarme bien con todos pero no hay por donde cogerlo al asunto.

**Comment by MithrandirCraft** [comment]
@UnicorniaxD Ya lo entiendo.

Esperaba que tendrías la capacidad para razonar un poco con los demás, y así aclararíamos todas las acusaciones que vais recibiendo desde hace tiempo, pero ahora has desperdiciado esa oportunidad.

No pasa nada, no todo el mundo tiene la misma habilidad para dialogar, si te sentiste intimidada es comprensible.

Sin embargo, sigue viendose feo porque no me lo comentaste al momento. Ahora es irreversible.

**Comment by UnicorniaxD** [comment]
Intimidada tampoco porque me son indiferentes, molestarme?? mucho. Ahora es irreversible? pues tampoco pasa nada. Tampoco es un crimen y que necesite pasar por un juicio. Yo tenia mis motivos, te lo e comentado y ya lo que te parezca a ti así es. Te aseguro que mi imagen junto con los de mi fac iba a seguir siendo fea.

**Comment by KawaiiGNE** [comment]
Ahora mismo me surjen 2 dudas:

1- por que si lo de kraz puede ser un bug, por que lo de toby_ no puede ser un bug, y no se reconsidera, no se avisa, y se le pone de forma directa un ban de 6 meses en un analisis de menos de 10 minutos?

2- por que se me cambia de tema a uno que no es de interés general acerca del tema de discusion de este github?

**Comment by MithrandirCraft** [comment]
No voy a seguir tratando un asunto ajeno. Si el afectado quiere decir algo puede abrir su propio ticket.

Me parece que discutir las cosas así, con un ambiente mas casual y menos centrado, pero siempre dentro de un marco de educación, nos permite ver las cosas en un contexto un poco mas global, y no tan centrado en las acusaciones a krazlas que presentas como tema principal del ticket. Es por ello que he mencionado la situación de Unicornia, y la imagen que me habéis transmitido a mi (y a diversos otros miembros de staff) por vuestra actitud en el servidor.

Además, creo que estás empezando a hurgar demasiado en todo lo que creas mencionable, no te voy a decir que está mal, porque al fin y al cabo yo hice lo mismo ayer, mencionando la imagen que me da vuestro grupo, señalando varios puntos. Pero espero que no lo estés haciendo porque hayas creído que desde staff nos guste hacer sufrir a la gente, o que nos divierta hacer estas cosas, o simplemente tengas algún tipo de fijación por contrariar al staff. 

Te puedo garantizar que nadie hace lo que hace con mala intención, de lo contrario seguramente yo no estaría atendiendote ahora mismo con tanta atención.

Pero me da la sensación de que estas desperdiciando esta atención, porque no veo que llegues a ningún punto adicional que sea tratable.

En cuanto a krazlas, no creo que se vuelva a producir de nuevo la actitud que me habéis mostrado. Sin duda las imagenes que habéis ido guardado le han ido bien para que aprenda a moderarse :)

Si se vuelve a producir tendrá consecuencias, así que ya podéis vigilarle. Pero espero que vosotros también aprendáis a comportaros.

**Comment by KawaiiGNE** [comment]
Bueno, tengo tres puntos que prefiero comentar aun que parezca pesado ahora mismo:

1-Por que el ban a toby_ es instantaneo y duradero a la minima sospecha en comparación al beneficio de duda del ban de kraz?

2-Si pienso que los moderadores van a por nosotros es por que parece que meterse con nuestra fac, banear y amenazarnos sea mas bien un deporte que algo que deban hacer para beneficiar a la comunidad del servidor.

3- De todas formas prefiero que sepas que agradezco que hayas tomado tu tiempo para contestar en este github y que lo tengo en cuenta.

**Comment by MithrandirCraft** [comment]
Los moderadores tienen todo el derecho de revisar y cuestionar si encuentran algo extraño en un comportamiento.
En cuanto a "meterse con vuestra facción" no tengo muy claras las circunstancias, quizá podrías mostrarme alguna otra imagen donde pueda apreciar un moderador con la misma actitud que krazlas (suponiendo que te refieras a algo similar)?
Amenazar de expulsión parece algo bastante sano... es comprensible que no os agrade una amenaza, pero un toque a tiempo aveces sirve para prevenir, y estos toques no suelen venir sin antes haber observado un comportamiento extraño.

**Comment by Zirix** [comment]
Hola Soy Zirix:
No vengo aqui para hacer ningun tipo de Pelea, ni poner mas tierran en donde no hay. Tampoco estoy de parte de nadie siemplemente Comento lo que es.

Bueno con respecto al comportamiento de el PB kraz1234, Todos estan de acuerdo que no es el correcto y antemano se es pera una disculpa de parte del PB, por dicha accion de este jugador. Bueno ahora con lo otro, "Hola, vengo aquí donde se hacen los "reportes serios" para quejarme de que uno de los publicistas del servidor utiliza hacks."  Con esa frase que pones se ve que tu no tomas enserio los reportes se de dicais abrir tickest acualquier sintoma de amenaza a su faccion en este caso.

Con respecto a los hacks de dicho moderador claramente se puede apreciar que es un bug visual de pvp en cual no le veo nada que desequilibrie el juego, con respecto asu "super velocidad" que mencionas no veo nada. 

Ahora bien con el Jugardor Toby_(pepapig), veo que son capaces de meter las manos al fuego por dicho jugador ya fue baneado por MOD xLebet y no vi ninguna queja de el hacia dicho moderador, se puede decir que acepto dicho castigo no dijo nada simplemente se creo otra cuenta. ahora con respecto al ban del jugador Toby_.

Bien ahora con lo siguiente:

"La cuestión es la siguiente, el moderador que fue capaz de banear por 6 meses a un jugador porque él creía que llevaba hacks, sin ni siquiera ser capaz de confirmarlo. Por qué no fue capaz de sancionar de la misma manera al publicista que estaba usando hacks de manera deliberada?"

La cuestion es la siguiente claramente se puede observa que dicho jugador lleva "hacks" y nose necesitan "pruebas fundamentadas para hacer dicho ban", el ban no es desicion de un solo jugar como ya sabeis y si yo estoy mal pueden retirar dicho ban hacia el jugador "Toby_", el cual no le veo que se defienda mucho.. Esto que nosda a entender.¿? Acepta dicho castigo¿?.

kraz1234 claramente se puede apreciar en el video que camina agachado, ¿hacks?, no veo y tampoco lo estoy defendiendo, si usa hacks  se merecera dicho castigo, pero claramente como todos sabes en pvp se presentan diversos "bugs" que nose conocen.

De mi parte no tengo Nada mas que decir..

**Comment by UnicorniaxD** [comment]
Yo solo añado que, algunos hacks permiten correr agachados y no hace faltar tener hacks para saber qué efectos tienen. Solo hace falta buscar por google y encontraras varias opciones para poder correr agachado.

Ahora, cada uno que busque la justificación que considere oportuna, pero es lo que es, una persona que se puso el modo agachado con velocidad y no se dio cuenta  ((Modo que se usa para asaltar Fac sin ser visto ya que el nombre del jugador desaparece)). 0 Pociones de velocidad y 0 bug.

**Comment by xLebet** [comment]
1-Por que el ban a toby_ es instantaneo y duradero a la minima sospecha en comparación al beneficio de duda del ban de kraz?

El ban de toby fue instantaneo por que ya fue baneado una vez, al momento de estar baneado deja una mala reputación y a la minima de un comportamiento extraño se debe ejecutar el ban (Agregando que yo le banee la primera vez por uso de hacks).

El tema de krazlas es un bug visual que no afecta en nada a la jugabilidad, simplemente le pasó por usar shift muchas veces y rapidamente, krazlas tiene un video mio en donde yo estoy escribiendo mientras tengo la espada cubriendome, ese también es otro bug visual que se genera de la misma manera que el de krazlas, espero haber resuelto tus dudas.

**Comment by MithrandirCraft** [comment]
Considero cerrado este tema. Si hay que añadir algo mas, lo reabrís.
