### ISSUE TITLE
Hacker:Maki en Youtube hay un video que les pasare el link...

### ISSUE THREAD

**Issue by vegetagamer9** [MithrandirCraft/MithrandirCraft#163]
Maki es hack en el minuto 2:35 salen sus hacks claramente, espero que le baneen permanentemente por direccion ip para que no use multicuenta y siga arruinando el server;  aqui el Link de el video 
https://www.youtube.com/watch?v=pLSu53eFhDg&feature

**Comment by MithrandirCraft** [comment]
Este caso lo valorará mi equipo de moderación.

Estoy trabajando en un sistema para detener este tipo de hacks de combate.

**Comment by vegetagamer9** [comment]
:D me alegro de eso Mithrandir

**Comment by MithrandirCraft** [comment]
No se aprecia nada concluente en el video, lo siento.

Sin embargo, pronto dejarán de poderse utilizar hacks de combate en MithrandirCraft, por lo que dejaremos de tener estos debates estupidos.

**Comment by vegetagamer9** [comment]
Vale.

**Comment by vegetagamer9** [comment]
vale* xD

**Comment by maki1** [comment]
aver yo voy p4 y tu hierro yo llevava filo 5 ademas eres multicuenta no se...

**Comment by maki1** [comment]
yo con p4 y tu hierro matao que quieres ganarme tienes muy mal perder para molestar a otras personas por no ser bueno jugando

**Comment by maki1** [comment]
yo p4 y el hierro nada mas ke decir
