### ISSUE TITLE
Toby_

### ISSUE THREAD

**Issue by tobyi** [MithrandirCraft/MithrandirCraft#164]
Hola, el motivo por el que abri este ticket es el ban de mi cuenta (toby_) del cual no encuentro razón, y si me banearon otra cuenta (pepapig) por presunto hacks que ella vio pero sin ofender no creo que el lag que hay en el servidor ayude mucho a detectar dichos asuntos.

Ahora mi baneo en la cuenta de Toby_ no encuentro el motivo de dicho ban. ¿Entrar y a los 10 minutos que te baneen sin hacer nada?, Es que no le encuentro motivo. ahora estaba leyendo un comentario de ziríx y él dice que me banearon porque ya no había razón de examinarme porque ya me habían baneado una cuenta antes por un presunto uso de hacks y no hay necesidad de hacer nada más, está bien si así fuese pero no le encuentro sentido a alguien que ya antes  banearon una vez y ahora entra según el con otra cuenta a seguir usando hacks?, No creo que alguien haga eso al menos  que le guste ser baneado muchas veces. No había abierto ningún ticket antes porque para mí y sin ofender pienso que es una pérdida de tiempo porque al final no solucionaran nada y le darán la palabra al que tiene rango. Así es esto aquí y en el mundo.

**Comment by rafaelox24** [comment]
Tenias un kill aura muy evidente, es tanto asi que pegabas mientras  comías y usabas potis y además crees que puedes venir y usar hacks y no nos daremos cuenta? y de paso encima de que te baneamos entras con otra cuenta y sigues con lo mismo? ese ban lo tienes bien merecido. Eso es todo cierro tema

**Comment by MithrandirCraft** [comment]
Bueno, sin duda si no abres un ticket no vas a saber si tienes oportunidad de debatir tu expulsion.

Por desgracia, no va a cambiar nada esta vez.
