### ISSUE TITLE
Wither (dudas)

### ISSUE THREAD

**Issue by AndresGatoXD** [MithrandirCraft/MithrandirCraft#165]
Tengo algunas dudas sobre esta criatura:
1. Este Mob donde puede y no puede ser invocado?
2. Este Mob puede destruir obsidiana en Fac?
3. Puede soltar su cabeza?
4. Hay posibilidades de que si alguien tratando de matarlo se pierda/extravie? (es decir, alguien muere y no sabe donde lo ha invocado, y este mob ande paseando por el mapa).

Este Mob es uno de mis favoritos (después de enderman xD) y merece ser una inspiración para crear un jefe (seria genial).

**Comment by MithrandirCraft** [comment]
Algunas de estas preguntas quizá te las respondan mas eficazmente mis staff. Quizá te sorprenda, pero el servidor es tan complejo que hay cosas que hasta las puede olvidar el administrador principal.

1. Puedes invocarlo en cualquier lado realmente. La verdadera pregunta es si PUEDES. En survival no se me ocurre ningún modo de obtener cabezas de Wither, pero quizá no nos convenga, ya que survival es un mundo pacifico donde no interesan las batallas contra jefes.
2.Se ha hablado de esto antes. Yo creo que está controlado, pero no puedo garantizarte los efectos del wither cuando se utiliza para asaltar facciones.
3.Creo que no. Pero he visto algunos tipos de cabezas de las cuales desconocía su existencia, asi que el wither quizá tambien dropee algo.
4.Si, pero tambien hay la posibilidad de que le pille una limpieza de entidades aleatoria y el jefe desaparezca.

Hubo un evento hace un tiempo con un wither, eso es lo mas cerca que hemos estado de utilizar su modelo como jefe. Por supuesto, esta planificado para ser utilizado en el futuro:
https://www.youtube.com/watch?v=jnL2MIMLWIg
