### ISSUE TITLE
Pierdo mi fac sin sentido alguno

### ISSUE THREAD

**Issue by vegetagamer9** [MithrandirCraft/MithrandirCraft#166]
esta mañana estaba tan tranquilo cuando me doy cuenta que no tengo home y antes tenia no se porque y tampoco nadie claimeo encima creo que es un bug y espero que me puedan llevar a mi home
 es Factions

**Comment by MithrandirCraft** [comment]
Me temo que es demasiado difícil analizar este caso.

No he oído nunca nada así, esta es la primera vez. Si realmente se trata de un bug, has tenido MUY mala suerte, especialmente tratandose de Factions, un componente del servidor que a penas se bugea desde que tengo conocimiento.

Lo que es mas probable es que el servidor haya sufrido un rollback y se haya restablecido un estado anterior de tu facción. Sin embargo, hasta eso parece poco probable, y tendrías que tener muy mala suerte también para que ocurriese (Podría ocurrir si colocaste tu f home muy recientemente).

Es responsabilidad tuya guardar siempre las coordenadas de tu Facción.

En cualquier caso, no se me ocurre como ayudarte. Hay algo que pueda hacer?
Si escuchas de algún caso similar, hazmelo saber.

**Comment by vegetagamer9** [comment]
Yo querria que me llevaras a mi home :/

**Comment by MithrandirCraft** [comment]
Me temo que si no existe, no hay forma de llevarte a ella.
