### ISSUE TITLE
Hacker en MithrandirCraft nadir153053850

### ISSUE THREAD

**Issue by vegetagamer9** [MithrandirCraft/MithrandirCraft#167]
este se le ve el kill aura, lebet vino y confirmo asi que antes vi que tenia anti-kb y me puse a grabar https://www.youtube.com/watch?v=nsqXddrxb00 url del video

**Comment by vegetagamer9** [comment]
PD: perdon por la calidad XD

**Comment by vegetagamer9** [comment]
Otra cosa Mith  aun asi tienes que poner mas moderadores que vigilen los hacks
 ErKillo es hack

4 VS 1
 y gana pegandonos de espaldas

**Comment by vegetagamer9** [comment]
Mith por favor hazme moderador

**Comment by MithrandirCraft** [comment]
Gracias por reportar esto. Las pruebas son suficientes para una expulsión.

Sin embargo, he observado tu comportamiento durante los últimos meses "vegetagamer9", no es fácil ignorar la actitud que ha presentado el usuario de tu nombre durante todo este tiempo, te has ganado un historial bastante desagradable como para solicitar formar parte de staff.

**Comment by vegetagamer9** [comment]
Si esque el server esta lleno de hackers hay muchos y para que no pare de aver hacks voy a otro server

**Comment by AndresGatoXD** [comment]
Aunque yo no pueda entrar al server...
Quisiera ser parte del Staff, este es el primer server y espero que no sea el ultimo. Aunque no se de que manera pudiera pero gustaría ayudar :)

Aunque solo puedo mantenerme activo en un Móvil :(
