### ISSUE TITLE
iTew

### ISSUE THREAD

**Issue by Lotzym** [MithrandirCraft/MithrandirCraft#168]
iTew me puso como enemigo entonces yo trate de ponerlo como aliado, despues se fue para mi fac y me puso como enemigo de nuevo y me mato sin razon alguna, denle una sancion y diganle que me devuelva mis cosas, por que la verdad eso me parece totalmente injusto, y de seguro no es la primera vez que el hace esto, el y su fac entera, espero totalmente que algun staff lea esto y haga algo al respecto, porque seguramente en este dia y en anterios iTew y su fac hicieron esto.
Espero con ansia su respuesta.

**Comment by MithrandirCraft** [comment]
Que estas reportando exactamente?

**Comment by Lotzym** [comment]
La injustisa de lo que hace iTew, sinceramente me parece bastente injusto que te ponga como enemigo sin razon alguna, y yo tratando de no tener ningun problema con su fac lo ponga como aliado, y el se telenstraporte a mi fac y me mate sin razon alguno.

**Comment by MithrandirCraft** [comment]
Sin embargo, él tiene todo el derecho de declararte como enemigo... no termino de entenderlo.

Quizá necesites un poco de direccionamiento acerca de como funciona factions: /warp tutorialfactions, echale un vistazo a ese tutorial, te aclarará muchas dudas seguro.

Alternativamente, si no estás convencido con la agresividad del mundo de Facciones, dispones del mundo Survival, pacifico.

**Comment by SwordGamerYT** [comment]
Viendo este tema, Lotzym, concuerdo con MithrandirCraft...

Ademas iTew, pudo llegar a tu faction home, porque cuando él te declaro enemy, algo que es totalmente permitido, tu le diste ally, y al darle aliado a una fac, esa relacion permite que la gente de esa fac aliada pueda ir tranquilamente a tu faction home, y lo que ocurre luego de eso, ya no tiene que ver con hacks o cosas ilegales.

 Simplemente cuando el fue a tu fac te volvió a declarar enemy, y te mató legalmente. Creo que el tema está bastante claro... Saludos

**Comment by MithrandirCraft** [comment]
De todos los errores se aprende, espero que hayas aprendido tu algo de esta lección @Lotzym Lotzym, y lo utilizes para jugar mejor la proxima vez :)

**Comment by Lotzym** [comment]
Ok, te entiendo, MithrandirCraft mejor cierra este post y problema solucionado, de echo no tengo problema por que mis facs aliadas me estan ayudando bastente.
Gracias por su respuesta.
