### ISSUE TITLE
Hackers en la facción de AquaInferno.

### ISSUE THREAD

**Issue by SimplyAcke** [MithrandirCraft/MithrandirCraft#169]
Apartado 2: Se trata de reportar a un jugador

· Mi nombre en MithCraft: Nepomucemo
· Jugador al que reporto: ErPikiDiParla (faction AquaInferno)

· Fecha en la que empecé a ver está actividad: 03/01/16

· Normas incumplidas por el jugador en cuestión: Uso de hacks "killaura" (también llamado autoaimbot) "speedhack" (en el vídeo no se aprecia pero lo tiene) y "autosword" que sirve para cuando un jugador se acerca te equipa automáticamente la espada. (Combinando los 3, era invencible, imagino que llevaría mas)

· Comentarios: Este jugador en cuestión además de varios insultos, lleva varios días viniendo con hacks a molestar, el resto está dicho en el vídeo de prueba: https://youtu.be/2H7C6A5ndec - Por desgracia la calidad del vídeo es pésima porque no pude grabarlo en mas calidad (desconozco la razón) Pido por favor 2 cosas: 1 el baneo de esta persona en cuestión y 2 el desbaneo de mi amigo iTew que es baneado sin razón (o sin pruebas).

**Comment by BlackBeemo** [comment]
Lo he baneado por kill aura.

Procuren de grabar en calidad suficiente de que se pueda leer algo :S.
