### ISSUE TITLE
Reporte a una faction.

### ISSUE THREAD

**Issue by Pabloxlive** [MithrandirCraft/MithrandirCraft#17]
Buenas,soy yo otro dia mas,y era para reportar a una faccion,por sosspechas (casi seguro) de hack/x -ray,te comento:

Hace unos dias,una faccion nos petó una faccion,hasta ahi todo correcto,despues de ese destrozo,nos  mudamos a las coordenadas X 4000 ( Muy muy muy lejos de la civilizacion) asegurandonos de que nadie nos pudiese ver,decidimos hacer la casa bajo suelo,no se notaba NADA que habia una faccion ahi,y menos tan lejos.
Es por ello,que mi faccion y yo creemos que la faccion Owlercity lleva hacks,y nos ha petado nuestra facc (RODEADA DE OBSIDIANA) muy lejos de la civilizacion.

Mi facc y yo pedimos justicia,ya sea penalizando a la faccion,o lo que crean conveniente,porque hemos perdido TODO,y lo mas seguro es que haya sido por hacks.

PRUEBAS DE QUE FUERON ELLOS:

http://oi58.tinypic.com/2eec07n.jpg

**Comment by BatmanNick** [comment]
Lo que esta destruido no era de obsidiana. era priedra pura.

**Comment by MithrandirCraft** [comment]
Preguntas importantes:
  - Estabais conectados cuando os invadieron? Y si es así, estabais en la facción?
  - A que profundidad se encontraba la base? Muy cerca de la superficie?
  - Como han destruido el obsidian? Por la imagen la facción parece estar bastante recubierta.

**Comment by Ivanovic24** [comment]
Si pasas por encima puedes ver el claim, y seguro q vuestra faccion estaba a la altura del diamante q es lo mas comun

**Comment by Pabloxlive** [comment]
Mithrandir,Missmosimoo ( o como se escriba) si estaba conectado.
Estaba a 4-5 bloques bajo tierra.
Pues eso es lo que nose,ya que hacia un cuadrado por dentro...

Ivanovic  vale que se pueda ver el claim,pero en la coordenada 4000 no hay nadie minando buscando tu faccion ( Nos habian amenazado previamente) ,y estaba a no mucha altura,pero aun asi...

**Comment by MithrandirCraft** [comment]
No se que decirte Pabloxlive. Ivanovic24 tiene razón, tan solo con pasar por encima, o usando el /f map, pueden encontrarte. Hay muchas otras cosas del sistema de facciones que seguramente ignoras, y para cubrirlas, voy a empezar a hacer tutoriales junto a MortisBlack, para que los mas novatos podáis aprender secretos sobre factions.

No importan las coordenadas, una facción siempre tendrá vulnerabildades, lo importante es saber reducirlas al mínimo.

Has visto la facción Sparta? És una facción de 2 años de antigüedad, y siempre ha estado lo mas cerca del spawn central de facciones posible. Se las apañan bastante bien.

**Comment by RoronoaOwlerCity** [comment]
Pabloxlive...cuando reportes a un jugador de una manera más seria , te recomiendo ser un poco más justo con lo que reportas. Y ten cuidado con tus aliados y dónde tienes que dejar de construir para que el territorio no sea público. Ah, y no mientas sobre tu faccion ¿no? con tal de hacer el mal te pones a decir que estaba full obsidiana y ese pedazo estaba sin obsidina incluyendo el suelo que explote, esas 2 partes nunca tuvieron ese material. Ten cuidado con ese tipo de cosas que no soy el único que hubiera podido greefear eso, cualquiera que te encontrará pudiera haber explotado esa fac. 

No es intención de lucha, eh. Nada que ver, sólo para hacer presencia porque estoy siendo nombrado acá y también dar  recomendaciones si es que lo ves Pabloxlive.
