### ISSUE TITLE
Que estoy haciendo mal?

### ISSUE THREAD

**Issue by AndresGatoXD** [MithrandirCraft/MithrandirCraft#170]
Me kikean por volar :/
Esto se vuelve seguido :(

**Comment by MithrandirCraft** [comment]
Quizá pueda solucionarlo, pero me gustaría ver tu personaje y como és kickeado.

Tienes algún síntoma de lag? Estas usando algún cliente modificado?

**Comment by AndresGatoXD** [comment]
Si, tengo mucho lag.
Pero como podrías ver como soy Kikeado?
No tengo ningún programa para grabar.

**Comment by MithrandirCraft** [comment]
Solo necesito verte online. Dime una hora y allí estaré.
