### ISSUE TITLE
Puñetazo Filo X

### ISSUE THREAD

**Issue by Catadolfa** [MithrandirCraft/MithrandirCraft#171]
Recientemente me he fijado que cuando pego a alguien sin armadura inflijo críticos que les baja entre 4-6 corazones, o a veces mas pues hay veces que pego mas de un golpe en el proceso del salto y simplemente me los cargo. La verdad no estoy muy segura de cómo se ha producido este bug pues nunca me he parado a hacer PvP sin espada. Tampoco creo que me habría dado cuenta si no hubiera sido por el mod para ver los corazones de la gente. 
Talvez el dios odín me ha concedido este Don para purgar a la gente sin armadura, alias free farm, de PvP. 
Es un misterio que está por descubrirse.

**Comment by MithrandirCraft** [comment]
Yo lo soluciono.

Es un bug bastante clásico, y por el momento solo sabemos que ocurre aleatoriamente. Si eres capaz de darnos alguna pista sobre como lo has reproducido, nos será muy valiosa para prevenirlo en el futuro.

**Comment by Catadolfa** [comment]
Ni idea, pero gracias <3

**Comment by MithrandirCraft** [comment]
Bueno, va a ser un poco mas complicado de lo que imaginaba solucionarlo, pero terminaré haciendolo, mientras tanto espero que no abuses de tu bug. :l

**Comment by Catadolfa** [comment]
No creo que se pueda abusar, ya tengo espadas. Solo se lo enseño a la gente y digo que tengo Afilado V en la chuleta e.e

**Comment by MithrandirCraft** [comment]
Solucionado.
Estoy trabajando en prevenir que esto ocurra mas.
