### ISSUE TITLE
Duda Sobre Tienda (VIP)

### ISSUE THREAD

**Issue by SwordGamerYT** [MithrandirCraft/MithrandirCraft#172]
Hola, Tengo una duda, hay alguna forma de pago por sms para Argentina, para el rango VIP (3 meses), porque para la obsidiana x64 si hay forma de pago por sms, pero para el rango que acabo de mencionar no la encuentro. Espero pacientemente su respuesta... Saludos

**Comment by MithrandirCraft** [comment]
Buenas tardes.
Aparentemente, en Argentina deberías tener activado un método de pago por SMS a través de Mobiamo, en la opción de pago por Paymentwall.

Utiliza esta opción si la tienes disponible para pagar con sms.

Sin embargo, parece que me estás comentando que distintos productos en la tienda te ofrecen distintos metodos de pago. Esto puede deberse a que ambos productos tienen precios distintos también, siendo uno mas caro que el otro, y por lo tanto, que Mobiamo disponga de algún tipo de limitación quantitativa.

No puedo comprobar esto yo mismo, solo puedo decir que los metodos son los que son de momento, y se irán expandiendo con el tiempo.

**Comment by SwordGamerYT** [comment]
Gracias por responder.
Justamente lo que explicaba era que Mobiamo, tiene opcion de compra para algunos objetos (como puse de ejemplo el stack de obsidiana) pero en otros objetos, cuando entro a pagar a Paymentwall, no me sale la opción de pago por Mobiamo.
El Resto lo entendí todo claramente, y no hay problema, se vera otro metodo de pago, o habrá que esperar...  Saludos y nuevamente Gracias por responder mi duda.

**Comment by MithrandirCraft** [comment]
Asi que los objetos con los que Mobiamo está disponible son aleatorios? No tienen ninguna relación? No se trata del precio?
