### ISSUE TITLE
perdí mi inventario completo

### ISSUE THREAD

**Issue by tobyi** [MithrandirCraft/MithrandirCraft#173]
Esta madrugada estaba conectado con todas mis cosas en el inventario y tuve que desconectarme un momento del server y cuando volví y me loggie no tenía nada perdí mi armadura p4, mi espada f5 un arco p5 y 5 manzanas op, intente salir y entrar e incluso cerrar el minercraft y no funcionaba no tengo ni idea como perdí mis cosas talves fue un bug o algo ayuda!
Atte: Chichen

**Comment by MithrandirCraft** [comment]
Pues parece que has tenido muy mala suerte.

No tengo ninguna manera de saber realmente si has perdido algo.

Solían producirse casos de perdida completa de inventario en el pasado, sin embargo en teoría ya están arreglados. Que comentes que tu inventario ha sido vaciado parece un caso muy singular en estos momentos.

Realmente no puedo ayudarte esta vez, pero lo que si voy a hacer es tener en cuenta este error que dices haber tenido, y abrir un hilo oficial en este sistema de tickets acerca de perdidas de inventario, para que cualquier otro jugador que pierda su inventario pueda reportarlo, y yo pueda ver una relación acerca de porqué se produce este error.

También echaré un vistazo a diversos componentes del servidor para comprobar que no haya errores que puedan causar barrido de inventario.

Asegurate también de que no estabas en modo PvP. Normalmente estas situaciones deben tener alguna respuesta logica.

De momento te recomendaría que hagas un comentario en el siguiente ticket: #174
