### ISSUE TITLE
Perdidas de inventario por bug (Has tenido este error? Reportalo aquí)

### ISSUE THREAD

**Issue by MithrandirCraft** [MithrandirCraft/MithrandirCraft#174]
Algunos usuarios reportan puntualmente haber perdido su inventario de forma parcial o completa, normalmente al desloguear, y sin poder atribuír una causa lógica. Si has sufrido este problema, reportalo aquí, siguiendo las siguientes indicaciones a responder:

Importante: Reporta aquí únicamente casos de perdida de inventario ajenos a motivos de gameplay. Por ejemplo: Reporta aquí un caso de perdida de inventario injustificada, pero no reportes aquí una perdida de inventario por haber huído en pvp, o cualquier otra situación de perdida de inventario durante un PvP.

Si perdiste tu inventario deslogueando y crees que se trata de un error:
    - Nombre de jugador:
    - Mundo en el que perdiste tu inventario:
    - Motivo del deslogueo (Voluntario, Kick, Crash, Bug, Reinicio):
    - Hora y fecha de deslogueo (Del servidor, en www.mithrandircraft.es):
    - Hora y fecha de relogueo y comprobación de perdidas (Del servidor, en www.mithrandircraft.es):
    - Objetos que has perdido:
    - Información adicional y detalles:

Si perdiste tu inventario esporadicamente sin desloguear y crees que se trata de un error:
    - Nombre de jugador:
    - Mundo en el que perdiste tu inventario:
    - Hora y fecha en la que notaste la perdida (Del servidor, en www.mithrandircraft.es):
    - Objetos que has perdido:
    - Información adicional y detalles:

**Comment by tobyi** [comment]
Fue el día de hoy en la madrugada, y por eso decidí abrir esto porque fue algo raro estaba en mi fac me desconecte y cuando me volví ah loguear no tenía nada en mi inventario, repito no estaba en ningún combate simplemente estaba en mi home me desloguie y cuando entre no tenía nada y es algo preocupante porque perdí cosas importantes y si me paso ah mi seguro le pasara ah alguien mas si esto es causa de algún error

**Comment by Popek345** [comment]
ayuda hace unos dias cuando el servers estaba regenerando un mapa y eso me fui teniendo una armadura completa encantada p4 y una espada afilado 5 entre muchas cosas mas en mi inventario y se perdio un 80% me quedaron unos 5 cosas nomas como las podre recuperar :-1: -1: espero tu respuesta

**Comment by MithrandirCraft** [comment]
@Popek345 

Lo que ocurrió ese día fue que hubo un rollback de unas 5h. Por lo que si estuviste jugando a esas horas, todo lo que hiciste se perdió.
Estaba esperando algún comentario sobre lo que ocurrió ese día, en este hilo, ya decía yo que tardabais mucho.
Sin embargo, no puedo hacer nada en este caso, ya que se trata de un problema que tuvo que sufrir mucha gente, no solo tu.

**Comment by Popek345** [comment]
ok igual gracias :+1:

**Comment by JessyelXD** [comment]
Hola soy JessyelxD y no e perdido ningún item pero se me duplico un pico muy chetado y hora tengo 2 xD pero parece que cuando gasto uno el otro también se gasta.

(Yo no e utilizado nada ni tampoco se como ocurrió simplemente es para evitar malos entendidos)

También el el único bug que me a pasado en el servidor y llevo como un año en este servidor ) 

La pregunta es puedo quedarme con los 2 picos o como les quito el bug (Ya e probado a ponerlos en el mismos cofre pero nada)

**Comment by MithrandirCraft** [comment]
@JessyelXD  Estas seguro de que no es solamente un bug visual?

Es curioso que me digas que tienes 2 picos, y ambos compartan la durabilidad.

Haz lo que quieras con ellos, pero si encuentras una forma de reproducir ese error, porfavor, abre un ticket sobre este asunto detallando como causarlo.

**Comment by jezzM** [comment]
Hola hace como 5 hrs estaba en suvirval y tenia mi armadura completa de hierro, picos comida, etc. , hice spawn y cuando regrese no tenia nada entonces volvi a hacer mi armadura completa de hierro y todas mis cosas y fui a buscar arena y llevaba muchas cosas cuando hice / home para vaciar mi inventario y regresar ya no tenia nada, y volvi a hacer mi armadura completa de hierro y todas mis cosas y para no perder nada mejor me desconecte y me conecte como dos horas despues y otra vez ya no tenia nada, pero tampoco tenia nada para volver a hacer mis cosas porque ya me lo habia gastado todo en lo que se perdio xDD mi nombre en el servidor es jjs y llevo como 2 semanas y no entro a pvp y la primera vez que se perdio de la nada mi inventario llevaba un pico y una espada de diamante espero y me puedan devolver todo gracias :DD

**Comment by vampiredrem** [comment]
Hola hace unos 15 minutos estaba jugando en survival y el server me saco, la verdad no ley el motivo xque es común que pase eso, y al volver no tenia nada de mi inventario los reporte a helpop pero nadie contesta, estaba construyendo en mi castillo y tenia el inventario completo, tenia mucha piedra y ladrillos del nether, pero lo que de verdad me interesa resolver es la perdida de mi armadura y mis armas y herramientas todas encantadas Mith ojala me des una solución. eran los mejores encantos que me habían salido desde que entro al server. gracias

**Comment by PvpFullPlayer** [comment]
Hola yo estaba tranquilamente matando gente y cuando fui a survival por error y luego volví al spawn 
había desaparecido todas mis cosas de mi inventario bueno espero Mith que esta vez almenos te agas responsable de esto

**Comment by vampiredrem** [comment]
me paso otra vez craftie todo de vuelta en surv jugué un rato encante y me fui a sala 6 pvp a pasar el rato y al volver a surv ya no tengo nada ! otra vez 2 veces el mismo dia joder !

**Comment by MithrandirCraft** [comment]
@jezzM 
@vampiredrem 
@PvpFullPlayer 

Respeten el formato de reporte, establecido arriba. Completen los campos requeridos ordenadamente.

Este problema debería haber sido arreglado desde ya. Confirmenlo.

**Comment by vampiredrem** [comment]
- Motivo del deslogueo (Voluntario, Kick, Crash, Bug, Reinicio):
kick del server simplemente un kick normal ..

 - Hora de deslogueo:
fue el lunes 14 a eso de la 20:20 horas. lo se xque saque pantallazos a la hora que me paso

- Hora de relogueo y comprobación de perdidas:
será a mas o menos 20:23 xque rápidamente entre de vuelta, y me di cuenta. y mande helpop, lo escribi en el chat global y lo reporte aca después de un  rato que me paso.

- Información adicional y detalles
estaba normal jugando en surv, y de pronto me saco el server cosa que supongo nos pasa a menudo a todos, volvi a entrar y ya no tenia nada, no voy a mentir que tenia toneladas de diamantes o 20 espadas con filo 5 .. la verdad es que tenia mucha piedra y ladrillos del nether xque a esa hora estaba construyendo, pero si llevaba mi armadura completa casco pechera y botas de diamante encantadas todas y pantalón de hierro encantado también, pala eficiencia e irrompibilidad,  acha lo mismo..  y espada filo 3 fortuna 2 creo e irrompibilidad todo esto de diamante encantado, 2 picos regalones para minar unos con irrompibilidad y eficiencia 3 solamente y el otro lo usaba para sacar los diamantes ya que tenia fortuna 2, irrompibilidad y eficiencia 3. de eso me acuerdo claro, lo demás era comida y bloques que no duelen tanto.
tenían mas encantos claro no me acuerdo de todo confirmo :) 


al rato jugué de vuelta craftie todo en surv de nuevo encante unas cosas y como todos estaban escribiendo que les había pasado lo mismo me fui de surv a la sala 6 en pvp ya que todo mundo va ahí, y como a la hora mas o menos vuelvo a survival y estaba en cero nuevamente  no tenia absolutamente nada ... ya hay me cabrie y no juegue mas .. después volvi al rato pero solo di vueltas mas nada .. 

ojala me haya explicado bn :)

**Comment by MithrandirCraft** [comment]
@vampiredrem Podrías darme tu nombre en el juego porfavor?

**Comment by vampiredrem** [comment]
si, perdón se me olvido .. en el juego soy VampiRe

**Comment by MithrandirCraft** [comment]
@vampiredrem Asi que perdiste tus objetos 2 veces seguidas en Survival?

**Comment by vampiredrem** [comment]
a si es con un rango de tiempo de mas menos 1 hora algo a si

**Comment by MithrandirCraft** [comment]
@vampiredrem Vas a tener que conectarte. Te daré un par de objetos de compensación, que no serán lo mismo que perdiste. Pero excederan su mismo potencial, asi que no deberías tener problemas en reestablecer lo que tenías con ellos.

Me temo que no tengo tiempo para ir reestableciendo los encantamientos exactos de cada uno de los objetos que habeis perdido.

**Comment by vampiredrem** [comment]
vale me conecto en 1 min te mandare un msn pv

**Comment by vampiredrem** [comment]
gracias mithrandir x la solución :)

**Comment by jezzM** [comment]
@MithrandirCraft  Ok
- Nombre de jugador: jjs
- Mundo en el que perdiste tu inventario: 
- Hora de deslogueo: ayer mas o menos 10:30
- Hora de relogueo y comprobación de perdidas: 11:00
- Objetos que has perdido: perdi 3 veces mi aradura completa de hierro, un pico y una pala de diamante, comida bloques, herramientas

**Comment by MithrandirCraft** [comment]
@jezzM Donde perdiste tu inventario? :P

**Comment by jezzM** [comment]
Perdon nose porque olvide ponerlo XD en survival en mi casa y asi xDD

**Comment by MithrandirCraft** [comment]
@jezzM Te digo lo mismo que le he comentado a vampiredrem. Tendrás que conectarte en Survival, y recibirás una compensación.

**Comment by OdyZeus** [comment]
hola
- Nombre de jugador: ArlekinHD
- Mundo en el que perdiste tu inventario: Factions
- Motivo del deslogueo (Voluntario, Kick, Crash, Bug, Reinicio): Voluntario
- Hora de deslogueo (Del servidor, en www.mithrandircraft.es): No recuerdo la hora exacta 
- Hora de relogueo y comprobación de perdidas (Del servidor, en www.mithrandircraft.es): 10/03/16 a las 4:10 Hora de Colombia. no tengo como comprobar lo que e perdido D:
- Objetos que has perdido: un armadura de diamante p4 una espada un pico de diamante realmente no recuerdo mas
- Información adicional y detalles D:

**Comment by jezzM** [comment]
Ya me conecte pero no me sale nada

**Comment by MithrandirCraft** [comment]
@jss Vas a tener que mantenerte conectado un poco mas, y en una franja horaria de España.

No puedo abrir tu inventario mientras estés desconectado (Por el momento).

**Comment by MithrandirCraft** [comment]
@jezzM restablecido.

**Comment by jezzM** [comment]
@MithrandirCraft  Muchas Gracias :D

**Comment by vegetagamer9** [comment]
Yo perdi mi inv
Como mith vio lo que perdi en el otro report, mith si puedes devolverme mis cosas

**Comment by MithrandirCraft** [comment]
@vegetagamer9 Te he dado indicaciones claras y concisas para que reportes tu situación debidamente. No lo repetiré mas.

**Comment by NosophorosVampire** [comment]
- Nombre de jugador: VampiRe

- Mundo en el que perdiste tu inventario:Survival

- Motivo del deslogueo (Voluntario, Kick, Crash, Bug, Reinicio): Reinicio anteponiendo el 
recomendado LOGOUT

- Hora de deslogueo (Del servidor, en www.mithrandircraft.es): 20:40 APROX

- Hora de relogueo y comprobación de perdidas (Del servidor, en www.mithrandircraft.es): 20:50 APROX

- Objetos que has perdido: Armadura de diamante encantada completa, espada, pico, pala, acha diamante encantado todo, y Arco que es lo que mas siento xque estaba encantado al full, lo demas eran posiones varias. en realidad todo estaba con buenos encantos solo que uno no se acuerda al pie de la letra se que entenderas son tantas cosas con 5 o 4 encantos.
es un buen de trabajo pasando en los spawn de mobs horas para levelear y a lo largo que juego en el serer voy obteniendo los encantos buenos tu sabes.

- Información adicional y detalles: vale me estaba pendiente del chat todo normal y vi cuando saludaste y todo y avisaste del reinicio, me desloguie como siempre...pasa que al volver no tenia mis cosas que llevaba, pero si estaba en el lugar donde puse el logout, y pregunte si estabas y te conte el problema, tenia mis cosas de hace 1 hora atras mas o menos, lo se xque tenia mi material de construccion que estaba usando con mi armadura de oro x si me caigo a la lava para no perder mis cosas chetadas, antes de acusar algun problema, fui a ver al cofre donde tenia mis cosas y no estaba nada, ni las posiones del cofre de posiones estaban, todo lo que llevaba se perdio sin mas :/

**Comment by NosophorosVampire** [comment]
Aviso: no se si a vs pero a mi me sale corregido todo lo que habia escrito del reporte que hice muchas palabras se cambiaron, vale solo eso

**Comment by vegetagamer9** [comment]
He mirado y no se me pasaron las cosas a survi mith :/

**Comment by MithrandirCraft** [comment]
@vegetagamer9 Como siempre, sin respetar la pauta de este ticket. Y no és la primera vez que te lo indico, sabes que este es el lugar indicado para realizar el reporte.

Si no especificas los detalles tal como se indica en esta pauta, y en este ticket, no tengo manera de saber ni quien eres en el juego, ni recopilar la información necesaria para prevenir el problema en el futuro. (No tendría ni que explicarte esto, simplemente deberías seguir las instrucciones dadas)

En fin, te haré un favor y adjudicaré tu ticket a esta linea, ya que ya está adjudicado.

Recuperarás tus objetos en tu enderchest (A pesar de haber poco espacio) aunque tu actitud de holgazán no lo merece. Si esto te vuelve a ocurrir reportalo debidamente. (Y doy por entendido que tu cuenta es TheShadowWither aunque podría dar a entender perfectamente que es vegetagamer9).

Gracias por tu extensa paciencia con esto y tus agradables comentarios hacia el servidor.

@NosophorosVampire Fue solucionado tu caso?

**Comment by vegetagamer9** [comment]
Mith una cosa, gracias por devolverme mis cosas pero los arcos no suelen llevar aspecto igneo llevan Fuego :S

**Comment by vegetagamer9** [comment]
Dejalo Lo arregle

**Comment by vegetagamer9** [comment]
Pierdo mi ENDERCHEST
como ya abri el reporte anterior mith ya sabe lo que me paso
reclame mi enderchest que usted lo vio ayer hora española usted me dijo que me lo daria tengo que matar usuarios en factions y pvp quiero mi enderchest con mis p4

**Comment by MithrandirCraft** [comment]
@vegetagamer9 
Ya te he contestado. No tengo manera de saber lo que había en tu enderchest antes de que se bugease, ni puedo restablecer su contenido.

Si tienes alguna prueba de lo que había lo restauraré de forma manual, aunque podría estar invirtiendo el tiempo en progresos mas interesantes para el servidor.

**Comment by vegetagamer9** [comment]
![2016-07-16_20 33 21](https://cloud.githubusercontent.com/assets/12957778/16896489/0221727e-4b95-11e6-863c-9a4ed9c55998.png)
 
Cascos P4 Irrom 3 
Petos Irrom 3 P4
Pantalones Irrom 3 P4
Botas Una de ellas tenia  Irrom 3 p4  paso helado 2  y otra irom 3 p4 agilidad acuatica
Una espada era Cheta Full y se llamaba Mythi La Princesa D Mis Sueños
La otra era igual pero con Afilado VI y se llamaba igual 
y la otra era la leyenda afilado VI  aspecto igneo 2 irrom 3 empuje 2 
y despues las esmes y bloks y chets

**Comment by vegetagamer9** [comment]
Mithrandir te di los datos yo tengo las cosas contadas
Reestableceme el enderchest

**Comment by MithrandirCraft** [comment]
@vegetagamer9  Hecho.

**Comment by vegetagamer9** [comment]
Mithrandir Te Faltaron las espadas :l

**Comment by vegetagamer9** [comment]
Me las puedes dar las espadas con los nombres

**Comment by vegetagamer9** [comment]
Me las puedes dar las espadas con los nombres

**Comment by FearMagix** [comment]
Nombre de jugador: FearMagix
Mundo en el que perdiste tu inventario:Spawn

Motivo del deslogueo (Voluntario, Kick, Crash, Bug, Reinicio): Deslogueo Voluntario

Hora de deslogueo (Del servidor, en www.mithrandircraft.es): 20:40 PM aproximadamente

Hora de relogueo y comprobación de perdidas (Del servidor, en www.mithrandircraft.es): 21:00 PM

Objetos que has perdido: Armadura de diamante p4 , espada filo5, pico muy chetado, Arco poder 4. 38 niveles de experiencia

Iformación_ adicional y detalles: estaba en mi home en factions y cuando estaba a punto de irme mate un par de creepers y me canse de hacerlo y me fui  al spawn para desloguearme sin correr riesgos de perder mis cosas y cuando me desconecte no me aparecio nada

cuando me vuelvo a loguear todo lo que tenia se perdio no se como pero ya no tenia nada de nada e intente volver a loguearme si aun caso era algun bug o algo asi y nada no tenia mi p4 ni nada

**Comment by MithrandirCraft** [comment]
@FearMagix En algun momento de esa perdida de inventario cambiaste de mundo entre Factions y Survival?

**Comment by FearMagix** [comment]
pues venia regresando de mi home de factions y cuando me fui al spawn

no habia entrado en pelea ni nada por el estilo

**Comment by KururuKiller** [comment]
- Nombre de jugador: _Kururu_
- Mundo en el que perdiste tu inventario: Factions
- Motivo del deslogueo (Voluntario, Kick, Crash, Bug, Reinicio): Reinicio
- Hora y fecha de deslogueo (Del servidor, en www.mithrandircraft.es): Aproximadamente 23:10 / 23:30
- Hora y fecha de relogueo y comprobación de perdidas (Del servidor, en www.mithrandircraft.es): 23:30 / 23:40
- Objetos que has perdido: Una armoro p4 entera, una Daga de diamante con Filo IV, Fuego II, Empuje II Irrompibilidad III. Un arco con Fuego II Infinidad I Irrompibilidad III, Poder I. 12 esmeraldas
- Información adicional y detalles: El inventario de Survival se traspaso a Factions, perdiendo el de Factions

**Comment by MithrandirCraft** [comment]
@KururuKiller Nos encargaremos de esto internamente.

**Comment by Blasfemia** [comment]
Hola, despues de multiples kick unos 40 en 2 horas aprox sin exagerar, claro que inofensivos xque cada vez que entre no perdia nada.
 hasta que .....

llego un reinicio fugaz sin aviso, al entrar me di cuenta que perdi mis cosas nuevamente.

calculo 1 hora atras hora del server seria 23:00 aprox ya que en mi pais son ahora mismo la 19:59 .. 
bueno..
estaba en el mundo SURVIVAL no cambie de mundo en ningun momento.
 
Perdidas

ARMADURA Completa:
Casco: P4, respiracion 3, irrompibilidad 3.
pechera: P4, espinas 3, irrompibilidad 3.
Pantalon: p4, irrompibilidad 3.
Botas: p4, caida pluma 4, agilidad acuatica 3, irrompibilidad 3

Herramientas:
Acha: eficiencia 5, irrompibilidad 3, fortuna 2
Pico: eficiencia 5, irrompibilidad 3 fortuna 3
Pico: eficiencia 4, irrompibilidad 3, toque de seda
pala: eficiencia 4, irrompibilidad 3

Armas:

Espada: Filo 3, irrompibilidad 3, empuje 2, aspecto de fuego 2, saqueo 3.
Arco: poder 5, flecha incendiria, reparacion, empuje 2, irrompibilidad 3, infinidad.

Bloques de construccion.

Ladrillos del nether rojos.
piedra del end, pulida 

que se compran con esmeraldas y oro, saque la cuenta y con 45 esmeraldas tengo para reponerlos, el oro me sobra no es necesario,

eso seria.


-El otro problema es: al entrar al server me dice "OTRAS DE TUS CUENTAS ACCOUNTS"  y sale:
 vampire, grindlock. 
esta ultima de grindlock que en mi vida la e visto, y nadie mas que yo ocupa mi notebook. mi otra cuenta es "Nosophoros"... le saque un pantallazo xque me parecio totalmente inadecuado que saliera ese nick asociado a mis cuentas, luego pueden decir que use la cuenta de ese jugador.

-al mutearme con la cuenta vampire entre con nosophoros, lo normal debio haber salido:
"OTRAS DE TUS CUENTAS ACCOUNTS"
vampire,nosophoros.  pero el nick de grindlock yo no se de donde salio...  no se  que se debe

gracias x tu tiempo mith.

**Comment by MithrandirCraft** [comment]
@Blasfemia

Es el bug de siempre. Te he entregado tus cosas.

Las cuentas que se muestran comparten la misma IP. No es ningún error. Si aparece una cuenta que no conoces, está utilizando la misma IP de tu router, si o si.

**Comment by Blasfemia** [comment]
gracias mith x devolver mis cosas :D  

perdida resuelta.

lo de la cuenta no tengo idea :O
