### ISSUE TITLE
Baneado, por que?

### ISSUE THREAD

**Issue by AndresGatoXD** [MithrandirCraft/MithrandirCraft#175]
Hola, quisiera saber la razón por que me han Baneado. Cuando entro me dice que desobedecí las normas pero en ningún momento lo he hecho.
Ademas cuando estaba peleando con el jefe Rey Zombi me ha kikeado la "CONSOLA" por "Kill Aura", fueron 2 veces y lo único que hacia es dar espadazos para todos lados por que los zombis me rodeaban (y el zombidito "Puninsher" es un estorbo), supongo que fue algún error de la propia Consola. Me moleste mucho cuando lo hizo, me hizo perder 2 veces suerte que no estaba en Fac.
Ademas habían 2 Rey Zombi uno con 800/800 de HP y el otro con 2000/2000.
Y otra cosa, es muy molesto que el Rey saque mas zombis, por que algunos de ellos pueden tomar ítems que el mismo Rey dropea al morir.

**Comment by AndresGatoXD** [comment]
Minutos después he podido volver a entrar, pero no kiero saber que cada acción que haga sea "ilegal" para la Consola.

**Comment by BlackBeemo** [comment]
Hemos baneado a Consola por no tener ni idea de como moderar, el administrador supongo que a estado modificando parámetros de algún nuevo plugin antihacks y se le fue la pinza, supuestamente el reset de hoy por la tarde revierte los cambios.

**Comment by AndresGatoXD** [comment]
Y que hay de lo Mobs que toman los ítems dropeados por jefes?

**Comment by BlackBeemo** [comment]
parece ser que aun hay  no funciona del todo bien el antihacks reabro esto.

**Comment by MithrandirCraft** [comment]
Hola, estoy al tanto de los problemas con los jefes en general.

Las duplicaciones se solucionarán pronto. En cuanto a los mobs recogiendo items, he aplicado un parche, espero que funcione.

Sin embargo, para cada problema deberías abrir un ticket, por lo tanto cierro el tema principal de este ticket que trata sobre el sistema antihacks, que ya ha sido calibrado ligeramente para evitar baneos por falso positivo.

Por el momento, sigo calibrando el nuevo sistema, asi que agradezco tu paciencia.

**Comment by AndresGatoXD** [comment]
He sido baneado por consola otra vez y esta vez por 10 min por "utilizar Regen hack 3 veces". No tengo ni la menor idea de que eso :/
