### ISSUE TITLE
Otra vez Baneado en falso. 

### ISSUE THREAD

**Issue by AndresGatoXD** [MithrandirCraft/MithrandirCraft#176]
Otra vez fui baneado... 2 veces el mismo dia: Una por "Regen" (no tengo la menor idea de que es eso) y otra por "FastClick" (tambien nose que es).

**Comment by AndresGatoXD** [comment]
Baneado otros 10min+ por "utilizar FastClik 4 veces" :/

**Comment by AndresGatoXD** [comment]
Baneado oooooooootta vez por utilizar "Spider". Peleaba con 2 zombis en Cueva cubo cuando paso -_-

**Comment by MithrandirCraft** [comment]
Solucionado.
