### ISSUE TITLE
Compatibilidad de drops de jefes con atributos y tiendas NPC

### ISSUE THREAD

**Issue by KawaiiGNE** [MithrandirCraft/MithrandirCraft#178]
Hola, hace unos meses que intentamos conseguir spawns de cerdo y de vaca, hemos conseguido desde hace bastante tiempo los recursos necesarios para obtener el spawn de cerdo, y nosotros nos preguntamos que para cuando estarían disponibles estos spawns o si se puede realizar alguna solución para este problema.

Gracias por su atención.

**Comment by MithrandirCraft** [comment]
Estoy al tanto de este problema. Este ticket permanecerá abierto hasta que sea solucionado.

Quizá hayáis podido apreciar que la disponibilidad de intercambio en esa tienda se ha bloqueado varias veces, sin embargo, en algún momento ha llegado a ser posible intercambiar ciertos spawners.

El problema es bastante complejo de explicar, así que me lo ahorraré. Pero puedo decir que esto se produce debido a que ciertos objetos con atributos internos presentan una mal función con su uuid interna.

No puedo poner una fecha acerca de cuando será arreglado, pero terminaré solucionandolo.

**Comment by MithrandirCraft** [comment]
Arreglado.
