### ISSUE TITLE
No me deja entrar al servidor.

### ISSUE THREAD

**Issue by BatmanNick** [MithrandirCraft/MithrandirCraft#18]
Ya e intentado con mas clientes como me dijiste pero sigue sin funcionar y no se pero sigue sin dejarme.
![7935fe0a-95cc-11e4-8b70-71b81be85755](https://cloud.githubusercontent.com/assets/10384583/5684431/56e6e7c0-9828-11e4-8d54-c249806db3a8.png)

**Comment by MithrandirCraft** [comment]
- Has revisado las faq's como te dije?
- Has probado las IP's alternativas de las faq's?
- Escribe la IP actual que estás introduciendo.

**Comment by BatmanNick** [comment]
Claro e revisado todo y lo e echo con diferentes launcher's,la ip actuac usaba la: mithrandir.craft.vg
Pero e probado tambien con la ip: 77.111.253.92
Y tampoco me deja entrar.

**Comment by BatmanNick** [comment]
Bueno al parecer hice un servidor de ip's en mi ordenador y accedi a una ip extranjera y al parecer ahora me deja entrar.

**Comment by FearMagix** [comment]
yo tengo ese mismo problema que no me deja entrar al servidor

**Comment by MithrandirCraft** [comment]
@FearMagix Has probado la solución de batman?

Has probado el nuevo DNS?: sv1.mithrandircraft.es

**Comment by FearMagix** [comment]
ya pude entrar pero hace tiempos abia probado esa ip y  no me abia funcionado
 
y gracias por tu ayuda Mithrandir
