### ISSUE TITLE
Anti spam

### ISSUE THREAD

**Issue by BlackBeemo** [MithrandirCraft/MithrandirCraft#180]
El anti spam salta muy amenudo, me salta a mi por escribir "muy seguido" y suele haber gente muteada por "spam".

**Comment by MithrandirCraft** [comment]
Si repites palabras o frases similares, es normal que aparezcan avisos de flood.

En cuanto al sistema habitual de bloqueo, creo que esta bien. Si quieres sugerir algun ajuste concreto comentamelo personalmente.
