### ISSUE TITLE
Necesito ayuda

### ISSUE THREAD

**Issue by vegetagamer9** [MithrandirCraft/MithrandirCraft#181]

**Comment by vegetagamer9** [comment]
Mithrandir... entro al sv y me quedo bugeado me podrias teletransportar al spawn?
Si no no podre jugar

**Comment by vegetagamer9** [comment]
ya esta
 lo solucione e.e

**Comment by vegetagamer9** [comment]
no sigue sin funcionar el server mith

**Comment by vegetagamer9** [comment]
me quedo bugeado

**Comment by vegetagamer9** [comment]
llevame al spawn

**Comment by BlackBeemo** [comment]
ya hay un ticket de esto men y sigues escribiendo como si esto fuese un chat :S
