### ISSUE TITLE
Hacks de RobGamer

### ISSUE THREAD

**Issue by vegetagamer9** [MithrandirCraft/MithrandirCraft#182]
https://www.youtube.com/watch?v=JCGEXCnBV_8&feature
Aqui el link de el hacker

**Comment by BlackBeemo** [comment]
Bueno RobGamer es un caso realmente especial. Al chico le de igual los bans y como le da igual los bans le dare jail indefinido a todas las cuentas que entre asta que suba un video borrando los hacks, si lo ven ablando esta de decoracion en la carcel numero cuatro de warp factions.

**Comment by vegetagamer9** [comment]
:D
