### ISSUE TITLE
Bug con marry tp

### ISSUE THREAD

**Issue by Catadolfa** [MithrandirCraft/MithrandirCraft#183]
Recientemente ocurrió una situación con el marry tp en el que jugadores casados con nombres parecidos se pueden hacer tp unos a los otros. Para ser mas clara, el bug funciona de la siguiente manera:

Si jugador X se casa con jugador Y
y jugador XX se casa con jugador YY

Jugador X le puede hacer marry tp a jugador YY cuando jugador Y está desconectado.

**Comment by MithrandirCraft** [comment]
Interesante.

Estaría bien que grabaseis esto, sin embargo, esto esta reportado clara y concisamente, por lo que creo que será suficiente.

**Comment by MithrandirCraft** [comment]
Puedes poner un par de nombres de ejemplo en vez de X e Y?

Si grabas un video sobre esto será más eficiente.

**Comment by MithrandirCraft** [comment]
Marry tp provisionalmente desactivado*

**Comment by Catadolfa** [comment]
si, pongamos de ejemplo el nombre KawaiiGNE, en este caso está casado con Unicornia_xD y el jugador Kawaii que no recuerdo con quien está casado, prero supongamos que conmigo, Ennya. Si yo uso el comando /marry tp y Kawaii no está conectado, el marry tp me llevaría hasta KawaiiGNE.

En otras palabras, puedo crearme una cuenta llamada Mithrandi y hacerme marry tp a ti si te encuentras en un mundo donde funciona el comando.

**Comment by Catadolfa** [comment]
Veré si puedo grabarlo mañana.

**Comment by MithrandirCraft** [comment]
@Catadolfa 
Confirma que esto está arreglado.
Revisen tambien si puede reproducirse con otras funciones, como el comando para enviar objetos.

**Comment by Catadolfa** [comment]
Bug arreglado
