### ISSUE TITLE
Hacks de TaTo_PvP

### ISSUE THREAD

**Issue by vegetagamer9** [MithrandirCraft/MithrandirCraft#184]
este video demuestra sus hacks :x https://youtu.be/O6Aiz5sDOM8

**Comment by BlackBeemo** [comment]
solo veo que este usando pociones de fuerza. Podrias especificar mas? En caso contrario cerrare el ticket como invalido

**Comment by Catadolfa** [comment]
Eso a lo que llamas es hack, es que muchas veces el lag deja a tu keko atras cuando tú ya has caminado como 4 pasos y aunque el jugador contra el que pvpeas le pegue a tu sombra tú sigues recibiendo el daño.

**Comment by Catadolfa** [comment]
Si de verdad quieres demostrar que TaTo_PvP lleva hacks dile a alguien que grabe por ti mientras tú haces PvP contra el.

**Comment by vegetagamer9** [comment]
Gracias por la idea Catadolfa

**Comment by AndresGatoXD** [comment]
Vegetagame9: En tu canal (theshadowither) por lo que veo hay una gran diferencia entre VER UN HACKER y ser MAL PERDEDOR. No eres Apto para acusar de alguien con uso de hack cuando claramente no sabes diferenciar. Y por favor sube cosas mas "interesantes" en tu canal, no a gente que te gana y la acusas de hack.
