### ISSUE TITLE
Propuesta: Sala de PvP de 1 Contra 1

### ISSUE THREAD

**Issue by Catadolfa** [MithrandirCraft/MithrandirCraft#185]
Rafaelox24 intentó robarnos la idea, pero aclaro aquí que posee copyright de Insidious. Se me ocurren varias ideas sobre como podrias hacer que funcione pero nose si son todas posibles. 

1. Con carteles así como en los servidores de PvP (No se si funciona ya que no lo he visto en este servidor)

2. Poner 2 placas de presión en el suelo que desaparecen cuando los jugadores las pisan para entrar. (Así como la misión de cura)

3. Que se haga con comandos.

Otra idea que se me ocurre, para matar 2 pajaros de un tiro, sería utilizar la sala de Baba Yaga para estos PvP y cambiar la sala de Baba Yaga de una vez para que deje de meterse entre las paredes.

**Comment by MithrandirCraft** [comment]
xD me ha gustado la excusa para las paredes de baba yaga.

Deacuerdo. Consideraré esta sugerencia, pero no prometo nada. Ten en cuenta que soy el único desarrollador de este servidor, estas cosas pueden llevar tiempo.

**Comment by rafaelox24** [comment]
Nunca le propuse nada de eso a Juanthrandir e.e

**Comment by Catadolfa** [comment]
Lo intentaste Nigguhelo.

**Comment by AndresGatoXD** [comment]
Me gustaría algunas salas de 1vs1 que imiten a los terrenos de batalla contra bosses, la idea esta genial ya que a mi tambien me molesta tener que estar viendo en que sala puedo estar solo con mi rival para luchar un 1vs1 sin que nadie se meta.

**Comment by GabbGabb** [comment]
1 vs 1? woah... que recuerdos xD

**Comment by MithrandirCraft** [comment]
Hola, por el momento voy a declinar esta sugerencia, no porque no pueda realizarse (Se puede realizar prácticamente sin ninguna modificación adicional y con pocas dificultades, solo con bloques de comandos, y implementando unas nuevas áreas)

Sin embargo, hace falta una construcción para cada una de estas salas "privadas", y la verdad, no estoy dispuesto a ponerme a hacerlo yo mismo. (Ya tengo suficiente trabajo)

Por lo tanto, cierro este tema, a no ser que alguien esté dispuesto a presentarse para Builder de forma comprometida, (Y no solo para realizar esta tarea.) y realizar estas construcciones.
