### ISSUE TITLE
Sugerencia: Raids y mundo Factions (Participación libre, comenta aquí tus sugerencias de balanceo)

### ISSUE THREAD

**Issue by Zerkley** [MithrandirCraft/MithrandirCraft#186]
El tema es que el raideo en este server es un poco aburrido debido a que la obsidiana no se rompe, los creeper no rompen, y es tan fácil como claimear, hacer un cubo de obsidiana sin agujeros y ser completamente impenetrable.

Por ello me gustaría que se cuidara un poco mas el tema del mundo Factions y la importancia de los raid, así como de la planificación y construcción de bases mas difíciles de raidear, lo que añadiría mas acción y menos sentimiento de impunidad en dicho mundo.

Espero que se revise esta sugerencia y, se tenga en cuenta o no, reciba alguna respuesta para saber el grado de satisfacción por dicha información.

Gracias.

**Comment by MithrandirCraft** [comment]
Balancear Factions no es algo sencillo. Este tema que acabas de abrir es algo que ya lleva debatiendo-se desde hace años, sin embargo, la solución no es tan inmediata como "activar obsidian destruible", al menos no aquí.

Ten en cuenta que en MithrandirCraft, el sistema de Facciones siempre proporciona una Defensividad mas elevada a las facciones de los jugadores, esa es la naturaleza de este Servidor, en contraste con otros servidores donde destruir facciones ajenas esta más facilitado gracias a obsidian destruible y withers destructores.

Las contrapartes de soluciones faciles como activar obsidian destruible (Y no digo que no pueda ser parte de la solución):
  - Facciones destruidas en menos de 1 minuto.
  - Facciones offline extremadamente vulnerables.
  - Esperanza de vida media de una facción menor a 24h.

A que punto de óptimo de balanceo de Factions queremos llegar?
  - Las facciones mas organizadas, activas, esforzadas, y con más miembros, deberían tener la 
    oportunidad de protección y ofensividad más elevada.

Esta claro que aún queda trabajo por hacer en ese ámbito de balanceo, y está genial que hayas abierto este ticket, porque así cualquier jugador podrá expresar su opinión y comentar acerca de este tema, que ya lleva tiempo mencionando-se.

**Comment by MithrandirCraft** [comment]
Ajustes provisionales:
- Duplicada cantidad máxima de terrenos claimeables (40)
- Quadriplicada capacidad de miembros por facción (40)
- Aplicada destructibilidad de obsidian con 30 explosiones de TNT.
- Aplicada destructibilidad de mesas de encantamiento y enderchests con 2 explosiones de TNT.
- Valores de coste destrucción x2 si hay agua.
- 1 punto de regeneración por bloque de obsidian cada 5 minutos.
Condiciones:
- Estos ajustes son experimentales (En vivo).
- El poder máximo de una facción sigue siendo de 100.
- Solo TnT hace daño a obsidian, ni Withers, ni Creepers, ni pollas en vinagre.
Cualquier valor mencionado puede ser provisional y debatible en este ticket

Factions actualizado.
Entran los ajustes YA.

**Comment by Catadolfa** [comment]
Preguntas:

- Como funcionará el poder ahora ya que se cuadriplican la cantidad de miembros en la fac? 40 miembros = 100 de poder? o 10 miembros = 100 de poder y el resto poder extra?

- ¿Si la obsidiana es destructible através del agua, la roca y otros materiales tambien?¿El agua aumenta la defensa de otros materiales?

- ¿La protección del agua es acumulable? Es decir ¿Puedo aumentar mas capas de agua y hacer que la protección se siga multiplicando?

**Comment by MithrandirCraft** [comment]
@Catadolfa 

- Como ya he dicho en la condición #2, el poder máximo sigue siendo de 100. Si quizá tienes alguna duda de como funciona la relación poder/jugadores/terrenos, puedes visitar /warp tutorialfactions.

Este tutorial esta desactualizado, ya que depende del mapa del mundo de eventos, que está siendo desarrollado en un servidor paralelo de construcción. Por lo tanto, cuando acutalizemos en mapa, entrará la información actualizada.

- Lo que seguramente estés pensando es correcto. Por el momento, solo la obsidiana es destruible a través de agua. Eso quiere decir que cualquier otro material recubierto de agua será más eficaz que obsidian.

- No, no es acumulable. Mientras el obsidian tenga una barrera de agua protegiendolo de la explosión, la dificultad de destrucción será duplicada. Es decir, un bloque de obsidian con 30 puntos bajará 0.5 puntos cada vez que reciba un impacto de explosión de TNT (sin agua, 1 punto). (Puedes imaginarlo como si dispusiese de 60 puntos solo por el hecho de haber agua cerca.)

- Si se revierten estos cambios será pronto y por que haya suficientes sugerencias de balanceo que lo inciten en este ticket. En cuyo caso (que de momento veo improbable) procuraré avisar, pero tened en cuenta que en ocasiones es necesario aplicar ajustes de forma inmediata por cuestiones técnicas.

Sigo trabajando en el balanceo de Factions, cualquier otra pregunta y/o sugerencia es bienvenida, ya que estoy seguro de que ayudará con el equilibrio de las raids.

**Comment by AndresGatoXD** [comment]
Con todo respeto, a la gente que no este de acuerdo de que en este servidor la obsidiana no sea petable, le pido por favor que vuelvan al otro servidor de donde sacaron la idea, no me gusta la idea de que la apartir de ahora la obsidiana sea petable. Ya hay un método de robar una facción sin petarla que es bajarle todo el power. 
Pero nose si podre acostumbrarme a estos cambios.

**Comment by KawaiiGNE** [comment]
Son unos cambios bastante radicales, que aparecen de golpe sin apenas información, no creo que haya sido la manera mas adecuada de ponerlos en el servidor, estaría bien un aviso con algunos días de antelación, de todos modos los cambios son bastante raros ya que si por ahora resulta que tapando bien con agua un material que no sea obsidiana resiste mas que la obsidiana descubierta o bajo agua, parecen unos cambios muy extraños.

No obstante este cambio es aun peor para todos, ya que ahora las facciones poderosas pueden defenderse igualmente, pero las facciones pequeñas están muy perjudicadas por que a la mínima que sean vistos ya les puedes decir adiós, las facciones medianas ahora son mucho mas vulnerables, lo único que se consigue con estos cambios es que los jugadores nuevos tengan mucha dificultad para empezar en factions y por ello prefieran irse, que los jugadores que crean tener seguridad en su facción de 15 días o 1 mes vean como fácilmente un grupo grande de jugadores no tenga dificultad en destruir su facción por completo.

Me gustaría añadir mi desacuerdo ante estos cambios y a la falta de aviso previo.

**Comment by Zerkley** [comment]
No creo que decirle a alguien que da una idea que se vaya del server sea algo respetuoso. Se puede debatir la idea, darle una forma mas equilibrada.

Y para quien cree que bajar el poder es suficiente para raidear una facción es que no ha intentado atacar facciones que son cubos de obsidiana sin entrada ni salida, en los que sus dueños simplemente hacen /f home y son intocables. Ya ni hablemos si la facción tiene mas de cuatro personas ahora que el límite de chunks ha subido a 40. La mayoría de facciones con base cubo como he mencionado son de +6 personas, lo que hace 60 de poder o mas. es decir, habría que matar a muchos de ellos incontables veces para bajar su poder por debajo de 20, que es lo que la mayoría de facciones tienen claimeado. Si a esto le sumas el hecho de que es casi imposible entrar en las bases y que el counterplay mas fácil contra un raideo es simplemente irse al spawn y esperar a que los raiders se aburran, pues si, creo que el factions está desbalanceado a favor de los defensores.

Aún así, sigo manteniendo que los balanceos se pueden ir probando progresivamente y que no es necesario crear tensiones con nadie. Este es un muy buen server, y hay que tener en cuenta que a veces, los cambios no gustan a todos.

**Comment by MithrandirCraft** [comment]
@KawaiiGNE @Zerkley 
Estoy bastante deacuerdo con ambas visiones. Creo que podemos distinguir entre 4 elementos a balancear: 

Jugadores veteranos (ventaja) - Jugadores novatos (desventaja). 
Facciones volatiles - Facciones completamente indestructibles.

Es cierto tambien que se va a tender a utilizar el agua y cualquier otro material defensivamente, y tambien lo tengo en cuenta. Me gustaría que por el momento me demostréis cuales son las mejores técinicas que teneis para defenderos. (Estoy testeando yo tambien.)

@AndresGatoXD 
Es comprensible que surja miedo por estos cambios, especialmente entre los mas veteranos, pero me temo que por aquí van los tiros. El sistema de facciones va a ir evolucionando poco a poco hacia un sistema que permite brechas de seguridad más cuidadas en todos los terrenos de facción.

He establecido algunos de los puntos ideales a los que deberíamos alcanzar.

Aún estoy haciendo cambios, tened por seguro que se presentarán pronto. Por el momento, estoy considerando otorgar durabilidades distintas a distintos materiales, de modo que haya distintos tipos de bloques utilizables defensivamente, mas o menos difíciles de obtener.

En cualquier caso, este es un tema que ahora que ha sido abierto con plenitud, va a tardar un tiempo en refinarse de forma perfecta, pero no se cerrará hasta que el balance esté en un punto aceptable.

**Comment by MithrandirCraft** [comment]
Nuevos valores de resistencia:
    enderchest: 2
    enchanting_table: 3
    anvil: 8
    end_stone: 20
    obsidian: 60
    bedrock: 300

**Comment by MithrandirCraft** [comment]
Algunos de estos valores no se estan aplicando correctamente, lo estoy arreglando.

**Comment by Catadolfa** [comment]
Mith, visita la fac Insidious. En mi opinión, y no por alardear, la mejor tecnica de defensa.

**Comment by MithrandirCraft** [comment]
@Catadolfa Interesante, gracias por compartir vuestra estrategia, echale un vistazo a este ticket porfavor: https://github.com/MithrandirCraft/MithrandirCraft/issues/183

**Comment by JessyelXD** [comment]
Mithrandir no esta mal la actualización pero la obsidian se regeneraría solo como un punto por cada 15 minutos, o la obsidian no se regenera????

**Comment by thothomas** [comment]
yo tengo 2 dudas:
que la bedrock tenga un valor de 300 significa que ahora es destructible?
para romper obsidiana se pueden explotar simultaneamente 60 tnt en el mismo lugar? O tiene que prenderse 1 a la vez?

**Comment by MithrandirCraft** [comment]
Colgaré todos los detalles que pidáis de golpe, en un informe final, cuando los ajustes completos hayan sido aplicados.

**Comment by Catadolfa** [comment]
Según tú has echo cambio en el valor de resistencia del End Stone ¿Eso es su valor bajo el agua o el valor normal? Si es el valor normal el cambio no se ha efectuado.

**Comment by JessyelXD** [comment]
### Hola soy el player: JessyelxD.

Me gustaría proponer que se retirara el sistema de protección de cofres como en los servidores de raideo masivo.

Para que los jugadores tuvieran que preocuparse por las defensas y resultara mas importante las defensas. Crear un mundo mas masivo en el que la gente tenga que luchar mas. pienso que estaría bastante mas emocionante el juego en general. También la protección de cofres se puede hacer con diversos sistemas de Redtone. También pienso que la TNT esta muy cara en el pueblo (no soy el único) 1 esmeralda por 1 TNT (Sale mas caro que los diamantes xD)
-----
Comentario todo el que apoye una de las 2 propuestas (no vale solo mirar) xD
Saludos

**Comment by Catadolfa** [comment]
- No me gusta la idea de que se retire la protección de cofres en su totalidad. Sin embargo si me gusta la idea de que baje el precio del TNT para que todos los jugadores tengan la oportunidad sacarle jugo a factions. Lo mismo se hizo con la obsidiana. Así como todos los jugadores deberían tener la oportunidad de defenderse, todos los jugadores deberían tener la oportunidad de poder petar a otros.

- Algo que sí estaría muy bien es ponerle un valor de resistencia a los cofres bajo el agua, algo no muy bajo pero tampoco indestrucctible. Un valor entre 40 y 60 estaría bien para los cofres.

**Comment by JessyelXD** [comment]
Hola gracias por apoyar con lo de la TNT. La resistencia de cofres contra explocones me parce un poco rarro que si un cofre tiene mas resistencia que la roca las casa estarian eschas de cofres xD resultaria muy raro creo que esta bien que exploten con facilidad (Un valor bajo seria 2 explociones no de 40) gracias por apoyarme esperemos que la bajen el Precio de la TNT si valieran lo mismo que la obsidiana 1 esmeralda por 8 TNT talves me e flipado un poco. pero almenos 4 TNT por cada esmeralda 
---
Venga vamos que nos creamos un hashtag: # TNTBarata

**Comment by AndresGatoXD** [comment]
Supongo que la TNT debería estar como 3 o 2 por Esmeralda, ya que tiene que ser un precio preciso y del cual los que compren no abusen.
#TnTBarata :V

**Comment by MithrandirCraft** [comment]
Sois conscientes de que también existen spawners de creeper?

También es posible conseguir TnT mediante drops de jefes. Se que no es gran cosa, pero aún estoy en ello para proporcionar mas.

**Comment by AndresGatoXD** [comment]
Mithrandir con todo respeto, eres consciente del precio de tal spawner?
Conseguir 64 bloques de esmes es algo difícil y los "Muelles" (botas con caida pluma V) es MUCHO mas. Ese item solo lo dropea El Maestro pero en una mínima posibilidad xD :V

**Comment by MithrandirCraft** [comment]
Habrá algún ajuste con el TnT para cuando haya arreglado el problema con los bloques. Para entonces debería haber otro informe de los cambios...

**Comment by JessyelXD** [comment]
Gracias por Considerar la propuesta 
---
una pregunta creareis vendedores de  RocaMadre? o nos obligareis a tener que gastar TNT para intentar obtenerla con altas pociblidades de que caiga al vacio ? o Creareis un Pico lejendario que pueda romper la RocaMadre? estaria bien que fuese un pico de bloques de diamantes xD

Gracias

**Comment by Catadolfa** [comment]
El end_stone se consigue comprandolo en el mismo aldeano que vende la obsidiana.

**Comment by MithrandirCraft** [comment]
@JessyelXD Roca madre es imposible de obtener ahora mismo. Pero os garantizo que se podrá conseguir.

Como ya te han dicho, la end_stone se consigue comprandola. La que ves en el end está protegida, simplemente, no puede ser minada.

Los valores que he establecido aquí, de durabilidad de bloques, no son fiables todavía. Voy a procurar estabilizarlos cuanto antes y realizar otro reporte más completo.

**Comment by vladtriana** [comment]
Hola buenas y a cuantos saldria la roca madre pa comprar... uff necesito 120 stack 😊

**Comment by vladtriana** [comment]
Hola mith los ajustes  provisionales son official  o siguen en beta experimentado 😊

**Comment by JessyelXD** [comment]
Hey una cosa muy importante mith podrías crear un cubo para recoger lava que en lugar de llenarse tuviera usos ejemplo: recojo 20 de lava y se me crea un cubo de lava con 20/30 usos y que se pudriera rellenar. tengo un gran proyecto pero me hace falta cantidades enormes de lava y resulta muy difícil recoger lava de 10 en 10 cubos... o si pudieras que la lava se pudriera hacer la lava como la agua. que el unio sitio donde hay la suficiente lava es en el neder

**Comment by SimplyAcke** [comment]
Mi propuesta sería una diferencia muy remarcable:

_Ningún cofre es protegido por la facción_. Esto potenciaría la **defensa** de la base con sus respectivas barreras de agua y lava etc... De esta forma, a pesar de que la fac está protegida, si logras entrar puedes abrir los cofres sin problema puesto que usar TNT para entrar en una faction ya es complicado, pero si encima hay que hacer explotar los cofres es bastante tedioso. Por eso opino que podríamos hacer que los cofres no se protejan así la gente encuentra maneras de proteger sus cofres como esta:

Paso 1: https://gyazo.com/0a345ac87599682279260c8680d9cb3b

Paso 2: https://gyazo.com/f34f0212b0cbee6839fd5a9408158b43

Paso 3: https://gyazo.com/5115836b56c711d333c9d30ad2965184

Paso 4: https://gyazo.com/37f813ab658d8783850817b52de99bd0

Detallando esto, es un generador de cobblestone usado para proteger los cofres mas preciados. De esta manera se le da más juego a la protección de cofres y más potencial al raid.

¿Qué opináis?

**Comment by JessyelXD** [comment]
Me Gusta la idea pero havria que avisarlo munos 4 dias antes en el servidor como un anuncuio para que todo el server lo sepa colo el anuncio del comando /f para ver los codigos de fac

**Comment by MithrandirCraft** [comment]
@SimplyAcke 

No eres la primera persona en pedir eso. No parece mala idea.
Lo único que puedo pensar es que reduciría el nivel estético del interior de una facción.

Que pensais los demás?

**Comment by MithrandirCraft** [comment]
@JessyelXD Existen limites en Minecraft vanilla que no voy a modificar. Estan allí por buenas razones de balanceo.

**Comment by JessyelXD** [comment]
Hola soy el player (JessyelxD) me gustaría que pusieseis alguna manera de clasificasion por facions, como en el pvp para confirmar que mi fac es la top xD, era broma lo de que soy la top facions pero me gustaría que las faciones se classificaran  como en el pvp(sumando los kills de todos los jugarores  o la facion con mas power(poder) o la facción con mas terno claimedos) no estoy muy seguro de como funcionaria el sistema però creo que todos queremos desir somos la mejor facion!! 

Comenta?¿!

**Comment by Nepo23** [comment]
Sugerencia de balanceo:
  1)Los jugadores inactivos puedan perder poder.
  2)Agregar modo pvp (EASY)
  3)Salas nuevas dedicadas a este nuevo modo (EASY)
  4)Que el jugador pueda elegir que llevar, basándose en algunos presets (EASY)
  5)Que el jugador no pierda el inventario y le sea sustituido al comenzar el pvp custom (HARD)

**Comment by ZertahhLoL** [comment]
@MithrandirCraft También se podría reducir la regeneración de poder por hora,que creo que esta muy elevada.Facciones se centra en raidear--->Explotando o matando para robar tierras,y es que entre tanta regeneración de poder y que no puedes matar muchas veces a uno o varios jugadores es casi imposible.

Esto se puede añadir también a lo que he comentado anteriormente de manera que,si la faccion es mas fuerte,obtienes menos regeneración de poder,o al revés,para darle un poco mas de lógica y además que cada lado tenga su beneficio.

(EJEMPLO)
Tienes una faccion en la que estas tu solo,tu poder se regenera de manera muy reducida,pero eres mas resistente a los raids .Pero si tu faccion tiene 10 miembros,tu poder se regenera mas rápido,lo que te permite morir más,pero eres mas vulnerable a raids,ya que,por ejemplo,tus cofres pueden ser abiertos...
