### ISSUE TITLE
Bug de PvP: "Toca y Corre"

### ISSUE THREAD

**Issue by AndresGatoXD** [MithrandirCraft/MithrandirCraft#187]
Hay un pequeño pero MUY molesto bug en PVP, Pongamos este ejemplo: Cuando el Perro golpea al Gato y este no le regresa el golpe, y el Perro vuelve a estar detrás de la linea (en zona segura) el Gato no podrá atacar al Perro ni él al Gato (de esta forma lograban matarme en pvp sin que mi rival reciba un golpe).

**Comment by MithrandirCraft** [comment]
Podrías grabar esto porfavor?

Se hicieron cambios para que nadie pudiese escapar de un combate huyendo a zona segura. Un combate dura 10 segundos desde que hay interacción de PvP entre 2 personajes.

**Comment by GabbGabb** [comment]
Andres, explicando cosas, es un profesional xD

Lo que querrá decir, es eso que comenté en su tiempo sobre lo del modo combate en zona segura entre allys.

al parecer, cualquier 1 vs 1, si estos son ally, de la misma fac, o truce, tras la zona segura no se dañarían entre ellos. No pasa con neutrales y enemy.

De hecho, para matar a personas molestas, le puse enemy a cierto grupo de individuos. Y actualmente, esos individuos siguen contaminando el PvP xD

**Comment by MithrandirCraft** [comment]
@AndresGatoXD Si lo que dices es así, y solo ocurre con aliados, me parece una hecho aceptable.
No puedo considerarlo un error, ya que trato la relación de alianza como una relación de confianza (rima y todo.), y consecuentemente, entre gente de confianza no debería estar ocurriendo eso.

Parece un bug bastante oscuro, asi que esta claro que si queréis que haga algo al respeto vais a tener que esforzaros mas detallandolo. Yo he entendido una cosa, pero no estoy 100% seguro de que sea lo que me queréis transmitir.

Este ticket lleva demasiado tiempo abierto sin una respuesta de @AndresGatoXD, por lo que voy a cerrarlo. Si desea abrirlo de nuevo y comentar sobre ello puede hacerlo, pero estoy esperando que aclare más entrando en detalles.

**Comment by AndresGatoXD** [comment]
No creo que sea eso, relaciones en entre fac. Este problema me sige ocurriendo aun con la resien perdida de mi Fac. Supongo que tendre grabarlo despues de todo, que flojera buscar un capturador de pantalla xD
