### ISSUE TITLE
hola ! 

### ISSUE THREAD

**Issue by vampiredrem** [MithrandirCraft/MithrandirCraft#188]
Tengo problemas con lo de proxy, e echo todo lo que estaba en el ticket cambiar la ip verificar si esta en una lista negra, lo de reiniciar, apague mi note, borre el server y lo puse otra vez ya no se que mas hacer aun sale el mensaje de proxy detectado, antes del ultimo mantenimiento de varias horas podía entrar sin ningún problema, desde que el server esta en ON  nuevamente ya no puedo entrar.
gracias de antemano.

**Comment by MithrandirCraft** [comment]
https://github.com/MithrandirCraft/MithrandirCraft/issues/108
