### ISSUE TITLE
Idea Sala PVP con perdida de Items y power sin magias

### ISSUE THREAD

**Issue by JC1609** [MithrandirCraft/MithrandirCraft#189]
En el servidor se podrían implementar salas de pvp con perdida de items y power ya que resulta aburrido ir a pelear sin conseguir una recompensa. Se implementarían o sustituirían unas 3 salas y alguna con caida al vacio y lava para darle mas emocion. Se me ocurrió esta idea ya que en el mundo factions es muy difícil encontrarte a algun player, esta implementacion animaría a jugadores a conseguir armors muy buenas como a perderlo todo. Espero que se lea!

**Comment by AndresGatoXD** [comment]
Es una buena idea, a pesar de que eso ya esta en factions... es verdad es dificil encontrar a alguien. Pero si se llega a poner esta sala supongo que estaría vacía o no habría a nadie a quien robarle, quien iría a esta sala y si esta llena con tipos con P4, y espadas OP xD

**Comment by JC1609** [comment]
Esa es la idea hacer varias salas, por lo general hay una sala de pvp que esta llena y las otras están vacías entonces todos estarán en una sala y los que quieran hacer pvp con hierro se van a otra...

**Comment by AndresGatoXD** [comment]
Si, y ademas de que agregaran 1vs1, para evitar metiches.

**Comment by JC1609** [comment]
Wow eso no lo sabia! le dara mucho juego al sv!

**Comment by MithrandirCraft** [comment]
Ok, pues que así sea, una sala de pvp con perdida de items.

Sin embargo, no creais que esa sala se va a librar de avisos pertinentes de perdida de items.

Como ha dicho @AndresGatoXD, intuyo que no va a visitarla mucha gente, por el factor de perdida de items. Por el momento, ya teneis Factions en si, y TheEnd.

**Comment by AndresGatoXD** [comment]
Mith, Podrias poner salas con limites de players?
1vs1
2vs2 (aqui habrian Team por color para evitar traiciones).

**Comment by JessyelXD** [comment]
Yo diría mas bien una sala de pvp con perdida de items pero sin perdida de poder como e visto en un montón de servidores. Con una sala sin perdida de poder pero con perdida de items podríamos hacer épicas batallas i venganzas

**Comment by MithrandirCraft** [comment]
@JessyelXD Así sería, sin embargo, el problema principal es hacer que los jugadores pierdan sus objetos en un area concreta de ese mundo, donde la perdida de objetos está bloqueada.

De hecho, eso me hace ver la principal diferencia entre pelear en una sala así, y pelear en Factions o el End, donde perder power sería posible.

**Comment by MithrandirCraft** [comment]
Saludos. He estado mirando opciones para implementar este tipo de sala de PvP.

La mejor manera sería aplicar por lo menos 2 plugins más, que funcionen en conjunto con el plugin de protección de áreas.

Debido al hecho de que añadir más componentes al servidor, solo va a significar más posible mantenimiento y trabajo... me temo que voy a tener que declinar esta sugerencia.

No es que no se pueda hacer, simplemente no estoy dispuesto a invertir el tiempo que hace falta para mantener tal función en el servidor, ni para desarrollar yo mismo tal función, para que de menos posibles errores al compaginarlo con el resto del servidor.
