### ISSUE TITLE
Contacto con mithrandir

### ISSUE THREAD

**Issue by Pabloxlive** [MithrandirCraft/MithrandirCraft#19]
Ya se que puede parecer que soy un pesado,pero necesito hablar contigo,y por aqui es un rollo,por el tema de la faccion aquella,dime tu skype o ts o lo que sea,pero hay que hablar esto ya que no me parece para nada justo lo que esta pasando.

**Comment by MithrandirCraft** [comment]
Tu skype.

**Comment by Pabloxlive** [comment]
pablorubiolp
