### ISSUE TITLE
Hacker o hackers no lo diferencio.

### ISSUE THREAD

**Issue by vegetagamer9** [MithrandirCraft/MithrandirCraft#190]
https://youtu.be/VMOdYgFszW4 
Este video hay hackers MineNinja que insulta 
y de ArlekinHD no estoy seguro del todo.

**Comment by vegetagamer9** [comment]
Esperaré impacientemente la respuesta

**Comment by MithrandirCraft** [comment]
El veredicto interno: No hay pruebas concluentes.

Recuerda que estamos trabajando en un sistema antihacks avanzado, por el momento tiene muchos bugs, pero no debería tardar mucho en ser implementado. Hasta entonces, paciencia, y a aguantar cualquier caso vezaz de uso de mods ilegales.
