### ISSUE TITLE
Bug con dispensadores 

### ISSUE THREAD

**Issue by KawaiiGNE** [MithrandirCraft/MithrandirCraft#191]
Hola, me he dado cuenta de que si dos dispensadores se activan al mismo tiempo, solo uno de los dispensadores realiza su función.

Es esto algo planeado por el server o es un bug?

Gracias por su atención

**Comment by MithrandirCraft** [comment]
Es intencional. Uno de los muchos cortes que he realizado en el servidor para prevenir lag.
