### ISSUE TITLE
una injusticia D:

### ISSUE THREAD

**Issue by OdyZeus** [MithrandirCraft/MithrandirCraft#192]
estaba yo tan normal en sala 6 de pvp  y entro Rafaelox24 y me mata regreso yo y le mato después de unos minutos me sale el letrero de bandeado por 1 mes por uso de hacks 
![7](https://cloud.githubusercontent.com/assets/17105555/12874591/86e314a0-cda4-11e5-80c8-96e183b5c375.png)
 
decido entrar con otra cuenta para preguntarle el por que de ese baneo  y no responde le digo  que me muestre la evidencia o que si quiere que le comparto pantalla por skype y le hago un pvp  para que se entere de como hago pvp y me responde que si sigo molestando que me mutea pero yo le sigo pidiendo que me retire el baneo por que no e echo nada malo y me mutea por 10 días eso es injusto que lo baneen  y uno ni se pueda defender D: 
![3](https://cloud.githubusercontent.com/assets/17105555/12874652/876dc1b2-cda5-11e5-8808-2371befb694f.png)
![4](https://cloud.githubusercontent.com/assets/17105555/12874649/867154cc-cda5-11e5-99e6-d91ac084176d.png)
![5](https://cloud.githubusercontent.com/assets/17105555/12874650/86c30358-cda5-11e5-8578-e35d2b1af357.png)
![6](https://cloud.githubusercontent.com/assets/17105555/12874651/86de0252-cda5-11e5-8b63-605fe58586e5.png)
![1](https://cloud.githubusercontent.com/assets/17105555/12874654/892c194a-cda5-11e5-948b-1f2ed74ec25e.png)
![2](https://cloud.githubusercontent.com/assets/17105555/12874653/87b24666-cda5-11e5-9370-ba23ee16fa25.png)

**Comment by vegetagamer9** [comment]
Rafa ahora se esta poniendo pro es decir, que a la mas minima BUM baneo en tu cara

**Comment by vegetagamer9** [comment]
osea aunque tengas lag

**Comment by MithrandirCraft** [comment]
No se mostrará ningún tipo de prueba para fomentar el motivo de ninguna expulsión.

Sin embargo, pasaré este ticket a mi equipo, para ver si quieren revisarlo.

Jugad legal, o las consecuencias empeorarán.

**Comment by OdyZeus** [comment]
1) ya e echo pvp con Farmex Zirix Xlebet Deidei y con ninguno de esos mods me avía pasado algo así ni similar. 
2) no entiendo si dice que me estaba vigilando por que no saco un vídeo para respaldar el baneo
3) y ademas me silencia por 10 días solo por pedirle que me dejara demostrarle que no uso hacks 
ni siquiera estoy promocionando otro server ni diciendo malas palabras ni tampoco repitiendo el mismo mensaje mas de 2 veces 

hago mucho pvp en sala 6 y no me considero malo 
![2016-02-07_17 30 04](https://cloud.githubusercontent.com/assets/17105555/12875837/f3bcfa5c-cdc0-11e5-99e7-724f79a46c6f.png)
 
acá dice que no confié en ellos en pvp pero entonces hagan una lista de los moderdores con se pueden matar así uno ya no les mira

**Comment by OdyZeus** [comment]
No se mostrará ningún tipo de prueba para fomentar el motivo de ninguna expulsión.

pero  y si es un error y uno es baneado injustamente que se puede hacer?
como se dice en mi país somos Humanos y cometemos errores

**Comment by rafaelox24** [comment]
Mira, no se si crees que soy ciego o que, te vi haciendo pvp y pegas super raro y de echo dure mucho rato en sala 6 para estar mas seguro, incluso al final me fui de la sala y decidi dejarlo asi y pensar que no era nada, pero al rato entro nuevamente a sala 6 y me empiezas a pegar estando AFK. Si vas a estar con hacks se mas cuidadoso n_n!!!!.

**Comment by OdyZeus** [comment]
y usted como sabe que estaba afk una cosa es que ami no me guste hablar mucho 

le pedí que por favor me dejara demostrarle que no soy hacker e echo pvp con muchas persona y no dicen nada incluso con mods  xlebet es una de la mejores por no decir la mejor en pvp y pega super rápido y eso no quiere decir que es hacker

**Comment by MithrandirCraft** [comment]
Caso cerrado.
