### ISSUE TITLE
Propuesta: "Nuevas formas de obtener esmeraldas".

### ISSUE THREAD

**Issue by AndresGatoXD** [MithrandirCraft/MithrandirCraft#193]
Ya se me hace un poco aburrido ir a tener que matar los mobs para que den sus cabezas, hay solo 2 jefes que dropean esmes (Jotunheim y el Maestro, pero 1 esme ambos), aunque también los dropean los mobs Zombi Oscuro y Zombi Esmeralda (según dice en su descripción) pero son muy raros de encontrarlos (y minar no es lo mio xD). También otra forma es en Tradeos, pero lleva mas tiempo.
Me gustaría algo como Misiones o "Búsquedas de tesoro", o que algunos jefes dropeen mas esmes. Algo que he notado es que no hay aldeanos que cambien las cabezas de Guardian, Golem de hierro, Muercielago, Lobo/Perro, Caballo y de Players (Jugadores, se pondran mas activos para sacar las cabezas de los demás)
Ah, y otra cosa, si Mithrandir no dropea cabeza, para que es el aldeano que la cambia?

**Comment by MithrandirCraft** [comment]
Estoy deacuerdo, y este tipo de formas de obtener esmeraldas ya están planificadas.

Voy a cerrar tu ticket, no porque ya se hayan aplicado estos métodos, sino porque ya los tengo en mente y se van insertando con las actualizaciones progresivas.

Mi cabeza suele entregarse en eventos. Ahora mismo creo que es el objeto mas valioso de todo el servidor... He bajado el precio de la bedrock porque va a empezar a ser mas común una vez sea destruible.

Como puedes ver, los cambios son siempre constantes, solo necesitais paciencia. Muchas de las sugerencias que se suelen hacer ya las tengo en mente.
