### ISSUE TITLE
Queja contra MOD FARMEX

### ISSUE THREAD

**Issue by Vegepapa** [MithrandirCraft/MithrandirCraft#194]
![banneo](https://cloud.githubusercontent.com/assets/17154330/12938506/47bdf0f6-cf7a-11e5-9b08-f51553553fbd.png)
El día de hoy el MOD Farmex me ha Banneado durante 24 horas por la supuesta Norma 14.

cuando el mas inactivo de mi fac solo tiene 5 días,, puedes revisar otras facciones donde hay usuarios con mas tiempo de inactividad.

y tengo un player xXKrixusXx que tiene mucho tiempo de inactividad pero por que fue banneado.. y por tal motivo no se ha conectado.

Exijo una explicacion y sea enmendada esta situación.

ya que gracias a su banneo se perderan todas mis cosas de valor que deje tiradas. y mi faccion puede ser atacada !!!! sin que pueda protegerla

**Comment by Vegepapa** [comment]
He platicado con el MOD xLebet, quien siempre se ha definido por su buen criterio el cual me explica que el mayor tiempo de inactividad permitido es de 30 días, sin embargo mi player mas inactivo es xXKrixusXx solo tiene 12 días soy lider de la fac Targaryan.

Me diriji a él por el rango que tiene, ya que el Mod Farmex, no tuvo la cortesía de responder a mis preguntas. posteriormente me dice que fui kickeado por que dije una mala palabra "zorrita" lo mas curioso es que me ha kickeado a mi por decir "zorrita", cuando estaba en medio de una pelea en PVP, con su amigo racso, quien utilizo palabras como pende.jo y a el si se lo permitió.

Mithrandir, quiero pensar que para escoger a tus MODS checas que tengan un buen criterio para saber cuidar de tu servidor, sin embargo en esta ocasión se ha dejado ver la preferencia.

O cuantos consideran la palabra "Zorrita" mas grave que "pende.jo"

Como podras ver me bannean por una razon, y luego me dicen que fue por otra, dejando ver que no conocen las normas que has establecido, para el buen control de tu servidor.

**Comment by ModFarmex** [comment]
Te he baneado por que tras una advertencia ( un kick por insultar), seguiste provocando al otro jugador que también expulse por insultos, insultos que tu provocabas al insultarlo con comentarios como zorra, zorrita etc.

Para prueba de ello esta imagen:
![insultos vegepapa](https://cloud.githubusercontent.com/assets/12589956/12939310/f8319bc8-cf83-11e5-8485-fe93ee9614e5.png)

En cuanto a la razón especificada en el Ban, he corregido, es por la norma 15.
(A-B)-C Cualquier actitud que un administrador o moderador considere perjudicial para el ambiente de juego o el servidor en general.

Ahora no recuerdo en que momento me hayas pedido una explicación y yo te haya ignorado, tienes alguna captura?. En fin, espero que ahora ya te quede claro el motivo.

**Comment by Vegepapa** [comment]
En tu captura de pantalla se observa donde racso dice que lo has kickeado. Sin embargo vuelve a utilizar la palabra perra,..


A mi jamás me kickeaste. Sólo me banneaste de manera directa.

Se puede observar la preferencia por mi hora de banneo y checar que a pesar que el dice perra.. No fue banneado. Y yo por decir zorrita si aplicas la norma...

Si es que lo expulstaste habría que ver si fue al mismo tiempo que a mi o fue mucho después ya cuando expuse mi queja.. Ante xLebet, si fuera así, habría que considerar si lo hiciste por las normas o sólo para cubrir la evidencia de preferencia.

**Comment by MithrandirCraft** [comment]
Lo que xLebet quiere decir, es que los jugadores con más de 30 días de inactividad son eliminados de la facción automáticamente.

En cualquier caso, por estar utilizando un lenguaje inadecuado. Una expulsión de 24h es pertinente, sin necesidad de ningún aviso. Si hay avisos o se muestran pruebas a través de imágenes como este caso, será únicamente por cortesía del/la moderador/a.

No toleraré que se cuestione la autoridad de moderación en el servidor. Si vais a poner en duda el juicio de un moderador, mas vale un poco mas de esfuerzo y fundamentos. En caso contrario, solo empeoraréis vuestra imagen.

Cierro este ticket.
