### ISSUE TITLE
Mis Spawners no funcionan

### ISSUE THREAD

**Issue by Vegepapa** [MithrandirCraft/MithrandirCraft#195]
Buen día Mith, hace unos días te comente sobre el problema que tengo con mis dos spawners de araña de cueva.

De un tiempo a la fecha han dejado de producirme mobs, pensando que los chunks estuvieran saturados, ya cambie mis ovejas y demas animales, así como he tratado de limpiar la zona de mobs, pero continuo con el mismo problema, en mi faction cuenta con 3 spawners 2 de araña de cueva y 1 de zombies, este ultimo produce en menor cantidad que al principio, pero en definitiva los de araña dejaron de funcionar, como lo venian haciendo. en algunas ocasiones se llegan a producir solo de 1 a 3 arañas, pero al matarlas ya no se producen más.

Me podrías apoyar revisando mis spawners y si hay alguna  forma de solucionarlo?

La faction es Targaryan.

De antemano Gracias por tu atención y enorme apoyo.

**Comment by Ivanovic24** [comment]
Si tienes cofres con objetos por la zona tambien puede llegar a saturar los chunks... Si no es eso, o fallo de iluminacion debe ser un bug aun mas interno.

**Comment by Vegepapa** [comment]
Si eso pensé.. El detalle es que no he movido nada. Todos los cofres están en su mismo sitio. La iluminacion es la misma. Y aún así funcionaban sólo de un día a otro dejaron de darme mobs.

Lo único que había agregado son ovejas y vacas pero ya las cambie de chunk y ni así funcionan.

Que otra cosa podría ser???

**Comment by MithrandirCraft** [comment]
Gracias por abrir este ticket.

Para solucionar esto, va a hacer falta un mantenimiento, ya que la causa es incierta, y necesitaré retirar componentes para encontrar el problema.

Añade las coordenadas de esos spawners porfavor.

**Comment by Vegepapa** [comment]
A donde te puedo enviar la coordenadas??? 

Ya que si las dejo aquí todos las verán :(

**Comment by MithrandirCraft** [comment]
Ok, no importa :)

**Comment by Vegepapa** [comment]
Si las dejo aquí todos verán las coordenadas de mi FAC :(

**Comment by MithrandirCraft** [comment]
@Vegepapa No importa, conozco tu facción, puedo ir a ella.

**Comment by Vegepapa** [comment]
Ok gracias mith.. Si necesitas que mueva algo me dices y se hace inmediato

**Comment by Vegepapa** [comment]
Mith ya puedes cerrar este ticket.. Los spawners se han destruido.. Gracias por tu apoyo :) 

A seguir jugando.. Por cierto me gustaría ser Mod.. Donde veo los requisitos???

**Comment by MithrandirCraft** [comment]
www.mithrandircraft.es/normas
