### ISSUE TITLE
Propuesta de nuevo sistema de Raid

### ISSUE THREAD

**Issue by JessyelXD** [MithrandirCraft/MithrandirCraft#196]
Hola soy el player: JessyelxD.

Me gustaría proponer que se retirara el sistema de protección de cofres como en los servidores de raideo masivo.

Para que los jugadores tuvieran que preocuparse por las defensas y resultara mas importante las defensas. Crear un mundo mas masivo en el que la gente tenga que luchar mas. pienso que estaría bastante mas emocionante el juego en general. También la protección de cofres se puede hacer con diversos sistemas de Redtone. También pienso que la TNT esta muy cara en el pueblo (no soy el único) 1 esmeralda por 1 TNT (Sale mas caro que los diamantes xD) 

-----------
Comentario todo el que apoye una de las 2 propuestas (no vale solo mirar) xD
Saludos

**Comment by MithrandirCraft** [comment]
Pasa esto a este ticket porfavor: https://github.com/MithrandirCraft/MithrandirCraft/issues/186
