### ISSUE TITLE
[Posibles hacks] Jugadores tramposos (?

### ISSUE THREAD

**Issue by krazlas1** [MithrandirCraft/MithrandirCraft#197]
Buen día a todos, he venido a comentar un poco sobre algunos jugadores tramposos en el servidor, ya ellos sabrán quienes son.

Por aquí tengo un material gráfico bastante contundente, fue grabado por mí y a mi parecer tiene muchas cosas sospechosas que quisiera que las estudie detenidamente el equipo de Staff de Mithrandircraft. 

Sin mas que agregar, les dejo el link directo del vídeo que alcance a grabar.

https://www.youtube.com/watch?v=1XI9oKnD1E0&feature=youtu.be

Que tengan feliz tarde.

-krazlas

**Comment by Catadolfa** [comment]
Tienes una voz bonita, pero yo no vi hacks en tu video. Aunque oye, buen intento.

**Comment by KawaiiGNE** [comment]
No te preocupes, yo también tengo grabada esa parte, voy a subirla.

**Comment by KawaiiGNE** [comment]
Toma, pa tu body https://www.youtube.com/watch?v=6ha1nzDQF2o incluye mucho swag

**Comment by Ivanovic24** [comment]
Kawai, no me deja ver tu video

**Comment by KawaiiGNE** [comment]
Vuelvo a pasar links, 
Respuesta a primer video de kraz (justo el de este post)
https://www.youtube.com/watch?v=6ha1nzDQF2o

Respuesta a segundo video de kraz (el que paso en el servidor)
https://www.youtube.com/watch?v=7I9wyUzuUdw

**Comment by MithrandirCraft** [comment]
Hay alguna sección en concreto en todos estos vídeos que debamos observar con detención? Podéis comentarnos que indicios de uso de hacks se pueden apreciar?

**Comment by KawaiiGNE** [comment]
No se, kraz se puso pesado con decir que tenemos hacks así que he subido el vídeo, he notado que kraz tiene bastante lag al jugar y se que eso puede dificultar el hecho tanto de detectar hacks como puede hacer ver mas fácilmente que los tiene.

Únicamente los subí para que vea que por mi parte no percibo hacks ni los emito.

**Comment by MithrandirCraft** [comment]
Sin respuesta. Cerrando ticket.
