### ISSUE TITLE
Bug Al Reclamar Claims  De Otras Facciones.

### ISSUE THREAD

**Issue by Zirix** [MithrandirCraft/MithrandirCraft#198]
Bueno el dia de ayer un player encontró una facción, la cual tiene un solo jugador y 20 claims. 
El problema es que al querer reclamar los claims que no debería poder proteger, no se puede reclamar cerca de dicha faccion, debido aque el nuevos sistema no te deja reclamar a un chuck en radio 1 a otra facción.

Es posible que el sistema de claimeo haya cambiado ahora o podría llamarse un bug mas..?

1. Un 1 jugador = 10 de Pow + 20 terrenos. Balance: 0.5 protege 1 terreno.
2. Que impide el reclamo? El poder del jugador? O la nueva medida?

Aqui se muestra el status de la faccion:
![captura de pantalla 2016-02-14 13 55 33](https://cloud.githubusercontent.com/assets/16519448/13036101/301c131c-d324-11e5-9638-73ee85ed000e.png)

Saludos A Rafaelox :u

__Editado por Mithrandir. Ya que se trata de un tema que hablamos ayer.__

**Comment by Ivanovic24** [comment]
Igualmente se podria eliminar el claim de dicha faccion con /f unclaim o

**Comment by MithrandirCraft** [comment]
@Ivanovic24 Me parece que eso no ayuda xD aquí se esta intentando robar el terreno de otra facción.

@Zirix Creo que el tema aquí es, que mientras tenga el poder al máximo, no podrás robarle seguramente ningún terreno igualmente. Su poder debe bajar al menos una vez, y entonces perderá derecho sobre la cantidad de terrenos acorde con el balance en esta situación: 0.5 pow = 1 terreno protegible. Como solo es 1 jugador, al ser asesinado 1 vez, la perdida de poder será mucho mas sentida que con más miembros.

En cualquier caso, parece que la función que impide claimear en radio 1 podría estar interviniendo en el reclamo de terrenos ajenos.

**Comment by MithrandirCraft** [comment]
Solución provisional aplicada. No volverá a aplicarse el radio de distancia hasta que no haya arreglo para esta situación.

**Comment by rafaelox24** [comment]
Saludos xDDD
