### ISSUE TITLE
Cambiar mi contraseña a través de un dispositivo móvil. Es posible?

### ISSUE THREAD

**Issue by AndresGatoXD** [MithrandirCraft/MithrandirCraft#199]
Quisiera saber eso... un amigo sabe mi contraseña y le tengo bastante desconfianza (lose, desconfio de mis amigos e_e). Le he dicho que no se metiera a mi cuenta pero rara vez lo hace, por temor a que me haga mala reputación o que me pierda cosas, quiero cambiar mi contraseña de la cuenta "AndresGatoXD" a traves de un celular (si es que es posible). No tengo una PC o Laptop para meterme dentro del juego, en realidad si tengo una PC pero el juego no me es posible ejecutarlo.

**Comment by MithrandirCraft** [comment]
No es posible cambiar de contraseña sin acceder al juego y utilizar el comando /email

Recuerda que compartir cuentas va contra la normativa del servidor.
