### ISSUE TITLE
Ivanovic abusando.

### ISSUE THREAD

**Issue by BatmanNick** [MithrandirCraft/MithrandirCraft#20]
Buenas..Ivanovic tiene una cuenta en mi Faction que no se como se llama y cuando me ve conectado se conecta con esa cuenta y trae a su cuenta principal que seria viniendo ''Ivanovic''..Yo creo que es infrigir una regla dejar una cuenta desconectada en una Faction y cuando ves a alguien conectado te conectas con tu otra cuenta traes la cuenta principal y los matas.

**Comment by MithrandirCraft** [comment]
Tu facción "GorMexH" tiene 3 miembros: BatmanNick, FlorinDm y LooXuu
Intuyo que todos estos nombres son tuyos. Cuál de ellos entonces és Ivanovic?

**Comment by BatmanNick** [comment]
No..el no esta en mi faccion es decir en mi Clan si no en mi Faccion a dentro..en mi base.

**Comment by MithrandirCraft** [comment]
Dos cuestiones entonces:
- Si alguien está en tu facción desconectado tendrás que deshacerte de él. Si eres incapaz de hacerlo,  
  ya has perdido.
- Si sabes exactamente donde está, has probado encerrar, o colocar una trampa en su posición desconexión?
- Todos necesitamos dormir, que tal si te conectas en una hora en la que él no esté? xD

**Comment by BatmanNick** [comment]
Bueno gracias por todo.
