### ISSUE TITLE
Bugeado.

### ISSUE THREAD

**Issue by vegetagamer9** [MithrandirCraft/MithrandirCraft#200]

**Comment by vegetagamer9** [comment]
Hoy quede bugeado cuando intente petar a un tal Mineralex, Mithrandir si fueras tan amable teletransportame hacia el spawn 

Gracias por su atención

**Comment by vegetagamer9** [comment]
Espero la respuesta.

**Comment by MithrandirCraft** [comment]
Podrías indicarme exactamente como quedaste bugeado? En un portal hacia el nether quizá?

**Comment by vegetagamer9** [comment]
No uno me trolleo en una trampa y quede bug

**Comment by MithrandirCraft** [comment]
Gracias por ser tan especifico.

Si no me das mas detalles no puedo ayudarte. Tu ticket será cerrado si no proporcionas suficientes detalles en 1h

**Comment by vegetagamer9** [comment]
pues este creo que utilizo mi cuenta y me cogio una p4 espada cheta y me encerro en una trampa donde me estoy quemando en lava, y tiene tolvas para conseguir las cosas

**Comment by vegetagamer9** [comment]
porque yo desconecte en casa
y asi porque si apareci en su casa

**Comment by vegetagamer9** [comment]
Por favor solo llevame al spawn no le costara mucho

**Comment by vegetagamer9** [comment]
Mith me llevaste al spawn por favor avisa

**Comment by MithrandirCraft** [comment]
Si compartes tu cuenta es problema tuyo. Además, estas infligiendo una norma muy importante del servidor.

Tu solo te has metido en este lio, no se si te das cuenta de que enviandome estas solicitudes egoístas, solo me estas quitando tiempo de trabajar en el servidor.

**Comment by vegetagamer9** [comment]
y me vas a dejar ahi mith?
