### ISSUE TITLE
que programas o plugin son legales 

### ISSUE THREAD

**Issue by vladtriana** [MithrandirCraft/MithrandirCraft#201]
Hola  buenas tardes 
Ser Jugador del server 
puff cual son los programas  y o plugin q se pueden usar legal y tener excelente el modo de  jugar  yver ߘʰߘʰߘʊSaludos 
...

**Comment by JessyelXD** [comment]
mira este es el foro oficial donde pone la normativa 

http://mithrandircraft.es/foro/viewtopic.php?f=4&t=6464

**Comment by MithrandirCraft** [comment]
@JessyelXD 

Gracias por comentarselo :)

@vladtrina

Como ya te ha dicho, en ese enlace encontrarás la lista con los mods permitidos, y los que no lo están. Lee cuidadosamente!
