### ISSUE TITLE
Hacks en mithrandircraft son 2 :V los dos se ven claros :)

### ISSUE THREAD

**Issue by vegetagamer9** [MithrandirCraft/MithrandirCraft#202]
Aca los links de los hackieros
https://www.youtube.com/watch?v=s5-iw3GSWqA&feature
https://www.youtube.com/watch?v=XXH-hUfAiIA
Son dos hacks el segundo se ve claro
Un cesar volador :o

**Comment by MithrandirCraft** [comment]
Hola. 

Podrías comentarnos que podemos apreciar en el primer video que te transmita indicios de uso de hacks? Podrías ponerle nombre al tipo de hack que crees que utiliza, también? 
Ten en cuenta que hemos bloqueado ya bastantes hacks avanzados.

En el caso del segundo video, tiene toda la pinta de ser un bug visual. Si ves eso, reportalo de inmediato en vivo, y podré confirmartelo. Pregunta tambien a otros jugadores si ven lo mismo.
Parece que el jugador no se movía, por lo que yo descartaría que fuese nada serio.

**Comment by vegetagamer9** [comment]
Tienes spy viste lo que dijo uruguayo

**Comment by MithrandirCraft** [comment]
En fin... cierro ya el tema o me vas a contestar?

**Comment by vegetagamer9** [comment]
y en el primer video, aaa21 se le ven los hacks
creo que no usaba kill aura y su rango
usaba sus golpes para pegar al rededor suyo

**Comment by MithrandirCraft** [comment]
No, efectivamente no usaba killaura, porque sino seguramente hubiese recibido como mínimo un kick al instante.

"Usar golpes para pegar alrededor", parece una técnica bastante estandard, puedes concretar un poco mas? xD

**Comment by vegetagamer9** [comment]
hmm pero esque no se como explicarlo...
Seria como tener un programa para pegar a tu alrededor cunado tu clickeas... es decir no es de el todo kill aura porque yo vi en muchas pc que se le sube el rango al kill aura el rango de clikear
y le puedes poner con macros por ejemplo 10 clicks por seg

**Comment by vegetagamer9** [comment]
Mire este video minuto : 4:01 empieza su pvp con hacks que no usaba kill aura
https://www.youtube.com/watch?v=nkD5U7H_vEc

**Comment by MithrandirCraft** [comment]
No... lo siento pero soy incapaz de ver los efectos de tal hack en el primer video que proporcionas. Y aún que sea así, el usuario sería kickeado practicamente de inmediato al entrar en combate.

Voy a cerrar este ticket por falta de pruebas... porfavor, si vuelves a abrir un reporte de uso de hacks, procura especificar más. Sigue estas instrucciones: https://github.com/MithrandirCraft/MithrandirCraft
