### ISSUE TITLE
Registro de cuentas,

### ISSUE THREAD

**Issue by vegetagamer9** [MithrandirCraft/MithrandirCraft#203]
Hoy me acabo de dar cuenta que la cuenta de ``TheShaark´´ no es de el pertenece a otro usuario 
quiero decir que por favor intenten configurar eso y baneen a todos inclyendo a este todos los que se hayan registrado con una cuenta premiun sin ser suya 

Gracias por su atención =)

**Comment by vegetagamer9** [comment]
Eso es ilegal!...

**Comment by vladtriana** [comment]
Y quien es ``TheShaark´ como se actualmente  de q faccion es ?
😊

**Comment by vegetagamer9** [comment]
es de Azurita y se registro con una cuenta que no es suya es como si ahora yo me registro con la cuenta de elrubius  por ejemplo y me hago pasar por el que mi hermano es TheShaark porque el compro una cuenta así

**Comment by MithrandirCraft** [comment]
Buenas tardes.
Primeramente, agradecería que cuando vuelvas a abrir un ticket incluyas más detalles... tu nivel de minuciosidad a la hora de transmitirme tus ideales es muy mediocre... Y es bastante provable que la proxima vez que vea un ticket tuyo abierto con tan poco grado de explicación, lo cierre directamente.

En MithrandirCraft puedes registrar el nombre, y utilizar la skin que desees, debido a la naturaleza de offline-mode.

Te invito a que me menciones algún otro servidor donde tengan control de reserva de nombres premium (Si conoces alguno), eso me permitiría investigar que metodologías utilizan para obtener tal control.

Yo me temo que no creo posible realizar tal control sobre los nombres premium (Parece que sería la solución idonea.), y tampoco lo encuentro tan prioritario e importante.

**Comment by vegetagamer9** [comment]
Emm yo sólo juego en MithrandirCraft es muy bueno y en muchos servers obligan a la persona que se le robo la cuenta a crearse otro usuario y comprobar la dirección ip
Así le das ban hasta que su ip de la cuenta premiun sea el verdadero usuario
