### ISSUE TITLE
Reinicio después del fallo del servidor

### ISSUE THREAD

**Issue by Calvinator77** [MithrandirCraft/MithrandirCraft#204]
Bueno como muchos saben y estaban esperando al que servidor abriera , me incluyo. Me encontré con la sorpresa de que hoy se reinicio todo , pues todo lo que había construido que me mate haciendo durante horas no esta , incluyendo los baúles que había dejado mis cosas. Pero luego pregunte a mas gente del server para saber si no me habían petado simplemente. Entonces muchos dijeron que a todos les paso lo mismo. Realmente no se que paso , pero creo que tal vez haya un back up durante los logs o nose? Espero que no se devuelvan al menos las cosas... Porque le puse mucho empeño mith... saludos

**Comment by MithrandirCraft** [comment]
Como siempre, este tipo de errores afectan a los jugadores más recientes, ya que son tambien los que mas progresan en poco tiempo.

Sin embargo, no puedo hacer nada para ayudarte. No se lo que tenías, y como tu has dicho, hay mas jugadores afectados. Si compenso a 1, debo compensar a todos.

Preferiría invertir mi tiempo en solucionar este tipo de errores, y prevenir que se vuelvan a producir.

Por el momento, estoy trabajando en un nuevo sistema de backups que realize backups con mas frecuencia, para evitar que se produzcan rollbacks de tal longitud.

Agradecería tu comprension, y que tengas en cuenta que trabajo para solucionar estos problemas.
