### ISSUE TITLE
Bug de Marry 

### ISSUE THREAD

**Issue by vegetagamer9** [MithrandirCraft/MithrandirCraft#205]

**Comment by vegetagamer9** [comment]
Esta tarde a las 16:50 hora española todos provamos a divorciarnos hasta mith, el caso es que no se puede arreglen el bug

**Comment by MithrandirCraft** [comment]
Creo que ya es posible. Sigues teniendo este problema?

**Comment by vegetagamer9** [comment]
No, Gracias por la atención =)
