### ISSUE TITLE
¿Mucho tráfico en la sala 6?

### ISSUE THREAD

**Issue by krazlas1** [MithrandirCraft/MithrandirCraft#206]
Buenos días, hoy entre al servidor, como de costumbre fui a hechar un vistazo a las salas de PvP, como hago habitualmente, y me he encontrado con esto:

https://www.youtube.com/watch?v=paRkCV_CT18&feature=youtu.be

Mi sugerencia: poner mas accesos hacia la sala o directamente un /Warp que la comunique, sin necesidad de tener que pisar la placa.

Gracias por su atención

Feliz fin de semana 

-Atte. krazlas.

**Comment by MithrandirCraft** [comment]
Solucionado.
