### ISSUE TITLE
no se reproducen los huevos 

### ISSUE THREAD

**Issue by vladtriana** [MithrandirCraft/MithrandirCraft#208]
Hola 
Buenas  tardes 

Mys saludos  mith 

Eh notado  que los huevos de animales no se reproducen... solo llegan a reproducir los que estan en los biomas

Espero  su respuesta  y solucionar...

**Comment by MithrandirCraft** [comment]
No termino de entender esto.

Lo que si es cierto, es que la reproducción de animales está drasticamente nerfeada para evitar lag causado por entidades.

Echale un vistazo a este apartado: www.mithrandircraft.es/informacion

Si deseas añadir algo mas, hazlo, o cerraré este ticket en 24h

**Comment by vladtriana** [comment]
!!!!Gracias x la respuesta...
Atte mys saludos...
