### ISSUE TITLE
problemas  al adoptar un animal  con una cuenta 

### ISSUE THREAD

**Issue by vladtriana** [MithrandirCraft/MithrandirCraft#209]
Hola 
Buenas  tardes 

Mys saludos  mith 

Eh notado q en tal cuenta ******* no es posible  adoptar ocelote.... pa no perjudicar esa cuenta  es enviado via mail

Saludos  mith... espero  alguna sugerencia  o solución

**Comment by MithrandirCraft** [comment]
Ok, lo investigaré cuando tenga tiempo, junto a https://github.com/MithrandirCraft/MithrandirCraft/issues/210

**Comment by MithrandirCraft** [comment]
Es bastante provable que se solucionen ambos problemas tras la actualización del servidor a 1.9

**Comment by vladtriana** [comment]
Okk gracias x la respuesta.... estare al tanto  de cada problema pa reportarlo y mejor server 😊😊
