### ISSUE TITLE
Pido perdon.

### ISSUE THREAD

**Issue by BatmanNick** [MithrandirCraft/MithrandirCraft#21]
Hola Mithrandir..queria pedir perdon por lo que hice mejor dicho por lo que dije..siento lo ocurido pero asi soy yo cuando me cabreo..quisiera pedirte porfavor que me des unban a mi cuenta ''FlorinDm'' no se volvera a repetir porfavor.

**Comment by MithrandirCraft** [comment]
Ofreciendo disculpas en un sistema de tickets. Como se arregla eso?

Porfavor, lee las normas de uso del sistema de tickets:
https://github.com/MithrandirCraft/MithrandirCraft
