### ISSUE TITLE
problema con vendedor de cabeza

### ISSUE THREAD

**Issue by vladtriana** [MithrandirCraft/MithrandirCraft#211]
Hola  buenas  dias

Me comunico que  el aldeano marinero no intercambia esmeralda...

Talvez xq han colocado minimo stock 

Atte Saludos

**Comment by MithrandirCraft** [comment]
Hola, creo que ya funciona. Pero podría estar equivocado, echale un vistazo.

**Comment by MithrandirCraft** [comment]
Nope... me temo que no consigo que funcione de forma estable. Las cabezas estan demasiado bugeadas.

Intentaré reprogramar yo mismo todo el sistema de cabezas, pero va a llevar un tiempo. Hasta entonces, tendrás que vivir sin cabeza de guardian en la tienda de cabezas.
