### ISSUE TITLE
servidor denuevo a 1.8.8

### ISSUE THREAD

**Issue by Popek345** [MithrandirCraft/MithrandirCraft#212]
el servidor desde la actualizacion de la 1.9 se lagea mucho y muchos no tienen la actualizacion y entraran muy pocos al servidor

**Comment by vladtriana** [comment]
Hola  
Buenas tardes 
Te comunico 

si se lagea es problema de tu pc, el servidor seguira actualizando cada version...

Grabate esto...
 al server  no entraran pocos como indicas jaja
Con esta actualización mejora mucho mas q la versión q deseas 1.8.8 puff version antigua como tu pc
   
Mys saludos... y disfruta del increíble  server 1.9 MithrandirCraft

**Comment by MithrandirCraft** [comment]
Hola

Comprendo las quejas que se están produciendo. Muchos de los componentes del servidor, todavía no han tenido la oportunidad de ser actualizados, y es por ello que puede producirse algo de lag adicional y algunos errores, en los que estoy trabajando para solucionar.

Sin embargo, debo decir que personalmente, he estado jugando en el servidor con mi cuenta de testing, desde varias localizaciones distintas (Hardware y conexion distintas) y no he tenido ni un resquicio de lag.

Estaría bien que si tienes algún tipo de lag, lo grabes, o describas los síntomas al detalle. Me ayudaría mucho a focalizar la causa.

MithrandirCraft siempre mira hacia adelante, y procura actualizar cuanto antes a la última versión de Minecraft, procurando también la adecuada actualización de todos sus componentes. Realizar estas actualizaciones es imprescindible para un servidor tan complejo, ya que quedarse atrás en tecnología, puede significar fallos graves a la larga.

Algunos jugadores no habrán actualizado todavía a 1.9, o no se habrán dado cuenta de la nueva version, pero no hay ninguna excusa para no actualizar hoy en día, ahora que es mas fácil que nunca sleccionar la versión desde el propio cliente.

Espero que lo comprendas, y tengas en cuenta que sigo trabajando para mejorar el rendimiento.

**Comment by Catadolfa** [comment]
Comento aquí para no tener que abrir un ticket sobre lo mismo.
El problema es que mucha gente antes tenía paquetes de textura que reducian el lag y el optifine,sin embargo muchas de esas cosas que reducen el lag aun no están disponibles para la versión 1.9 y eso hace que la cantidad de lag se note mucho mas. Sin embargo, me parece que tambien hay una nueva actualización de Java que puede estar causando que los mapas tarden mucho en cargar, que es lo que a mi me ha estado pasado ultimamente. Sin embargo, la jugabilidad no cambia, el unico lag que tengo por parte del servidor es el lag que todos tenemos y siempre hemos tenido desde las versiones anteriores. Personalmente opino que la actualización se hizo demasiado rapido, y que se debia haber esperado que salgan el optifine y los paquetes de textura 1.9 ya que Mithrandircraft es un servidor que tiene lag ya de por si. Aunque tambien siento que es muy tarde para volver a la 1.8, imagino que eso solo traería mas errores y se tendría que volver a configurar el servidor para la 1.9.

**Comment by MithrandirCraft** [comment]
@Ennya Estoy deacuerdo con todo lo que has dicho. Y la razón por la que decidí actualizar de forma tan temprana, es que se que en un par de semanas no voy a tener tiempo para hacerlo hasta Verano. Es por ello que he rusheado varias cosas para no tener que actualizar alrededor de las pasquas, momento en el cual seguramente solo tenga tiempo para actualizaciones menores.

Poco a poco iré actualizando los componentes que faltan, y que pueden estar dando errores y lag ahora mismo.
