### ISSUE TITLE
Cambio de Vercion Fail

### ISSUE THREAD

**Issue by TheShaark** [MithrandirCraft/MithrandirCraft#213]
Desde que cambiaron la vercion ala 1.9 el server anda muy pero muy lag , definitivamente no puedo hacer nada , farmear , pvpear , minar etc , la verdad pienso que desde que cambiaron la vercion la an liado , yo creo que el server tendria que volver ala 1.8 y no lo digo yo , directamente lo viven diciendo en el chat , NADIE esta satisfecho con el cambio de vercion , la verdad fue una mala idea pero la respeto , muchas gracias por su tiempo , att:TheShaark

**Comment by MithrandirCraft** [comment]
https://github.com/MithrandirCraft/MithrandirCraft/issues/212
