### ISSUE TITLE
Maldita 1.9 Devuelvanme mis cosas

### ISSUE THREAD

**Issue by XxGamerPvP322xX** [MithrandirCraft/MithrandirCraft#214]
Estuve picando y de la nada me da lagg y se me sale el maincraft entro de nuevo y no tenia nada de cosas -.- se desaparecieron ahora q ago denme mis cosas

**Comment by MithrandirCraft** [comment]
https://github.com/MithrandirCraft/MithrandirCraft/issues/212

**Comment by MithrandirCraft** [comment]
No voy a hacer caso a este ticket, por falta de redacción pertinente.
