### ISSUE TITLE
Funcionamiento de los Spawner y comando /cast repair

### ISSUE THREAD

**Issue by xXandrescolXx** [MithrandirCraft/MithrandirCraft#215]
Buenos días

Mi ID en MithrandirCraft es xX_andrescol_Xx

el primer problema es que luego de la actualización a la versión 1.9 de minecraft el comando /cast repair para los VIP+ no funciona.

El segundo es que en mi FAC hay un spawner de esqueletos, al momento de farmear o coger XP, salen los esqueletos, caen y luego se desaparecen, lo mismo ocurre en otro spawner de Creepers. Este problema viene ocurriendo desde antes del backup de 24 horas.

**Comment by MithrandirCraft** [comment]
Hola, he probado el cast repair esta mañana con una cuenta vip+, y funciona perfectamente. Cuando reportes algo, asegurate de que no haya sido arreglado ya :)

Estoy al corriente del segundo problema, le echaré un vistazo cuando pueda.

Para cada problema, 1 ticket. Asi que si quieres, abre un ticket solo para el problema con los esqueletos. Y confirma que sea solo con ese tipo de spawners (Si puedes)

**Comment by xXandrescolXx** [comment]
Ok, acabe de entrar y si funciona el repair.

Voy a probar con otros spawners y luego abrire el otro ticket como dices.
Muchas gracias
