### ISSUE TITLE
Problemas con el ally.

### ISSUE THREAD

**Issue by uNFixe** [MithrandirCraft/MithrandirCraft#216]
Buenas. 
1-A la hora de intentar poner a una fac de ally no deja. Tira un error de (No relations matches "fac") aunque las dos facs manden el ally.
Solo sucede esto con el /f ally, el truce y neutral funcionan correctamente. 

2- Tampoco se puede ver las relaciones que tienen las otras facs, por ejemplo no puedo ver los ally, truce, y enemy de otras facs (No se si esto fue implementado de forma voluntaria por el admin).

**Comment by rafaelox24** [comment]
Si puedes toma algunas capturas, y compartelas. Saludos

**Comment by KawaiiGNE** [comment]
Creo que el problema esta presente en todo el servidor, varias facs mas compartimos el mismo problema

**Comment by Zirix** [comment]
Hola:

Te marca ese error porque los comandos son diferentes a los  que conocias antes ahora son diferente manera, podrias ver los con comando /f h son los comandos basicos he aqui una imagen de como es para hacer lo que antes mencionantes.
![captura de pantalla 2016-03-12 17 37 34](https://cloud.githubusercontent.com/assets/16519448/13726012/db4e0d3e-e879-11e5-8026-6ca9456db6f7.png)


Espero te sirva saludos.

**Comment by uNFixe** [comment]
Gracias por la respuesta. De esa manera si se puede dar ally (:
