### ISSUE TITLE
¿Bugs en sistema de tiendas?

### ISSUE THREAD

**Issue by krazlas1** [MithrandirCraft/MithrandirCraft#217]
Buen día, vengo a darme un paseíto por aquí para preguntar acerca de esto:

https://www.youtube.com/watch?v=CjgskgNwSGM&feature=youtu.be

Al poner el spawnegg de aldeano en la mano no salta la ventana tutorial en donde te explica como poner la tienda.

¿Esto es un bug?

Si es así solucionenlo por favor xD

Nos vemos, Feliz día.

**Comment by MithrandirCraft** [comment]
Confirma que esto ya está arreglado.

Tendrás que comprar el nuevo tipo de objeto de creación de tienda. (Un ticket)
Puedes comprarlo en el mismo sitio.
