### ISSUE TITLE
Recuperar cuenta sin correo asociado

### ISSUE THREAD

**Issue by Danylex** [MithrandirCraft/MithrandirCraft#218]
Aloha, el reciente incidente que ha ocasionado la creación de este ticket, no puede ser solucionado por mí. He olvidado la contraseña de mi cuenta, y por tanto me es imposible entrar al servidor.
Empecé a jugar hace varios años en MithrandirCraft, el nombre de mi cuenta es Danylex.
En el momento que dejé de conectarme al servidor, no existía la posibilidad de asociar un email a la cuenta, por tanto no hay ninguno asociado y no puedo cambiar la contraseña. 

https://gyazo.com/31490d804a4fdcd859eef01beb15e9fa

https://gyazo.com/10c000dd22372a1917b241eb0262c82f

**Comment by MithrandirCraft** [comment]
Solucionado. tienes respuesta en FB
