### ISSUE TITLE
Mis Cosas!!

### ISSUE THREAD

**Issue by TheShaark** [MithrandirCraft/MithrandirCraft#219]
Hola vengo a hacer este report porque el dia de hoy lunes 14/3 , desaparecieron mis cosas completamente , nose paso ni nada , solamente entre al server y no tenia nada yo estaba jugando anteriormente las tenia , me desconecte para ir a almorzar , me conecto y ya no estaban no tenia nada ni mi experiencia es como si hubiera muerto nose que paso le pregunto a un amigo si mori o algo y me dijo que no que me habia desconectado , y yo la verdad nose que paso , tambien hay gente en el server diciendo que sus cosas desaparecieron pero la verdad , yo quiero mis cosas denuevo (mi espada full y mi arco full) , muchas gracias por su tiempo. pd: TheShaark

**Comment by RuePlumet** [comment]
Boh, hasta me da miedo entrar al server con esto de las cosas desapareciendo e.e

**Comment by MithrandirCraft** [comment]
Esto debería solucionarse con futuras actualizaciones. La cosa es que hemos actualizado bastante temprano, y hay algunos componentes que podrían estar malfuncionando.

Comenta en este tema: https://github.com/MithrandirCraft/MithrandirCraft/issues/174 
Incluye imagenes de lo que perdiste, el nombre de tu personaje, y cuando empezó a producirse este problema en tu cuenta.

Incluye también que mundos frecuentas, cambias mucho entre mundos?
