### ISSUE TITLE
Farmex abusa de moderador y de spawnkill

### ISSUE THREAD

**Issue by rubenoskiHD** [MithrandirCraft/MithrandirCraft#22]
Bien, aquí expongo el problema: Todo empezo cuando le invitamos a nuestra faccion en la cual lo metimos en un agujero antes de sacarlo para ver si podiamos confiar en el y salio con enderpearls a matarnos y hacernos spawnkill, despues de un rato se fue y dijo que era divertido. Despues empezo a decir que me iba a banear a mi por pegar a larga distancia cuando estaba claro que era por el lag que el tenia en su momento y por decir el nombre de mi faccion me kickeaba. Ziri se niega a contestar preguntas que realizan los usuarios como si sabe en que consiste su trabajo. A ziri le explicamos brevemente la situacion y se puso de lado de farmex y empezo a kickearme por intentar explicarle los hechos mas detalladamente. Tengo pantallazo de el momento en que ziri por la pregunta y pasar de el le dice tonto al pobre chaval que no tenia culpa de nada. Aqui dejo el aporte

**Comment by rubenoskiHD** [comment]
Ahora me ha baneado zirix por decir que soni (jorgito), el perrito faldero de farmex, que me estaba faltando al respeto cuando me decía pesado por entablar una conversación con otro usuario del servidor. Esto yo lo veo una falta de moderación muy clara. Si no veo que hagan algo por este abuso inapropiado, voy a pensar que estos dos están donde están por algo llamado enchufe gracias por su tiempo.

**Comment by J0R91T0** [comment]
looooooooooool 
esto no es un sistema politico avanzado.... es un videjuego xDDD si piensas que estamos en alguna especie de sitema politico o algo parecido estas muy enfermo mi querido amigo... xDDDD

**Comment by rubenoskiHD** [comment]
Eso no tiene nada que ver con el tema querido amigo, yo solo comunico que hay unas normas en este servidor que se están saltando tus amiguetes los moderadores. Como por ejemplo esta la de no faltar al respeto y usted perdona que le diga me lo estaba faltando a mi

**Comment by J0R91T0** [comment]
TU SOLO QUIERES SALSEO
#NoMasSalseo

**Comment by rubenoskiHD** [comment]
Sinceramente no se lo que esperas que te diga a ese spam que introduces en un reporte a algo que tendrían que mirarse lo antes de decidir quien debería formar parte del equipo staff o como lo quieras llamar.

**Comment by J0R91T0** [comment]
te quedas hablando solo :* paso de formar parte de este asunto :3

**Comment by rubenoskiHD** [comment]
Así me gusta, que no te metas en conversaciones privadas macho que ya van tres con esta...

**Comment by J0R91T0** [comment]
entra al srvr, que ya puedes hablar con mas moderadores :D!

**Comment by rubenoskiHD** [comment]
Sabes que pasa? que viendo como tratan estos dos moderadores a los usuarios (no con sus amigotes como tu) y tu diciéndome que entre al servidor para hablar con mas de ellos, me da un poquito de miedo mezclado con repelús... espero que lo entiendas cariño.

**Comment by Nepo23** [comment]
Primero que nada creo que tu lo llevaste a tu fac para matarlo y no lo niegues entonses, porque no devio matarlos? no vengas con confiar es como desir te mato para ver si confio en ti, creo que esta en todo su derecho.
Segundo el mod no implica que no sea un jugador como todos asi que el puede matarte, destruir tu fac, porque es un jugador mas. Ultima cosa tu lo invitaste no llores porque te maten.

**Comment by MithrandirCraft** [comment]
Hola. Me preocupa bastante lo que dices @rubenoskiHD 

El equilibrio entre jugadores normales y moderadores es algo importante, y el abuso de poder por parte de un moderador es motivo para la retirada de su título.

En cualquier caso, para reportar hechos de abuso por parte de un moderador, necesito que proporciones más pruebas. Si no las tienes ahora, puedes intentar conseguirlas durante el futuro transcurso de tu juego. Lo mínimo que puedes proporcionar son imagenes, hora de los hechos, e información mucho más detallada, pero lo mejor que puedes hacer para demostrar la actitud incorrecta de un moderador es grabarlo.
Sin todo este material no puedo tomar acción, pero te garantizo que lo consultaré con Zirix.

Veo que te estás tomando con calma este asunto, pero te pediría que te lo tomes con más calma todavía, las cosas no se resuelven con insultos y comentarios desagradables.

**Comment by rubenoskiHD** [comment]
Gracias por responder mithrandir, yo lo llevo con mucha calma esto, ya que no me importa ser baneado de un servidor al que acabo de entrar solo porque a un moderador le de por decir que yo tengo hacks cuando obviamente era lag. Solo queria informar de la clase de moderadores en este caso dos y no me he querido encontrar con mas, que tienes en el servidor y de como llegan a manejar a sus usuarios. En cuanto a nepo23 tu mismo lo has dicho, son usuarios como nosotros al fin y al cabo por lo tanto se deben ceñir a las normas, y una de ellas es no hacer spawn kill que porcierto eso fue lo que hizo, no hables sin saber o almenos lee todo el reporte para poder comentar... Gracias ^^

**Comment by MithrandirCraft** [comment]
El kill spam EXAGERADO es penalizable en caso de que se esté utilizando con la finalidad de aumentar posición en el ranking, o esté spameando demasiado el chat.

Por ello ya existe una autoexpulsión automatica que detiene el abuso antes de que ocurra.

En el kill spam intervienen tanto el asesino como el asesinado, si vuelves a tu facción cada vez que te asesinan, tu también eres parte del problema.

Si el spamer es expulsado, dispones de 60 segundos para moverte, y además dispones de una protección cada vez que respawneas tras ser asesinado.

**Comment by MithrandirCraft** [comment]
Lo que puedes denunciar con este tema no és el kill spam, sino un abuso de poder por parte de un moderador.
Si consideras que un moderador ha abusado de sus funciones de moderación en beneficio propio durante el juego, proporcioname pruebas.

No es la primera vez que recibo reportes dudosos en situaciones de greefeng perfectamente normales por parte de moderadores. Si no hay pruebas, no hay acciones.

**Comment by AGGuille** [comment]
Aqui se amenazo a Rubén con banearle si no demostraba por que atacaba de tan lejos (cosa que pudo ser del lag), luego Soni, me acuso a mi y a Rubén y a mi de ser la misma persona, tachándonos de multicuentas (cosa a la que le conteste que mirase nuestras ips, a ver si eran las mismas, pero aun asi, es un ataque bastante gratuito). No creo que un mod (Farmex) deba de realizar amenazas tan a la ligera ni permitir que se difame por que si en el chat, (en una ocasión me pregunto si yo era tonto, cabe destacar que yo argumente todos los puntos durante la conversación tras amenazar a Rubén con banearlo) además de que a ambos mods en ese momento se les pregunté si sabían en que consistía su trabajo y uno me dijo "no te voy a contestar", ¿Qué clase de mods tiene el servidor que rehúsan de contestar una pregunta tan simple como decir en que consiste su trabajo?¿Acaso ellos saben en que consiste ser mod?.
Hay un problema grave en el server, y es que los mods no están formados correctamente, por no mencionar el "trafico de influencias" y como Soni defendía de forma incondicional a los mods para que no contestaran.
El chat debería tener un registro, no apliques la misma política de ellos de "o me das pruebas o nada", si tu eres el dueño (o lo que sea, por que supongo que seras un alto cargo dentro del servidor, por encima de los mods) deberías moverte, pues son tus "empleados" por llamarlo de alguna forma, quienes están realizando el abuso de su poder.

**Comment by rubenoskiHD** [comment]
Perdona que te diga mithrandir, spawn kill significa matar en el spawn y el estaba esperándonos al lado del spawn para matarnos, abuso? bueno, yo 20 muertes si lo veo abuso, ya que tu creas que 20 muertes no es abusar no es mi problema. Eso de que no pueda volver porque esta haciendo spawnkill me parece un poco raro, si esta prohibido el abuso de spawnkill supongo que debería poder volver sobretodo porque lo único que pierdo es el terreno y según tu ya tengo que empezar de nuevo a si que no pierdo nada.

**Comment by Nepo23** [comment]
Esto no es un foro aca es para informar abussos y solo veo muchos mensajes sin definir cual es el abuso. Lo del spawn que te informaste mal que se llama warp factions en ese lugar se puede utilisar mas warp como el norte sur este oeste porloque si sales y te matan no spawm kill es tu problema por no informarte sobre los comandos. Otra cosa mas porfavor informate de los comandos si lees correctamente sabras que sethome esta para los vip+ algo que puedes comprar para apoyar al servidor.

**Comment by rubenoskiHD** [comment]
Pues mire usted nepo, creo que el que no se informa bien eres tu. Si te has fijado bien, el spawn es donde aparecen las personas, si te informas por otros lados y no comentas con el **** podrías averiguar que spawn kill se refiere a matar en el spawn alias home de la facción. No estamos mandando mensajes sin definir cual es el abuso, estamos mandando mensajes para ayudar a este reporte a ser revisado y reflexionado pero siempre hay un payasete como en este caso tu que se mete en medio del reporte para intentar llamar la atención. No es por joder pero esto no te incumbe para nada así que ¿porque no dejas hablar a los mayores y sales un poco a que te de el aire?.

**Comment by MithrandirCraft** [comment]
@rubenoskiHD Abre otro ticket si vas a mencionar un tema distinto (limitador de minería)

En cuanto al tema que nos concierne, repito lo mismo. Si no hay pruebas, no puedo tomar acciones, pero hablaré con Farmex para que me explique su versión de a que se debe este follón.

Comprendo que ver a un moderador destruir tu facción puede ser impactante, y no és la primera vez que se producen "quejas" al respeto, derivadas de asuntos similares.
Un moderador debe saber distinguir el juego de sus obligaciones, y no mezclar ambas. Pero aquí la cuestión a determinar es si se trata de un simple greef completamente legal por parte de un moderador/jugador, o si realmente hubo algo más, y se abusó de poder.

**Comment by AGGuille** [comment]
¿Acaso no es un abuso de poder decir "o me explicas como atacaste de tan lejos o te tendré que banear"?¿En este servidor no hay medios para detectar quien tiene hacks o no?¿Tampoco hay registro del chat como en muchos otros? Así podrías ver la conversación (además de las veces que nos mato, ya que si no me equivoco también salen reflejadas en el chat) y no preguntar a Farmex y a su entorno, que te dirán, obviamente, que todo eso es erróneo.

**Comment by Nepo23** [comment]
En el spawn no se pueden matar esta protegido la unica manera para que no mueras esque estes en tu home de faccion o que estes en warp factions. Y si me incumbe porque lo que haces es manchar un el buen nombre de un moderador sin pruebas y solo por  matarte cuando el solo se defendia.

**Comment by MithrandirCraft** [comment]
He hablado sobre este tema con Zirix, me ha explicado lo mismo.

Llego a la conclusión de que analizando todos estos datos no veo nada grave.

Si puedes proporcionar alguna prueba de mala práctica de moderación, hazlo mediante los metodos comentados previamente, y vuelve a abrir este ticket.

---------------------------------------------------------------------------------------------------------------------
Por otra parte: @rubenoskiHD @AGGuille 

Si sois te la misma facción, procurad vigilaros mutuamente. El uso de determinadas modificaciones (hacks) no está permitido en mithrandircraft, y por el hecho de que habéis hecho saltar el limitador de minería, más los reportes de Zirix acerca de posibles hacks de combate, os ganais fama de estar haciendo trampas.

Como os lo estabais preguntando, ya os lo confirmo. El servidor analiza los comportamientos extraños para detectar a tramposos, por lo que procurad aplicaros las reglas vosotros también. Os estaré vigilando de cerca.

**Comment by AGGuille** [comment]
Gracioso es ver como ahora los "malos" somos nosotros, dime como no hacemos saltar el limitador de minería si encontramos una veta de 6 de diamante y al picar 2 ya no nos deja más (nos pone un contador de 3-5 minutos) ¿o es que acaso es a los únicos que les pasa?, parece que no conoces como va tu propio servidor.
Investiga a tus mods, no a los usuarios, que para parar hacks ya hay bastantes programas para añadir al servidor (estaría bien que hicieras las cosas como debe ser), pero para parar a 3 coleguitas que hacen una coartada juntos ¿qué tienes?.
Preguntale a Farmex por qué me ataco sin siquiera tocarlo, cuando le envió tp a Rubén y yo solo estaba por allí, y como es que aguantó que 3 personas (con dos espadas de hierro y una de diamante) le atacaran sin parar y sobrevivió, a lo mejor debes "investigar" por hacks o por mal uso de los comandos a tus mods ¿o sois coleguitas también?¿Cómo sabe Zirix si tenemos o no hacks de combate si contra el no "luchamos" sino contra Farmex? Creo que el reporte debería de hacerlo Farmex no él, ya que Farmex fue el que acuso de "hack".

**Comment by MithrandirCraft** [comment]
Puedes verlo como quieras, este tema esta cerrado.
Si tienes algo más que reportar abre otro ticket, o reabre este si vas a proporcionar alguna prueba convincente.

**Comment by AGGuille** [comment]
http://gyazo.com/cc1034d5a4cba07694ee9bf0ae085052
Ahí tienes a Ziri insultándome.

**Comment by rubenoskiHD** [comment]
Jaja eso si que me ha causado gracia mithrandir ^^ acusando de hacks a alguien cuando lo único que hace es lo típico en minecraft, agujero de 2x1 en la capa 10 y a minar. Vamos, lo normal es encontrar diamante si sabes jugar y como bien te dije solo encontré una mena. Bien gente con esto hemos aprendido que la corrupción también existe en este pequeño servidor y como podemos comprobar para ser del equipo de staff necesitan o un buen enchufe, o una buena mamadita al señor mithrandircraft... Y yo que pensaba que me ibas a caer bien y todo señor mithrandir pero veo que usted es el mas corrupto de todos ^^ aquí te dejo en tu servidor de mierda con tus amiguitos y/o amiguitas (ya me entiendes Ö --:)

**Comment by MithrandirCraft** [comment]
@AGGuille 

Tienes un buen punto con esta prueba visual, parece que Zirix ha perdido un poco el control en esta situación. Los insultos no eran necesarios.

Aún así no veo demasiado grave la situación, no se ha producido un abuso de poder en ningún momento (Lo mas cercano, la amenaza de expulsión. Ciertamente también la veo innecesaria, pero no se ha producido ninguna expulsión inadecuada. En ocasiones, un moderador puede hacer preguntas interrogativas, pero no veo necesaria acompañar estas preguntas con amenazas). 
No es la primera vez que se produce algo así pero estoy bastante seguro de que a partir de esta ocasion, Zirix intentará controlarse en el futuro tras ver este asunto. 
Si te parece bien, he hablado con él, y lo volveré a hacer de nuevo para asegurar que no se produzcan cosas asi de nuevo.

Si deseas proporcionar alguna otra prueba que haga replantear mi decisión de solucionarlo con una simple charla con Zirix, me gustaría verla.

-----------------------------------------------------------------------------------------------------------------------------
@rubenoskiHD 

No acuso a nadie de nada, és una advertencia, una advertencia nunca está de menos, y la recibes desde el momento en que accedes al servidor.

Tras ver tu desagradable mensaje, queda claro que estoy hablando con un impresentable maleducado, no mereces que respondiendo a tus mensajes. 
Con este último comentario te has ganado una expulsión de este sistema de solución de problemas.

**Comment by MithrandirCraft** [comment]
Los temas relacionados con @rubenoskiHD han sido eliminados debido a su comportamiento inadecuado. Él ha abierto el tema, pero si @AGGuille desea continuarlo mantendré este ticket abierto.

**Comment by MithrandirCraft** [comment]
He revisado los logs en base a ese mensaje. Si hay algún comportamiento inadecuado por parte de Moderación, debe revisarse a fondo, es un tema importante:

He encontrado algo que me ha llamado la atención en el chat, sin mirar el contexto, y analizando puramente el chat @AGGuille Hizo varias preguntas impertinentes a Zirix, como la siguiente:

"<*Los****** AGGuille> Una pregunta a los dos mods, ¿sabeis en que consiste vuestro trabajo dentro del server?"

Estas preguntas fueron evidentemente ignoradas por Zirix, es la mejor acción que pudo tomar.
Los moderadores están plenamente instruidos para realizar sus funciones, no es asunto de nadie meter las narices en su trabajo. Tampoco es la primera vez que veo críticas y questionamientos hacia Moderación, y por experiencia se que se trata de comentarios alimentados por la envidia, o el odio derivado de asuntos de juego.

Esta es mi opinión @AGGuille . Este sistema de tickets lo he establecido para ayudar a los jugadores, pero no tengo porque analizar tanto esta disputa.
Creo que lo mejor que podemos hacer en esta situación es dejar el tema de lado, jugar sin agresividad verbal, y si realmente se produce algún hecho de abuso por parte de Moderación, se proporcionen pruebas.

-----------------------------------------------------------------------------------------
Comprendo que los jugadores sean exigentes con la calidad, y ausencia de corrupción en el servidor. La corrupción y las normas son precisamente un tema que me parece muy importante, por lo que:

Ya que os lo estáis preguntando mucho, y parecéis muy interesados en la normativa del servidor, y las obligaciones del equipo de Moderación, voy a reformar las normas para aclarar y actualizar más puntos desconocidos para los jugadores, como es el caso de en que consiste el trabajo de un Moderador en MithrandirCraft.

**Comment by AGGuille** [comment]
La pregunta no era impertinente, la pregunta la realicé tras ver como se me ignoraba cuando preguntaba una y otra vez si no era abuso de autoridad amenazar con una baneo por que sí (mientras que a Rubén si le contestaban). 
Mith, deberías haber tomado la postura que has tomado en el último comentario desde un principio, analizando el registro de chat y ahorrarnos tiempo a todos. Como tú mismo dijiste en un comentario anterior ya tenemos fama de "tramposos" cuando no lo somos. Deberías tomar una postura mas autoritaria frente a problemas como este, en los que los mods están involucrados si o si, ya que como deberías saber, muchas veces una charla no basta.
Otra cosa bastante grave (al menos a mi me lo parece) es ver como Soni contestaba por ellos, tratando de que ellos no se mancharan las manos o que dijeran algo fuera de lugar, mis preguntas y argumentos iban dirigidas hacia los moderadores, no hacia un usuario normal (independientemente del rango que tenga, yo quiero hablar con el mods, pues el problema los concierne a ellos directamente), quizás deberías "hablar" también sobre eso con ellos, pues lo único que hacia era intentar restarle importancia al asunto, cuando ya deberías saber que un problema en el que un mod este implicado es bastante grave.
Dudo que volvamos a jugar en este server, nos vamos con una opinión bastante negativa de los mods, aunque no del servidor, ya que, en mi opinión, me parece muy bueno, hubiera estado bien que la "voz" de la razón hubiese estado presente desde un principio para solucionarlo adecuadamente.
PD: La mejor opción que pudieron haber tomado los dos mods no era ignorarnos, sino solucionar el problema adecuadamente, pues una disculpa por parte de Farmex, admitiendo que su amenaza de baneo fue exagerada y sus acusaciones innecesarias e injustas, hubiese bastado para evitar todo esto.

**Comment by MithrandirCraft** [comment]
A sus ordenes.
