### ISSUE TITLE
Inventarios aleatorios en cambios de mundo Survival - Factions

### ISSUE THREAD

**Issue by KawaiiGNE** [MithrandirCraft/MithrandirCraft#220]
Hola, hoy mismo se han perdido algunas cosas debido a este error, voy a subir un video donde se muestra el error que hay.

El caso es que los inventarios desaparecen de un jugador y aparecen en otro o si no es totalmente aleatorio, convendría alertar a los jugadores, también se puede perder vida o nivel

https://www.youtube.com/watch?v=sfqwLtHPbMs

La calidad disponible para el vídeo aumentará en función del tiempo que pase

**Comment by MithrandirCraft** [comment]
Confirma que esto esta arreglado.

**Comment by Vegepapa** [comment]
Si ya quedó el bug

**Comment by MithrandirCraft** [comment]
@Vegepapa que?

bueno... intuyo que esto ya esta solucionado. Cierro este ticket.
