### ISSUE TITLE
Reporte a un jugador ofensivo

### ISSUE THREAD

**Issue by SimplyAcke** [MithrandirCraft/MithrandirCraft#221]
Mi nick en el juego _AckeHD_
Reporto al jugador llamado _Gambacha_
Fecha _16/03/16_ , hora semi-exacta _17:30_
Sección por la cual reporto a este jugador _Comportamientos contrarios a la normativa del servidor_

Buenas, soy Acke, en el día de hoy (16/03) he podido observar el comportamiento negativo de el jugador _Gambacha_ el cuál ha estado faltando el respeto hacia mi persona y hacia otros jugadores incluido el propio administrador, todo esto empezó porque él quiso hacer una pelea _1vs1_ la cuál varios ganamos. Este jugador en cuestión empezó a hacer comentarios ofensivos, admito que le contesté de una manera un poco inmadura pero no llega a ser tan ofensiva, quiero añadir esto porque quiero que quede todo bien explicado.

E aquí las 2 capturas de pantalla que he podido hacer durante estos acontecimientos:

(están actualmente en _Gyazo_ un programa que permite hacer capturas de pantalla y tenerlas **online**)

[https://gyazo.com/aadf89bf27f566b9233bc655244a41b7](url)
[https://gyazo.com/7324e9681c8b44273f51f2950af16876](url)

Me gustaría que este jugador quede por lo menos advertido de esto, por su falta de respeto hacia otros jugadores y hacia el propio servidor, gracias y buenas tardes.

~Acke.

**Comment by SimplyAcke** [comment]
Me gustaría añadir que después de agradecer a _Ninten_ un moderador por ayudarme a hacer el reporte, el jugador reportado añadió lo siguiente:

[https://gyazo.com/fb71895794b7c3d11e04e40ddebd1317](url)

Lo cual demuestra que no tiene respeto por el **staff** del servidor.

**Comment by MithrandirCraft** [comment]
Hola. Voy a darte una respuesta en 2 secciones:

- No suelen importarme las faltas de respeto dirijidas hacia mi, porque se que la persona que las emite no debe ser demasiado inteligente, y no valora en absoluto mi trabajo. Tengo bastante paciencia, y no suelo perder el tiempo ofendiendome por lo que escribe un desconocido.

- Sin embargo, una falta de respeto hacia cualquier otro miembro de la comunidad, debe ser advertida e incluso castigada protocolarmente.

- Le echaré un ojo al jugador, ya le he advertido una vez, si sigue con este plan tomaré medidas.

**Comment by SimplyAcke** [comment]
Gracias mith por tu comprensión y mi objetivo no era que lo baneases ni que te enfadases por ello, sólo quería informarte de su actividad un saludo :)
