### ISSUE TITLE
Reporte a un jugador ofensivo #2

### ISSUE THREAD

**Issue by SimplyAcke** [MithrandirCraft/MithrandirCraft#222]
Mi nombre en MithrandirCraft _AckeHD_
Reporto al jugador _Pepe_Slim_
Fecha _16/03/16_ hora semi-exacta _17:50_
El jugador ha incumplido la norma siguiente _Comportamientos contrarios a la normativa del servidor_

Hola de nuevo, vengo a reportar esto puesto que mientras estaba agradeciendo al moderador _Ninten_ y a los demás jugadores que me habían ayudado a realizar el reporte, este otro jugador decidió hacer un comentario no relevante. La captura lo dice todo;

[https://gyazo.com/8e806d4d60419ecf3428212aaacd7fcb](url)

**Comment by MithrandirCraft** [comment]
Tus capturas no llevan a ninguna parte :(

Reabre este ticket si deseas añadir un enlace que funcione.

Por cierto, YO soy Ninten.

**Comment by SimplyAcke** [comment]
Como reabro el ticket? Sé como hacer que vayan


2016-03-16 21:11 GMT+01:00 Mithrandir <notifications@github.com>:

**Comment by SimplyAcke** [comment]
https://gyazo.com/8e806d4d60419ecf3428212aaacd7fcb (copia y pega el link en la barra de búsqueda, si no e aquí la imagen) 

![](https://i.gyazo.com/8e806d4d60419ecf3428212aaacd7fcb.png)
