### ISSUE TITLE
Caso reabierto de Reporte a un jugador #2

### ISSUE THREAD

**Issue by SimplyAcke** [MithrandirCraft/MithrandirCraft#223]
Mi nombre en MithrandirCraft _AckeHD_
Reporto al jugador _Pepe_Slim_
Fecha _16/03/16_ hora semi-exacta _17:50_
El jugador ha incumplido la norma siguiente _Comportamientos contrarios a la normativa del servidor_

Hola de nuevo, vengo a reportar esto puesto que mientras estaba agradeciendo al moderador Ninten y a los demás jugadores que me habían ayudado a realizar el reporte enviandome links etc... Este otro jugador decidió hacer un comentario no relevante. La captura lo dice todo;

![](https://i.gyazo.com/8e806d4d60419ecf3428212aaacd7fcb.png)

**Comment by SimplyAcke** [comment]
La captura debería funcionar ahora, o eso espero.

**Comment by MithrandirCraft** [comment]
Solo es un insulto. Que debería hacer sobre eso?

No puedo volver al pasado y advertirle. Parece ser que en ese momento no había ningún moderador, asi que que le haremos.

Las advertencias en estas situaciones tienden a funcionar mejor en el momento justo.
