### ISSUE TITLE
Bug al atacar

### ISSUE THREAD

**Issue by SimplyAcke** [MithrandirCraft/MithrandirCraft#224]
Buenas, soy el jugador _AckeHD_ recientemente, desde la actualización del servidor a la 1.9 hay un bug que hace que al atacar una unidad ya sea **jugador** o **mob** hace aparecer un calamar sobre el jugador que ha atacado (breve explicación si yo ataco a un esqueleto me aparece un calamar invisible encima dando vueltas) creo que esto es debido a algún plugin que facilitaba la detección del jugador cuando ataca, no estoy seguro de ello pero desde que añadieron sonidos a los calamares se ven las partículas de al rededor y se escuchan sonidos al atacar además por la propia colisión de unidades añadida en la 1.9 hace que al pegar puedas ser impulsado un poco hacia atrás por el calamar lo cual puede empeorar el estilo de juego. El bug persiste actualmente día 16/03/16 a las 23:56.

Comentarios adicionales (no tienen que ver con el bug en cuestión): Me hizo gracia encontrar este bug puesto que estoy seguro que es debido a algún pluggin de detección de jugadores que atacan y es divertido como he logrado en ocasiones atacar al calamar sin lograr matarlo y ver las partículas de agudeza en el calamar invisible.

**Comment by MithrandirCraft** [comment]
Muy interesante. El sistema no ha sido actualizado para 1.9, es normal que ocurran estas cosas que no ocurrirían antes en 1.9 :P

Gracias por comentarmelo, lo tendré en cuenta.

**Comment by MithrandirCraft** [comment]
Porfavor, confirmame si todavía hay problemas hoy tras las 18:00h
