### ISSUE TITLE
Mods ilegales.

### ISSUE THREAD

**Issue by vegetagamer9** [MithrandirCraft/MithrandirCraft#225]
Hoy 15:11 horario español HuMuFer  confesó un uso de mod ilegal. aqui les dejo al prueba 
![2016-03-19_15 09 17](https://cloud.githubusercontent.com/assets/12957778/13899070/e9002adc-ede4-11e5-9f90-e3abe2c9632c.png)

**Comment by vegetagamer9** [comment]
Segun el era " legal " no estoy muy seguro.

**Comment by MithrandirCraft** [comment]
Seguramente Tracers o Xrays + Patearse el mapa. No existe ningún mod que permita encontrar coordenadas lejanas, de chunks que no están ni cargadas.

Admitir uso de hacks no es suficiente en la gran mayoría de casos, debe haber pruebas.
