### ISSUE TITLE
Los hornos se paran.

### ISSUE THREAD

**Issue by SimplyAcke** [MithrandirCraft/MithrandirCraft#226]
Buenas, soy _Acke_ conocido en MithrandirCraft como _AckeHD_, varios jugadores han reportado este bug en concreto desde hace ya bastante tiempo (Aprox. poco mas de 2 semanas) Este bug se trata de que los _hornos_ y los _brewing stands_ se **paran** al descargar el chunk y **al regresar no se reactivan**.
En el vídeo siguiente lo muestro con un _Brewing Stand_ (Estante de pociones), pero el bug sigue existiendo en los hornos: (Por favor si has encontrado este mismo bug en otros bloques que no sean _Hornos_ o _Estantes de Pociones_ por favor coméntalo, estarás ayudando al arreglo de este.)

https://youtu.be/BVshzq5FMN0

**Comment by SimplyAcke** [comment]
Debo añadir algo importante, las mesas de encantamiento actúan de manera similar. Cuando descargas el chunk, la mesa se queda en un estado llamémoslo _estancado_. Es decir puedes encantar igual el problema es que los encantamientos que tuviese la última vez antes de descargar el chunk, serán los mismos _para siempre_ **a menos que** quites la mesa y la vuelvas a poner.
Es grave puesto que si toca un encantamiento bueno te chetas en 15 minutos a p4 o a espadas.

**Comment by MithrandirCraft** [comment]
Esto sigue ocurriendo?

**Comment by MithrandirCraft** [comment]
Tengo entendido que esto ya esta solucionado.
