### ISSUE TITLE
Reformas con los kits? Haznos llegar aquí tus sugerencias/opiniones.

### ISSUE THREAD

**Issue by JessyelXD** [MithrandirCraft/MithrandirCraft#227]
Mi propuesta es que el kit basura contenga comida y una armadura completa de cuero también que se alargue el tiempo de petición del kit  cada 10 minutos

**Comment by MithrandirCraft** [comment]
Hola JessyelXD.

Supongo que haces esta solicitud como medida de proporción de ayuda adicional básica en uno o varios mundos en concreto?

Apreciaría que argumentases más tus sugerencias. No voy a aplicar una sugerencia que solo invierte 2 lineas de explicación.

Ten en cuenta que además del kit basura (Que acabo de renombrar como: basico), hay un NPC en /warp factions que intercambia drops de jefe por armaduras de hierro basicas.

Ahora mismo el sistema de jefes esta desactivado, pero no tardará mucho en volver a estar disponible. Los drops que se intercambian en esa tienda del novato son muy fáciles de obtener, y permiten a alguien ganarse un par de armaduras básicas con facilidad, para aplicarlas a Factions.

En cuanto a Survival, considero que parte de la gracia de ese mundo es el hecho de que comienzas con prácticamente nada (Y ya es demasiado que empiezes con un kit.)

Tambien debo indicar, que los jugadores que disponen de rangos vip o vip+, disponen de kits con mayor cooldown, y con herramientas, armas y armaduras de mayor utilidad, asi que considera obtener uno de esos rangos si quieres colaborar con el mantenimiento del servidor, y obtener así estos kits útiles.

**Comment by JessyelXD** [comment]
Yo ya dije poner el kit basura con una armadura de cuerro completa, o hacer como en otros servidores en lugar de que se llame (kit basura) poner (kit rata) resulta divertido (o un kit avanzado diario como lo de votar que solo se puede votar cada 24h)

**Comment by MithrandirCraft** [comment]
Cerrando tema por inactividad e innecesidad de cambio.
