### ISSUE TITLE
Servidor caido?

### ISSUE THREAD

**Issue by JessyelXD** [MithrandirCraft/MithrandirCraft#228]
El servidor no funciona Día: 2016/03/27 Hora: 13:00 Que ocurre y por que no se a notificado ?

E notado que la mayoría de servidores españoles no funciona no se por que

**Comment by vegetagamer9** [comment]
JessyelxD el servidor ya funciona, puedes entrar hubo problemas de 20h con el RollBack ( te pegaban y no retrocedías )

**Comment by MithrandirCraft** [comment]
https://github.com/MithrandirCraft/MithrandirCraft/issues/231
