### ISSUE TITLE
Problemas al entrar al servidor.

### ISSUE THREAD

**Issue by vegetagamer9** [MithrandirCraft/MithrandirCraft#229]
Esta tarde, horario español 15:50 MythicalMidget no pudo entrar con su cuenta. Solo pido que la baneen haciendo que se registre de nuevo sin perder cosas. Como hicieron con pekenomaton 

Gracias por su atencion =)

**Comment by vegetagamer9** [comment]
Lo mismo pasa con Johanna3
MeepMurp

**Comment by vegetagamer9** [comment]
esas tres personas no pueden

**Comment by Wachi15** [comment]
tengo el mismo problema como lo soluciono jaja

**Comment by vegetagamer9** [comment]
Wachi mith no responde :/

**Comment by Wachi15** [comment]
:/ y solo hay q esperar ..? pierdo las cosas.?

**Comment by vegetagamer9** [comment]
No se Mith esta on en el server espero que responda

**Comment by MithrandirCraft** [comment]
https://github.com/MithrandirCraft/MithrandirCraft/issues/231
