### ISSUE TITLE
Casino

### ISSUE THREAD

**Issue by xXMetalRamboXx** [MithrandirCraft/MithrandirCraft#23]
Se podria hacer un casino en el servidor para ganar premios y items. Un saludo xXMetalRamboXx

**Comment by MithrandirCraft** [comment]
Un casino de verdad, donde siempre sales perdiendo? O un casino chollo, donde ganas cualquier cosa invirtiendo cualquier chorrada? O tiene que ser un local justo y equilibrado para añadir a la ya desconocida complejidad del servidor. El 80% de jugadores en MithrandirCraft desconoce que puede sentarse en una escalera mediante un comando, porque les da "palo" informarse acerca de los comandos. Cuantos jugadores crees que se darían cuenta de que existe un casino?

Me gustaría saber, cuanto crees saber sobre el servidor? Me la juego a que podría decirte que ya existe un casino, y no lo habrías visto.

No existe ningún casino, pero si realmente crees firmemente en tu idea, organiza una votación en los foros, y atrae gente para que voten de forma neutral. Luego muestrame los resultados en forma de encuesta, y quizá plantee añadir tal función al servidor.

El servidor ya és muy complejo, no puedo aplicar nuevas funciones a la ligera.
