### ISSUE TITLE
¿Que paso con las contraseñas?

### ISSUE THREAD

**Issue by krazlas1** [MithrandirCraft/MithrandirCraft#230]
Buenas.

El día de hoy 27 de marzo de 2016 he querido entrar al servidor, entre en la sala de login, escribí mi contraseña y me dice que es incorrecta.

Ya intenté varias veces pero me sigue insistiendo que es incorrecta

No he cambiado mi contraseña en 3 años, así que sigo dudando de que la esté escribiendo mal o cualquier cosa por el estilo, tampoco tengo el Mayus activado.

Si alguien puede ayudarme me seria muy util :l 

feliz día.

**Comment by carruly71** [comment]
hola.

yo tengo el mismo problema y logicamente he hecho lo mismo he intentado logearme varias veces y me dice contraseña incorrecta etc etc 

enfin me consuela no ser el unico la verdad y espero q esto se solucione

un saludo

**Comment by MithrandirCraft** [comment]
https://github.com/MithrandirCraft/MithrandirCraft/issues/231
