### ISSUE TITLE
Hilo oficial de problemas con el sistema de contraseñas.

### ISSUE THREAD

**Issue by MithrandirCraft** [MithrandirCraft/MithrandirCraft#231]
Buenas tardes.
Ayer por la tarde ocurrió un problema grave con la base de datos del sistema de contraseñas, que impide que algunos jugadores ya registrados se conecten. Este problema es irreversible.
Consecuentemente, desde el equipo interno hemos estado valorando las opciones actuales, para restablecer el acceso al servidor, para los jugadores cuyo acceso se ha corrompido.

Hemos llegado a la conclusión de que el mejor curso que podemos tomar, es purgar la base de datos, y hacer que todos los jugadores vuelvan a registrarse de nuevo.
Esto implicaría un reinicio del sistema de contraseñas, y limitación de registros a 1 por IP.

Evidentemente, esta acción produciría una brecha de seguridad bastante comprometida, sin embargo, confiamos en la buena voluntad de los jugadores. Cada jugador deberá registrar únicamente su propia cuenta.

Esta es la estructura temporal que pretendemos tomar para realizar esta operación:
ESTEN ATENTOS PARA CUALQUIER CAMBIO CON ESTE HORARIO:
21:30h - El servidor entra en mantenimiento.
00:00h - El servidor vuelve a estar accesible. Los jugadores deberán re-registrarse de nuevo, exactamente a esta hora.

Esta operación generará consecuentes violaciones de la normativa del servidor. Aquellos jugadores que sean detectados explotando esta brecha, serán expulsados de forma permanente.
Además, para discutir esta operación en tiempo real, se ha creado un hilo oficial en GitHub, para realizar comentarios y hacer el seguimiento del proceso de re-registro.

Estamos tomando también diversas medidas para detectar a jugadores malintencionados y hacer más justos los re-registros.

**Comment by vegetagamer9** [comment]
tendremos que poner /register ( contraseña ) (contraseña) ?

**Comment by vegetagamer9** [comment]
di mithrandir
y mis multicuentas??

**Comment by agente00** [comment]
bueno bueno me robaron la cuenta

**Comment by agente00** [comment]
;n;

**Comment by MithrandirCraft** [comment]
A nadie le han robado la cuenta (todavía) Solo esten atentos a la hora de reapertura para re-registrar sus cuentas.

Habrá limitaciones iniciales, asi que procuren registrar sus cuentas mas importantes con prioridad.

**Comment by agente00** [comment]
ah ok 
le voy a decir a shadow algo

**Comment by agente00** [comment]
mith no voy a estar conectado a esa hora le puedo decir a alguien que se logee por mi?

**Comment by UnicamenteYoxD** [comment]
Solo se permite con una IP agente.

**Comment by agente00** [comment]
D:

**Comment by agente00** [comment]
pero no vo

**Comment by vladtriana** [comment]
Mejor reinicien el server... es mejor opción pa todos ya q solo podemos usar 1 sola ip 

Como haremos pa los q teniamos varias cuentas legales...

Atte espero su respuesta con integridad de q por los menos 3 a 5 cuentas x ip se puedan usar mys saludos

**Comment by saul1207** [comment]
lo  mismo opino yo q se reinicio el server y q las compras q se aiga. Echo q se den de regreso eso sería la mejor solución

**Comment by TheJuandeMc** [comment]
Ya son las 22:00 y no está abierto el server, pasa algo? :S

**Comment by TheJuandeMc** [comment]
Ups es a las 22:30 perdonen

**Comment by vladtriana** [comment]
Q dejen las cuentas 10 x ip o medio imperio de gente esta decida  a dejar el server... bajara la reputacion

Son rumores q dice el pueblo....

**Comment by agente00** [comment]
mith porque no reinicias el sv como hiciste antes?
Creo que seria la mejor solucion ya que gente tiene cosas importantes es sus multis y ahora no las van a poder recuperar
...

**Comment by vladtriana** [comment]
Estas es la 4cuarta vez q pasa cada 3 o  5 meses suceden estas fallas

La mejor opción es  reiniciar el server el clan de johanna"🙌 esta a favor...y habiliten varias cuentas x ip

**Comment by agente00** [comment]
reinicien el sv es la mejor opcion!

**Comment by Chilikuman** [comment]
En el caso de que el reinicio del server no solucione el problema, me parece que esta claro que mith 
no tiene otra salida que hacer esto. Aunque no me ha quedado claro si el registro por ip sera de 1 y luego aumentara gradualmente, no ha quedado claro, pues dejar 1 como dice aqui deja muchas cuentas inhabilitadas. Solo queda esperar que la gente sea honesta por el bien del server. Mucha suerte a todos y a cruzar los dedos xd. 
Me gustaria que Mith estuviera mas presente y se mencionara.

**Comment by Chilikuman** [comment]
me huele que se desatara el caos

**Comment by TheJuandeMc** [comment]
Suerte a todos que no les roben las cuentas!

**Comment by TheJuandeMc** [comment]
Que pasa? D:

**Comment by TheJuandeMc** [comment]
Mith responde :v Aparecimos en un sitio raro e.e

**Comment by Chilikuman** [comment]
pudiste entrar?

**Comment by TheJuandeMc** [comment]
Si, estuvimos maki y yo pero Aparecimos no podíamos usar comandos, era como si fuera un server vanilla

**Comment by Chilikuman** [comment]
luego te ha tirado?

**Comment by TheJuandeMc** [comment]
Si

**Comment by TheJuandeMc** [comment]
Pero no había que poner register, simplemente el login

**Comment by Chilikuman** [comment]
algo me dice q empieza 1 min

**Comment by TheJuandeMc** [comment]
Sigue cerrado :S

**Comment by Chilikuman** [comment]
nose porq sigo confiando en mis instintos si nunca han dado resultado...

**Comment by TheJuandeMc** [comment]
Nos volvieron a kickear

**Comment by TheJuandeMc** [comment]
El caos ha llegado ñeñeññe

**Comment by agente00** [comment]
el sv esta en mantenimiento :v

**Comment by vladtriana** [comment]
Reinicien el server y ahorrense un dolor de cabeza  siii

**Comment by TheJuandeMc** [comment]
Mith di que pasa :S

**Comment by agente00** [comment]
Reinicien el server y ahorrense un dolor de cabeza siii

**Comment by vegetagamer9** [comment]
Con un reinicio seremos felices el clan de johanna esta a favor! :raised_hands:

**Comment by agente00** [comment]
Con un reinicio seremos felices el clan de johanna esta a favor! :raised_hands:

**Comment by vegetagamer9** [comment]
Con el clan de johanna nos referimos a los de 300
okno xD

**Comment by agente00** [comment]
jajaj

**Comment by agente00** [comment]
spartans! what is your profecion? AU AU AU

**Comment by vegetagamer9** [comment]
guerreros! xD

**Comment by Vegepapa** [comment]
He logrado  entrar  sin registrar pero me voto inmediatamente. .. :(

**Comment by vegetagamer9** [comment]
mith reclamamos un reinicio!
de inmediato, deja de comerte la cabeza que te tiene que estar hechando humo! y reinicialo y ya esta si no te hara BOM la cabeza que tienes

**Comment by TheJuandeMc** [comment]
Pero un reinicio que se refieren a un reseteo del server? :O

**Comment by agente00** [comment]
el pueblo quiere un reinicio!

**Comment by carruly71** [comment]
a ver chavales no se si os a pasado como a mi pero he releido el primer comentario de mith donde lo explica todo y dice q el server abre a las 23:30 y no a las 22:30 como parece q creeis la mayoria asi que solo queda esperar media hora mas 

y si haceis el favor de no decir tonterias en el post se agradece porque lo unico q conseguis es liar mas las cosas

**Comment by TheJuandeMc** [comment]
O.o carruly mi salvador xD gracias no me había dado cuenta

**Comment by vegetagamer9** [comment]
mith kickea a carruly

**Comment by Vegepapa** [comment]
Mith  algo en lo pueda o podamos apoyarte???

**Comment by agente00** [comment]
no

**Comment by vegetagamer9** [comment]
vegepapa no podemos hacer nada
son cosas de admins

**Comment by vegetagamer9** [comment]
si te hicieras moderador pues podrías ayudar xD

**Comment by agente00** [comment]
:v:

**Comment by Chilikuman** [comment]
no deberia haber abierto ya'?

**Comment by vegetagamer9** [comment]
nu se

**Comment by Chilikuman** [comment]
cambio el mensaje ya lo abriran

**Comment by agente00** [comment]
ya casi :v

**Comment by agente00** [comment]
yo prefiero un reinicio :S

**Comment by MithrandirCraft** [comment]
Buenas noticias. Lo he arreglado todo.

**Comment by TheJuandeMc** [comment]
Mith no hay registers

**Comment by agente00** [comment]
porque lo arreglo :v

**Comment by MithrandirCraft** [comment]
Todo esta arreglado. Olviden las advertencias sobre re-registros. He conseguido solucionar lo que os impedía loguear.

**Comment by agente00** [comment]
:O
