### ISSUE TITLE
la mejor opción es reiniciar el server... asi no se puede vivir... 

### ISSUE THREAD

**Issue by vladtriana** [MithrandirCraft/MithrandirCraft#232]
Mejor reinicien el server... es mejor opción pa todos ya q solo podemos usar 1 sola ip

Como haremos pa los q teniamos varias cuentas legales...

Atte espero su respuesta con integridad de q por los menos 3 a 5 cuentas x ip se puedan usar mys saludos

**Comment by vladtriana** [comment]
Q dejen las cuentas 10 x ip o medio imperio de gente esta decida a dejar el server... bajara la reputacion

Son rumores q dice el pueblo....

**Comment by vladtriana** [comment]
Estas es la 4cuarta vez q pasa cada 3 o 5 meses suceden estas fallas

La mejor opción es reiniciar el server el clan de johanna":raised_hands: esta a favor...y habiliten varias cuentas x ip

**Comment by rosejohanna** [comment]
Buenas tardes saludos a todos, me parece que lo que está pasando en el server es una pena, creo que no solo tú tienes esta preocupación Triana y como dices no es la primera vez que pasamos por este problema y sería una buena opción “Reiniciar el Server” así se calmaría el temor de todos al perder sus multicuentas ya que solo una cuanta permitirán registrar por ip, lo cual se podría arreglar con un baneo a la ip que robe una cuenta, pero existen los café internet en muchos países donde cualquiera puede ir a registrar una cuenta desde ese lugar desclaimiar fac,robar ítem y no le perjudicara en su ip porque lo hará desde un punto aleatorio o programas que cambian la ip.
 
Entonces eso nos deja vulnerables totalmente asi que porque no dar un reinicio general y ser parejo con todos, seria grandioso un nuevo comienzo con la actualización nueva de la 1.9 me encantaría construir en un lienzo nuevo n.n y ver esas mentes brillantes como van en busca de los mejores chunk para sus hogares en faction…

Espero que Mith tome la mejor decisión para nuestro lugar de recreación n.n por lo tanto si no hay igualdad, comenzaré por ahí con mis amistades y familia buscando un nuevo entretenimiento… 

Es un placer jugar en mithrandircraft ya que siempre ha sido justo con todos los jugadores y nos brinda un lugar donde más que un juego se convierte en una red social donde puedes conocer maravillosas personas y una enriquecida diversidad de culturas.

Les saluda Rose Johanna B.

**Comment by vegetagamer9** [comment]
Lo cierras, asi? ni respondes ehm.... ya veo no quieres reinicio, y porque, que te cuesta?

**Comment by MithrandirCraft** [comment]
Lo he leído todo, no tengo nada que añadir. Esta todo arreglado.

**Comment by agente00** [comment]
mith podemos logearnos con nuestras cuentas entonces?

**Comment by agente00** [comment]
porque en ellas tengo cosas muy importantes

**Comment by MithrandirCraft** [comment]
Olviden las advertencias, olvidenlo todo. He estado estudiando el problema con detalle y lo he solucionado.

**Comment by vegetagamer9** [comment]
Al menos, dí las razones de por que no el reinicio...

**Comment by agente00** [comment]
vegeta ya arreglo todo :v si queres podes usar tus multis :v

**Comment by rosejohanna** [comment]
Gracias Mith eres grande :*

**Comment by MithrandirCraft** [comment]
No teneis nada que agradecer. Gracias a vosotros.

**Comment by agente00** [comment]
mith me debes una espada filo IV con aspecto igneo II
