### ISSUE TITLE
Robo, Bug ? O.O? o las perdí de verdad? y solo paso despues del error que hubo

### ISSUE THREAD

**Issue by DarkArcano** [MithrandirCraft/MithrandirCraft#233]
Hola, soy DarkArcano ... Buenas tardes compañeros y compañeras

recién , después de que arreglaran el problema..... la ultima vez que me fui tenia puesta una cabeza de blaze, y unas elytra hoy recién me conecto.... 
y desparecieron por arte de magia... 
reclamo porque me costo y nada es gratis en la vida todo lo obtienes con esfuerzo.... 
y lamentablemente no me esperaba que eso pasara... 
por lo tanto lo reporto porque valoro lo que tengo y es mejor reportar que callar esto...

espero , se encuentre alguna solución a este problema

Cordial saludo a todos

gracias de antemano por su tiempo

espero no incomodar su tiempo

**Comment by MithrandirCraft** [comment]
Cuando las conseguiste?
El servidor regresó al estado en el que estaba el Sábado a las 7A.M. (Hora española) de la mañana.

Consecuentemente, TODOS los cambios fueron revertidos.

Revisa que no estén tus objetos en otro lugar.

**Comment by DarkArcano** [comment]
la verdad mith, analizó lo que pasa primero se devolvió todo lo que tenias hace 2 días según veo.... había hecho cosas en survival construcciones que también quedaron como si nunca las hubiera hecho....
y varias cosas que tenia.... la gente dice que ya esta acostumbrada a esto pero... sinceramente , si es asi que los jugadores se aguantan eso con todo respeto mith.. como dueño y persona es una burla y falta de respeto que a una persona le hagan eso....... y que mas encima no se le reembolse eso si fue falla del servidor pruebas de lo que tenias si hay problemas con eso pero también los fallos son imprevistos que salen... y en imprevistos es algo que llega de la nada... si todos supieran hasta toman foto de lo que tienen...


por cierto revisa tu correo te mande algo... cuando tengas tiempo léelo.... que yo tengo disposición ..

**Comment by MithrandirCraft** [comment]
Me es imposible restaurar los inventarios de todos los jugadores a su estado antes del rollback completo.

Consideraré tu solicitud, entonces, si deseas añadir algo mas, lo podrás hacer directamente.

**Comment by DarkArcano** [comment]
no, para nada gracias :D .... esperare la respuesta a mi solicitud..
gracias por todo buen dia

2016-03-31 11:04 GMT-05:00 Mithrandir <notifications@github.com>:
