### ISSUE TITLE
Sugerencias Mundo Survival (Comenta lo que te gustaría ver)

### ISSUE THREAD

**Issue by SimplyAcke** [MithrandirCraft/MithrandirCraft#234]
Este _post_ ha sido abierto puesto que ya muchos jugadores de _Survival_ desean cosas y no saben dónde exprimirse. Si juegas _Survival_ y tienes **propuestas** de balanceo o de cualquier otro tipo que tenga que ver con este mundo coméntalas aquí!

Tenemos 2 mundos Survival y Facciones hay que potenciar los 2! Queremos saber qué es lo que todos vosotros necesitáis y así ayudáis a mejorar el servidor. :)

**Comment by NosophorosVampire** [comment]
Hola yo juego surv, y siempre e querido encontrar Tesoros !! 
Mi idea es:
 que alguien se encargara de enterrar tesoros  en cofres x todo el survival a diferentes profundidades al azar, no tengo idea si hay algun comando o programa que lo pueda facilitar, como hay filtro de x ray no abra problema supongo, y que los tesoros sean de todo tipo partes de armadura con encantos de alto nivel herramientas y armas , monturas, armaduras de caballos, diamante, esmeraldas y todo lo mas valioso claro solo un tesoro x cofre ej: me encontre unas botas con encantos super buenos, unos 50 tesoros x bioma que al encontrarlo se vayan renovando y moviendo de lugar..  estaria bueno encontrarse uno mientras minas .. CLARO un tesoro de minerales podria ser 30 diamantes !, un stack de oro ejemplo... que valga la pena la alegria al encontrarlo..  digo yo

QUEJA:
tambien que ojala hubiera un moderador activo en survival un encargado que viera todo y con la facultad de arreglar los problemas de todos nosotros.

**Comment by Vegepapa** [comment]
Hola vampire

Los Mods  que en la actualidad  existen. Son para ambos mundos. Tanto Factions  como Survival. 

Es una realidad  k el mundo de survival  se encuentra un tanto abandonado.

Sin embargo existimos varios players que no somos mods, pero si en algo te podemos ayudar con gusto lo haremos.

Con respecto a los cofres de tesoros, no lo veo muy viable, lo interesante de survival  es k puedes andar libremente por todo el mundo sin k otro player te mate. Aquí  lo importante es ver k tanto en factions como survival las cosas se obtienen por mérito propio al pasarte horas picando y explorando.

Ahora si quieres botín te invito a que juegues  Factions,  aprendas a petar a las demás factions  y veraz k divertido es y a su vez si corres con suerte un buen botín te llevaras

**Comment by NosophorosVampire** [comment]
me gustaria ver un mod o admin activo para el mundo survival, ya que hay muchos jugadores nuevos y nadie los ayuda mas que los mismos player.

**Comment by SimplyAcke** [comment]
La verdad, en esto te doy la razón; pero como dice el motd "Los **Mod** y / o **PB** también son _jugadores ofensivos_ y con esto se refiere que hasta mods pueden pedir "_tpakill_". La idea es buena pero su desarrollo lo veo difícil por ahora... A ver qué opina Mithrandir =)

Cordial saludo,
~Acke.

**Comment by Erzasaulnattajhosvampmarcieriotieshadon** [comment]
ooo no habia pasado por aqui y lo que dice acke es sierto n.n yo en lo personal muero porque los huevos de creditos puedan cambiarce en survival como se hace en faction o que vendieran materiales que no se encuentran por falta de biomas como el hielo comprimido la arcilla de colores la arena arenisca roja los bloques marinos ya que en todo survival solo hay dos templos los cuales no existen fisicamente solo estan los guardianes por lo tanto no tenemos esos bloques y seria bueno tenerlos ademas los nuevos bloques del end las frutas para hacer otras cosillas, espero puedan mejorar eso en survival :)

**Comment by GaaZ** [comment]
Perdón por ser tan impertinente pero... VENDAN FAROS EN SURVIVAL DE UNA VEZ! Aunque sea a stack de bloques de esmes pero vendeme uno sh*t ! P#$%A M#$$%A DEMORO UN SIGLO MINANDO TODO UN CHUNK PARA LLENARLO DE REDSTONE t.t asdasdafgdfgasjfdasjfgkashfashfl #redstonetutorialfail #deberiacambiardeservidorokno #Lebetnuvequisdelol :v

**Comment by MithrandirCraft** [comment]
@GaaZ He añadido una cabeza de wither a la tienda. Espero que eso ayude.

**Comment by Blasfemia** [comment]
abran la nueva tienda en la parte baja en survival, esta prometido hace mucho x los admin pero ya meses que no pasa nada.

**Comment by Blasfemia** [comment]
pongan arcos y todos los libros con encantos posibles aunque esten caros ya que e perdido mi inventario un par de veces, a si compro las cosas y ya no me hago mala sangre :/

**Comment by MithrandirCraft** [comment]
@Blasfemia Si pierdes tu inventario hazlo saber de inmediato en el apartado de perdidas de objetos, especialmente si durante la perdida estabas cambiando de mundo.

**Comment by Neto9998** [comment]
@MithrandirCraft  Deberian aunmentar el limite a los Usuarios VIP+ para minar :( yo llevo horas y  horas y siempre me dice que espere 5 minutos y dia que estoy libre se me da por ir a minar unas horas y me limita :'( y talvez agregar comprar esme en la tienda hehehe y una pregunta no actualizaran el server a la mas reciente? 
Saludos

**Comment by MithrandirCraft** [comment]
@Neto9998 Siempre actualizamos el servidor. En el momento adecuado.

Los limites están para prevenir el abuso por parte de tramposos. Me temo que tendrás que tener paciencia.
