### ISSUE TITLE
Duda sobre el tiempo de desprotección de una casa (surv)

### ISSUE THREAD

**Issue by NosophorosVampire** [MithrandirCraft/MithrandirCraft#236]
Hola Mithrandir quisiera saber cual es el tiempo real de desproteccion de una casa en survival x inactividad,
e visto jugadores con 2 meses 3 dias de inactividad y aun siguen protegidos y en las normas dice 1 mes, por favor pongan el tiempo real y avisen para evitar malos entendidos. 
gracias x tu tiempo.

**Comment by MithrandirCraft** [comment]
Los datos actuales deberían estar aplicandose. Le he echado un vistazo para revisar que asi sea, si a partir de las 6 sigue sin desreclamarse un terreno cuyo dueño lleve mas de 30 días inactivo, hazmelo saber aquí mismo.

De ser asi, specifica coordenadas contenidas en ese terreno, me encargaré de arreglarlo yo mismo.

**Comment by NosophorosVampire** [comment]
okey, el limite de tiempo es 31 dias?

**Comment by MithrandirCraft** [comment]
30, tienes los detalles en /warp comandos.

Y bien, hay progreso?

**Comment by MithrandirCraft** [comment]
Cierro esto. Reabre si tienes algo mas que comentar.
