### ISSUE TITLE
Saludos Cordiales

### ISSUE THREAD

**Issue by RuePlumet** [MithrandirCraft/MithrandirCraft#237]
Hola.

**Comment by MithrandirCraft** [comment]
Esto es un sistema de reportes, utilizalo responsablemente o podría serte negado el acceso.

Lee las instrucciones aquí: https://github.com/MithrandirCraft/MithrandirCraft

**Comment by SimplyAcke** [comment]
Ennya, qué ha sido de ti? D: te echamos de menos
