### ISSUE TITLE
problemas con nuestras skins..

### ISSUE THREAD

**Issue by NosophorosVampire** [MithrandirCraft/MithrandirCraft#238]
hola no se si hago bien en abrir un ticket x cada consulta que tengo u o problema
vale desde hace varios dias no puedo ponerme mi skin y otros jugadores tambien tienen el mismo problema, tanto como hay quienes tienen problemas otros si pueden usar su skin, ya e tratado saliendome mil veces probando con otros nombres de skin, pero no pasa nada.. es divertido tener su skin y una de las cosas que me gusta de tu server es que dejas tener nuestras skins eso esta muy bueno y lo hace diferente a muchos server donde solo los vip pueden, gracias x eso..
ojala puedas solucionarlo :+1: .
soy: VampiRe

gracias x tu tiempo :D

**Comment by MithrandirCraft** [comment]
Esta bien, pero ya estamos al corriente de este problema.
Es bastante común que cada X tiempo este componente de errores un tiempo, hasta que lo arreglemos.

Este ticket permanecerá abierto hasta que el asunto se solucione.

**Comment by NosophorosVampire** [comment]
gracias mithrandir :)

**Comment by MithrandirCraft** [comment]
Fixed.
