### ISSUE TITLE
Reportar Chat 

### ISSUE THREAD

**Issue by JhosxBlack** [MithrandirCraft/MithrandirCraft#239]
Disculpen si no es el lugar indicado, pero realmente no entiendo mucho este foro. 

Quiero reportar lo siguiente:
El el chat se encontraban discutiendo 2 faction's, una de ellas estoy yo, mas no dije nada insultante, el comportamiento que note es el siguiente:

Tanto como la persona que fue banneada (miembro de mi faction) como otras personas estaban insultando diciendo groserías de manera publica (enemigos de la faction). incluso los miembros de otras fact.. llegaron a meterse con otras personas ausentes en el momento.

Pero solo la persona que esta dentro de mi faction fue castigada por el moderador, y se encontraban mas de 2 moderadores conectados, pero ellos eran de factiones enemigas involucradas en el asunto. Me parece injusto que solo pague un miembro de mi faction y los otros se encuentren impunes. así que por medio de la presente hago notar unas capturas de pantalla capturando el chat entre ambos bandos.. y dando a conocer de manera publica la injusticia que fue cometida.
Con todo el respeto, las normas se hicieron para cada individuo del servidor. 

![2016-04-29_17 43 09](https://cloud.githubusercontent.com/assets/18745300/14931880/23d55de8-0e39-11e6-92cb-747deee2a35e.png)

![2016-04-29_17 43 26](https://cloud.githubusercontent.com/assets/18745300/14931881/266d7c70-0e39-11e6-8995-4280f33c5a84.png)

![2016-04-29_17 46 41](https://cloud.githubusercontent.com/assets/18745300/14931882/287868e0-0e39-11e6-9a2d-6e459c2e36ae.png)

![2016-04-29_17 46 55](https://cloud.githubusercontent.com/assets/18745300/14931890/2b2bb6d2-0e39-11e6-96f7-a79867f5a448.png)

![2016-04-29_17 47 34](https://cloud.githubusercontent.com/assets/18745300/14931891/2ec7916c-0e39-11e6-95da-4d26c2563bb0.png)

![2016-04-29_17 48 10](https://cloud.githubusercontent.com/assets/18745300/14931893/30fdb3a8-0e39-11e6-9785-bfb1bf647bc3.png)

![2016-04-29_17 51 07](https://cloud.githubusercontent.com/assets/18745300/14931906/4c853254-0e39-11e6-9b23-10d25bf2bf36.png)

![2016-04-29_17 51 12](https://cloud.githubusercontent.com/assets/18745300/14931907/4ed54d3c-0e39-11e6-95e8-9c708a086130.png)

![2016-04-29_17 51 28](https://cloud.githubusercontent.com/assets/18745300/14931909/50a2287e-0e39-11e6-918d-c47353425253.png)

![2016-04-29_17 52 10](https://cloud.githubusercontent.com/assets/18745300/14931910/5261fefa-0e39-11e6-994d-b070a1fa583d.png)

![2016-04-29_17 52 24](https://cloud.githubusercontent.com/assets/18745300/14931911/54228232-0e39-11e6-9010-d273dfbceb79.png)

P.D: las imágenes que incluyen los nombres de las personas que fueron nombradas las envié sin editar a la pagina oficial de facebook por mensaje privado. 
No quiero que las personas ausentes sean afectadas por el contenido, públicamente. 
El asunto no quedo aquí, luego siguieron, y el único que pago fue el miembro de mi fation.

**Comment by KawaiiGNE** [comment]
Las únicas burlas de filtro estuvieron hechas por miembros de tu fac actualmente theshadowwither, el cual después de ser baneado durante un dia, volvió con una multicuenta para insultar a través del ayudaop, que causo otro ban de 4 horas en su otra cuenta.

Nadie mas realizó burlas de filtro ni uso inadecuado del ayudaop a parte del jugador previamente mencionado

**Comment by MithrandirCraft** [comment]
Muy entretenida la lectura.

Este ambiente es bastante habitual a horas punta en el servidor, creo que el equipo de moderación ya sabe actuar ante estas situaciones.

No considero que haya que tomar medidas excesivas durante estas ocasiones, tan solo un par de advertencias, kicks, y expulsiones de corta duración.
Los casos de mal lenguaje extremos y reiterados si podrán ser penalizados con castigos más elevados.

Mi recomendación es, que si encontráis un jugador malhablado, y no os gusta lo que dice en público, le ignoréis, y no participéis en su juego verbal. El equipo de moderación hará el resto.
