### ISSUE TITLE
Supuesto bug de Damage de xLebet

### ISSUE THREAD

**Issue by Ivanovic24** [MithrandirCraft/MithrandirCraft#24]
El caso es que xLebet va diciendo por ahi que tiene fuerza 3 y la verdad esque si lo tiene, en los hg te mata practicamente de un golpe y medio; y hace no mucho fue a mi faccion a matarme y de un Espadazo me quito 4.5 corazones con p4, dice q lo izo con su ´´Super click Ultraveloz`` q consiguio bugear su damage, ahora es practicamente invencible :c.

Foto de lo q dijo xLebet:
http://imgur.com/eBtZKR0
Haber si pueden solucionar ese supuesto bug, q ace q el pvp no sea justo

**Comment by MithrandirCraft** [comment]
Muy bien, investigaré este asunto.

**Comment by MithrandirCraft** [comment]
Solucionado.
