### ISSUE TITLE
Perdida de inventario.

### ISSUE THREAD

**Issue by vegetagamer9** [MithrandirCraft/MithrandirCraft#240]
Hoy a las 17:50 Hora española perdí mi inventario y lo que mas coraje me dio es que perdi una armadura con mending todo mending y p4 
Por favor devuelvame mis cosas.

**Comment by vegetagamer9** [comment]
aqui esta mi armor : 
![2016-03-26_15 41 02](https://cloud.githubusercontent.com/assets/12957778/14959365/53786cc2-108f-11e6-9259-c82b1286a736.png)
![2016-03-26_15 41 03](https://cloud.githubusercontent.com/assets/12957778/14959366/53938e58-108f-11e6-89ed-1c447774679e.png)
![Uploading 2016-03-26_15.41.05.png…]()
![2016-03-26_15 41 07](https://cloud.githubusercontent.com/assets/12957778/14959371/5b30f9fc-108f-11e6-9bce-c735a68f8385.png)

**Comment by vegetagamer9** [comment]
![2016-03-26_15 41 05](https://cloud.githubusercontent.com/assets/12957778/14959526/0fb5df64-1090-11e6-8207-c2481f51946c.png)

**Comment by vegetagamer9** [comment]
La pieza que faltaba.

**Comment by MithrandirCraft** [comment]
Buenas tardes.

Los casos de perdida de inventario se reportan aquí:
https://github.com/MithrandirCraft/MithrandirCraft/issues/174

Procura seguir bien las indicaciones.
