### ISSUE TITLE
Sugerencias de Normas

### ISSUE THREAD

**Issue by SimplyAcke** [MithrandirCraft/MithrandirCraft#241]
Como he podido notar, hay algunas normas que necesitan un **rework** / **actualización**, por ello voy a redactar aquellas que _en mi opinión_ necesitan algún cambio.
### Importante:
**Si tú también opinas que alguna norma puede ser modificada a mejor en beneficio de todos escríbenos un comentario con tu proposición.**

_Norma_ permitida nº1
Asaltar y robar a otros jugadores en Factions(Griefing). Se dan suficientes medidas de protección para evitar estos asaltos, asi como las suficientes para permitirlo si un jugador no se defiende.

Propongo el cambio de **Griefing** a **Raiding** puesto que el 2ndo término es más usado _en mi opinión_.

_Norma_ permitida nº5
Embaucar (Engañar/Timar) a otros jugadores, en las siguientes situaciones: Con finalidades de ventaja en PvP y Factions (Mandar un tp con proposito ofensivo, infiltrarse en una facción...), Durante un intercambio, o venta de objetos (con o sin NPC)

Aquí propongo que en vez de _las siguientes situaciones_ que pase a ser **en todas las ocasiones** dado que no hay ninguna norma que prohíba lo contrario.

Añadiré cosas que vea necesarias.

**Comment by MithrandirCraft** [comment]
Bueno, he revisado la normativa.

No me parece demasiado desactualizada, es bastante concisa. No voy a cambiar nada mas a no ser que me des mas motivos, y más convincentes.

Gracias por tu aportación.
