### ISSUE TITLE
Error en login

### ISSUE THREAD

**Issue by Marioski** [MithrandirCraft/MithrandirCraft#244]
Hola! ayer me registré y estoy seguro de la contraseña que puse y me la marca como incorrecta, creo que se bugeó por un cambio de versión del servidor o algo así le dijo un admin a un amigo que estaba preguntando por mi in-game.
no alcancé a poner correo asociado por lo que no puedo resetear la passwod ahí, me pueden resetear la password o borrar mi cuenta para registrarme denuevo (ya que soy premium no puedo solo cambiarme el nombre y registrarme de 0 denuevo)

Username: Marioskii

Gracias de antemano!

**Comment by MithrandirCraft** [comment]
Desregistrado.
