### ISSUE TITLE
Baneo incoherente (KawaiiGNE)

### ISSUE THREAD

**Issue by RandyNotaLokaa** [MithrandirCraft/MithrandirCraft#245]
_**Me encontraba recorriendo el mapa, bla bla no viene al caso. Resulta que en el chat log estaban peleando Elvis, y theShadowWither. Este ultimo insultando a Elvis, en eso entra el MOD Kawaii, ve la pelea, paso lo siguiente, empeze a trolear a shadow, sin insultar. En eso banea a Shadow, y me termina baneando a mi por 24 horas, segun el "Norma2" Sin razon alguna ni nada, Elvis, esta presente y en ningun momento dije o hize algo fuera de las reglas, Este moderador ya lleva haciendo lo mismo desde hace dias, solo por que no le cae bien alguien.**_

### **_Att: RandyNotaLokaa_**

**Comment by KawaiiGNE** [comment]
Norma 2: El lenguaje ofensivo o falta de respeto hacia otros miembros de cualquier rango y o por cualquier motivo. Especialmente hacia miembros de la comunidad con rango/s staff.
Norma 16: Cualquier actitud que un administrador o moderador considere perjudicial para el ambiente de juego o el servidor en general.

Si segun tu no has dicho nada, yo nada mas entrar por aviso de otro staff que me aviso de que no paraba el jugador tercero de insultarle, nada mas entrar el jugador tercero y tu empezasteis a faltar el respeto a 2 miembros del staff, con insultos tales como: Gordo, donde tienes el cerebro, tienes el hammer en el cerebro, pues a ti te vi diciendo exactamente esas palabras.

**Comment by MithrandirCraft** [comment]
Parecen motivos convincentes. Tienes algo más que añadir @RandyNotaLokaa o debemos molestarnos en revisar con mas profundidad este caso?
