### ISSUE TITLE
Baneo Incoherente.

### ISSUE THREAD

**Issue by RandyNotaLokaa** [MithrandirCraft/MithrandirCraft#246]
Si tienes fotos, o demas subelas. Si tienes claro esta, el que estaba diciendo todo eso era Shadow. Lo unico que le dije fue "Ratika" al Shadow por insultar a Elvis, y ya venis vos a banear. Ni avisas que pare el mal lenguaje ni nada, y el que te insulto a ti y a Elvis, fue ShadoWither, segun el, por que elvis lo mato y le robo las cosas. Por eso le dije rata, entonces tu entras y baneas sin saber que esta pasando y te vas como si nada, media pila jugar asi. Cuando miembros de tu faccion o amigos hacen lo mismo, no das bola en pie, y los dejas que sigan flasheando. Asi cualquiera flaco. Tienes la mania de kikear y banear gente por que si. O queres que te ponga la foto en lo que dijo Elvis "Cuantas esmes me das y digo la verdad".

**Comment by SimplyAcke** [comment]
Randy, no das ninguna explicación. Por favor concreta más.
