### ISSUE TITLE
Rumores de un reinicio general en el server...

### ISSUE THREAD

**Issue by NosophorosVampire** [MithrandirCraft/MithrandirCraft#247]
Hola mith, hay rumores de que habra un reinicio general en el server... a reinicio general me refiero a que se actualizara todos los mapas, en resumen se volverá todo a cero x ende se perderá toda construcción e items de los jugadores...  un par de jugadores afirman tal cosa.

Quiero y se que todos también les gustaría saber de tus letras si esto es verdad o no?

x mi ojala no pase nada, xque e trabajado mucho en construir algo genial para el server, espero tu respuesta y gracias x tu tiempo

**Comment by MithrandirCraft** [comment]
http://www.mithrandircraft.es/informacion

Lee el último parrafo con la filosofía del servidor.

No hay ningún reinicio planificado, ni es la intención de nadie destruir el trabajo de los jugadores (Me temo que en alguna ocasión lo hemos tenido que hacer, porque no nos quedaba otra opción, sin embargo, nos gustaría no tener que recurrir a esto nunca más). No se donde habrá salido ese rumor, pero me da mala espina.
Si se produce un rumor así, és porque creeis que existe algún motivo que fundamente un reset total, como por ejemplo, que la economía se haya corrompido de forma grave.

Si tienes algo más que comentarme hazlo.

**Comment by NosophorosVampire** [comment]
entendido,  solo es rumor de pasillo x a si decirlo.. gracias te invito un dia a ver mi trabajo :dancer.

gracias x reponder
