### ISSUE TITLE
(Lee esto antes de reportar mal ambiente en chat) Respuesta generica.

### ISSUE THREAD

**Issue by RandyNotaLokaa** [MithrandirCraft/MithrandirCraft#248]
Bueno, ya hace dias este pibacho viene insultando a diestra y siniestra, lo peor del caso es que dice que como el paga medio sv segun el, no le hacen nada. Por que creo que nadie mas paga vip aca, ademas de eso, de tener mas de 50 cuentas y en todas hacerse pasar por amigo de alguien y terminar robando cosas y pasandoselas a su cuenta real, bueh eso no viene al caso. Segun el no le haran nada si insulta o no por que paga vip. Si quieres las fotos, te las pongo toditas en orden. Para que veas lo "enfermo" que esta este sujeto.

**Comment by MithrandirCraft** [comment]
Si no te agrada el ambiente que causa un jugador, o lo que está diciendo por el chat, dispones del comando: /mute

Cuando una situación en el chat ascienda a peor, nos encargaremos nosotros. Siempre estamos vigilando la actividad en el chat, y en ocasiones no consideramos necesaria ninguna intervención.

La intervención ideal debería pasar por vuestra propia actitud. Debéis aprender a ser mas tolerantes con la actitud inmoral de los demás jugadores, y procurar refinar vuestro propio comportamiento.

También os añado que es bastante habitual encontrar este tipo de actitud en un servidor de facciones, debido a la propia naturaleza del modo de juego. Prácticamente forma parte del contexto. Y por ello somos bastante tolerantes. Sin embargo evidentemente, todo tiene un límite.

En cuanto a la estrategia de "engaño" que mencionas, te hago saber que és una estrategia plenamente valida y permitida en la normativa del servidor. Echale un vistazo si todavía no lo has hecho: www.mithrandircraft.es/normas (Ten en cuenta que és obligatorio)

(Voy a convertir este ticket en una respuesta automatica de recurrencia para todos aquellos que denuncien mal ambiente en el chat, si es de conveniencia.)

**Comment by RandyNotaLokaa** [comment]
![2016-05-25_23 24 12](https://cloud.githubusercontent.com/assets/19366645/15578784/a2460e00-232b-11e6-9889-119d0ffab78b.png)

**Comment by RandyNotaLokaa** [comment]
Lo que molesta es que cualquier user normal sin VIP dice algo. Y le clavan un ban de 24 horas. Inflitrarse en una faccion esta permitido si, pero con tu cuenta real me imagino no? Por que asi que gracia tiene jugar al sv, si el 70% son todos Erza, ya ni se puede confiar en nadien aca jaja. Si queres muchas mas fotos, te las puedo pasar. Ademas su comportamiento no es normal, lo hace solo por que el mismo dice "Compro vip y hago lo que quiero y lo que se me venga en gana" Osea si compro mi VIP puedo pasar por encima de los demas?

**Comment by Erzasaulnattajhosvampmarcieriotieshadon** [comment]
![2016-05-25_21 38 57](https://cloud.githubusercontent.com/assets/19599752/15594126/ebed3f26-236f-11e6-882c-9a7f98469439.png)

**Comment by Erzasaulnattajhosvampmarcieriotieshadon** [comment]
![2016-05-23_18 01 54](https://cloud.githubusercontent.com/assets/19599752/15594142/20758d48-2370-11e6-9bd9-a6bb7eac2f55.png)

**Comment by Erzasaulnattajhosvampmarcieriotieshadon** [comment]
![2016-05-25_21 39 22](https://cloud.githubusercontent.com/assets/19599752/15594146/3f765bfa-2370-11e6-8f6a-ff6db02d00e1.png)

**Comment by Erzasaulnattajhosvampmarcieriotieshadon** [comment]
![2016-05-25_21 39 42](https://cloud.githubusercontent.com/assets/19599752/15594156/60111d46-2370-11e6-8b3b-710e821ce878.png)

**Comment by Erzasaulnattajhosvampmarcieriotieshadon** [comment]
![2016-05-25_21 40 53](https://cloud.githubusercontent.com/assets/19599752/15594161/7df5f552-2370-11e6-8170-79888c80b85c.png)

**Comment by Erzasaulnattajhosvampmarcieriotieshadon** [comment]
![2016-05-25_21 41 49](https://cloud.githubusercontent.com/assets/19599752/15594182/ab20e3c0-2370-11e6-8f0e-6c0063a0659e.png)

**Comment by Erzasaulnattajhosvampmarcieriotieshadon** [comment]
no se pero se ve claro que el que siembra cosecha XD el que busca encuentra :)

**Comment by Erzasaulnattajhosvampmarcieriotieshadon** [comment]
![2016-05-25_21 44 51](https://cloud.githubusercontent.com/assets/19599752/15594237/12eeb324-2371-11e6-9cfb-eb17f0b18553.png)

**Comment by Erzasaulnattajhosvampmarcieriotieshadon** [comment]
bueno y e aqui encontro lo que el buscaba que lo tratasen a su nivel n.n y el que quiere leche se le da :)

**Comment by Erzasaulnattajhosvampmarcieriotieshadon** [comment]
![2016-05-25_21 48 00](https://cloud.githubusercontent.com/assets/19599752/15594301/9338a09e-2371-11e6-8fd0-030aadc8bd3e.png)

**Comment by Erzasaulnattajhosvampmarcieriotieshadon** [comment]
y bueno se le da lo que el cesar quiere asi quiere que lo trate como escoria asi lo tratare espero siempre de el paso tu comiensas yo termino n.n no muestro las capturas a medias tu me provocas yo te sigo el game asi de facil crees que te tengo miedo asi como atacas a todos yhasta del mismo dueño del server hablas y dices que no te importa que te hechen pues bien felicidades  randy n.n no se que tienes en la cabesa que crees que todos somos vampirez y que el es dueño del server y tiene miles de cuentas como no se te puede hacer entender que no somos ese jugador hay que seguite la corriente que es lo que te gusta nadei en el server puede desir algo positivo de vampirez porque se hace automaticamente una multicuenta de vampirez asi de hueca tienes la cabeza...

**Comment by Erzasaulnattajhosvampmarcieriotieshadon** [comment]
![2016-05-25_21 51 08](https://cloud.githubusercontent.com/assets/19599752/15594386/6171d714-2372-11e6-8457-604aede5dd9e.png)

**Comment by Erzasaulnattajhosvampmarcieriotieshadon** [comment]
ha por sierto sin mencionar que es el ganster de el server que nos compra a todos los vip+ y todo lo que tenemos,  como que nadie mas puede dar donaciones al server, aparte de eso pasas amenasando a medio server con hacer tik sin tomarte la molestia primero de leer las reglas y primero hablas de inrespeto cuando eres inrespetuoso lee primero antes de atacar, por sierto que crees que mith no se da cuenta de las cosas o quienes somos en realidad?  o que hacemos si no sabes te lo explico para mi es el dueño del server que te recuerdo es un server totalmente GRATUITO que nos permite estar en el 
pero para nosotros es gratuito a el si le cuesta plata pasta money dinero dolares y su valioso tiempo para hacerle caso a personas como tu o como yo que nos la partimos dentro del server crees que valemos su tiempo tu y yo y el resto con los que segun tu somos vampirez y si vampirez es tan rico como lo crees porque anda petando y enganado para robar si puede tener lo que guste con money e.e haber explicame eso y si no te gusta el server vete las puertas estan habiartas para cuando quieras salir y si desides regresar igaul estan habiartas como te recuerdo es el dueño y por lo tando puede hacer lo que se le venga en gana justo tanbien hecharnos de su server a ti y a mi lo que no sirve se larga no tengo problemas pero eso si a ti te quiero conmigo randy no quiero te quedes solo en ese server tan bello recuerda tengo 100 cuentas 3 cuartas partes de faction es mia y sin mencionar survival que ahi me compre el creativo y sobre todo ya estoy ahorrando par atener los rayos lazer que tienen los mod que estan muy mola si que los quiero

**Comment by Erzasaulnattajhosvampmarcieriotieshadon** [comment]
![2016-05-26_08 02 03](https://cloud.githubusercontent.com/assets/19599752/15594691/36ec24d8-2375-11e6-8e91-44e4e53267a0.png)

**Comment by Erzasaulnattajhosvampmarcieriotieshadon** [comment]
![2016-05-26_08 24 19](https://cloud.githubusercontent.com/assets/19599752/15594706/6676a642-2375-11e6-9fc8-dc1d193d1272.png)

**Comment by Erzasaulnattajhosvampmarcieriotieshadon** [comment]
y unos cuantos extras de captura de salto de filtros por ahi asi que aqui nadie es santo hasta parte del staff se salta el filtro nene

**Comment by Erzasaulnattajhosvampmarcieriotieshadon** [comment]
![2016-04-24_10 36 07](https://cloud.githubusercontent.com/assets/19599752/15594754/cfc41e72-2375-11e6-87e2-c03a24e4e241.png)

**Comment by Erzasaulnattajhosvampmarcieriotieshadon** [comment]
![2016-04-24_10 36 51](https://cloud.githubusercontent.com/assets/19599752/15594791/3c98ddf8-2376-11e6-9d89-cdd65d4c0147.png)

**Comment by Erzasaulnattajhosvampmarcieriotieshadon** [comment]
![2016-04-25_12 49 12](https://cloud.githubusercontent.com/assets/19599752/15594808/910263aa-2376-11e6-8b7d-bc259b6f1383.png)

**Comment by VampAlucard** [comment]
Buenas Noches...
Tantos han qerido como tu "RandyLaloka" qemarme... 
pero aun, tú no llegas ni a basura, eres pura escoria...
¡Vete de aquí o te haré gritar como un cerdo! muajajaja
saludos

**Comment by RandyNotaLokaa** [comment]
khe riza (x3) (bis)

**Comment by Erzasaulnattajhosvampmarcieriotieshadon** [comment]
bueno creo que el trabajo del PB es para atraer personas a el server pero con esa boquita no creo que quieran estar en el server empesando por el staff de publisimo que en vez de ayuda y ser la cara del server tratan mal y hacen que se marchen desepcionados pero bueno eso es otro cuento como el de los nuevos rangos exelentes por sierto me agrada que tega mas ayuda el adm pero por favor que se oculten dan un paro cardiaco cuando le aparecen en la face de repente volando presumiendo su rango 
como jugadores normales que eran antes ahora como quien dice te tengo en la mira y te are la vida imposible aqui muaajaja algo siniestro por sierto muy malvadillo eso y no hablo de mi queridisimo rafael que es par mi un elegante contrincante buen jugador fue buen publisista y no dio probl como mod me gusta tenga ese rango ups creo que los demas se enfadaran pero por favor escondanse si no les tomare pic o videito para que vean mi paro cardiaco y mas que todo en la noche sinistra uyyy da meyo eso e.e pero me diviert por lo menos que digan que van empaz y que no le aran daño a uno u.u

**Comment by RandyNotaLokaa** [comment]
Este no sabe con que cuenta comentar jajajaj, tu tomastes fotos de lo del PB con Alucard (Vampirez) Por que en ningun momento vi conectado a Erza jajajajaja y igual con las fotos donde sale radaland estabas conectado con Alu ajajja

**Comment by Erzasaulnattajhosvampmarcieriotieshadon** [comment]
aun sigo buscando las ip de vampirez y el listado que segun muchos mith publico que eran cunetas de vampirez tengo entendido que el es neutral y no le encuntro la logica que lo haga y si lo hace es al staff cosas que no es etico desirlo al server como staff que son eso si el lo compartio es para el staff si no es asi porque no lo sigue enviando como msj en el server el adm y sobre todo para que serviria eso? faction es de estrategia

**Comment by Erzasaulnattajhosvampmarcieriotieshadon** [comment]
que risa me das aun crees que soy vampirez ? Genial me encanta eso e.e que tipo mas inteligente tenemos aqui te llevaran los rusos para hacerte jabon JAJAJAJAJAJAJAJAJAJAJAJA uyyy solo a ti se te ocuren unas cosas increibles por eso te amo loco jajajaj por favor mith no dejes que se valla del server me hace reir muchisimo esta bien chingon el randy me agrada mucho ademas le quiero comprar un vip+ por ser tan comico el wey JAJAJAJAJAJAJAJ

**Comment by infinityfairylolbleachorigenislacamilo** [comment]
Buenas, pasé por aquí y vi este interesante reporte donde se habla de esos sustitos que dan los nuevos mods... Con la diferencia que a mi solo un espectro me ha salido D: 
A continuación aquí tenemos el espectro:
![2016-05-23_03 12 20](https://cloud.githubusercontent.com/assets/19601397/15596063/de44212c-2389-11e6-98db-a41c9bc0d21d.png)

**Comment by infinityfairylolbleachorigenislacamilo** [comment]
Segundo sustito, el tercero y me muero. Le dije hola para ver si no era hostil, o tal vez un bug de imagen, pero no, se me evaporó en el aire
![2016-05-23_03 12 29](https://cloud.githubusercontent.com/assets/19601397/15596171/dd61ee64-238a-11e6-94f5-75917fb54959.png)

**Comment by MithrandirCraft** [comment]
Borrados diversos comentarios impertinentes*
Eliminado spam de imagenes*
Si vuelvo a ver a alguien comentando aquí algo fuera de tono, será expulsado.

Estáis montando un buen espectáculo, esto me deja bastante claro que no sabéis comportaros.
Me gustaría recordaros que esto no es un foro, sino un sistema de reportes serios.
Esto no es un lugar para que os montéis batallitas verbales, haced el favor de concienciaros con lo que os he dicho en el segundo parrafo si os encontrais en una situación como esta de nuevo, aprended a comportaros como humanos ejemplares.

Finalmente os recuerdo que leer la normativa es obligatorio. La normativa actual exige un castigo ante el lenguaje inadecuado o fensas hacia otros miembros de esta comunidad. Sin embargo, consideramos que romper esta norma constituye una infracción de grado C (Leve), por lo que a no ser de que se trate de una situación grave y reiterada, no se aplicará ninguna acción.

Tened en cuenta también que cualquier persona implicada que fomente el mal ambiente en cualquier grado, ya sea contestando o simplemente haciendo caso de la situación, podrá verse también implicada en el castigo. Me dan completamente igual los "Ha empezado él" al mas puro estilo crío.

Si alguien desea añadir algo más, lo hará con diligencia, respeto y formalidad. Voy a borrar todos los mensajes que se limiten a crear mal ambiente en este ticket.
