### ISSUE TITLE
Calibraje Anticheat (Comenta aquí tus falsos positivos, ¿Kick automatico injusto?)

### ISSUE THREAD

**Issue by MithrandirCraft** [MithrandirCraft/MithrandirCraft#249]
Abro este ticket para que los jugadores anoten situaciones en las que han sido kickeados injustamente por el sistema anticheat.

Se analizarán estas situaciones, y se calibrará el sistema para que se produzcan con la mínima frecuencia posible.

**Comment by jezzM** [comment]
Hola queria informar sobre un fallo lo que sucede es lo siguiente, en mi faction tenemos bloques de slime para bajar de un piso a otro entonces cuando me dejo caer automaticamente me bota del server y a las tres veces me bannea y dice que uso spider hack

**Comment by MithrandirCraft** [comment]
@jezzM Estoy en ello.

**Comment by Vegepapa** [comment]
soy vegepapa  a mi marco kill aura cuando mataba gallinas y spider. 

puedo someterme a revisión.
