### ISSUE TITLE
Tiempo de duración en el desbaneo

### ISSUE THREAD

**Issue by iCrazyMadafaka** [MithrandirCraft/MithrandirCraft#25]
Hola Mithrandir, me he fijado y recorde que yo tenia 1 mes de baneo con la cuenta de iCrazyMadafaka, hoy he visto que me quedaban 2 semanas (2 weeks) cuando quiero entrar al server con la cuenta baneada (iCrazyMadafaka), cuando me conecte con PvP4ever (otra cuenta mía creada hace poco solo para sustituir a iCrazyMadafaka) puse /Seen iCrazyMadafaka me sale que estoy desconectado en 27 días y algo mas, entonces, se puede ver ha simple vista que si llego al 1 mes de baneo no me desbanean, si no que tengo que esperar 1 semana mas, aquí doy los cálculos xD :         
1 mes = 31 dias
Tiempo de desconectado = 27 días
Tiempo de ban = 1 mes (31 días)
Tiempo de ban (Lo que me falta) = 2 semanas
31 (dias de ban) - 27 (dias de desconectado) = 4 dias (lo que duraría mi desbaneo)
Pero 2 semanas son 14 días no 4, aquí, dejo dos fotos del tiempo de desbaneo y mi /seen (tiempo de desconexión)
![captura de pantalla 2015-01-24 a la s 10 44 47](https://cloud.githubusercontent.com/assets/9981163/5886941/b72956ec-a3b6-11e4-839b-29ef6ba573ab.png)
![captura de pantalla 2015-01-24 a la s 10 45 31](https://cloud.githubusercontent.com/assets/9981163/5886946/ed4884d2-a3b6-11e4-85f5-e16774f370b4.png)

**Comment by iCrazyMadafaka** [comment]
![captura de pantalla 2015-01-24 a la s 10 45 31](https://cloud.githubusercontent.com/assets/9981163/5886944/d585ce54-a3b6-11e4-9f36-7546f4f7c32f.png)
Lo siento, pero la siguiente foto que puse no iva entonces puse este otra vez haha

**Comment by MithrandirCraft** [comment]
Hola.
Los siguientes datos pueden comprobarse mediante el comando /bh check JUGADOR

El nombre iCrazyMadafaka fue expulsado por uso de texturas transparentes / xrays.
La expulsión tiene una duración de: 1 mes, 1 semana, 2 días, 13 horas, 30 minutos, 56 segundos y 170 milisegundos.
Dicha expulsión termina en 2 semanas.
iCrazyMadafaka fue avistado por última vez hace 27 días (momento en el cuál se encontraba conectado)

Al no tener claro el tiempo real de expulsión, és normal que no te parezcan correctas las 2 semanas restantes.

Si tienes algo más que añadir, reabre este ticket.
