### ISSUE TITLE
Problemas a miles :/

### ISSUE THREAD

**Issue by NosophorosVampire** [MithrandirCraft/MithrandirCraft#250]
Hola Mith ..
paso a reportar que hay problemas en el server

-te caes cuando haces una columna para ir subiendo, volvio ese problema y no conforme con eso, a veces te quedas trabado y mueres x asfixia :O es realmente fastidioso :/.

-al ir corriendo en cualquier lugar cuando subes un bloque de alguna montaña o algo, a veces te quedas atrapado y mueres x asfixia :O perdi cosas valiosas que nunca pude encontrar de vuelta :/.

-cuando tomas tu caballo y sales a explorar, puedes avanzar mucho, correr biomas enteros y de un momento a otro en cualquier lugar te devuelve 1 o 2 biomas atras :O, es como si tuvieras un tiempo para cabalgar y si lo sobrepasas te vuelve a otro punto al azar .. pasa bien seguido este problema.

-si estas montado en tu caballo y x alguna razon te bota el server, sea tu internet que mando error o cualquier cosa, el caballo ya no lo ves mas, desaparece y con el, la montura y la armadura, e perdido  varias veces a mis caballos :/

-al encontrar un perro o gato te vas con tp para llevarlo a casa y se queda sentado en el lugar donde te fuiste con tp :/ antes no pasaba eso, se iba contigo :/.

creo que eso son los mas notables sobre todo hacer columnas ya que es imposible construir y jugar  de manera fluida es frustrante la verdad.

yo juego SURVIVAL todo el reporte es referente a este mundo, no se si en FAC pasa lo mismo.

gracias x tu tiempo y ojala puedas arreglarlo.

gracias !

**Comment by NosophorosVampire** [comment]
PD: todo esto comenzo desde la ultima actualizacion a 1.9.4 .

**Comment by MithrandirCraft** [comment]
Esto debería estar arreglado mañana las 13:00h

**Comment by MithrandirCraft** [comment]
Porfavor, confirma que problemas se han solucionado ya.
