### ISSUE TITLE
Problema en el pueblo

### ISSUE THREAD

**Issue by Natta19** [MithrandirCraft/MithrandirCraft#251]
En warp pueblo desapareció un chunk entero (si no me equivoco). Pense que era problema mio al cargar, hasta que me caí al vacío xD. Creo que igual lo veras mith, pero avisar no esta de mas.
Saludos Natta.

**Comment by Natta19** [comment]
![image](https://cloud.githubusercontent.com/assets/19634817/15633735/320a1ef8-258b-11e6-8bae-3a8755afefb5.png)

**Comment by JhosxBlack** [comment]
aqui una foto de el pedazo de pueblo que falta xD 
![2016-05-29_09 49 43](https://cloud.githubusercontent.com/assets/18745300/15633745/bcabeb3e-257e-11e6-8863-e0183d5ab53a.png)

**Comment by MithrandirCraft** [comment]
Arreglado.
