### ISSUE TITLE
Pregunta sobre problema de nuestras skin

### ISSUE THREAD

**Issue by NosophorosVampire** [MithrandirCraft/MithrandirCraft#252]
Hola mith.
te explico, nuestras skin son como nuestra cara visible todos ya nos conocemos x las que usamos
pasa, que ya me a pasado 2 veces que de un momento a otro ya no puedo usarlas mas, primero me paso que al poner el nombre que use siempre me sale la skin predeterminada de que trae el minecraft, y ahora la siguiente que elegi que ya llevaba meses usando, al poner el nombre me sale otra skin bien horrible :/ 
abra alguna forma de arreglar esto? 

gracias x tu tiempo :D

**Comment by MithrandirCraft** [comment]
He purgado la base de datos de skins por si hay algun problema con las últimas versiones del restaurador. Ten en cuenta que los servidores offline normalmente muestran las skins de los jugadores, pero nuestro servidor es una excepción.

Nadie más me ha comentado ningún problema de este tipo... tienes pinta de estar seleccionando nombres cuya skin debe ser precisamente una skin por defecto. Lo has probado con muchos nombres?

En cualquier caso, vuelvelo a intentar y prueba nombres mas diversos. Confirma que la skin que intentas usar realmente utiliza una skin premium customizada.

**Comment by NosophorosVampire** [comment]
okey entiendo, si puedo usar otras skins... solo era el problema con la que usaba hace meses el nombre ya no sirve, tendre que elegir otra mas nada :/

gracias x la respuesta :+1:
