### ISSUE TITLE
Falla de Fortaleza en el end, 

### ISSUE THREAD

**Issue by VampAlucard** [MithrandirCraft/MithrandirCraft#253]
Buenas tardes
Comunico que el barco de la Forteleza esta fuera del limite... 
![2016-05-30_02 54 08](https://cloud.githubusercontent.com/assets/14955811/15640937/7b049dc6-2613-11e6-876a-44d29c83646c.png)

espero que puedan arreglarlo... 

Mys Saludos.....

**Comment by MithrandirCraft** [comment]
Soy plenamente consciente de ello.

Es lo que hay. Imagino que queréis las elytras, de momento tendréis que esperar para poder conseguirlas.
