### ISSUE TITLE
problemas con spawners y golem arcano

### ISSUE THREAD

**Issue by Vegepapa** [MithrandirCraft/MithrandirCraft#254]
No se si soy el único pero el dia de hoy.

Los spawners  otra vez dejaron de darme mobs.

**(Procura ser mas detallado a la hora de reportar.)** - Mith

**Comment by MithrandirCraft** [comment]
1 Ticket para cada reporte porfavor.

Golem arcano funciona perfectamente. Si notais que un ataque no le hace efecto, puede ser por algún motivo, procura documentarte en el catalogo de jefes.
(Borrando comentario sobre el golem.)

En cuanto a los spawners, estoy al coriente de que hay muchos mas reportes de lo habitual indicando fallos... La verdad es que no tengo ni idea de que podría estar causandolo, dejaré este ticket abierto, pero no prometo una solución rápida.

**Comment by MithrandirCraft** [comment]
Hola. Sigues teniendo problemas con tus spawners?
