### ISSUE TITLE
Reasignación de inventarios al cambiar de grupo de inventarios (Survival <> Factions)

### ISSUE THREAD

**Issue by MithrandirCraft** [MithrandirCraft/MithrandirCraft#255]
De forma aleatoria, los inventarios de survival y factions se intercambian y o sobreescriben.
Esto no se produce continuamente al cambiar de mundo, sino con un pequeño porcentaje de posibilidad.

**Comment by Blasfemia** [comment]
me paso recien despues de este ultimo reinicio x el problema de los spawner, puse el log out como aconsejaste y al volver mas tarde no tenia mis cosas chetadas, tenia arena vidrio y 3 troncos :/ ... 
no puede ser.

**Comment by MithrandirCraft** [comment]
Porfavor reporta tu perdida aquí https://github.com/MithrandirCraft/MithrandirCraft/issues/174
Asegurate de seguir la pauta.

**Comment by MithrandirCraft** [comment]
APARCADO
