### ISSUE TITLE
No Sale el jefe El Purgador

### ISSUE THREAD

**Issue by FearMagix** [MithrandirCraft/MithrandirCraft#257]
Quiero ser Cura y al momento que quiero ir a matar al el Purgador no aparece Pasan minutos y aun no aparece y e esperado dos dias y sigue en lo mismo espero puedan leer el mensaje y me ayuden con este problema

**Comment by MithrandirCraft** [comment]
![screenshot_1](https://cloud.githubusercontent.com/assets/6623704/15981942/164be466-2f7d-11e6-8e67-dc2d0e242ae1.png)
Sigue intentandolo.
