### ISSUE TITLE
Balance de PvP en 1.9

### ISSUE THREAD

**Issue by MithrandirCraft** [MithrandirCraft/MithrandirCraft#258]
Saludos. Lean detenidamente y con atención lo que les tengo que decir, antes de realizar un comantario en este ticket.

Soy plenamente consciente de que a mucha gente le ha disgustado la actualización del sistema de PvP a 1.9. 
(Tengo entendido que solo es el pvp, y que todo lo demás no interviene en el drama de la 1.9)

Vean también este asunto sobre balance en Factions: https://github.com/MithrandirCraft/MithrandirCraft/issues/186

Doy por avanzado que el pvp no será downgradeado al de 1.8 por completo, de forma exacta. Sin embargo si estamos dispuestos a "Crear nuestro propio pvp, posiblemente a gusto de todos"

Por ejemplo, se que todos los usarios que odian el pvp de 1.9 están muy descontentos con la regeneración de la comida (Exagerada), y el ritmo que da al pvp el hecho de tener un cooldown en las espadas de 20 ticks.

Se también que a algunos usuarios no les desagrada el PvP de 1.9 (O algunos de sus aspectos), o no les importa en absoluto. (Porque viven felices en Survival).

Es por ello que abro este ticket para debatir un rebalance del PvP en MithrandirCraft. Me gustaría saber exactamente que funciones os desagradan del pvp en 1.9, y se proponga un rebalance alternativo que no se limite a "regresar a 1.8" (Lo cuál sería muy dificultoso y muy negativo para el servidor, considerando que ya se encuentra en un estado tan actualizado.)

**Feedback de funciones desagradables hasta ahora:**
- El cooldown con las espadas
- La regeneración de vida exagerada por saturación, con cualquier comida, que difuculta la finalización de un PvP (Se reduce a destruir la armadura del oponente).

**Ajustes en progreso:**

- Espadas 0 cooldown fáciles de obtener o intercambiar por espadas con cooldown.

- Creación de diversas tiers de espadas que podréis obtener intercambiando en /warp pueblo. Estas espadas tendrán atributos distintos que permitirán al jugador jugar como desee. (Con cooldown o sin cooldown.) El balance en este aspecto es complicado, por lo que va a tomar un tiempo en completarse esta medida, y además no garantizo que sea satisfactorio para todos. Creo que contra mas se medite este balance, mejores resultados puede dar.

**Ajustes aplicados:** (A todos los mundos)
- Retirada regeneración por saturación al comer.
- Regeneración automatica periodica en cualquier circunstancia. (Medio corazón)
- Rebalance de espadas y hachas.

------------------------
Para los resignados que siguen insistiendo con "regresar el servidor 1 o 2 versiones atrás":

El futuro de MithrandirCraft reside en las actualizaciones. Podemos trabajar en mejorar lo que os desagrade de las versiones más actuales, pero no regresar. Realizar esta acción sería muy negativo para el aspecto interno y técnico del servidor (Hasta puntos que no podéis imaginar). Por lo tanto puedo confirmaros que uno o varios descensos de versión del servidor no no van a ocurrir.

MithrandirCraft no és una network. Algunas networks grandes pueden permitirse disponer de servidores tanto 1.8 como 1.9, sin embargo el futuro de un servidor como el nuestro, libre de bugs, debe pasar por realizar actualizaciones tando de MC Vanilla como todos sus componentes.

Como ya he dicho, solo estamos dispuestos a debatir los aspectos que os parezcan negativos sobre la versión actual, y trabajar en ellos. (No veo porque no debería ser suficiente.)

------------------------
Algo que añadir? Hacedmelo saber y lo hablamos.

**Comment by krazlas1** [comment]
Sí. Tienes toda la razón en cuanto a lo del CoolDown de las espadas y la regeneración obscena.

Hay otro punto que se deberia tener en cuenta, y es que se ha reducido el incremento de fuerza de las pociones de fuerza I y II, tambien el daño de las espadas ha bajado, y esto también incomoda a la hora de hacer un pvp o un pve (Antes el daño de una espada con Sharpness V y Strenght II podia asesinar a cualquier mob común, ahora se necesita de 2 espadazos cargados al máximo, y esto ralentiza mucho a la hora de farmear, o un encuentro inesperado con una oleada de mobs que vengan en todas direcciones (Hola CuevaCubo).

Y bueno, espero que mi aporte contribuya de alguna manera con lo planteado en el ticket n_n.

Saludos.

**Comment by MithrandirCraft** [comment]
@krazlas1 Lo que dices lo pondré a prueba. Pero intenta contrastarlo con el echo de que la regeneración ya no es tan exagerada. De hecho no funciona ya ni con manzanas de oro, pero si con Manzanas OP. (Que no son obtenibles, pero algunos las tienen.)

**Comment by krazlas1** [comment]
¡Me había olvidado por completo de las manzanas!
Se deberían poder obtener, ya que si la regeneración va a ser nerfeada, se necesitará un sustento como el de las Appleblock. Propongo que se puedan obtener mediante esmeraldas en el Crescent Ville. En tal caso que se puedan obtener creo que la regeneración proporcionada por la manzana op debería ser un poco mas fuerte, para que tenga un mayor contraste que el de una pocion de regeneración II.

**Comment by MithrandirCraft** [comment]
@krazlas1 Podrán conseguirse.

**Comment by MithrandirCraft** [comment]
Sin embargo, estoy valorando no aplicar las manzanas OP, creo que balancea mucho mas el pvp no disponer de ellas. Porque creo esto?:

- Los jugadores ya disponen de pociones de regeneración.
- Las manzanas OP otorgan una saturación muy elevada de corazones. (Esto desbalancea muy evidentemente el pvp)
- El combo de regeneración + saturación es inequiparable.

**Comment by ZertahhLoL** [comment]
Entonces,si las quitan,¿las van a eliminar de todo el juego no?.Porque algunas facciones las tienen de versiones anteriores.

**Comment by xXandrescolXx** [comment]
Pensando como mejorar el PVP se me acaba de ocurrir una idea. Tomar el daño hecho por el numero de golpes promedio que se podian pegar en la 1.8 en el tiempo del coldown, y asignarle ese daño a un solo golpe de la 1.9, de tal forma que el mismo daño que se hacia en la 1.8 sea el mismo daño de la 1.9 durante el coldown

**Comment by MithrandirCraft** [comment]
@xXandrescolXx Esto ya me lo comentaste internamente? Me suena mucho haberlo leído. Es una buena idea como base para los calculos de relación daño/cooldown/atributos que tengo previstos para nuestro sistema custom de PvP, a gusto de todos.

**Comment by MithrandirCraft** [comment]
Considero concluido el tema de balance de pvp. Si alguien desea añadir algo mas, puede intentar abrir este ticket. Sin embargo trabajo adicional futuro en el balance de PvP será debatido internamente.
