### ISSUE TITLE
Creación de un servidor de Team Speak 3 para el servidor.

### ISSUE THREAD

**Issue by Gambacha** [MithrandirCraft/MithrandirCraft#259]
Buenas tardes a tod@s!

Me parece una buena idea crear un servidor de Team Speak 3 para que todos podamos hablar con amigos o miembros de nuestra facción por voz. Comentad que os parecería la idea, y a lo mejor Mith puede llevarla a cabo (que no lo sé xD)

Saludos :D

**Comment by MithrandirCraft** [comment]
Hola. Ya creamos un servidor de TS hace meses, estuvo más de 3 meses abierto, plenamente anunciado en el indice de nuestra página web, en la página de FB, y en mensajes automaticos dentro del servidor.

La participación fue muy cercana a nula.

Por no hablar de que hostear salas profesionalmente puede llevar o dinero, o contactos. Si conoces a alguien que disponga de espacio libre en su servidor y no le importe dejarnoslo, por mi parte no me importaría dirigir a los jugadores allí.

Si es así, hazmelo saber.

**Comment by Gambacha** [comment]
Hola Mith, si la actividad fue nula no creo que merezca la pena entonces, aun así puedo hablarlo con un amigo que tiene un servidor a ver si puede hacer algo.
Saludos :D
