### ISSUE TITLE
Han entrado con el nombre de mi cuenta (Premium)

### ISSUE THREAD

**Issue by SrSnowyDuck** [MithrandirCraft/MithrandirCraft#260]
Al parecer, cuando entro al servidor, en vez de aparecer el comando /register, me aparece el de /login, y nunca me he registrado. Mi nombre es SrSnowyDuck, si podéis hacer algo, por favor responded.

**Comment by MithrandirCraft** [comment]
Siento que te hayan quitado el nombre.

En esta ocasión no puedo hacer nada para ayudarte. Alguien se ha llevado ese nombre en nuestro servidor antes que tu. Sin embargo, te hago saber que el uso de nombre premium tan solo trae ventajas a la hora de votar (Algunas páginas no te dejan votar si no eres premium, y eso esta fuera de nuestro control).

No puedo ayudarte porque la cuenta que mencionas es activa y tiene recursos recientes dentro del juego. Normalmente si lo haría si la cuenta fuese extremadamente inactiva.
