### ISSUE TITLE
Reporte a el moderador "Radiostaus" (by Zertahh)

### ISSUE THREAD

**Issue by ZertahhLoL** [MithrandirCraft/MithrandirCraft#261]
Hola,soy un jugador de Mithrandircraft (Zertahh) y tengo un par de quejas con pruebas en contra del moderador "Radiostaus".

Bueno,esto es una larga historia...

Todo empezo cuando el estaba en mi facción y quite una construcción que el habia hecho,entonces,se salió y creo una nueva facción,también me puso "Enemigo".Hasta ahi todo legal.

Un día,el entró en mi facción y yo como cualquier "Enemigo" lo mate,y ahí empezaron los problemas...Comenzó "Spameandome" el chat por /msg.
![spam 1](https://cloud.githubusercontent.com/assets/20175690/16398996/250cf730-3ca5-11e6-9537-ebf1624b930f.png)
Luego de eso,unos minutos despúes,publicó mi información personal...
![informacion personal 1](https://cloud.githubusercontent.com/assets/20175690/16399036/784ee9e4-3ca5-11e6-8023-b9218326bc2c.png)

Me insultó por otros medios,esto fue cuando yo le avise a Mithrandircraft que me estaba spameando... 
![insultos 1](https://cloud.githubusercontent.com/assets/20175690/16399273/65337a12-3ca7-11e6-9396-c0db6be3dd7d.png)

Hoy, 27/06/2016 ,Vino a atacarme a mi facción,como mi equipo salió victorioso,me kickeo sin razon y con la excusa de "Estaba probando si funcionaba".
![kickeo sin razon 1](https://cloud.githubusercontent.com/assets/20175690/16399102/ece15eae-3ca5-11e6-879a-0ac56ebf4a17.png)

También me falto el respeto reiteradas veces,las cuales tengo poca evidencia,pero creo que es suficiente porque no deberia suceder ni una vez.
![falta de respeto 1](https://cloud.githubusercontent.com/assets/20175690/16399130/24792ea0-3ca6-11e6-9ce6-06081e6e5227.png)

También,muteo a mi aliado y a mi por 1 hora,sin razon aparente mas que mi comentario "Negro Cagón",pero mi aliado no tenia culpa.

Por otro lado,intento negociar conmigo sobre el mute injusto de mi aliado xXK9TrooperXx  y me volvió a faltar el respeto...
![intento de negociacion](https://cloud.githubusercontent.com/assets/20175690/16399218/ceff95a8-3ca6-11e6-91b2-20fc27153bae.png)
![falta de respeto 2](https://cloud.githubusercontent.com/assets/20175690/16399227/deb95326-3ca6-11e6-9d4f-0a24dbc72498.png)

Espero sea rapidamente solucionado el caso.
Gracias por su atención.
Zertahh

**Comment by ZertahhLoL** [comment]
El reporte fue editado para ocultar la cuenta de skype de el moderador.

**Comment by radiostaus** [comment]
losiento zertahh no devi comportarme asi yo teamo en el fonndo de mi coraxzon eres lo mejor guapo :3

**Comment by MithrandirCraft** [comment]
Muchas gracias por reportar esto.

He analizado la situación que reportas, y he llegado a la conclusión de que ciertamente ha habido un problema de comportamiento y falta de responsabilidad por parte del moderador.

Consecuentemente he hablado con él, y ha tomado la propia decisión de abandonar el equipo. Una decisión que considero adecuada para un staff que no se comporta en adecuación con la normativa de moderación.

De nuevo, gracias por indicarnos esto, y desde el equipo pedimos disculpas por cualquier problema que te haya causado este staff.

**Comment by radiostaus** [comment]
deje dde hablar tanta mierda hpt que uted  me   volvio a meter me iso pedir disculpas para sacarme  gas que asco me das

**Comment by MithrandirCraft** [comment]
@radiostaus Muy impertinente ese comentario Radiostaus, eso termina de dejarme claro que debo vigilar mas a quien selecciono.

Dejas bien clara tu verdadera faceta.

**Comment by ZertahhLoL** [comment]
Muchas gracias Mithrandir por estar al tanto ^_^ .
