### ISSUE TITLE
Propuesta de Reinicio de factions (Intervención libre)

### ISSUE THREAD

**Issue by xXandrescolXx** [MithrandirCraft/MithrandirCraft#263]
Buenas Tardes

Me gustaría proponer que se reinicie factions ya no hay un buen balance en las facs. No hay facs que tengan los suficientes recursos como para protegerse o para petar las facs mas chetas. Para mayor balance en ese aspecto propongo que se reinicie factions.

Gracias

**Comment by Gambacha** [comment]
Hola a tod@s!

Pues yo no estoy de acuerdo, porque tengo cosas y estoy bien, no tengo porque perderlo todo. Si os aburrís porque no tenéis rival es tan simple como tirarlo todo (o casi todo) y volver a empezar por vuestra cuenta. Hay que pensar en los jugadores que no están tan avanzados, pero que tampoco son "noobs" (como yo). Esos jugadores no querrán perder todo lo que tengan.
Esta es mi opinión xD

Saludos :D

**Comment by ZertahhLoL** [comment]
Hola,mi nickname es Zertahh.

Yo opino que sería todo mas agradable,pero tiene varios inconvenientes por parte de ambos lados,los que si quieren y los que no.

Por un lado,siempre entraría gente nueva,por lo tanto ¿deberían reiniciar el servidor cada cierto tiempo? opino que eso hace perder mas users que lo normal,a pesar de que estoy a favor del reinicio.

Además aunque se reinicie creo que hay dos opciones,si no se reinicia,seguirá habiendo desventajas,pero las facciones buenas...tarde o temprano llegarán a ser grandes...Por otro lado,si se reinicia,los únicos cambios que puede haber es que jugadores buenos,sean colocados y trabajen con otros también con experiencia en todos esto,pero los que no entienden no crecerán se reinicie o no el servidor.

mi opinión todavía no estoy seguro,pero no creo que ninguna de las dos opciones sea la solución,estoy mas del lado que las facciones,desde un punto sufran mas riesgos,como por ejemplo.A partir de mantener 10 jugadores activos la facción dirá sus coordenadas al escribir el comando /f show,o cuando obtengan mucho de un material,como diamantes,armaduras encantadas o eso,que sus cofres dejen de tener la protección y cualquiera pueda abrirlos...De esta manera solucionaríamos también varios problemas de gente que le gustaría que los cofres puedan abrirse,por ejemplo.

**Comment by MithrandirCraft** [comment]
@ZertahhLoL Interesantes argumentos. Los tendré en cuenta.

En cuanto a la propuesta de reinicio. Lo cierto es que me decantaría por lo que la mayoría de los jugadores deseen. Aunque yo soy defensor de ausencias de reinicios y trabajar en balancear el juego.

Sin embargo, debéis tener en cuenta que la política del servidor defiende la ausencia de reinicios.

Si es cierto que en el último año se han producido algunos incidentes que nos han obligado a reiniciar diversos aspectos del servidor. (No había alternativa) No és algo de lo que esté contento, y lo considero un fracaso para el servidor, que no debería repetirse de forma indeseada de nuevo.

Como me gusta tanto hablar de balance, os dejo los aspectos en los que creo que debo trabajar para mejorar la situación que describe andrés, y ya he debatido internamente:

- Dar herramientas a novatos para que se desarrollen
- Asegurar que puedan esconderse eficientemente sin que les encuentren en 24h
- Asegurar que las facciones grandes no sean invulnerables.

También os recuerdo que hay un tema abierto sobre balance en factions: https://github.com/MithrandirCraft/MithrandirCraft/issues/186, y balance en PvP: https://github.com/MithrandirCraft/MithrandirCraft/issues/258

**Comment by unicorn4771** [comment]
No estoy de acuerdo, hay otras maneras de conseguir un balance en factions.
Bien dice Mith, dar herramientas a los nuevos y asegurar que las facciones grandes no sean invulnerables es una buena opción. Claro en un reinicio todos empezarían desde cero pero tienes que tomar en cuenta que siempre entraran personas nuevas, y que llegara un momento en el que tu fac o cualquier otra crecerá y la de otros no. Entonces cuando te des cuenta que no hay facs con suficiente poder o que se encuentren al mismo nivel que la tuya con tantos recursos, de nuevo vas a sugerir otro reinicio?.
Sera un circulo vicioso, siempre te encontraras con factions que estén iniciando, que no poseen los mismos recursos ni el mismo poder que la tuya, llegara un punto en que como dice @ZertahhLoL se debería reiniciar el servidor cada cierto tiempo.
A mi parecer no es algo que este afectando al server, hay otras cosas por resolver y lo ideal es buscar lo que es mejor para el server y para sus jugadores, en este caso solo no piensas en ello.

**Comment by Nepo23** [comment]
No estoy de acuerdo, primero porque reiniciar factions no ayuda en nada, ya se a reiniciado faccion anteriormente y que ha ocurrido? nada. El unico motivo por el que proponen esto es porque estan aburridos y quieren construir de nuevo probar otro metodo de proteccion o ideas de construcciones diferentes por lo que les invito a ir a survival y construir sus cosas.
No veo y no ha ocurrido nada que mejore a faccion con reiniciar el mapa.
Me han pasado 3 reinicios de mapas y siempre es lo mismo.. Usar un metodo muchas veces no cambia el resultado.

**Comment by MithrandirCraft** [comment]
Propuesta denegada.
