### ISSUE TITLE
[BUG] Dejar de quemarse.

### ISSUE THREAD

**Issue by ZertahhLoL** [MithrandirCraft/MithrandirCraft#264]
El otro día,estaba por morir quemado,por lo tanto me desconecte (no se exactamente porque,pero fue un movimiento reflejo de apretar ESC y salir del juego),cuando vuelvo a conectarme me deje de quemar y por encima mientras me logueaba se me regeneraron algunos corazones...

**Comment by MithrandirCraft** [comment]
Me temo que no puedo arreglar esto. Podeis aprovecharlo tanto como considereis.
