### ISSUE TITLE
Pierdo mi inventario -_- :/

### ISSUE THREAD

**Issue by vegetagamer9** [MithrandirCraft/MithrandirCraft#265]
Hoy a las 18:00 Hora española he perdido mi inventario con mi p4 y mi espada y arco que mas uso,
Quisiera que me las devuelvan mi nombre de usuario es TheShadowWither
Ha pasado de esta forma, estaba afk esperando a que los zombies se respawnearan para matarlos, me mato un zombie escalatra recogi mis cosas y mate al zombie escalatra 
me vuelvo  a poner afk me voy a yt a pasar el rato entro aver si se han respawneado unos cuantos mas y PUM piero mi inv 
Datos:
Mi espada era Filo V igneo II Irrom III Empuje II Saqueo III Se llamaba: Mythi la princesa de mis sueños
Mi arco era Power V Fuego I Irrom 3 Retroceso II Infinidad Se llamaba: AsgardForEver
Mi p4
Casco: Protecc 4 irrom 3 respiracion 3 afinidad acuatica 3
Peto Irrom 3 Protecc 4
Pantalon Irrom 3 Protecc 4 Reparacion 1 
Botas  protecc4 irrom 3  Paso Helado 2

**Comment by Vegepapa** [comment]
K  tal theshadow.... tienes alguna forma de comprobar  todo lo k has perdido???

**Comment by vegetagamer9** [comment]
La verdad esque no pero no tenía sentido mentir yo quiero hacer que el server sea famoso, como el cube pero si todos reportamos constructivamente podremos cumplir eso

**Comment by vegetagamer9** [comment]
me darian las cosas?

**Comment by MithrandirCraft** [comment]
Cambiaste de mundo en algún momento? No tiene mucho sentido que pierdas tus cosas al desloguear sin cambiar de mundo. Existen algunos problemas de perdida de inventario al pasar de Survival a Factions, aunque son muy singulares.

He estado creando logs de debugging durante todo el mes pasado, esperando que a alguien le ocurriese a algo con su inventario, hace 2 días desactivé estos logs por temor a que estuviesen saturando de datos la memoria en disco del servidor (Infundamentado, y no era así.) 
Justo apareces ahora reportando un error que a penas puedo rastrear... Mala suerte para mith supongo.

Otra cuestión, este no es el lugar indicado para reportar tu suceso. Te estás cogiendo un habito de no leer si ya hay algún tema abierto donde colocar tu reporte.

Vuelve a abrir tu reporte allí y lo hablaremos. En cualquier caso estoy investigando este asunto.

**Comment by MithrandirCraft** [comment]
https://github.com/MithrandirCraft/MithrandirCraft/issues/174

**Comment by Blasfemia** [comment]
Nombre de jugador: VampiRe

Mundo en el que perdiste tu inventario:Survival

Motivo del deslogueo: solo me saco el server un kik comun

Hora de deslogueo (Del servidor, en www.mithrandircraft.es): 21:00 APROX le avise de inmediato a Tianna una admin unicornia creo que es.

Hora de relogueo y comprobación de perdidas (Del servidor, en www.mithrandircraft.es): 21:05 APROX

Objetos que has perdido: todo mi inventario armadura de oro encantada (completa) , ticket para abrir tienda (25), herramientas de diamante encantadas (pala, pico,acha),  lo que mas siento es el arco (full) con remiendo y todo :/ lo demas eran posiones y creo que 5 esmeraldas no recuerlo lo demas.. :/ 

Información adicional y detalles: estaba comprando unos ticket a un aldeano en survival, y me boto el server no lei el motivo, solo aprete nuevamente y entre de vuelta.. al logearme, tuve que pagarme en la placa de presion para irme al spawn, me fui a las placas que te mandan a survival y me di cuenta que no tenia absolutamente nada, estaba en cero me sali y volvi a entrar al server y nada a si quede sin mas, es frustrante la verdad.

gracias x tu tiempo

**Comment by Blasfemia** [comment]
ESTO FUE OTRA OCACION, PENSE QUE HABIA ESCRITO EL TICKET EN EL LUGAR CORRECTO AHORA LO PONGO ACA.

NosophorosVampire commented on 10 Jun • edited
Nombre de jugador: VampiRe

Mundo en el que perdiste tu inventario:Survival

Motivo del deslogueo (Voluntario, Kick, Crash, Bug, Reinicio): Reinicio anteponiendo el 
recomendado LOGOUT

Hora de deslogueo (Del servidor, en www.mithrandircraft.es): 20:40 APROX

Hora de relogueo y comprobación de perdidas (Del servidor, en www.mithrandircraft.es): 20:50 APROX

Objetos que has perdido: Armadura de diamante encantada completa, espada, pico, pala, acha diamante encantado todo, y Arco que es lo que mas siento xque estaba encantado al full, lo demas eran posiones varias. en realidad todo estaba con buenos encantos solo que uno no se acuerda al pie de la letra se que entenderas son tantas cosas con 5 o 4 encantos.
es un buen de trabajo pasando en los spawn de mobs horas para levelear y a lo largo que juego en el serer voy obteniendo los encantos buenos tu sabes.

Información adicional y detalles: vale me estaba pendiente del chat todo normal y vi cuando saludaste y todo y avisaste del reinicio, me desloguie como siempre...pasa que al volver no tenia mis cosas que llevaba, pero si estaba en el lugar donde puse el logout, y pregunte si estabas y te conte el problema, tenia mis cosas de hace 1 hora atras mas o menos, lo se xque tenia mi material de construccion que estaba usando con mi armadura de oro x si me caigo a la lava para no perder mis cosas chetadas, antes de acusar algun problema, fui a ver al cofre donde tenia mis cosas y no estaba nada, ni las posiones del cofre de posiones estaban, todo lo que llevaba se perdio sin mas :/

**Comment by MithrandirCraft** [comment]
@Blasfemia Porfavor, reporta en el lugar adecuado y sigue las pautas.
