### ISSUE TITLE
Entidades invisibles (Reporte de Item frames)

### ISSUE THREAD

**Issue by ZertahhLoL** [MithrandirCraft/MithrandirCraft#266]
Hola soy Zertahh.

No sé si será el lugar indicado para esto,pero si no es aquí,no se donde publicarlo.

Tengo un error que no se si sera mi configuración en optifine (aunque ya estuve mirando un poco y estoy casi seguro que no es eso) o que sea el servidor,ya que los cuadros con item no me cargan aveces.Cuando voy a mi faccion es como si desaparecieran y aunque les haga click izquierdo como para quitarlos no ocurre nada,es como si no estuvieran,la única solución que encontré hasta ahora es desconectarme y volverme a conectar pero si cada vez que voy a mi faccion tengo que hacer eso es un poco pesado.

A1

•Por lo que veo y creo solo ocurre cuando descargo los chunks,es decir,me voy muy lejos,ya que cuando voy a mi /f home desde el spawn no ocurre,pero si lo hago desde /warp factions o cualquier otro lugar dentro del mundo factions si ocurre

**Comment by MithrandirCraft** [comment]
Estoy al corriente de que esto ocurre con diversos tipos de entidades. Debería estar arreglado para 1.10.2

**Comment by Blasfemia** [comment]
me a pasado varias veces lo mismo desaparecen los cuadros, tambien los cofres y los caballos. 
te cuento un poco..
tengo muchos caballos con montura y armaduras estaba en mi casa y no los vi a los lejos en sus corrales
me acerque y se escuchaban pero no se veian tuve que reiniciar el minecraft para que salieran.
tambien pasa con los marcos de item no se ven, sabes que estan pero no se ve nada.
tambien pasa que se ve el marco pero no el item.
y x ultimo se borran los cofres y tienes que reiniciar para que salgan nuevamente.

puse lo de los caballos xque es exactamente lo mismo que con las otras cosas, la diferencia es que los caballos emiten ruido las otras cosas como marcos y cofres obviamente no lo hacen, x eso creo que se debe a lo mismo.

**Comment by MithrandirCraft** [comment]
@Blasfemia Sigue ocurriendo?

**Comment by ZertahhLoL** [comment]
@Blasfemia ¿Podés interactuar con los caballos mientras no los ves? eso me ocurre con los item frames.

@MithrandirCraft Y supongo que vos no lo sabes,por eso no esta solucionado (supongo que no,debo comprobarlo),pero el server no cierra mientras lo vea,luego cuando "relogeo",no lo veo y ademas no me deja interactuar con ellos,debe ser algo relacionado con el jugador ya que no creo que el servidor quite los item frames y luego los vuelva a poner de la nada,sin reinicios ni vueltas en el tiempo.

Voy a comprobar si sigue ocurriendo,probablemente edite este comentario u lo elimine :) si es asi...Comentario edición limitada  :D

**Comment by MithrandirCraft** [comment]
Supongo que debería seguir ocurriendo. Todavía no hemos actualizado ni 1 solo componente del servidor. Estamos haciendo tiempo para que los distintos componentes se actualicen y así avanzar a una versión estable.

**Comment by MithrandirCraft** [comment]
Hola, alguien sabe si esto aún se reproduce?

**Comment by MithrandirCraft** [comment]
Lo voy a dar por solucionado entonces. Si se sigue produciendo abran nuevo ticket o reabran este.
