### ISSUE TITLE
Perdí mi enderchest

### ISSUE THREAD

**Issue by vegetagamer9** [MithrandirCraft/MithrandirCraft#267]
Hoy hora española a las 10:00 tenia mi enderchest bien como siempre  Pero a las 11:30  no me dejaba abrirlo despues me fui a hacer cosas personales y entre a las 15:35 y Fui a coger Hierro y oro para reparar  pero vi que mis cosas no estaban primero de todo pregunte a otros jugadores si les habia pasado me dijeron que no 
Usuario: TheShadowWither
Fecha de el  " bug ": 15/7/16-15:35
Motivo: No lo se yo reporto esto porque guarde todas mis cosas en el y por el bien de el servidor que no pase mas :/

**Comment by vegetagamer9** [comment]
Mithrandir

**Comment by MithrandirCraft** [comment]
Deacuerdo, he podido confirmarlo. Eres todo un suertudo. 2 perdidas en menos de 1 semana.

Reestableceré tus cosas, pero estoy pensando en aplicarle un backup a tu cofre. Si realizo esta acción te lo haré saber en el mismo juego. Tendrás que esperar un poco mas.

**Comment by vegetagamer9** [comment]
Ok

**Comment by vegetagamer9** [comment]
Cuanto tiempo, aproxmimadamente

**Comment by MithrandirCraft** [comment]
Lo siento vegeta pero no puedo hacer nada para restablecer tu inventario. Tendré en cuenta el error y miraré de que no se vuelva a producir en el futuro.
