### ISSUE TITLE
Me despido.

### ISSUE THREAD

**Issue by SimplyAcke** [MithrandirCraft/MithrandirCraft#268]
No tengo mucho que añadir, así es, me despido, he pasado buenos y malos momentos en este servidor, un saludo a toda la gente que he conocido aquí. Lo dejaré claro, no le deseo nada malo a nadie pero a la gente que me ha hecho daño directa o indirectamente: iros a freír espárragos.

Cordialmente, Acke.

**Comment by ZertahhLoL** [comment]
Por un momento iba a decirte que elimines el mensaje o te podían banear,pero ahora me acuerdo que te vas del servidor ^_^ .Eliminalo si tenes pensado volver.

**Comment by MithrandirCraft** [comment]
Esto no es un foro Acke :/ Tampoco es un lugar para despedidas.
