### ISSUE TITLE
Problemas con la Daga.

### ISSUE THREAD

**Issue by vegetagamer9** [MithrandirCraft/MithrandirCraft#269]
https://www.youtube.com/watch?v=2vAdYN3XIFg Mi espada de Irrompabilidad 4 esta hecha con libros todos menos la irromp 4 obvio pero no me deja juntarla

**Comment by MithrandirCraft** [comment]
No puedo ayudarte con esto. Sin embargo, me han comentado que quizá estés haciendo algo mal.

El caso de objetos con atributos que no se fusionan correctamente con equipo normal encantado es algo que ya he escuchado con anterioridad.

Si no recuerdo mal, creo que hay un truco especifico para fusionar tus armas, así que sigue intentandolo y pregunta.

**Comment by MithrandirCraft** [comment]
Puedes reabrir este ticket si quieres comentar algo mas.
