### ISSUE TITLE
Anti x-ray

### ISSUE THREAD

**Issue by Ivanovic24** [MithrandirCraft/MithrandirCraft#27]
Hola, algunos usuarios al igual q yo estamos cansados del anti xray q hay ahora en el servidor por que no nos deja picar los minerales despues de un rato de mineria y nos jode tener q dejar cosas q nos pueden interesar y ademas sin tener x-ray, ademas de que dice en 5 minutos y en realidad son como 10 o mas :C. Seria posible q se bajara esto un poco para asi poder picar mas rato :C?

**Comment by MithrandirCraft** [comment]
El sistema limitador lleva aproximadamente un mes, és normal que en su incorporación aún no se encuentre calibrado.
Les pedí a mis moderadores que pusiesen a prueba el sistema limitador, pude comprobar que especialmente los jugadores novatos resultan afectados por el problema, debido a las altas restricciones temporales en jugadores nuevos.

Por otro lado, he comprobado que en ocasiones minas vetas para farmear experiencia. Si haces esto en las capas más bajas, es comprensible que tus puntos de minería disminuyan. Pero si minas en capas superiores a nivel 60, no deberías tener problemas para farmear.

Procuraré calibrar este sistema.

**Comment by Ivanovic24** [comment]
ok gracias

**Comment by MithrandirCraft** [comment]
No me has dicho si haces saltar el limitador con tu metodo de farmeo.

Imagino que lo estás haciendo saltar minando de forma normal, que tecnica utilizas?

**Comment by Ivanovic24** [comment]
imagino q sera por eso xD. 

Mi tecnica se trata de mimar dn Extreme Hills siempre( pienso q es el q tiene mas minerales de todos los biomas , por q siempre q mino ahi encuentro muchas cosas), Pico con fortuna 3, y nose por q, sidmpre q me cruzo con grava o barro giro a la izquierda y a la altura 11.

**Comment by Ivanovic24** [comment]
A veces uso toqe de seda y luego pico las menas en mi fac.
A y si encuentro cuevas grandes en Extreme hills tambien las ago

**Comment by MithrandirCraft** [comment]
Si vas a farmear experiencia con Menas de minerales, procura hacerlo por encima de altura 60.

**Comment by MithrandirCraft** [comment]
Este tema quedará abierto un tiempo, por si alguien más desea comentar sugerencias de recalibración antixray.
