### ISSUE TITLE
Perdida De Inventario ( enderchest )

### ISSUE THREAD

**Issue by vegetagamer9** [MithrandirCraft/MithrandirCraft#270]
Esta tarde eran las 16:05 mas o menos cuanto compré huevos de creditos en la tienda desaparecieron al instante cuando los cambie por esmeraldas, y me desaparecieron a los 20 minutos... eran 1 stax de bloques de esmeraldas solo pido eso :/
Nombre del usuario: Nachox_PvP
Hora De El " Bug " 16:05
Mundo en el que ocurrio factions

**Comment by MithrandirCraft** [comment]
Según la información que me das, interpreto que compraste creditos huevo. Fuiste al centro de comercio donde se ofrecen esmeraldas por créditos, dices que el intercambio no salió bien? Pero eso de los 20 minutos? No entiendo nada, porfavor, expresate mejor.

No me has explicado que tiene que ver el enderchest con esto.

**Comment by MithrandirCraft** [comment]
Cierro esto. Han pasado 3 días y todavía no hay mas detalles.
