### ISSUE TITLE
¿Precio exagerado para Manzanas de Bloque? ¿Inflación en Mithrandircraft?

### ISSUE THREAD

**Issue by krazlas1** [MithrandirCraft/MithrandirCraft#271]
Hola, vengo a comentar sobre algo que me tiene preocupado, y es el precio de las Manzanas de Notch en el /Spawn.
Como todos bien saben las manzanas de Notch fueron nerfeadas muy relevante mente en esta version, reduciéndose a solo poder obtenerlas en Dungeons, cofres generados por el Minecraft vanilla, etc.

Otro nerfeo importante es la regeneración que otorgan a la hora de usarse, sólo es regeneración II, a cambio de esto, otorgan 8 corazones adicionales como efecto de Absorption, estos corazones son vida máxima, por lo tanto una vez que se comienzan a perder no se pueden recuperar a no ser que se coma otra manzana en el momento de que se acabe el efecto. Esto deja mucho que pensar sobre el PvPGapple, el cuál es fundamental en un servidor de facciones. 

Sí, hay otros ''sustitutos'' que pueden remplazar a la Manzana de Notch, como pociones de splash de vida, pero estas no se pueden stackear, por lo tanto se descartan para hacer un pvp de larga duración

Ya con todo esto creo que queda mas que claro que el precio de las Manzanas de Notch está muy elevado. A mi parecer deberían costar solamente los 8 bloques de oro que se necesitaban para craftear anteriormente, y obviamente una manzana roja, o si se desea mas dificultad una manzana de oro, pero creo que un bloque de esmeralda es un precio muy alto para una manzana tan nerfeada :L 

Si nos ponemos a sacar cuentas para hacer un stack de manzanas de bloque se necesitan 576 bloques de Oro, los cuales serian  4 stacks y medios de Esmeraldas. Solo por ahi ya es bastante caro, si sumamos los otros 9 stacks de esmeraldas que se necesitan, es un valor exorbitante difícil de conseguir, 13.5 stacks de Esmeraldas, y para solo poder ser obtenidas por cabezas de Esqueleto/zombie a 3 esmeraldas, y Creeper a 6 esmeraldas, es un valor inimaginable.

Espero que mi opinión sirva de algo, 

Atentamente krazlas.

**Comment by ZertahhLoL** [comment]
Apoyo la opinión de @krazlas1 .

Espero sea buffeada la manzana o que bajen el precio,no tengo nada mas que agregar puesto que ya lo dijo todo el creador del post.

**Comment by MithrandirCraft** [comment]
Bajaré un poco el precio por el lado del bloque de esmeralda.

Fui plenamente consciente a la hora de establecer ese precio. Los factores que condicionan ese precio son muy diversos. Me temo que no puedo expresar porque lo hago con plenitud, pero hay muchos factores que intervienen.
