### ISSUE TITLE
Consulta y Reporte sobre el nuevo "AntiHack" (limitación de minería)

### ISSUE THREAD

**Issue by ZertahhLoL** [MithrandirCraft/MithrandirCraft#272]
Hola Mith,no se como funciona exactamente este "AntiHack" me gustaría que me lo expliquen por favor,o que me digan donde puedo conseguir la información necesaria.

Pero,por lo que se,puedo decirles que las limitaciones de Hierro,Diamante y esmeraldas las veo muy molestas,ya que,en una mina artificial puede ser que no encuentres tanto,pero yo entre en una rabín y no me dejaba minar hierro,con suerte me encontré y piqué 7 menas,algo normal en una rabín ¿o no?

Sobre el diamante,me encontré como 4 menas,un día de suerte hahaha,pero si no recuerdo mal a la mitad de la  3ra mena ya tenia que esperar 6 minutos,y tuve que llamar a un colega para que lo pique por mi.

Por último,la esmeralda,esto no lo justifico mucho,pero que amplíen el limite a 1 o 2 bloques de esmeralda mas,aunque fue un día de suerte y no se encuentra todos los días,es molesto tener que esperar para minar.

(**HABLANDO SIEMPRE DE ENCONTRARSE UNA MINA Y NO HACERLA ARTIFICIALMENTE**).

En resumen,en mi reporte/consulta,quiero decir que los limites de picar minerales están muy "limitados"...Valga la redundancia jaja.

•Con "menas" me refiero a un conjunto de minerales del mismo tipo(4 bloques de hierro,por ejemplo).Para llamar a los minerales individualmente me refiero a ellos como bloques de (mineral).

•Otro error que encontré es que yo,en lo personal,me gusta picar los minerales con toque de seda y luego en mi facción picarlos con Fortuna todos juntos ¿no podré hacerlo mas?

•Por otro lado,debía esperar 1 minuto para poder picar el bloque,pero pasado el minuto (de  --:52 a --:54 fueron 2 por si acaso) seguía sin dejarme...

Efectivamente,conté 5 minutos con cronómetro para picar una mena de diamante,eran los que me faltaban,y al intentar picarlo me dice que me faltan otros 4 minutos...Finalmente,luego de 10 minutos me dejo picar el mineral.

•Es probable que también sea que piqué los diamantes y esmeraldas con fortuna y eso me dio más diamantes que lo normal,por tanto el sistema lo habrá tomado como que pique muchas más menas,aunque lo del hierro sigue en la misma.

Espero sea resuelto pronto,mis saludos,Zertahh.

**Comment by MithrandirCraft** [comment]
Ok, todo esto parece bastante razonable.

Sin embargo, debes comprender que estos limites estan porque son nuestra mejor y mas estable defensa posible contra xrays.

Trabajaremos para balancear los limites y mejorar nuestros metodos de prevención.

**Comment by ZertahhLoL** [comment]
Muchas gracias ^_^. 

Solo aclarar que yo pedía eso,que lo "reworkeen" no que lo quiten.

**Comment by MithrandirCraft** [comment]
@ZertaahLoL también realizaré un vídeo explicativo razonando los beneficios de usar este sistema.

**Comment by ZertahhLoL** [comment]
@MithrandirCraft Agrego el lapizlasuli,no me dejo acabar de picar una mena de 5 que ya me pide esperar 1 minuto,lo demás sigue ocurriendo,luego de 2 menas de diamante de aprox. 5 picadas con fortuna a la 3ra ya me limito,por "1 minuto" que cuando acabo resulto ser "6 minutos".

Supongo todavía que el error esta en que el plugin capta cuantos minerales tienes en el inventario u cuantos obtienes,ya que la lapiz la pique sin fortuna y para dejarme picar solo 3/4 de mena es raro,También puede ser que el plugin se configure no por menas sino por cantidad de mineral como dije antes.

**Comment by TeamLittenFTW** [comment]
hola perdón por molestar, hace unas horas me banearon. yo ya había alcanzado el limite de picar diamantes y estaba con un amigo y dige wow soy muy bueno picando creo que dije eso no me acuerdo, y rafaelox24 me baneo por  dos semanas por favor que hago soy nuevo y no se donde reportar y lo dije acá perdón si me equivoco ah casi me olvidaba me baneo por uso de X-ray

**Comment by TeamLittenFTW** [comment]
y yo no uso hacks

**Comment by MithrandirCraft** [comment]
@TeamLittenFTW reporta esto en la sección de APELACIONES en: www.mithrandircraft.es/foro
