### ISSUE TITLE
Algunos aldeanos no intercambian. (Warp Pueblo)

### ISSUE THREAD

**Issue by ZertahhLoL** [MithrandirCraft/MithrandirCraft#273]
El aldeano que compra las cabezas de araña en /Warp Pueblo a cambio de esmeraldas cuando quieres intercambiar con el y le das el item necesario (en este caso la cabeza de araña) no ocurre nada,ni te desaparece la cabeza ni obtienes tus esmeraldas,solo se coloca la cabeza en el slot de intercambio.

Saludos
Zertahh

**Comment by MithrandirCraft** [comment]
Suelen ser esas cabezas las mas problematicas, pero en general, todas dan problemas.

Estamos arreglando esta situación.

**Comment by ZertahhLoL** [comment]
•También hay problemas para tradear con las cabezas de Enderman

**Comment by MithrandirCraft** [comment]
El problema existe con todas las cabezas del segundo piso del gremio de cabezas.
La cosa es que estas cabezas utilizan valores internos que varían al ser configurados en una tienda y reiniciar el servidor.

**Comment by krazlas1** [comment]
Osea, básicamente cada vez que el servidor se resetea el bug vuelve.

**Comment by ZertahhLoL** [comment]
@krazlas1 Exactamente

@MithrandirCraft El bug ahora también ocurre con el aldeano que ofrece el Zombie Spawner.

Para resumir los aldeanos que yo conozco que funcionan mal son:
•Gremio de cabezas 2do piso.
•Cabeza de Juggernaut. (El que intercambia la Cabeza por otra idéntica)
•Zombie Spawner

**Comment by MithrandirCraft** [comment]
Me gustaría hacerles saber que aún estoy en ello. Este asunto es importante y debe ser resuelto.

**Comment by MithrandirCraft** [comment]
Bien. Andrés se ha encargado de parchear este bug. Seguís teniendo problemas con las cabezas?

Tened en cuenta que solo funcionará el parche con cabezas nuevas obtenidas. Me temo que las antiguas están demasiado bugeadas. Podeis pedir a Tianna16 que os las cambie manualmente si la veis por el servidor.

**Comment by ZertahhLoL** [comment]
Bueno,muchas gracias,al parecer no hay mas problemas,tenía una sola cabeza conseguida recientemente y la intercambie sin problemas,solo que con las que tengo guardadas hace tiempo no se ha podido,le pediré a Tianna en cuanto la vea.
