### ISSUE TITLE
Mino un diamante cada 10 minutos o más.

### ISSUE THREAD

**Issue by pab993** [MithrandirCraft/MithrandirCraft#275]
Pues básicamente es eso, si encuentro un conjunto de diamantes mientras mino, sólo puedo picar uno de ellos y tengo que esperar un tiempo muy grande, a veces me muestra que faltan 7 minutos, vuelvo más tarde y faltan 5 (cuando han pasado más), vuelvo más tarde y faltan 7 otra vez. Me deja minar cuando le da la gana al juego. Me gustaría solucionar esto. Gracias.

**Comment by MithrandirCraft** [comment]
https://github.com/MithrandirCraft/MithrandirCraft/issues/272

Duplicado. Porfavor, comentalo allí. Ten en cuenta que aplicamos este limitador para prevenir abusos. No creo que prefirais un desbalance exagerado de ores.
