### ISSUE TITLE
Mithrandir Contacto Importante. (TRAMPAS)

### ISSUE THREAD

**Issue by ZertahhLoL** [MithrandirCraft/MithrandirCraft#276]
Hola mith,necesito comunicarme con usted por un medio privado,es algo sobre un jugador que utiliza trampas pero las pruebas no son in-game(un video,por ejemplo),por lo que no puedo publicarlo aquí,ya que se daría cuenta que lo saben y no utilizará nada por un tiempo,(**para dejarlo en claro y que no mal interpretes mi post,me refiero a que si por ejemplo,Lucas utiliza hacks y sabe que los staff estan al tanto,no lo utilizará**),y al no ser un hack pvp no puedo demostrarlo con video

Ya se y tengo bien en claro que no debo hacer esto pero **NO** es un reporte con intencion de castigo,sino de estar alerta los staff.

Si bien estas pruebas son completamente editables hasta con paint,solo pido que estén atentos a el.

Seria muy amable de tu parte que me concedas este favor,por el bien del servidor.

Atte: Zertahh

**Comment by Nepo23** [comment]
Enterado se dara el seguimiento correspondiente.

**Comment by MithrandirCraft** [comment]
https://github.com/MithrandirCraft

Sigue las pautas del readme para reportar jugadores porfavor. No contacto con personas por privado, si quieres reportar a alguien y tienes evidencia, debes presentarla con el debido formato para que tomemos acción.

**Comment by ZertahhLoL** [comment]
@MithrandirCraft Ya estaba informado sobre esas pautas,solo que no tengo las pruebas suficientes para que lo castigen,por lo que poner su nombre seria avisarle que los administradores lo miran,pero igual ya no importa.
