### ISSUE TITLE
Trampas de moderadores y hacks, 

### ISSUE THREAD

**Issue by vegetagamer9** [MithrandirCraft/MithrandirCraft#277]
Esta tarde me petaron mi fac, bueno se reconstruye pero lo q mas rabia me da esque me petaron con hacks pusieron tnt SIN permiso y tambien  estaba Rafaelox24 detonando y poniendo tnt con el /vanish
Quisiera que los banearan los usuarios eran kraz1234, xLebet, rafaelox24 y CricketTV aunque no se muestre en el video, estaban petando mi fac ilegalmente https://www.youtube.com/watch?v=kD1rFifuRyI ( video ) 
![2016-08-04_19 00 21](https://cloud.githubusercontent.com/assets/12957778/17412553/a0bb0ad4-5a7d-11e6-8cd5-ee26a591f48c.png)
( screenshot ) de cuando rafa detona a  SPECTRO en mi fac aunque no se vea :/

**Comment by MithrandirCraft** [comment]
Estoy juzgando este caso con el equipo interno.

- Estas seguro de que alguien invisible puso tnt?

**Comment by vegetagamer9** [comment]
No era invisible, era /vanish
Y quiero 2 stax de bloques de esme y 2 spawns de creeper para reconstruir mi faction

**Comment by vegetagamer9** [comment]
vegepapa es el dueño de la fac

**Comment by Tianna16** [comment]
Hola shadow. Rafa no ayudo a petar ya que fue a la fac justo en ese momento con el tipico tp rutinario para controlar a los jugadores y por casualidad le dio a una palanca sin querer y mató al jugador. Los que te petaron son los responsables ( ya sabes quienes son) y ellos tienen tus cosas, por lo tanto no podemos darte nada. Si como tu dices, alguien puso el tnt, piensa en alguien de tu fac xD "lo dejo caer" ya que no puedo decir nada mas <.<

**Comment by vegetagamer9** [comment]
Con hacks, me refiero a que rafa puso tnt en mi fac

**Comment by vegetagamer9** [comment]
ilegalmente

**Comment by MithrandirCraft** [comment]
Poner tnt en tu facción no puede ser valorado como uso de hacks.

**Comment by vegetagamer9** [comment]
Pues entonces como deberia ser valorado?

**Comment by vegetagamer9** [comment]
y lo vi con un arco de fuego y con el /v

**Comment by vegetagamer9** [comment]
Rafa os come la cabeza, dadle la razon si tanto confiais en el...

**Comment by MithrandirCraft** [comment]
Puedes llamarlo "Intervención en el juego por parte de un moderador Etereo" En cuyo caso ese moderador estaría incumpliendo la normativa especifica para moderadores.

Sin embargo no nos has proporcionado ninguna prueba de que esto haya ocurrido.

**Comment by vegetagamer9** [comment]
la screen
pero lo que no entiendo es  el mensaje de uni
lo de la palanca

**Comment by MithrandirCraft** [comment]
Aparentemente hubo un accidente no intencional. Rafaelox pulsó una palanca que hizo escapar unos creeper, eso causó la muerte de ese jugador, pero fue solo accidental.

**Comment by MithrandirCraft** [comment]
En cualquier caso rafaelox24 aceptará las consecuencias del suceso, ya que algunos integrantes del equipo interno juzgaron justa una democión.

Creo que no tienes suficientes fundamentos como para implicar a los demás jugadores, ni pruebas acerca de la colocación de tnt en vanish, por lo que creo que este ticket está ya resuelto.

**Comment by vegetagamer9** [comment]
Y las cosas
Me petan ilegalmente y asi como asi?

**Comment by MithrandirCraft** [comment]
Perdona, no has demostrado ninguna intervención por parte del moderador que haya resultado en los sucesos de tu facción. Tienes alguna prueba mas? Quizá deberías ir cogiendo el habito de grabar tus partidas, ya que sueles reportar bastante por aquí

**Comment by vegetagamer9** [comment]
... ya dejare el servidor para que peten ilegalmente y encima me toman por  mentiroso ya pa q jugar
