### ISSUE TITLE
Hacks a plena vista

### ISSUE THREAD

**Issue by vegetagamer9** [MithrandirCraft/MithrandirCraft#278]
Sobre las 20:50 ESP, un jugador me pidio que le ayudara con un tema, le di mi skype y se me puso a compartir pc y me doy cuenta que tiene hacks pero no el x ray ( aunque este incluido ) el kill aura, chestesp https://youtu.be/QR9unZKbYBo aqui se ve todo. Este jugador abusa de hacks ya que nunca comparte pc  ( dicho por el ) y aqui va otra screenshot que tambien puede servir aunque no este muy seguro :x 
![2016-08-10_20 55 54](https://cloud.githubusercontent.com/assets/12957778/17566967/bae3db38-5f3d-11e6-965b-389045383756.png)

**Comment by ZertahhLoL** [comment]
Muy bien,por donde comienzo.

El jugador desde el inicio se ofreció a ayudarme con un problema con las tiendas,yo cedí,le pase mi skype y compartí pantalla para que vea el bug (por que según el sabia),luego antes de irme me dice que me "estuvo grabando" (cuya prueba no veo en este reporte) y que el ChestEsp no esta permitido,que me iba a reportar y un montón de cosas mas.

Primero que nada,su presentación y pruebas no son ni suficientes ni lo suficientemente "profesionales" como para justificar esto,lo único que se ve en esa screenshot es que yo le digo "Claro,sino que" a su colega (Todo esto para que me reporten mas rápido y pueda explicar lo sucedido mas rápido).

Además sus argumentos son que solo el Xray esta permitido para buscar facciones (lo cual se entero hoy por que tianna fue amable y le respondió sus preguntas,ya que el,claramente no lee las reglas),y mi pregunta es Que diferencia hay entre el Xray y ChestESP si es lo mismo,es mas,deberían quitar que se permita el Xray y que solo se permita ChestESP porque no te deja ver mas que los cofres (los cuales puedes ver con Xray Tranquilamente y más.

Por otro lado le tiene pruebas de que utilizo un Hack Cliente,pero no si utilizo para minar,yo lo tengo y solo utilizo para buscar facciones y/o jugadores.

Antes de terminar con esto quería decir que el jugador le pide cosas a la administradora Tianna (lo cual ella obviamente responde que no) pero igual esta contra las normas del servidor. 

Ah y por cierto me olvidaba el jugador esta tan obsesionado con destruirme ami y ser PB que buscó la mas mínima excusa para reportarme y tener mas chance de serlo,es obvio,y si no es asi,quiere decir que no es consciente de la situación y si reporta cada tontería no creo que se merezca ser PB,por ejemplo reportes fuera de su número o reportes sin suficientes pruebas,aquí dejo algunos...

#277 
#225 
Y creo que he leído alguno que otro que en este momento no encuentro.

Yo por el momento no tengo nada mas que decir por mi parte está mas que claro lo sucedido.

•Nunca dije "Nunca comparto pantalla",así que no puede saber si "Abuso de hacks"

Atte: Zertahh

**Comment by MithrandirCraft** [comment]
@vegetagamer9 Gracias por tu rigurosidad (Característica) a la hora de proporcionar información.

No he visto en ningún lado el nombre del jugador al que estás reportando. En cuanto me he dado cuenta, he decidido ignorar este ticket, que parece contener una biblia adyacente.

Por si os interesa saber como abrir un ticket: https://github.com/MithrandirCraft/MithrandirCraft
