### ISSUE TITLE
Solicitud Permitir ChestESP y Prohibir xRay

### ISSUE THREAD

**Issue by ZertahhLoL** [MithrandirCraft/MithrandirCraft#279]
Mis argumentos son simples,el xRay puede utilizarse para minar y el ChestESP solo te permite ver la HitBox de los Cofres de un color resaltante,de esta manera opino que no va a haber tanto hack para minar.

Lo siento que este reporte no sea amplio,que suelen serlo,pero no hay mucho que explicar.

También hay algunos problemas como que los jugadores deberían descargarse un hack cliente y solo puedan utilizar eso (lo que puede llevar  a la tentación de otras cosas) pero se puede programar uno diferente con otras opciones que solo tengan las mismas (ChestESP,Fullbright,básicamente lo permitido en el servidor).

Atte: Zertahhh

**Comment by MithrandirCraft** [comment]
Nuestra intención es bloquear la visibilidad de jugadores que no se encuentran en rango de visión, haciendolos completamente invisibles cuando se encuentren en tal rango desde el punto de vista del jugador que observa.

Considerando esta función que será implementada en breve, consideras que haya mucha diferencia entre ambos hacks? Cambia en algo tu opinión?

Yo creo que la normativa está bien así. Trabajamos para bloquear más hacks en el futuro, especialmente de combate.

**Comment by ZertahhLoL** [comment]
Yo me refería a esto para buscar facciones,te permite ver la hitbox de los cofres solo cuando estas a cierta distancia.Para los jugadores se puede agregar el freecam (como un gamemode 3) que te permite alejarte de tu personaje (impidiéndote controlarlo) y pudiendo observar todos los chuncks que tienes **cargados**.

Todo esto lo digo con la intención de que la gente no utilice el xRay,ya que directamente estaría prohibido (Por que algunos lo usan mas que para Jugadores y Facciones).

**Comment by MithrandirCraft** [comment]
Me temo que no puedo hacer nada con los minerales que no vaya a daros un lag tremendo por parte de vuestro cliente xD

Solo podemos bloquear la visibilidad de entidades y jugadores que no estén a la vista. Eso incluye cofres, que también son entidades. Sin embargo esto no costaría un poco mas.

En fin, espero que eso te aclare un poco mas por donde van los tiros. Solo teníamos previsto retirar la visibilidad de jugadores.

**Comment by ZertahhLoL** [comment]
Ah muchas gracias por la información :D .

**Comment by vegetagamer9** [comment]
Jaja, te quieres salir con la tuya y no quitarte los hacks? Niño date cuenta que la gracia de Factions es hacerlo todo por ti mismo, sin ayuda de hacks.

**Comment by MithrandirCraft** [comment]
Por cierto hemos abierto una sección de reportes especifica en el nuevo foro. Para reportar comportamientos. Podeis acceder al post informativo desde el indice de www.mithrandircraft.es

**Comment by ZertahhLoL** [comment]
@vegetagamer9  No voy a responderte de forma ofensiva ya que a mi estoy seguro que si me castigarían,solo te diré que no puedo creer que no te hagan nada mientras te la pasas utilizando de mala manera el foro,pidiendo cosas al staff e insultando.

**Comment by MithrandirCraft** [comment]
Valoraremos esto, pero por el momento no tomaré ninguna medida.
