### ISSUE TITLE
Spawner de Zombies

### ISSUE THREAD

**Issue by Ivanovic24** [MithrandirCraft/MithrandirCraft#28]
Hola, queria saber, por q mi spawner de zombies no spawnea mobs :C, esta en una habitacion oscura asi q deberia funcionar pero no es asi.
El nombre de la faccion donde se encuentra es: fac
xD un saludo

**Comment by MithrandirCraft** [comment]
A revisar.

**Comment by MithrandirCraft** [comment]
Bien, cuando he llegado me he encontrado un zombi spawneado encima de hoppers, presumiblemente ha tenido que salir del spawner.

Ten en cuenta que hay un límite de 40 entidades por chunk. Si en esa misma chunk se encuentran demasiadas entidades, es posible que el spawner no pueda agregar más carga a la misma chunk.

Y por lo visto cerca tienes muchos animales y cofres. Recomiendo colocar los spawners siempre alejados de entidades.
