### ISSUE TITLE
Corazones de mas e inventario desaparecido

### ISSUE THREAD

**Issue by AndresGatoXD** [MithrandirCraft/MithrandirCraft#280]
1) Bueno, como dice el titulo tengo vida de mas teniendo 15 corazones,  este (maravillosos xD) bug lo tengo desde principios de la actualización el server a la 1.9... lose un poco tarde para reportarlo :v pero he estado jugando tan poco en el server que quería disfrutarlo xD. Si mi memoria no me falla este bug se me creo de los tantos kikeos que tenia por problemas de lag. Estaba con la armadura vital y salia a por matar mobs pero al rato me kikeaban por "fly", me logeaba y me ponia esa armadura, kikeandome y poniendome la armadura como unas 5 o mas de veces se me bugearon los coras :v.

2) Tal cual... chau inventario :,v
Se que soy muy inactivo en el server, pero mi nivel (fac y survi), el inventario, y terreno de survival que tengo no han cambiado pero mis cosas del pueblo han desaparecido. Sinceramente no recuerdo que tenia pero aunque lo recordara no creo que me lo devuelvan. Ya me han pasado tantas cosas en este server que me da igual que se me pierde o no xD.
Llendo al punto del 2do pido por favor que esto no vuelva a pasar, a veces se vuelve un poco molesto volver a recuperar todo.

PD: no tengo imágenes que demuestren esto por que no tengo laptop ni pc que soporte el juego para sacar screenshot de lo sucedido :v

**Comment by MithrandirCraft** [comment]
1. Este bug fue solucionado hace ya tiempo. Estará plenamente arreglado para la proxima actualización a 1.10.2

2. Si quieres reportar una perdida de inventario debidamente, para que la analizemos y corrijamos el error, debes dejar un reporte en la sección pertinente. Tenemos un ticket abierto solo sobre perdidas de inventario, con unas pautas para realizar el reporte. Si no sigues este procedimiento, no recuperarás nada, y no podremos arreglar el error.

Llevamos muchos meses esperando que alguien reporte una perdida de inventario al cambiar entre mundos de Factions a Survival (La principal causa de perdida de inventario por bug), para que podamos analizar los logs y corregir el problema. Sin embargo, nadie nos da nunca suficiente información precisamente porque no se realiza un reporte correcto.

Para terminar, haz el favor de abrir un solo ticket para cada reporte, y lee estas pautas para tickets genericos: https://github.com/MithrandirCraft/MithrandirCraft
