### ISSUE TITLE
Reporte a el jugador/moderador Rafaelox24

### ISSUE THREAD

**Issue by vegetagamer9** [MithrandirCraft/MithrandirCraft#283]
No tengo nada que decir ya que este ticket lo abro porque el usuario Víctor03king no puede ya que no sabe crearse una cuenta en GitHub, las respuestas que de desde esta cuenta serán tanto como por mi parte para quitarle el ban como para su parte ya que el quiere jugar le pregunté por Skype lo básico y algunos detalles sin mas dilaciones les pasaré las srenshots de cuando hablé con el

**Comment by vegetagamer9** [comment]
Tienen que esperar 2 horas o así el celular de él demonio no me deja mandar screnshots

**Comment by vegetagamer9** [comment]
![47666bbe33822e79ead33a77bb643b0074625a8c342d1b32cf pimgpsh_thumbnail_win_distr](https://cloud.githubusercontent.com/assets/12957778/18025453/2804783c-6c2a-11e6-88df-ef061a5d0f2c.jpg)
![d79c5279cf09c2c3525c57153802ec9937f34a0e892511a30c pimgpsh_thumbnail_win_distr](https://cloud.githubusercontent.com/assets/12957778/18025454/2adcb326-6c2a-11e6-9c13-6dbed6050c86.jpg)
![bec81ef7bbcae0a1dc13744258ceb0afac71c4561dd135be5c pimgpsh_thumbnail_win_distr](https://cloud.githubusercontent.com/assets/12957778/18025455/2deac1b6-6c2a-11e6-991a-a1700dd02f0a.jpg)
![e3859e7392b1c70180370a93a00f111b4cf1b9d944c9967a3c pimgpsh_thumbnail_win_distr](https://cloud.githubusercontent.com/assets/12957778/18025458/542d14b4-6c2a-11e6-8db2-a1323760a427.jpg)
![efd8fbe95e2909a5f63221b801027dd5c3350150caa45ec2b3 pimgpsh_thumbnail_win_distr](https://cloud.githubusercontent.com/assets/12957778/18025460/6b8391c4-6c2a-11e6-9182-416a534235f8.jpg)
![971db0fed4d1e133fe93821bbe6a6ad0f2f9aa672ba1c25c26 pimgpsh_thumbnail_win_distr](https://cloud.githubusercontent.com/assets/12957778/18025461/6e0184ce-6c2a-11e6-8029-fdff6974c90f.jpg)

**Comment by vegetagamer9** [comment]
La 3 es la prueba de lo que dijo lokero ( victor ) lo de el ban ip

**Comment by ZertahhLoL** [comment]
En esas pruebas no puede observarse nada bien.ni con zoom,Por cierto en vez de enviar 80 mensajes puedes editar tu reporte o enviarlo todo ya escrito.

**Comment by Vegepapa** [comment]
Buen día. 
Vegetagamer9

1.-Por favor ocupe el foro de mithrandircraft.

2.- El jugador afectado es quien debe exponer su inconformidad.

3.- Cuando envíe screen  Procure sean legibles

**Comment by MithrandirCraft** [comment]
Hay demasiadas cosas incorrectas en este ticket, desde la calidad del reporte hasta el puro hecho de que estás reportando en el lugar incorrecto. Con el mismo esfuerzo que te ha tomado abrir este ticket, me limito a indicarte por 3ra vez que leas las pautas para realizar un reporte: https://github.com/MithrandirCraft/MithrandirCraft/blob/master/README.md
