### ISSUE TITLE
Banean a tato por entrar con mi cuenta.

### ISSUE THREAD

**Issue by vegetagamer9** [MithrandirCraft/MithrandirCraft#284]
Bueno como yo confio en tato muchisimo y puede entrar con TODAS mis cuentas sin permiso o con permiso como ya soy viejito en el server y todo el mundo me odian regale mi cuenta a tato porque el tiene derecho a tener todas mis cosas ya que fue el primero que uni a mi fac propia comparto todo con el.
Desbaneenle le doy permiso de por vida para entrar con todas mis cuentas cuando se le desbanee pueden cerrar el ticket.

**Comment by ZertahhLoL** [comment]
Este es el foro incorrecto para este tipo de reportes,como siempre te lo recuerda mith,voy a ahorrarle el disgusto de decírtelo,** # este es el foro correcto:** http://mithrandircraft.phpbb-foro.es/t1-pauta-de-reportes-obligatorio-leer-antes-de-reportar

Además no das Screenshots en donde diga quien lo baneo,la hora y el motivo.Tampoco se dice exactamente quien fue el baneado y quien hace el reporte.

Me he tomado el tiempo de buscar en los foros y cederte la información exacta a ti y a los encargados sobre este reporte.El jugador Tato_PvP Fue baneado por rafaelox24 el día 31/08/16 a las  00:14:56 (hora de servidor) hasta el 07/09/16 por incumplimiento de la norma 12: (A)Acceder y tomar control de nombres de acceso al servidor ajenos.

Si no me equivoco también te comento el moderador Vegepapa que solo el jugador afectado puede apelar en su defensa.Aparte,aunque confíes en el y quieras darle tu cuenta,según tengo entendido,no puedes,porque la norma 12 lo prohíbe.

**Comment by vegetagamer9** [comment]
Oye tú tienes que comentar todo lo que yo escribo? Vete a tener vida social, rata de laboratorio.

**Comment by ZertahhLoL** [comment]
Estoy en mi derecho,mientras no falte el respeto como tu,iré a reportarte al **FORO CORRECTO**.

**Comment by vegetagamer9** [comment]
MithrandirCraft tienen que poner como un permiso para que comente quien tú quiera no que te hablen ratas y te hagan perder tiempo

**Comment by ZertahhLoL** [comment]
Cualquier staff que lea esto le comunico que ya he reportado al usuario correctamente,aquí el link: http://mithrandircraft.phpbb-foro.es/t9-reporte-al-usuario-vegetagamer9#19 .

**Comment by MithrandirCraft** [comment]
@vegetagamer9 Se acabó, está claro que no sabes utilizar este medio de forma adecuada. Quedas expulsado.

Mi consejo: Aprende a leer y pidele a alguien que te eduque en morales, porque desde el día 1 llevas infligiendo todas las normas y protocolos posibles.
