### ISSUE TITLE
Algunas cosas, deben permanecer enterradas. (Glitchs)

### ISSUE THREAD

**Issue by krazlas1** [MithrandirCraft/MithrandirCraft#285]
Primero que nada debo decir que este reporte no está en el Foro oficial de la comunidad de Mithrandircraft por una simple razón, no me da confianza que no tenga casi o ningun reporte abierto, y mucho menos sobre el tema que estoy por tratar a continuación.

Hola, hoy vengo a exponer públicamente el uso de un glitch que no esperaba que siguiera funcionando, pero al parecer, jugadores tramposos lo han estado aprovechando.

El glitch va de conectarse con la cuenta de una persona, que ya está logeada en el servidor, y automaticamente el servidor kickea a esa persona, puesto que son dos nicks iguales. Esto puede afectar gravemente a los pvp de factions, y ya lo ha hecho el día de hoy.

Comento mi situación:

El día de hoy, Jueves /09/2016, estuve jugando como de costumbre en MithrandirCraft, hablando con conocidos y retando a jugadores enemigos a pvp, para mi suerte, aceptaron, pero para mi mala suerte utilizaron ese Glitch 3 veces para sacarme del servidor mientras hacíamos PvP. La primera vez que sucedió, lo tomé con mucha calma, volví a hacer login en el servidor, fui de nuevo a la zona en la que estábamos haciendo el PvP, maté a 2 de los que estaban ahí, y vuelven a usar el Glitch, esa vez el servidor a parte de kickearme, me sancionó por Combat logging, Eso ya me sobresaltó, volví a ir por tercera vez a la zona del PvP, había un player que estaba parado y no se movía, le empecé a pegar, y unos 5 segundos después, de nuevo me kickea la consola, con el mismo mensaje

''You loggedin from another location'' - has iniciado sesión desde otra ubicación.

A mi me da igual perder o morir en un juego, y más en un servidor que está centrado en eso, pero de manera justa, así como yo he matado a muchos también tengo el derecho de morir, pero no sean tan descarados para usar un Glitch como este, o como ninguno porque nadie debe usar Glitchs.

Jugadores involucrados en el PvP

-TheShadowWither
-PipasConSal
-x_YerPvP
-eliezerpvp
-AlconGalactico
******************
-kraz1234
-Elizabeth
-MeepMurp

Bien, pues tengo una ultima cosa que decir, TODOS los jugadores que se aprovecharon de este Glitch tan rastrero y valurdo, deberían ser sancionados, puesto que esto es tan grave como un hack, es más, es mucho peor, poder matar a alguien solo, con logear su cuenta? eso si es un Cheat verdadero.

Ya esta bien de prorrogas para TheShadowWither, estoy harto de que cada vez que va a ser sancionado diga ''lo siento unicornia xDXdxdXDd'' y luego el Admin lo pase por alto, y hasta los Mod.

Ya es suficiente.

PD: El player que se había quedado parado fue eliezerpvp, desde muy dentro de mí siento que el fue el que estaba ejecutando mi nickname desde su pc para sacarme en combate.
 
Por favor, tomen cartas en el asunto.

**Comment by MithrandirCraft** [comment]
Hemos hablado esto por Skype. Se solucionará con la actualización a 1.10.2

Dejo este ticket abierto hasta que haya sido solucionado. Y mientras tanto, los jugadores que saquen partido de este bug serán sancionados.

**Comment by SimplyAcke** [comment]
Buenas, primero que nada, gracias por detallar tu reporte pero, por mi parte he de decirte que el _nuevo_ foro de MithrandirCraft es igual de funcional que este, no por ser nuevo se le da menos importancia, de hecho se le presta atención por si se puede aplicar alguna mejoría. De nuevo gracias por tu reporte.

Att
~Acke.

**Comment by MithrandirCraft** [comment]
No, si de hecho el lugar adecuado para reportar un bug es este. Haced el favor de leer en www.mithrandircraft.es

**Comment by MithrandirCraft** [comment]
Creo que esto ya está arreglado. Confirmalo. @krazlas1

**Comment by MithrandirCraft** [comment]
Lo siento, pero sin poder determinar quien realizó la infracción, no puedo tomar ninguna acción.
Como ya te dije, lo adecuado hubiese sido no loguear y reportarlo de inmediato. Por suerte hemos arreglado esto rápidamente.
