### ISSUE TITLE
Sugerencia para la nueva economía del servidor.

### ISSUE THREAD

**Issue by ZertahhLoL** [MithrandirCraft/MithrandirCraft#286]
Bueno,sucede que como dijo "tipodeincognito" en el otro foro: http://mithrandircraft.phpbb-foro.es/t10-discusion-el-porque-del-pago-con-esmeraldas-cuando-existe-el-dinero-virtual-o-viceversa este nuevo método te permite mantener a salvo tus esmeraldas,pero provoca que escaseen mas los raids ya que no saldrá muy rentable para facciones pequeñas/medianas por que perderán mas esmeraldas de las que ganarán 

Considerando que generalmente los botines que obtienen este tipo de facciones no son muy valiosos,debido a que GENERALMENTE no raidean a facciones mucho mas grandes a las suyas,que la relación Items (armaduras,armas,etc...) con esmeraldas gastadas no sea equiparado u mejor con respecto al botín y que los raids deberían ser siempre o la mayoría de las veces con mas ganancia para la faccion que lo haya hecho,propongo esta solución:

Se puede pulir mucho mas y obtener un mejor resultado,pero básicamente es que convertir esmeraldas en este nuevo dinero tenga un tiempo de espera,por ejemplo,máximo 64 esmeraldas/2 días.

Si las esmeraldas pueden mantenerse a salvo en forma de dinero sin restricción alguna,pierden las facciones pequeñas y ganan las mas poderosas (por la cantidad de esmeraldas que poseen) y creo que lo que se busca es nerfear a estas últimas.

Por último,recalcar que puede añadirse a lo que he dicho hace bastante,que solo a facciones con cierta peculiaridad se les coloque este límite,(como tener 10 jugadores,etc..)

Como ya dije anteriormente puede pulirse mucho mas,pero se basa en eso.

Atte
Zertahh

**Comment by MithrandirCraft** [comment]
Es interesante y cierto lo que dices.

Por otro lado lo voy a poner muy simple. Otros servidores utilizan una economía numerica integrada como metodo economico exclusivo, y les está yendo muy bien. El PvP se fomenta dramáticamente gracias a la inflación y abundancia creados por este banco seguro virtual.

Sin embargo, MithrandirCraft no és "Otros Servidores", con lo que sigo creyendo que tienes razón :P
La economía numerica facilita unas opciones muy interesantes para el servidor, consideraré tu sugerencia de cooldown y valoraré mas opciones. Haznoslo saber si se te ocurre algo mas.

**Comment by ZertahhLoL** [comment]
Muy bien,te agradezco por haber considerado mi propuesta.

**Comment by MithrandirCraft** [comment]
Seguiremos trabajando en el balance de la economía. Somos conscientes de los factores que se han tratado en este tema.
