### ISSUE TITLE
JAVA tm platform SE binary dejo de funcionar 

### ISSUE THREAD

**Issue by krazlas1** [MithrandirCraft/MithrandirCraft#287]
De nuevo aquí...

No sé si les ha pasado a otros jugadores del servidor, pero el error que impide entrar al servidor de manera usual ha estado molestando las últimas horas en las que fue actualizado a la 1.10.2

''JAVA tm platform SE binary dejo de funcionar''

Intento logear en el servidor, pero a los 2 segundos de entrar sale este mensaje. 

Debo recalcar que es la primera vez que me aparece este mensaje.

**Comment by ZertahhLoL** [comment]
No es problema del servidor,estuve buscando información y te recomiendo entrar a .minecraft quitar todo lo que necesites,como mapas,resourcepacks,etc y llevarlos al escritorio,luego elimina .minecraft,abre el juego y crea tu perfil con la versión bla bla bla para por ultimo entrar nuevamente en .minecraft y colocar las carpetas que has quitado para recuperar tus mapas y etc.

Espero haberte ayudado.
Atte
Zertahh

**Comment by MithrandirCraft** [comment]
Prueba eso porfavor. Haznoslo saber si sigues teniendo problemas.
Si nadie mas esta teniendo este problema me temo que es altamente provable que sea solo un problema con tu entorno.

**Comment by MithrandirCraft** [comment]
Solucionado intuyo.
