### ISSUE TITLE
Reporte al jugador Maki.

### ISSUE THREAD

**Issue by TheShadowWither** [MithrandirCraft/MithrandirCraft#288]
Buenas tardes/noches/dias. Esta mañana en las 11 en mi pais yo estaba tranquilo remodelando mi fac para que sea dificil de petar y el jugador maki me empezaba a insultar me decia palabras malsonantes creando mal ambiente espero que tomen medidas. Screenshots:
![2016-09-08_20 29 02](https://cloud.githubusercontent.com/assets/12957778/18390126/422787f2-76a9-11e6-843b-d4a7f2862eee.png)
![2016-09-08_20 32 43](https://cloud.githubusercontent.com/assets/12957778/18390125/42279120-76a9-11e6-852c-b00a54511a3b.png)
![2016-09-09_11 22 43](https://cloud.githubusercontent.com/assets/12957778/18390142/53bceb92-76a9-11e6-831d-0ffacf01a8e9.png)
![2016-09-09_11 15 35](https://cloud.githubusercontent.com/assets/12957778/18390145/53bfaddc-76a9-11e6-9f47-7d9f77759431.png)
![2016-09-09_11 19 16](https://cloud.githubusercontent.com/assets/12957778/18390141/53bbf520-76a9-11e6-9e23-81138328b2b2.png)
![2016-09-09_11 20 02](https://cloud.githubusercontent.com/assets/12957778/18390144/53bea964-76a9-11e6-8202-24c052894f57.png)
![2016-09-09_11 21 04](https://cloud.githubusercontent.com/assets/12957778/18390143/53bd11ee-76a9-11e6-8d12-34c4320c2727.png)
![2016-09-09_11 22 07](https://cloud.githubusercontent.com/assets/12957778/18390146/53c0480a-76a9-11e6-8895-79a889d9de3a.png)
![2016-09-09_11 24 32](https://cloud.githubusercontent.com/assets/12957778/18390157/5c52ccfe-76a9-11e6-9598-4906487bcbd9.png)
![2016-09-09_11 23 52](https://cloud.githubusercontent.com/assets/12957778/18390158/5c61b6a6-76a9-11e6-87ef-0860a60f2ff9.png)

**Comment by TheShadowWither** [comment]
![2016-09-09_16 29 07](https://cloud.githubusercontent.com/assets/22100734/18390449/95c354b2-76aa-11e6-8bcc-649b07f904bf.png)

**Comment by xXandrescolXx** [comment]
Ya he procedido con la debida sancion

**Comment by SimplyAcke** [comment]
Shadow, aun que las pruebas y el reporte son correctos, debes crear este post en el foro de reportes. De esa forma todo queda bien hecho.

Gracias,
~Acke.

**Comment by TheShadowWither** [comment]
Si supiera como hacerlo lo haría. Pueden comunicarle a MithrandirCraft que haga un vídeo explicandolo  :D

**Comment by MithrandirCraft** [comment]
Acostumbrate a reportar en el lugar adecuado, o volverás a ser expulsado -> www.mithrandircraft.es
