### ISSUE TITLE
[BUG]En las alcantarillas,las brujas tomaron control.

### ISSUE THREAD

**Issue by ZertahhLoL** [MithrandirCraft/MithrandirCraft#289]
En las alcantarillas del "/Warp Pueblo" el acceso hacia el aldeano que vende Obsidiana,piedra del end,etc,no se abre.Intenté varias veces presionando el botón y es que los pistones se mueven pero los barrotes se mantienen en su lugar. 

(los barrotes hacen un movimiento extraño pero sin moverse del lugar).

Atte
Zertahh

**Comment by krazlas1** [comment]
Tal véz actualizaron la redstone en la 1.10, porque diversos sistemas que funcionaban con pistones estan presentando problemas. (dentro del mismo warp pueblo)

**Comment by ZertahhLoL** [comment]
Imposible,horas antes a este reporte (hecho a la tarde/noche) a la mañana podía entrar tranquilamente.

**Comment by xXandrescolXx** [comment]
Ya esta solucionado.

muchas gracias por reportarlo

**Comment by ZertahhLoL** [comment]
Por nada,y gracias a ustedes por solucionarlo.

**Comment by ZertahhLoL** [comment]
Este caso ya ha sido solucionado,solicito que si es posible cierren este github.
