### ISSUE TITLE
Hackers muy claros de pvp

### ISSUE THREAD

**Issue by Ivanovic24** [MithrandirCraft/MithrandirCraft#29]
Bueno queria reportar a unos hackers nuevos que ha traido ShoCk(NeuroticSD, Dhock, Dazet...) otro hacker exmiembro de mi faccion, sus nombres son SkazenMC, xDarkSide, motre y por supuesto ShoCk. Todos ellos tienen kill aura pero, por ejemplo SkazenMC tiene autoarmor, motre y xDarkSide tienen antinoockback y todos x-rays y tracers.

Grabare un video, pero no tengo canal para subirlo a YouTube. Si me pueden decir algun programa o web para subirlo...

Un Saludo

**Comment by iCrazyMadafaka** [comment]
Yo a esos hacker pude grabar a xDarkSide (No se ve bien claro su hack, pero se que lo llevaba puesto) pero a SkazenMC se le veía clarísimo, lo subiré a Youtube, pero si hay aquí algo para subir vídeos abisame Mith que subo el video, aquí traigo una foto de que ShoCk no quería compartirme y decidió poner una escusa cuando le dije que me compartiese pantalla
![captura de pantalla 2015-02-15 a la s 20 25 44](https://cloud.githubusercontent.com/assets/9981163/6204578/d587d3ce-b550-11e4-89d4-0f7d624b904d.png)
No se si se ve muy bien e,e

**Comment by iCrazyMadafaka** [comment]
Bueno, vi que no se ve muy bien, pero pone esto
iCrazyMadafaka : venga que te comparto las mie**** (perdón por esto) pochas esas que tu dices
Neurotic : Deja
iCrazyMadafaka : Que te muestro
Neurotic : Concha tu madre deja me va a desenchufar (Su madre le iva a apagar su PC supuestamente) xDDD bye
iCrazyMadafaka : ._. xau

**Comment by Ivanovic24** [comment]
Aqui esta el video de uno de los hacks  xDarkSide en el canal de pvp4ever:
https://www.youtube.com/watch?v=_owqclerVQY&feature=youtu.be

**Comment by MithrandirCraft** [comment]
Me pierdo un poco en el video. Podrías indicarme exactamente que indicios del vídeo te hacen pensar que usa hacks?

En un principio he podido observar que el jugador grabado no le perturbaba el knockback, aunque no tengo ni idea de que atributos lleva la espada de quien graba. En la segunda mitad del video, el knockback ha empezado a afectarle. Además de posiblemente estar pegando a 2 jugadores a la vez. Aún así no lo veo muy claro.

Hay algo más que deba ver y no esté viendo?

**Comment by Ivanovic24** [comment]
mith el q le afectaba el nockback era un jugador diferente al q no le afectaba.

**Comment by Ivanovic24** [comment]
Mi espada era Empuje 2 (podeis creerme o no) y aunqe no tuviera empuje ninguna de las 2 espadas siempre hay un ligero empuje, pero el ni se inmutaba y ademas si te fijas una vez esta mirando a uno y depronto si gira automaticamente para pegar al de detras. Igualmente si se sancionara a alguno avisalo por aqui si puedes el nombre del sancionado y si no se sanciona todavia iremos subiendo pruebas.

**Comment by Ivanovic24** [comment]
Ademas si te fijas bien en el 1º jugador crazy al pegarle tampoco lo mueve y al 2º jugador q viene le pega y lo manda a salamanca e.e, eso significa q PvP4ever tambien tenia knoockback 2 y que xDarkSide tenia antiknoockback

**Comment by MithrandirCraft** [comment]
Ok. Con esta prueba visual es suficiente para tomar 1 sola acción contra un jugador.

 - xDarkSide será expulsado temporalmente (6 meses) del servidor por uso de hacks de combate.

Si tenéis pruebas adicionales para terminar de dejarme claro otro hacker, y así incriminar a alguien más, reabrid este ticket, o preferiblemente cread uno nuevo.

**Comment by iCrazyMadafaka** [comment]
Cierto, yo también tenia el knockback 2, yo creo que xDarkSide se quito el Kill Aura, pero se puso el trigger bot o como se llame, al segundo, se le veía muy bien el kill aura, una cosa muy peculiar de los hackers es que si utilizas el kill aura cuando pegas, se ve que pega mirando hacia arriba, no normal, pruebalo con alguien mith, yo te aseguro que te confirmo eso

**Comment by Ivanovic24** [comment]
ok gracias

**Comment by MithrandirCraft** [comment]
@iCrazyMadafaka No es suficiente. No puedo castigar a alguien sin pruebas más convincentes.

Rastrear hackers no es fácil, por suerte, en estos tiempos donde ciertos hacks escapan al control del servidor, aquellos que dependen excesivamente de hacks terminan siendo expulsados de 1 manera u otra.

Mas vale prevenir que curar, por lo que también estoy dedicando atención a nuevos metodos para prevenir los peores hacks de pvp como kill aura y anti knockback.

**Comment by Ivanovic24** [comment]
xDarkSoul es xDarkside

**Comment by Ivanovic24** [comment]
https://www.youtube.com/watch?v=9KppXr5pyQ4&feature=youtu.be

Confesion de ShoCk sobre su amigo el hacker, nose si es suficinte para actuar,
SkatezMC ese es el 2º hack del video de crazy
