### ISSUE TITLE
Ineficiencia de Spawners ¿Donde están los mobs?

### ISSUE THREAD

**Issue by krazlas1** [MithrandirCraft/MithrandirCraft#290]
Buenas noches.
11/09/2016

Desde hace un tiempo para acá, después de la actualización del servidor a 1.10.2, he notado que la eficiencia de los Spawn Blocks ha disminuido considerablemente, a tal punto de ser imposible conseguir XP de esta manera.

Ya he probado reduciendo las entitades de las cercanias a casi 40, y aún los Spawners siguen siendo muy lentos, así que se puede descartar que sea por un exceso de entidades en dicha zona de chunks.

Por favor arreglen esto lo más pronto posible, o den otra solución como aumentar la cantidad de botellitas de XP que vende el Hipnotizador en /Warp Pueblo

Gracias por su tiempo.

**Comment by xXandrescolXx** [comment]
Muchas gracias por la información, revisaremos las configuraciones sobre el limite de mobs que spawnean

**Comment by xXandrescolXx** [comment]
Solucionado
