### ISSUE TITLE
Propuesta y reporte sobre los duelos.

### ISSUE THREAD

**Issue by ZertahhLoL** [MithrandirCraft/MithrandirCraft#291]
Hola,mi propuesta la voy a dividir en los siguientes puntos.

•**Crear un broadcast.**
-Para que se fomenté mas este método de PvP en igualdades de condiciones.

•**Crear nuevas y más cantidad de arenas.**
-Por el simple hecho que no puede haber mas de 1 duelo activo a la vez,lo que resulta molesto tener que esperar mucho tiempo para PvPear.

-Para mejor aceptación a la vista,ya que,hay que decirlo,es un cubo de cuarzo y por alguna razon da lag,en ese aspecto MithrandirCraft carece de "MithrandirCraft".

•**Arreglar ortografía de la "revicida" de un duelo,(recibida)**
![image](https://cloud.githubusercontent.com/assets/20175690/18494767/cba9812c-79ee-11e6-8865-e5253e6100a6.png)

Atte
Zertahh

**Comment by MithrandirCraft** [comment]
Los builders están trabajando en el desarrollo de nuevas salas. (Estas llevan tiempo haciendose desde antes de la imlementación del sistema en Alpha.)

Como he dicho, este sistema se encuentra en Alpha, por lo que todavía falta mucho por implementar y arreglar.

En cuanto a broadcasts creo que prescindiremos de excesos ya que precisamente al incorporar mas salas, habrá mas spam. Se trata de no pasarse.

**Comment by MithrandirCraft** [comment]
Ticket permanece abierto un tiempo.

**Comment by ZertahhLoL** [comment]
Yo desconocía que el sistema estaba en Alpha,muchas gracias por la información.

De todas maneras insisto en que al menos el mensaje que se envía luego de terminar una batalla solo lo reciban los jugadores que participaron y/o haya un comando para deshabilitarlo,etc,ya que como dijiste generará spam. También considero que un Broadcast durante la primera semana en que el sistema este terminado no vendría mal,teniendo en cuenta que ocurriría cada varias horas.

**Comment by MithrandirCraft** [comment]
@ZertahhLoL "Broadcast" Estas proponiendo que se anuncie el sistema? Si es así, relax. El sistema aún esta al 10% de su totalidad. Algunos de mis staff se han impacientado y han empezado a revelar los comandos a todos los jugadores. Cuando esté satisfactoriamente implementado se publicitará por todos los medios.

**Comment by MithrandirCraft** [comment]
Bueno, las salas nuevas estarán ya pronto. Doy por hecho que lo que has sugerido se implementará asi que cierro ticket.
