### ISSUE TITLE
Bug por culpa de las alas [Elytra]

### ISSUE THREAD

**Issue by Gambacha** [MithrandirCraft/MithrandirCraft#292]
Buenas.
Resulta que estaba volando por el mundo de facciones y al aterrizar llegue a las hojas de un árbol y me quede ahí bugeado (lo que suele pasar cuando estás todo el tiempo cayendo y subiendo de forma muy rápida). Pensé en quitarme las alas para parar el bug pero caí al suelo (unos 2 bloques de altura) y morí por caída teniendo toda la vida.
Las alas (elitros) son un objeto muy importante, además de que no eran mías, eran prestadas. Preguntaba si algún administrador me las podría devolver, en el caso de que se devuelvan cosas perdidas por bugs.

Saludos y gracias :D

**Comment by TheShadowWither** [comment]
Hola @Gambacha a mi no me pasa ese bug no se si es denominado un " bug " porque yo andaba haciendo esto en pvp sala 06 cuando volaba cayendo al vacio, probe lo que me dijistes de caer en un  bloque y no pasa y eso que lo intenté solo pasa en bloques que no tienen alta resistencia " CREO " ya que las hojas se rompen con falicidad esto pasa cuando caes en lava, agua espero que presten atencion. Gracias :)

**Comment by MithrandirCraft** [comment]
Suena como que te has estrellado.
