### ISSUE TITLE
[Bug] Barcos (Vanilla)

### ISSUE THREAD

**Issue by ZertahhLoL** [MithrandirCraft/MithrandirCraft#293]
Resulta que yo estaba con un amigo haciéndome tranquilamente mi supernormal casa acuática con una sala con agua en  la cual puse aproximadamente 30 barcos amontonados.

Luego al subirme a uno y conducirlo por unos  5 segundos me kickea por fly.

(pd:también al caminar encima de ellos)

![2016-10-01_17 21 01](https://cloud.githubusercontent.com/assets/20175690/19017054/c3c612cc-8803-11e6-861a-18128c74905e.png)

**Comment by MithrandirCraft** [comment]
Cuál es exactamente el mensaje?
Puedes reproducirlo continuamente y con facilidad?
Esos barcos están encima de agua?
Cuantos barcos hay amontonados uno encima del otro?

**Comment by ZertahhLoL** [comment]
Esta es una mecánica que veo muy interesante,crear pasillos con barcos a los cuales luego le tiras agua por encima y se hunden mientras se actualiza arena flotante y nadie mas puede pasar.Paredes de barcos que hayas puesto y luego los dejas caer.

el problema es que te kickea al caminar sobre ellos o hasta conducir un barco sobre el mismo.

**Comment by MithrandirCraft** [comment]
Ya, pero puedes contestar a mis preguntas? xD

**Comment by ZertahhLoL** [comment]
•Ya esta arriba el mensaje
•El que puedo reproducir?
•Si
•Ninguno,solo es un barco al lado del otro.

**Comment by MithrandirCraft** [comment]
Este bug es de MinecraftVanilla. Como tal, deberías dirigirte a la sección de bugtracking de Mojang y apoyar los reportes ya existentes sobre el asunto.

Cierro este ticket ya que no depende en absoluto de mi.
