### ISSUE TITLE
Algunos Spawner inactivos :O

### ISSUE THREAD

**Issue by vampiredrem** [MithrandirCraft/MithrandirCraft#294]
Hola.. 
 Te comento lo siguiente: tengo 2 spawner (zombies y arañas)
El de zombies funciona super bien, ningún problema.
pero el de arañas de cueva no funciona para nada, hace como 2 semanas que esta desconpuesto, ya lo e reportado a un admin (Tianna16) y lo fue a ver, me dijo que no sabia que ocurria, pero lo estarían revisando, pasa que ya a pasado mucho tiempo y al ser un spawn de arañas de cueva triple osea  3 spawner juntos,  la cantidad de arañas es excelente para obtener xp y me a echo mucha falta ojala puedan verlo y arreglarlo.
gracias x tu tiempo.

el spawner se encuentra en las siguientes coordenadas ( X: 965)  (Y: 26) ( Z: -2.052) mundo survival.

**Comment by MithrandirCraft** [comment]
Si alguien es capaz de reproducir este error, que la verdad, es un classico, que reabra un ticket e indique coordenadas, a ser posible en el momento en que ocurra.
