### ISSUE TITLE
Mundos Cruzados   @_@ ??

### ISSUE THREAD

**Issue by vampiredrem** [MithrandirCraft/MithrandirCraft#295]
Hola buenas tardes..

Estaba en survival pasando el rato, y un amigo me invito a ver su fac, y paso lo siguiente: 

:O .. pregunte .. ESTO ES FAC  O SURV ???  .. 
Era fac y mis cosas no estaban :/ .. se lo comunique a la andim Tianna16 de inmediato y me dijo que reportara.

PASO LO SIGUIENTE:

-En el presente iba full oro encantado, herramientas, armas y bloques de construccion. (survival)

-Me fui a fac, y esperaba tener mis cosas de FAC, Mi kit de diamante cheto, herramientas, armadura, armas.. posiones, TNT comida ect.

Pero............

-Tenia el inventario de survival, PERO ! .. tenia el inventario de survival de hace unos 2 o 3 dias atras , donde iba full hierro encantado y mi kit completo bloques etc.. 

++++esto nunca me paso y ahora que hago? PERDI TODO EL INVENTARIO DE FAC ..

*Esto paso mas o menos a las 20:30 hora del serviador, fue reportado al instante y explicado en el chat a una Admin también.

PD: a "kit" me refiero básicamente a ... ARMADURA, HERRAMIENTAS, ARMAS. :dagger: 

gracias x sus tiempos .

VampiRe

**Comment by MithrandirCraft** [comment]
Si, esto parece el bug de inventarios que abrí yo mismo.

Consideraré lo de que tu inventario era una version antigua.

**Comment by Blasfemia** [comment]
ush ya a esta altura es bien dificil saber que encantos tenian, pero era full diamante, mas las armas y herramientas todo encantado.
espada
arco
pico
pala
acha
 eso :/
 eficiencia 4 la mayoria de las herramientas mas irrompibilidad, mi arco que me regalaron estaba con: irrompibilidad, poder 4,  infinidad, flecha incendiaria, retroceso, reparacion ... y la espada tenia poder de fuego, filo 4 empuje e irrompibilidad.

de lo que me acuerdo ya tanto tiempo paso .. :/

**Comment by MithrandirCraft** [comment]
Duplicado: https://github.com/MithrandirCraft/MithrandirCraft/issues/255
