### ISSUE TITLE
HACIENDOSE RICOS SIN SUDAR NI UNA GOTA !!! 

### ISSUE THREAD

**Issue by Blasfemia** [MithrandirCraft/MithrandirCraft#298]
mithrandir te explico resumidamente..

en la tienda de survival se estan vendiendo 1 esmeralda X 4 diamantes
y el aldeano normal vende 1 esmeralda x 2 diamantes ..
 ya me entenderas vos como es que se estan aprovechando, aparte del pb AGUS tirando p4 a tal y a cual..
yo no entendia de principio en el chat de tal bug de que salgan de la tienda de que este y este otro se estan aprovechando, de que tienen bloques de esmes en las manos etc.

hasta que AGUS me lanzo 64 diamantes y le dije xque me das diamante y em dijo xque tengo mucho .. vale .... hasta ahi todo bien y luego supe lo que te comentaba anteriormente y los empece a bardear a decirles que no roben xque el mal es pa nosotros mismos.. 

QUIERO DEJAR EN CLARO QUE YO NO SAQUE NADA, XQUE LO MIO ES LA CONSTRUCCION Y SI X ESTA ESTUPIDEZ QUE ACABAN DE HACER LA GENTE DE SURVIVAL BORRAS TODO Y TODO MI TRABAJO LO ENCONTRARIA UNA INJUSTICIA TREMENDA.

ojala lo hables con los chicos y que sean castigados los que se propasaron PERO QUE NO NOS VENGAN A BORRAR NUESTROS TRABAJOS DE GENTE QUE SE A DEDICADO A CONSTRUIR COSAS BONITAS 

bueno pasa que frustran estas situaciones sin saber cual seran las consecuancias 

te invito a ir a mi claim y que veas lo que e echo e el esta en  : X -232 ___ Z -758 y decime si no toma tiempo hacer algo a si, solo y entrando todos los dias a tu server.

 bueh gracias x tu tiempo

Yo preferi salirme del server hasta ver a un admin confiable y reportar 

VampiRe.

**Comment by MithrandirCraft** [comment]
Solucionado. Y también se han confiscado los recursos.
