### ISSUE TITLE
Error a la hora de votar.

### ISSUE THREAD

**Issue by ZertahhLoL** [MithrandirCraft/MithrandirCraft#299]
Hoy mismo (11/12/16) intenté votar en la página de "Mineserver (NET)" desde el sitio oficial del servidor (http://www.mithrandircraft.es) pero a la hora de darle a "Vote for this server!" te dirige hacia una página que dice lo de la imagen.

Página Mineserver (NET) : http://www.mineservers.net/servers/152-mithrandircraft
**Error:**
![error](https://cloud.githubusercontent.com/assets/20175690/21123373/fb615bf6-c0b6-11e6-9b6a-47a66a037a9c.png)

Tampoco estoy seguro de que no sea un error mío,pero en ese caso,quisiera saber como solucionarlo.

PD: En la página "40servidores" (http://www.40servidoresmc.es/vota.php?cod=387) ocurre algo parecido,ya que al entrar te redirije hacia http://www.40servidoresmc.es ,no se si será un error.

Gracias!

Atte: Zertahh

**Comment by MithrandirCraft** [comment]
Lo siento, pero esta página no esta dentro de mis competencias. Es un problema de esa página. Este error no perjudica a la publicidad del servidor ya que está afectando a todos los servidores alistados en ella, no solo al nuestro.

Siempre puedes intentar contactar con los desarrolladores de la página y comentarles el problema, si lo que quieres es tener una página de voto mas.
