### ISSUE TITLE
Otra vez el bug

### ISSUE THREAD

**Issue by Ivanovic24** [MithrandirCraft/MithrandirCraft#30]
Hola, hoy Lunes dia 23/2/2015 a las 23:00, el servidor a tenido una caida y al volver a entrar todas las cosas de mi inventario, exceptuando la armadura, se le cambio el nombre por \* y los objetos que ya tenian nombre se les puso el mismo nombre, pero se añadio \*. Ademas todos esos objetos han perdido sus encantamientos:

1º Espada de diamante: Futon: Obama Raseng Shuriken: Afilado V, Empuje 3, Irrom 3, Aspecto Igneo 2, Botin 3
2º Arco: Poder V, Fuego 1, Irrom 3 y Infinidad 1.
3º Pico de Diamante: Efi 4, Irrom 3.
Fotos:
http://imgur.com/IBsdTvJ,211BQMl,4lYwqmV,Ypu4gLH#3

**Comment by MithrandirCraft** [comment]
Hola, he localizado la causa de la caída, por lo tanto puedo identificar plenamente que es lo que causa este error con los valores, pero no puedo garantizar un arreglo rápido.

Ten en cuenta que este tipo de errores vienen de serie, al tomar la decisión administrativa de que MithrandirCraft sea Offline-Mode, estoy firmando un contrato con una gran suma de bugs garantizados que se añaden a la balanza. 

Debes comprender que el servidor a penas recibe donaciones, pero yo estoy mas que encantado de mantener sus funciones básicas, ahora si, no estoy dispuesto a sobreesforzarme para curar los errores que podrían solucionarse con mayor facilidad si el servidor tuviese mayores fondos económicos.

Además, lo que te ha ocurrido a ti, puede haberle ocurrido a cualquier otro jugador. Imagina si yo solo tuviese que ir arreglando las malfunciones de cada jugador afectado, y haciendo todo este trabajo sin que nadie me pague por ello!

Prefiero dedicar mas esfuerzo en la prevención, que en la curación. Y por lo tanto en un principio no solucionaré las malfunciones en inventarios derivadas de estos crashes.

Aún así, me gustaría añadirte a Skype para hablar sobre algo. Si lo haces estaré encantado de compensartelo soluicionando tu problema. 

Pasame tu nombre en skype aquí y hablamos.

**Comment by Ivanovic24** [comment]
agregame mith, creo q me tienes bloqueado por q yo antes era muy pesado:
Ivanovic24

**Comment by Ivanovic24** [comment]
y el tema del bug, lo raro esq a la armadura no le afecta, sabes por que?

**Comment by MithrandirCraft** [comment]
La armadura que llevas puesta?

**Comment by Ivanovic24** [comment]
si la armor no le afecta
