### ISSUE TITLE
¿Antihack excesivo? ¿LAG?

### ISSUE THREAD

**Issue by ZertahhLoL** [MithrandirCraft/MithrandirCraft#301]
Resulta que estoy explorando una mina en la cual ya había estado, y de la nada me encuentro con una pared de esto, en plena mina natural.
![2017-01-07_17 51 56](https://cloud.githubusercontent.com/assets/20175690/21745100/63d6d198-d502-11e6-8bc8-8ea7968f30f4.png)

Vuelvo a repetir, estaba en una mina natural, y me parece un poco excesivo.

Hoy mismo cuando entre al servidor ya notaba un poco de lag para logearme y para hacer /warp, no se si esto se deba a este antihack, al cambio del servidor a network o a que, pero estoy notando mucha latencia en el servidor (lag) y según he leído en otros post muchos jugadores les ocurre lo mismo.

PD: Mi opinión es que con el limitador de minería ya era suficiente, ya limitaba bastante hasta el minar limpiamente y ahora esto que al parecer también genera lag uff...
Atte 
Zertahh

**Comment by MithrandirCraft** [comment]
Hubo muchas quejas sobre el limitador de minería.
Personalmente, soy esceptico acerca de si es el bloqueador de xrays lo que os causa tanto lag. De todos modos, vamos a retirarlo, y a reincorporar el limitador anterior.

**Comment by MithrandirCraft** [comment]
Saludos, aún tienes problemas con este asunto?
Ten en cuenta que si no puedes entrar por el momento, podría deberse a que el servidor ha sido actualizado a 1.11.2

**Comment by ZertahhLoL** [comment]
No puedo comprobarlo en este momento, en unos dias voy a ingresar al servidor y te confirmo.

**Comment by MithrandirCraft** [comment]
Buenas tardes. Podrías indicarme tu proveedor ISP? (Compañía de internet)

**Comment by ZertahhLoL** [comment]
Mi proveedor de internet es Telecentro Argentina.

**Comment by MithrandirCraft** [comment]
Danos tu feedback cuando puedas.

**Comment by ZertahhLoL** [comment]
Ya esta solucionado :+1:  Gracias

**Comment by MithrandirCraft** [comment]
Abre otro ticket si tienes alguna replica.
