### ISSUE TITLE
Problema de lag excesivo desde el cambio a network

### ISSUE THREAD

**Issue by vive36** [MithrandirCraft/MithrandirCraft#302]
Lo he puesto en el foro pero he leido posteriormente que el tema bugs iba aqui. 

Asi que mis disculpas por la duplicidad, desde el cambio hasta hoy segun las horas a las que se entre el lag es increiblemente lento, y te regresa al cabo de unos 30 segundos a la posicion inicial.  En definitiva no te permite jugar, en cambio hay hora sobre todo a partir de las 10 de la noche que el juego se desarrolla de forma totalmente normal incluso muy fluida y correcta.  

En las horas en las que funcionamiento del server es lento, he revisado conexion y conectado a otros server mucho mas lejanos y todo ha ido correctamente, asi que descarto mi equipo y a mi conexión como fuente u origen del problema y por eso escribo aqui. 

Tambien queria comentar el tema de la desparicion de los cerdos cuando los alimentas. 

Un saludo y gracias por la atencion.

**Comment by MithrandirCraft** [comment]
Hola, primeramente, gracias por reportar esto, y disculpa por la demora.

Estamos al corriente de los problemas que estais teniendo algunos jugadores, que parecen afectar a unos mas que a otros.

Somos conscientes y asumimos la responsabilidad por parte del servidor en este asunto.
Lo mejor que puedo decirte es que terminaremos arreglando este problema, sin embargo, no podemos dar una fecha.
El servidor fue transformado a network de forma relativamente reciente, y aún estamos trabajando en pulir varios aspectos.

Todavía no tenemos identificada la causa del lag que sufrís algunos jugadores, pero vuelvo a insistir, lo vamos a solucionar, como hemos solucionado todos los problemas que han surgido durante estos 4 años :)

**Comment by MithrandirCraft** [comment]
Saludos, aún tienes problemas con este asunto?
Ten en cuenta que si no puedes entrar por el momento, podría deberse a que el servidor ha sido actualizado a 1.11.2

**Comment by MithrandirCraft** [comment]
Buenas tardes. Podrías indicarme tu proveedor ISP? (Compañía de internet)
