### ISSUE TITLE
Error o bug?

### ISSUE THREAD

**Issue by iPredictioNz** [MithrandirCraft/MithrandirCraft#303]
Hola

Hoy entre las 11:10 y 11:50 de México,, me encontraba en el End,, al hacer /f Home, se me cancelo el teletransporte y en automatico me envio al spawn con la leyenda:

iPredictioNz ha caído desde muy alto.

Esto es la segunda ocasión que me ocurre, en dos días consecutivos, la primera ocasión pense que habia sido un error mio pero en esta ocasión no estaba parado ni siquiera cerca de algún borde todo lo contrario estaba en el area del Koth

A causa de esta situacióny a llevo perdido lo siguiente

1 p4 completa,, 
1 espada diamante agu 2
1 espada diamante igneo 2, irrompi 3
4 cabezas de zombie 
10 esmes
lo demas lo considero basura ya que era material de mineria

Pero que solución me pueden dar a este error,,, les anexo la pantalla con la leyenda que les indique

![a](https://cloud.githubusercontent.com/assets/25229195/22117513/ed377d76-de39-11e6-8844-bc7ade72755e.png)

**Comment by MithrandirCraft** [comment]
Lo analizaremos.

**Comment by MithrandirCraft** [comment]
No puedo reproducir este problema. Podrías realizar varias pruebas y confirmar como reproducirlo?

**Comment by iPredictioNz** [comment]
Hoy estuve jugando skywars con maurogames, axelar,, y contri,, me desconecte,, a los 5 minutos entro para ir a mi faction  y vuelvo a aparecer muerto ahora no se donde aparecí muerto !!!! Volví a 
perder otra vez:


armadura completa p4
espada con filo 4 irrompi 3 igneo 2 botin 2
1 bloque de diamante
arco con infinidad irrompi 3 y poder 4

 lo demas era basura,, pero es imposible que esto me pase solo por cambiar de mundo !!!

Siguen sin darme una solución,, por un error del server :'(

![2](https://cloud.githubusercontent.com/assets/25229195/22309974/27839482-e313-11e6-9e22-eb3230a8a133.png)
