### ISSUE TITLE
Falta de cofres en mapa de Skywars

### ISSUE THREAD

**Issue by Kinina** [MithrandirCraft/MithrandirCraft#304]
Hola, soy kinina.
Vengo a reportarles que en el mapa Sword de la modalidad Solo en el server de Skywars hay una isla a la que le faltan dos cofres. Al inicio, cada isla tiene 3 cofres, uno en la parte superior de la espada, otro en la superficie y el último en la parte baja de la isla; en esta isla solo existe uno en la parte superior y como nos sucedió un día, la jugadora a la que le tocó estar en ella no seleccionó el kit gratuito y fue bastante penoso ver su frustración al no poder alcanzar el único cofre que había en la isla por falta de equipamiento. Revisamos el día 06 de Febrero del 2017 y este error aún existía. Anexo capturas de la localización de la isla y las fotografías de donde deberían estar los cofres. 

![2017-02-06_15 34 08](https://cloud.githubusercontent.com/assets/25625843/22719644/0bd48152-ed6c-11e6-98d9-0c5db74bc5ab.png)

![2017-02-06_15 36 24](https://cloud.githubusercontent.com/assets/25625843/22719668/2bd97eb2-ed6c-11e6-9b9e-a7d71211c427.png)

![2017-02-06_15 36 32](https://cloud.githubusercontent.com/assets/25625843/22719669/2bdcbe42-ed6c-11e6-8b9b-8f3f43ea310e.png)

![2017-02-06_15 36 22](https://cloud.githubusercontent.com/assets/25625843/22719670/2be1fb3c-ed6c-11e6-8112-397acd527fa9.png)

Ojalá pueda solucionarse este asunto para conservar la igualdad en el juego.

Saludos

**Comment by ChaoFM** [comment]
Gracias por el reporte kinina, no es un fallo prioritario pero lo solucionaremos lo antes posible.
;D

**Comment by ChaoFM** [comment]
Solucionado.
