### ISSUE TITLE
Implementación de FullPvP

### ISSUE THREAD

**Issue by ZertahhLoL** [MithrandirCraft/MithrandirCraft#305]
Hola soy Zertahh
Quería sugerir que se implemente "FullPvP" como un nuevo minijuego.

FullPvP, fue un modo de juego muy popular hace un tiempo, ahora escasea un poco, pero en mi opinión es uno de los mejores minijuegos inventados. Generalmente consiste en un PvP con un kit gratuito de hierro (Armadura, espada de hierro, comida, arco y flechas) donde puedes salir a luchar contra otros jugadores.

Hasta ahora parece lo típico, pero acá viene lo bueno.

•Cofres por todo el mapa con Items / Minerales (por ejemplo) que se reinician cada 5 minutos, pueden contener desde un palo Knockback III hasta una moneda del servidor, o varias, como oro, hierro, pepitas, etc...

○Estos cofres no son compartidos, es decir, un jugador puede tomarlo y si antes de esos 5 minutos otro quiere hacer lo mismo va a poder y el tiempo va a ser individual

• Tiene una tienda donde la moneda del servidor puede ser utilizada para comprar equipamientos mejores.

○Generalmente la moneda son los minerales, los cuales puedes vender para conseguir dinero virtual y por ultimo comprar objetos normales o comprar esmeraldas, con ellas, conseguir equipamientos mucho mas "Chetados" (Por ejemplo: 32 Bloques = 1 Pechera Protección 5/6/7...

•Tiene Cofres Key: Para donantes, Votantes y para koth

○Muy divertido el koth en este modo
○El crate de votantes puede ser modificado u compartido con uno que al asesinar otros jugadores te otorgue una key y seas capaz de conseguirla con /key.

Este minijuego es bastante versátil, puede modificarse demasiado sin arruinarse, ya que siempre va a estar la escencia y la competitividad de el PvP y el objetivo de conseguir armas mejores. También soy consciente de que es muy parecido al kit-pvp pero, a mi parecer es mucho mas competitivo y tiene mas cosas.

Casi todo lo que se modifique queda genial con este modo.

Gracias!

**Comment by MithrandirCraft** [comment]
Me gusta tu sugerencia. Hasta a mi me gustaría jugar a un modo así.

**Comment by ZertahhLoL** [comment]
¿Donde puedo contactar con él? o que debo hacer.

**Comment by MithrandirCraft** [comment]
Se lo he hecho saber. Estamos interesados en la idea de proporcionar una modalidad de pvp similar... no puedo garantizar que sea exactamente lo mismo, pero desde mi punto de vista, la gracia de tal modalidad sería permitir un pvp libre que permita pelear contra varios jugadores a la vez, con algunos potenciadores. En especial facilitando asesinatos multiples sin un desgaste de vida exagerado que vulnerabilize a quien más kills hace.
