### ISSUE TITLE
Mis cosas desaparecieron del enderchest!

### ISSUE THREAD

**Issue by Senpai14** [MithrandirCraft/MithrandirCraft#306]
Lo mas importante que tenia eran como 6 stacks de enderpearls (1 stack de enderpearls= 16 enderpearls) y 2 cabezas de enderman. Esto paso después del reinicio de las 22:30 (hora del servidor) revise mi cofre en survival y ya no había nada.

**Comment by MithrandirCraft** [comment]
Hola, cerraste el ticket. Fue accidental?

**Comment by Senpai14** [comment]
No, me sali del server y me volvi a meter y ya estaban mis cosas asi que mejor cerre el ticket :T


________________________________
De: Mithrandir <notifications@github.com>
Enviado: sábado, 18 de febrero de 2017 02:57 p. m.
Para: MithrandirCraft/MithrandirCraft
Cc: Senpai14; State change
Asunto: Re: [MithrandirCraft/MithrandirCraft] Mis cosas desaparecieron del enderchest! (#306)


Hola, cerraste el ticket. Fue accidental?

**Comment by MithrandirCraft** [comment]
Ah ya entiendo, te dio un glitch visual :) menos mal.
Aveces ocurre que le echas un vistazo a tu enderchest y no aparece nada, suele ser un problema de delay de conexion. En cualquier caso, te hago saber que es imposible perder los objetos del enderchest.
