### ISSUE TITLE
Algunos comandos de casados no funcionan

### ISSUE THREAD

**Issue by Senpai14** [MithrandirCraft/MithrandirCraft#307]
Hace unos días que eh tratado de usar /marry tp con mi pareja pero no funciona y me dice que no tengo el permiso de usar eso. Lo mismo pasa con el /marry home, pero con el /marry pvp lo identifica como si fuera a casar a alguien y me pone ""PvP" no esta conectado". Espero que arreglen estos comandos pronto.

**Comment by Senpai14** [comment]
Después del reinicio de factions siguen sin funcionar

**Comment by ChaoFM** [comment]
Solucionado! 
Postdata: /marry pvp fue eliminado del plugin, los demas ya funcionan ;D
