### ISSUE TITLE
Favor de ayudarme con este problema de bug!!!

### ISSUE THREAD

**Issue by NatWolf26** [MithrandirCraft/MithrandirCraft#308]
Hola... Te digo de que tengo un problemón lo que pasa esque me quitaron mis cosas al teleportearme a una parte estaba en un duelo o duel como quieran decirle pues cuando volvi vi que mi inventario estaba vacio y no es la única vez que me pasa es la segunda vez y aparte estos bugs no me pasan solo ami a casi a todos los perdi en la tarde alas 5:35 P.M  es cuando te matan a veces los fuegos artificiales en duelos y pues eso no me paso, creo pues cuando volvi al spawn de duelos ya no estaban mis cosas en mi inventario

**Comment by ZertahhLoL** [comment]
Tenes que dejar la hora aproximada en que te sucedió esto y en que mundo estabas, si es posible también una lista de lo que perdiste.

**Comment by MithrandirCraft** [comment]
Lo revisaremos.

**Comment by MithrandirCraft** [comment]
Podrías porfavor detallar lo siguiente?:
- A que hora perdiste tu inventario.
- Las circunstancias exactas para reproducir el problema.

**Comment by NatWolf26** [comment]
ya hize lo que me pediste Mith

**Comment by MithrandirCraft** [comment]
Hemos solucionado el problema de perdidas de inventario en Duelos.
