### ISSUE TITLE
Sugerencia deshabilitar el "Entity Cramming"

### ISSUE THREAD

**Issue by ZertahhLoL** [MithrandirCraft/MithrandirCraft#309]
**¿Que es el Entity Cramming?**

Es una mecánica en Minecraft 1.11.2 que lo que hace es evitar que haya mas de 24 mobs en un bloque (cuando llega al numero 25 les hace daño a todos hasta que muera como mínimo 1).

**¿Cual es el problema?**

Granjas de experiencia arruinadas, la mayoría y mas eficientes de ellas son las que los mobs se acumulan en un espacio de 1x1 bloques.

Si se toma la desición de mantener esta mecánica activa, puedo recomendar un vídeo donde explican como hacer una granja para pasar por alto el **Entity Cramming**, pero sería lo mismo que deshabilitarlo.

**Atte
Zertahh.**

**Comment by MithrandirCraft** [comment]
Si se puede evadir, y encima este nuevo factor dificulta mas el farmeo de experiencia (Que esta rotisimo), por que deberíamos arreglarlo nosotros?

**Comment by ZertahhLoL** [comment]
¿Esta permitido utilizar la granja que evita esta mecánica?

**Comment by MithrandirCraft** [comment]
Los bugs de minecraft vanilla no solemos tratarlos por nuestro lado, pero si parcheamos en ocasiones algunas cosas que consideramos afectar negativamente al balance de juego.

Si crees que deberíamos tomar alguna acción haznoslo saber. De lo contrario cierro este ticket y no tomaremos ninguna acción, a no ser que alguien reporte algun problema con ello.

**Comment by ZertahhLoL** [comment]
A pesar de esta mecánica, las granjas siguen funcionando casi perfectamente, lo he comprobado.

Simplemente creo que es un nerfeo mas a las granjas con spawners múltiples, que pueden seguir funcionando con un poco de ingenio para que los mobs no se acumulen.

Cierro el ticket.
