### ISSUE TITLE
Bug con el Plugin /marry al usuario reicon12

### ISSUE THREAD

**Issue by Ivanovic24** [MithrandirCraft/MithrandirCraft#31]
Hola, hoy a las 18:05 hemos casado PvP4ever y luego yo a los usuarios Lesliplay y reicon12.
Cuando pusieron los dos /marry accept, Lesliplay aparecia que estaba casada con reicon12 en el chat, pero reicon12 aparecia que no estaba casado con Lesliplay y cuando ponia /marry kiss decia: no estas casado con ningun jugador.

Fotos:
http://imgur.com/pBv2P9A,suiy25t

**Comment by MithrandirCraft** [comment]
Revisando.

**Comment by MithrandirCraft** [comment]
El problema debería estar arreglado. Si ves a reicon12 o Lesliplay y siguen sin poder hacer nada, reabre este ticket. Necesitaría pillarles conectados para poder forzar un divorcio (debería solucionar el error.)

Preferiblemente, si están interesados en solucionar si problema, que abra uno de ellos un ticket para poder acordar una hora a la que quitarles la relación.

**Comment by Ivanovic24** [comment]
Ok gracias
