### ISSUE TITLE
Sugerencia en el tema de "raidear"

### ISSUE THREAD

**Issue by PvpIsLife** [MithrandirCraft/MithrandirCraft#310]
Nombre de tu jugador en MithrandirCraft :
1lucky
Ambito del servidor en el que podría aplicarse tu idea :
Factions
Idea :
Pues quería comentar el tema de raidear facciones. Solo hay dos métodos para raidear que son : 
- Claimear cuando tienen menos poder que claims.
- Destruir la base con TnT's.
Propondría otro metodo más para poder raidear y es el de "la activación de cofres cuando un integrante de una facción se conecta".
Bien, no voy a dar los pros y los contras ya que se me da fatal expresarme pero pongámonos en 
situación.

MithrandirCraft lleva desde 2012 y es un server (principalmente) de Factions pero hoy en día la gente ha dado de lado esa modalidad de juego y ahora mayoritariamente casi todos están en Survival.

¿Por qué la gente juega más en survival?
Tal vez porque están seguros de sus cosas y nadie les puede robar ni fastidiar pero, ¿que pasa si añadimos "la activación de cofres cuando un integrante de una facción se conecta"?
Pues que toda la gente va a tener más posibilidades de estar entre los mejores en "Factions" ya que siempre están los mismos en el "TOP" y con ese plugin (por así llamarlo) todo el mundo va a poder estar al alcance de esas personas y así estar todos en igualdad de condiciones.

He de comentar que MithrnadirCraft desde 2012, las facciones no se podían explotar con dinamita hasta el 2015/16 (no lo se exactamente) pero, ¿de qué ha servido activar la TNT? Todas las personas están preparadas para defender su base y no hay quien les pille para poder raidear bases. Pues bien, hay influyen los cofres. Tal vez en el exterior no puedan hacer nada pero, si están en el interior de la base y no está activado ese "plugin", ¿de qué les sirve estar adentro? Pues de nada la verdad.

Pues mi propuesta es que activaseis los cofres cuando se conecta alguien ya que casi todos los servers hacen eso. ¡Ojo! No estoy comparando servers. Sino que, desde mi punto de vista, lo veo más fácil para todos y así la gente dejará un poco de lado el Survival para competir contra otras personas ya que el promedio de las personas conectadas a la misma vez cada día son 15 personas y de esas 15 más de la mitad está en Survival.

Nada más que decir, un saludo.

**Comment by MithrandirCraft** [comment]
Interesantes argumentos, y sin duda consideraremos vulnerabilizar los cofres en la situación especifica que indicas, especialmente considerando que no es la primera vez que se sugiere (Intuyo que debido a influencias de servidores externos). Sin embargo, soy esceptico acerca de los beneficios en cuanto a trafico de jugadores que una modificación tan concreta pueda traer en Factions.
Es debatible.

**Comment by MithrandirCraft** [comment]
Los cofres han sido vulnerabilizados 24/7.
