### ISSUE TITLE
Error con la creación de Faction Warps.

### ISSUE THREAD

**Issue by ZertahhLoL** [MithrandirCraft/MithrandirCraft#311]
Ninguno de los comandos ( /f addwarp/setwarp/createwarp) funciona, al intentar usarlos simplemente no existe respuesta por parte de la consola, no dice ni que hubo un error ni que se creo con satisfacción (obviamente tampoco se crea el warp).

Atte:
Vendetta

**Comment by MithrandirCraft** [comment]
Cuando reportaste esto, creo que no funcionaba ningún comando /f.
Lo hemos arreglado, prueba ahora.
Si está solucionado, cierra el ticket.

**Comment by ZertahhLoL** [comment]
Si funcionaban, al menos los que yo utilizaba ( map,sethome,home,title,kick,add).

De todas formas sigue sin funcionar.

**Comment by ZertahhLoL** [comment]
Pd: No se si será reelevante pero yo soy Officer en la faccion, no creador.

**Comment by MithrandirCraft** [comment]
Nose, que ni siquiera te aparezca como mínimo la descripción del comando me parece extraño.

A mi si me aparece, pero he de decir que tengo todos los permisos.

Lo revisaremos.

**Comment by ZertahhLoL** [comment]
Al parecer es un error de cuando sos officer.

Ahora soy lider de la faccion y si me lo permite.

(Tambien cuando cambias los permisos de la faccion con "f perm show" no te permite modificar quien puede y quien no crear warps).

**Comment by MithrandirCraft** [comment]
Me comentan que es un malentendido por tu parte, y qye los warps funcionan perfectamente.
Cierro ticket.
