### ISSUE TITLE
Sugerencia (Cambios en el servidor).

### ISSUE THREAD

**Issue by ZertahhLoL** [MithrandirCraft/MithrandirCraft#312]
Hola, soy Vendetta.

Vengo a proponer una idea que puede aplicarse en todo el servidor y sus instalaciones.Consiste en que todos los cambios que se hagan en el servidor, sean publicados en cualquiera de las redes sociales, tanto así sean casi ínfimos (P.Ej: Que las cajas shulker no puedan almacenarse mas en EnderChest).

Publicarlos para que cada uno pueda expresar su opinión respecto al cambio (que no serían muchos, pero esta bueno dar la oportunidad).

También si es muy molesto andar publicando cada cambio ínfimo que se haga,(EJEMPLO) pueden hacer una lista de los que quieran cambiar y cada semana publicarlos y cambiarlos todos juntos.

Pd: Este me parece un error mínimo y no merece un post, aprovecho para acotarlo aca mismo. Todo el mundo por defecto tiene permisos para abrir los cofres de una faction menos los del rango Miembro.

![asdasdasdqwdeqwdqsfrhgterjrjrfkj](https://cloud.githubusercontent.com/assets/20175690/24734941/ac675e20-1a56-11e7-8757-3a212a209b45.png)

Atte

**Comment by MithrandirCraft** [comment]
Ya lo intentamos, pero la verdad es que quienes más cambios hacen en el servidor, no estan teniendo tambien suficiente tiempo como para anunciarlos.

Siempre nos questionamos si deberíamos o no notificar o consultar a los jugadores antes de aplicar un cambio. Me temo que en esta ocasión, por falta de tiempo nos hemos limitado a realizar el cambio directamente.

Hay algo que nunca cambiará aunque las reglas de juego cambien en Factions, y es que ese servidor contiene un entorno hostil e inseguro, mientras que Survival és un entorno impermeabilizado y seguro.
