### ISSUE TITLE
Torneo de PvP (injusto)

### ISSUE THREAD

**Issue by PvpIsLife** [MithrandirCraft/MithrandirCraft#314]
Pues nada... que es eso, el torneo de PvP por el quinto aniversario del servidor fue básicamente muy injusto.
He de decir que ya se que esta no es la página para reportar a un jugador pero igual lo pongo para que no os hagáis ningún lío yendo desde una página a otra.
He puesto el reporte a TheShadowWither en la página de reportes correspondiente BTW.
Pruebas :
https://youtu.be/OKghLMTCx1E

- TheShadowWither con hacks de combate (Infracción de la norma 1) (prueba visual) min. 03:44 (me golpea a través de la pared y antes también ocurrió lo mismo).
- TheShadowWither al golpear siempre saltaba y si mal no recuerdo eso es Critics y encima me lanzaba críticos todo el rato y no creo que sea casualidad desde el min. 03:41
- TheShadowWither muere por Martiki03 al min. 00:55 y TheShadowWither aparece de nuevo en la sala de PvP.
- Ender pearls disabled min. 02:44 (con previo aviso de que las ender pearls estarían habilitadas.
- Ender pearls disabled aún al min. 03:55 (aún sin solucionar ese "error").
- Ahora que me fijo no se si TheShadowWither lleva antiknockback (prueba visual desde el min. 03:41) (Sin confirmar).

Propongo otro torneo de PvP y que el ganador (axelar) devuelva el deseo que pidió a su normalidad.
Un saludo.
                                                                                                                            1lucky 👤✌️

**Comment by MithrandirCraft** [comment]
Hola, lo primero de todo, este no es lugar para reportar infracciones.
Sin embargo, contestaré esta vez, pero los reportes sobre jugadores y apelaciones deben enviarse exclusivamente al foro.
Contestando en orden:

Efectivamente, tus pruebas son lo suficientemente concluentes como para determinar que el jugador usa hacks, y además, no es la primera vez que este jugador incumple la normativa, por lo que será expulsado de forma permanente. Ten en cuenta tambien que estamos siempre investigando nuevas formas avanzadas de detectar y detener hacks para que nadie tenga que sufrir este tipo de desigualdades en el juego.

Es cierto que dijimos que las enderpearls estaban activadas, sin embargo, esa es una sala donde en la misma puerta pone que no lo están. La verdad es que me equivoqué, pero tampoco lo veo como un motivo por el qual tener que repetir la pelea.

Ten en cuenta que todos los eventos que se hicieron ayer por la tarde los organizamos con muy poco tiempo disponible y como acto simbolico para el quinto aniversario del servidor, así que te aconsejaría que aceptes el resultado y valores el esfuerzo que hicimos por llevarlos a cabo.
