### ISSUE TITLE
Sugerencias para reducir el lag. (PARTICIPACIÓN ABIERTA)

### ISSUE THREAD

**Issue by ZertahhLoL** [MithrandirCraft/MithrandirCraft#315]
Nombre de tu jugador en MithrandirCraft: Vendetta

Ámbito del servidor en el que podría aplicarse tu idea: Muchos

Explicación extensa de en que consiste tu idea, como crees que puede aplicarse, y como beneficiaría al servidor: El servidor tiene pocos jugadores, algunos que llegan se van porque no les gusta, y muchos otros porque no pueden jugar debido al lag de fps que produce, me incluyo, aunque por suerte lo mio si puede soportarse. Cada ves que voy al warp pueblo tengo 20 fps.

Soluciones:
Dejar de usar tantos bloques semitransparentes como estos.
![aaaa](https://cloud.githubusercontent.com/assets/20175690/24833751/05da876c-1ca9-11e7-8228-8fcf5aa7344f.png) (pueden reemplazarse los vidrios por bloques transparentes, barriers block)

![sin titulo](https://cloud.githubusercontent.com/assets/20175690/24833753/05dd747c-1ca9-11e7-9283-25dfa3eded34.png) (puede ser reemplazado, por ejemplo, por hojas de arbol.

![aaaaawedqw](https://cloud.githubusercontent.com/assets/20175690/24833752/05db778a-1ca9-11e7-8a77-907f0e144aaf.png) Este aura no me permite hacer pvp, cada ves que golpeo a un jugador tengo 5 fps, hable con Martiki03 sobre el tema y a el también le da lag, como supongo que a muchos otros.

Son pequeños detalles pero que todos juntos perjudican la experiencia en mithrandircraft, hay muchos mas pero no puedo mostrarlos a todos.

Las construcciones para evitar esto deberían ser hechas mas con bloques sólidos (la arcilla es un gran ejemplo), ladrillos, etc...

**Comment by MithrandirCraft** [comment]
Ufff... pero te das cuenta de que lo que estas reportando son bajones de fps?
Es difícil dar causas especificas a lo que experimentas (Puedes formular las teorías que quieras, pero al final yo creo que se trata de tu propio hardware), pero yo puedo decir que no he tenido ningún problema con el frame rate desde que lleva el servidor abierto, claro que juego desde un ordenador bastante decente (Incluso desde un portatil no tengo problemas, y con una cuenta normal).
Normalmente se atribuye el frame rate a una mancanza de hardware local, y no del servidor. Pero, también se pueden hacer cosas de nuestro lado para mejorar el framerate... Sin embargo, dudo mucho que podamos ayudarte demasiado en ello.

La verdad, no se ni que decirte. Si quieres que intentemos reducir el numero de bloques de ese tipo, podemos hacerlo, pero se supone que Minecraft en si debería estar lo suficientemente optimizado como para que elementos tan triviales como "que bloques hay en el mapa" afecten al rendimiento de tu juego.
Que te dan lag esos contornos? bueno, la verdad es que es la primera vez que lo oigo xD bastante singular lo que indicas.

**Comment by ZertahhLoL** [comment]
Con que quiten el aura en pvp me es suficiente, yo juego factions en el servidor y no puedo realizar un pvp comodamente.

Abajo te voy a dejar una explicación extensa sobre lo que ocurre, por si te interesa **(no justifica nada, solo para que comprendas que lo que produce el lag, no es un simple bloque con textura transparente).**

"se supone que Minecraft en si debería estar lo suficientemente optimizado como para que elementos tan triviales como "que bloques hay en el mapa" afecten al rendimiento de tu juego" : Sí, es verdad, pero los mismos desarrolladores han dicho que el código del juego fue hecho a lo "chapuza" por que utiliza java en ves de un motor gráfico, esto provoca que elementos tan simples como un vidrio transparente se transformen en un problema con los recursos que consumen. mucha gente que tiene buenas pc les anda lag Minecraft.

Ejemplo: Tienen un cuadrado y quieren hacerlo mas pequeño, en ves de recortarlo para hacer todo mas simple y fluido, por falta de presupuesto simplemente lo doblan y complican el proceso.

**Comment by ChaoFM** [comment]
Buenas Vendetta, debo decirte que es completamente problema de tu ordenador, que es demasiado básico para disfrutar del Minecraft a 100%. A mi en el pueblo me va a mas de 100 fps y en ocasiones me baja como máximo a 80 fps pero de ahi no baja mas, tengo todos los gráficos al máximo y la distancia de renderizado a 13 chunks.
![captura de pantalla 2017-04-09 a las 22 53 42](https://cloud.githubusercontent.com/assets/25326191/24840957/6ecc4664-1d78-11e7-9ec8-836aac2aab52.png)

**Comment by MithrandirCraft** [comment]
Sobretodo ten en cuenta que no tratamos de ofender. Lo que nos comentas es 100% comprensible, y podemos trabajar desde nuestro lado en aportar un entorno con elementos que no den tanto lag.

Sin embargo si es cierto que solo podemos llegar hasta cierto punto (sobretodo si se trata de frames), y creo que deberías considerar mejorar tu equipo.

Y si, Minecraft és un juego exigente en cuanto a memoria y consumo de cpu. Pero no deberías subestimar la conciencia con la que se hizo a la hora de programarlo eficientemente, a pesar de que Notch decidió desarrollarlo en Java originalmente (Un lenguaje que no suele ser elegido a la hora de programar videojuegos). Te lo digo yo como aprendiz de programador de videojuegos que soy, ya que considero poder apreciarlo.

**Comment by ZertahhLoL** [comment]
Ok, voy a realizar una serie de pruebas para comprobar que causa mi lag.

Muy pocas veces tengo lag en otros servers, en mithrandircraft solo en el pueblo. En singleplayer tengo de 80 a 65 fps, juego con 250 ms en mithrandircraft, en otros llego a los 300 y no tengo lag.

De todas formas no importa. Solo les pido que desactiven el aura roja en pvp, no es tan necesaria y a varios les produce lag.
