### ISSUE TITLE
El servidor no reconoce mi contraseña

### ISSUE THREAD

**Issue by Arlopis** [MithrandirCraft/MithrandirCraft#318]
No se que pasa, pero intento logearme como siempre y no se me permite. Hoy estuve jugando normalmente, fui a hacer otra cosa y cuando volví e intenté logearme de la forma usual, no me reconoce la contraseña. Agradeceré mucho que me ayuden. Mi nombre de usuario en el juego es Arlopa.

**Comment by MithrandirCraft** [comment]
Estoy bastante seguro de que el sistema de contraseñas funciona perfectamente (Lleva 5 años funcionando bien), claro que no podría descartar un error puntual.

Sin embargo debes comprender que primero considere una equivocación por tu parte.
- Asegurate de que la estás escribiendo bien.
- Recuerda que compartir tu cuenta con otras personas es peligroso y está prohibido, y podría resultar en un robo de cuenta, en cuyo caso no nos hacemos responsables tal como indica la normativa..
- Cuando te registraste por primera vez, se te indicó encarecidamente la importancia de registrar tambien un email, para poder restablecer tu contraseña. Si no lo hiciste, la situación se complica, de lo contrario puedes restablecer tu contraseña con el comando /email (puedes ejecutarlo entrando al servidor sin loguear).

Si eres incapaz de resolver el problema de acceso pasando por estos pasos, hazmelo saber.

**Comment by Arlopis** [comment]
Ciertamente no le he dado mi contraseña a nadie y es la misma con la que he jugado desde que entre por primera vez al servidor, de hecho, estuve jugando normalmente, sali un rato y mas tarde cuando intenté ingresar, no pude. No creo haber registrado mi correo, claro error de mi parte, soy bastante nueva en esto y me ya fue dificil el simple hecho de registrar la cuenta sin vincuar el correo. Bueno, si no hay nada que hacer al respecto, gracias de todas formas.

**Comment by MithrandirCraft** [comment]
Hemos recibido varios reportes más sobre el problema que describes, aunque lo que me está llegando a mi personalmente son reportes de que "Hay un extraño lag al introducir la contraseña" o "Es dificil escribir"
No parece ocurrirles a todos.
En respuesta hemos actualizado el sistema de contraseñas a su version mas reciente. Vuelve a intentar loguearte mañana a partir de las 13:00h, después del reinicio.

**Comment by Arlopis** [comment]
Lo que me ocurre particularmente es que escribo: "/login contraseña" le doy a Enter y no ocurre nada. Es como si me ignorara, como si no hubiese escrito nada. He registrado mi correo en el sitio web con mi nombre de usuario y mi contraseña y me las aceptó. Lo único es que no puedo loguearme en el juego mismo. Hice distintos intentos, como intentar registrar con "/register contraseña" y me sale el mensaje de que el usuario ya está en uso, lo que me indica que mi contraseña es la correcta, porque dudo que alguien más use una igual (es una contraseña muy personal con letras y números). Lo más probable es que ocurre lo que tú dices, así que intentaré loguearme mañana después del reinicio. Debo agregar que mi hermano tampoco puede ingresar desde su ordenador con sus datos, es por eso que me pareció improbable que las dos contraseñas estuviesen equivocadas. 
Saludos y gracias por tu preocupación respecto al tema.

**Comment by TeamLittenFTW** [comment]
a mi me pasa igual

**Comment by PvpIsLife** [comment]
Si no tienes respuesta del servidor procura poner /login (en minúscula), tal vez sea eso.

**Comment by Arlopis** [comment]
No. Definitivamente no me deja loguearme aunque mi hermano si pudo.

**Comment by MithrandirCraft** [comment]
https://discord.gg/x79uVfS Entra y enviame un mensaje.

**Comment by MithrandirCraft** [comment]
arreglado.
