### ISSUE TITLE
Bug del agua y de las ender perls

### ISSUE THREAD

**Issue by Martiki03** [MithrandirCraft/MithrandirCraft#319]
Hola, quería comentarles 2 bugs.
1)Cuando se acepta tpa estando en el agua te teleporta a la parte de arríva de donde estas ejemplo: estas en una cueva y aceptas el tpa y estas en el agua, el que se teleporta aparece en la superficie.
2)Cuando lanzas una enderperl a una esquina o borde, te deja bugeado en donde lanzaste la enderperls y si alguien te manda tpa y aceptas, la persona que se teleporta, aparece arríva o el lugar mas cercano y seguro de donde estas bugeado. (no te manda tan lejos, solo a 2 o 3 bloques de distancia de donde estas bugeado).

**Comment by MithrandirCraft** [comment]
1. No puedo reproducirlo. Puedes detallar más concretamente o grabarlo tu mismo?:
https://youtu.be/Y2ekNs8OmFA

2. Lo he verificado. Es un bug de Minecraft vanilla, muy similar al que había de atravesar suelos hace tiempo.
https://youtu.be/Y2ekNs8OmFA

**Comment by MithrandirCraft** [comment]
Me han pasado un video sobre el bug #1, así que lo considero reproducible:
https://youtu.be/H2d7NefPK0c

**Comment by MithrandirCraft** [comment]
Solucionado.
