### ISSUE TITLE
Muerte en el Limite del Mundo

### ISSUE THREAD

**Issue by Ivanovic24** [MithrandirCraft/MithrandirCraft#32]
Hola, hoy SpainDut6y y yo hemos muerto como idiotas en el limite del mundo por tirar una enderpearl afuera :C. Me preguntaria si pudieran cambiar eso, que no mueras al tirar una enderpearl fuera del mundo, que pasara como antes que era q te teletrasportabas de nuevo al sitio. 

Un Saludo

**Comment by MithrandirCraft** [comment]
Yo personalmente lo considero un buen handicap, a cambio de tener la oportunidad de encontrarte en un punto del mapa donde no puedes seguir avanzando, o tener una facción con uno de sus lados protegido por la barrera...

Me temo que no voy a cambiar esto. Ve con más cuidado.
