### ISSUE TITLE
Error con la creación de Faction Warps.

### ISSUE THREAD

**Issue by PvpIsLife** [MithrandirCraft/MithrandirCraft#320]
ZertahhLoL commented on Apr 1
Ninguno de los comandos ( /f addwarp/setwarp/createwarp) funciona, al intentar usarlos simplemente no existe respuesta por parte de la consola, no dice ni que hubo un error ni que se creo con satisfacción (obviamente tampoco se crea el warp).

Atte:
Vendetta

-----------------------------------------------------------------------------------------------------------------------
Pues bueno, al parecer el comando /f addwarp/setwarp/createwarp funcionan correctamente al utilizarlos. Siendo líder de una faction puedes crear y borrar warps como si nada pero, al ser officer no puedes crear un warp (esto ocurre cuando borras un warp de tu faction). Por eso está ese "bug".
                                                                                                                                                             1lucky

**Comment by MithrandirCraft** [comment]
Hola. Me han comunicado que el sistema de warps fue retirado, no es que no funcionase, es que aparentemente a penas nadie lo utilizaba según me comentan.
Consecuentemente procedo a cerrar el ticket.

**Comment by MithrandirCraft** [comment]
Ah, parece ser que el sistema quizá si se conservó, en cuyo caso me comentan que ya debería estar funcionando.
