### ISSUE TITLE
Sugerencia para mejorar la economía y el juego

### ISSUE THREAD

**Issue by alexaviermu** [MithrandirCraft/MithrandirCraft#321]
_**Propuesta sistema de economía**_

He pillado un sistema de economía que permite a los jugadores intercambiar bienes de forma justa y prosperar de forma que cada vez más quieren participar y seguir jugando. El año anterior, en mi facción hemos implementado un sistema de mercados que consistían en dar acceso a todos los habitantes de una ciudad a un edificio donde colocaban ofertas de compra y venta en cofres. En la siguiente imágen se aprecia como intercambiabas bienes, eso dependía de la palabra del comprador de hacer lo justo y no robar. Al principio intercambiaban cosas por cosas, pero con el tiempo renombramos en un yunque las pepitas de oro a "denarios" y todo vendían y compraban usando "denarios"

![mercado roma](https://user-images.githubusercontent.com/30022819/27996269-22ab4618-64a4-11e7-98aa-7dbee63f890b.jpg)

A los habitantes les gustaba mucho esta forma, sin embargo el primer imperio colapsó con una conquista sistemática de las facciones bárbaras a todas sus ciudades. He dado vueltas por algunos servidores y me he topado con un sistema que aplica el uso del "/money" que es exactamente lo mismo que la cantidad virtual que se utiliza en facciones para los claim, solamente que aplicado al intercambio de bienes en cofres, en vez de "denarios" A continuación un ejemplo de como son estos cofres:

![nuevomercado2](https://user-images.githubusercontent.com/30022819/27996270-2dfdb582-64a4-11e7-9d72-8ef864eb0347.jpg)

En estos cofres hay dos casos, [buy] "comprar" y [sell] vender
en el de comprar, el usuario coloca un cofre y un cartel, en la primera fila coloca su nombre, en la segunda pone [buy] "para activar el comando". En la tercela fila pone la cantidad y el nombre del item. Y en la cuarta fila pone el precio en /money "dinero". Luego que el cartel está listo, el usuario debe tener dinero en su cuenta, y los mercaderes que se acerquen al cofre tendran el item en su mano (el que el usuario dice comprar en el cofre) y harán clik izquierdo sobre el cartel, entonces el item desaparecerá de sus manos directo al cofre, y el saldo de la cuenta del usuario irá a la cuenta del mercader.

En el segundo caso [sell] "vender" el usuario coloca igualmente su nombre en la primera fila, el comando [sell] en la segunda. El numero de items que vende por cada clik y el tipo de item en la tercera fila. Y el precio en /money "dinero virtual" en la cuarta fila. A continuación deberá colocar el item que dice vender dentro del cofre, cuanto más items coloque, más tiempo tardará en agotarse el stock del cofre tienda. Seguido el mercader que quiera comprar deberá tener saldo en su cuenta y hacer clik derecho sobre el cartel del cofre, su saldo se transferirá a la cuenta del vendedor y el item o numero de items comprados debido al numero de cliks que haga irá del cofre a las manos del jugador.

**Comment by MithrandirCraft** [comment]
Si, somos 100% conscientes de como funciona una economía numerica. Y en mith tambien la hemos implementado, sin embargo acabar de implementarla del todo arruinaría completamente el sistema actual basado en esmeraldas. No se como lo ves.

**Comment by alexaviermu** [comment]
En una humilde opinión, habría que darle un uso útil al dinero virtual, de fácil acceso y sobre todo, que no solamente sea usado con un fin a tradear cosas con NPC's sino que sirva de forma de intercambio entre los propios usuarios, y este podría ser un verdadero fin último, una forma de intercambio entre los jugadores, que les sea una herramienta y un incentivo a jugar y quedarse en el server, que un impedimento o dificultad, esto tiene que ver mucho con descentralizar las libertades, las esmeraldas son de difícil acceso. Sin embargo, no las destruiría, porque las esmeraldas son como el oro o diamantes en la vida real, una acumulación de mucho dinero, imaginate que para ir a comprar un taro de leche o una funda de doritos tengas que usar diamantes, casi nadie podría comer.

Es posible que sea una forma útil: "que la moneda de intercambio sea de fácil acceso para los jugadores al tener libertad de mercado (crear cofres y carteles con madera para un mercado privado) que la armadura prote 1 de fac sea para los chicos de survival, y en facs que empiecen desde 0 o si mismo quieren con armadura de cuero, pero no muy exagerado, con esto quiero decir que haya igualdad de comienzo para todos, no que unos tengan cosas que otros no tienen (al inicio) de allí, si las personas trabajan por tener algo diferente, eso si lo consiguen por ellos mismos, entonces es justo"

**Comment by alexaviermu** [comment]
En una humilde opinión, habría que darle un uso útil al dinero virtual, de fácil acceso y sobre todo, que no solamente sea usado con un fin a tradear cosas con NPC's sino que sirva de forma de intercambio entre los propios usuarios, y este podría ser un verdadero fin último, una forma de intercambio entre los jugadores, que les sea una herramienta y un incentivo a jugar y quedarse en el server, que un impedimento o dificultad, esto tiene que ver mucho con descentralizar las libertades, las esmeraldas son de difícil acceso. Sin embargo, no las destruiría, porque las esmeraldas son como el oro o diamantes en la vida real, una acumulación de mucho dinero, imaginate que para ir a comprar un taro de leche o una funda de doritos tengas que usar diamantes, casi nadie podría comer. Mira ejemplo, Venezuela, la comida cuesta casi como si fuera un lingote de oro real o diamantes, nadie come. Es verdad que en minecraft puedes cazar animales y comer rápido, pero lo que se busca con el mercado, es fomentar el intercambio de comida, suponiendo el caso de que un jugador no sepa como conseguir alimento ya que se dedica a fabricar productos de otro tipo, cuando se trate de intercambios a gran escala.

Es posible que sea una forma útil: "que la moneda de intercambio sea de fácil acceso para los jugadores al tener libertad de mercado (crear cofres y carteles con madera para un mercado privado) que la armadura prote 1 de fac sea para los chicos de survival, y en facs que empiecen desde 0 o si mismo quieren con armadura de cuero, pero no muy exagerado, con esto quiero decir que haya igualdad de comienzo para todos, no que unos tengan cosas que otros no tienen (al inicio) de allí, si las personas trabajan por tener algo diferente, eso si lo consiguen por ellos mismos, entonces es justo"

**Comment by MithrandirCraft** [comment]
Bueno, de momento he aplicado los siguientes ajustes:
- Las esmeraldas y Bloques de esmeralda son ahora reversibles a economía numerica. Pueden venderse por un precio similar al que se compran. (Menor)
- www.mithrandircraft.es/economia -> Revisa el nuevo esquema de tiers en cuanto a monedas que he colocado en la cabezera de la página. Básicamente se ha incorporado una moneda oficial por debajo de la esmeralda. Sientete libre de utilizarla, o no. Pero debería ayudarte si lo que quieres es vender objetos que son mas baratos que una esmeralda, ya que ahora acumulando x64 pepitas de oro (Especiales) puedes sacar una esmeralda entera.

En cuanto a los usos del credito numerico, efectivamente tenemos intención de aumentar su variedad de aplicaciones. Sin embargo, ofrecer objetos a cambio de credito numerico directo no entra en nuestros esquemas, ya que la economía de intercambios se basa en la esmeralda en MithrandirCraft.

**Comment by MithrandirCraft** [comment]
Procedo a cerrar el tema tal como acordé. Ha pasado 1 semana y no ha habido respuesta.
