### ISSUE TITLE
Problema de cofres y leyes

### ISSUE THREAD

**Issue by alexaviermu** [MithrandirCraft/MithrandirCraft#322]
Anarquía en Facciones
(Tengo un problema bien grave de órden interno)

ImperivmRomanvm
![roma_sicilia](https://user-images.githubusercontent.com/30022819/27996296-b128e080-64a4-11e7-9530-47511fd6f073.jpg)

Saludos, quisiera sugerir por favor que dentro de una facción, los nuevos reclutas no puedan acceder a todo cofre que quieran, solamente los que tengan /f access o sean miembros o rangos más altos porque cualquier recluta que ingresa a la fac puede ir a los terrenos que son propiedad de otros miembros con acceso exclusivo y pueden tomar objetos de sus cofres, en el Imperivm al principio con hacks robaban bovedas de obsidiana en el edificio de gobierno, pero eso no va, en otro caso ya hubo un caso de robo solamente por reclutas nuevos que pillan en el edificio de gobernación, la cosa es,, pues hace unos meses esto no era asi, con el /f access podía poner órden sobre quien puede hacer qué en ciertos claims y así establecer un órden de propiedades y derechos, de restringirlos así como de otorgarlos, por favor si hubiera alguna forma de restituir esta pieza esto se lo agradecería mucho.

El punto es, que un nuevo y simple recluta no pueda abrir todos los cofres que quiera, solamente si es ascendido o si tiene permisos especiales de acceso a cierto claim, explico, bastaba con darle /f access p nombredenuevorecluta. sobre uno o varios claims y ese jugador podia administrar dentro de la faction con la seguridad de no estar en wildernes, pero tampoco de afectar a los demás jugadores, hoy esta tuerca faltante en el sistema establece una anarquía que promete a los jugadores estar por encima de nuestra ley.

Lo que pasa es que he traido jugadores nuevos al server para evitar los multicuenta de las facs enemigas, pero lo que sucede es que los roban, se roben entre ellos, lo que consiguen y trabajan con esfuerzo, de seguro no les gusta y lo que pasa es que no han regresado.

![bloqueo sicilia](https://user-images.githubusercontent.com/30022819/27996295-a40ee552-64a4-11e7-8bf5-46af5af2046f.jpg)

Se han bloqueado los accesos a viviendas, fábricas y la gobernación temporalmente para evitar saqueos

**Comment by MithrandirCraft** [comment]
Hola, quiero hacer claros unos puntos, y comentar unas dudas:
**Aclaraciones:**
- Aunque los nuevos reclutas sean vetados de abrir cofres e interactuar con puertas y palancas. Nada les impide abandonar tu facción para formar parte del tag "Neutral" o "Enemigo", y entonces robarte.
- Una facción siempre és insegura, y corresponde a los jugadores confiar en sus compañeros. Las traiciones tambien forman parte del juego.
**Dudas:**
- No entiendo como modificar el acceso por defecto de un jugador recluta en tu facción, ayudaría a que consigas organizarla mejor internamente. Concretamente no se que tenga que ver /f access (Comando que permite acceso a personas externas a la facción)

**Comment by MithrandirCraft** [comment]
Procedo a cerrar este ticket. Sin respuesta. Lo consideraré solucionado.
