### ISSUE TITLE
Propuesta de libertad de mercado

### ISSUE THREAD

**Issue by alexaviermu** [MithrandirCraft/MithrandirCraft#323]
En una humilde opinión, habría que darle un uso útil al dinero virtual, de fácil acceso y sobre todo, que no solamente sea usado con un fin a tradear cosas con NPC's sino que sirva de forma de intercambio entre los propios usuarios, y este podría ser un verdadero fin último, una forma de intercambio entre los jugadores, que les sea una herramienta y un incentivo a jugar y quedarse en el server, que un impedimento o dificultad, esto tiene que ver mucho con descentralizar las libertades, las esmeraldas son de difícil acceso. Sin embargo, no las destruiría, porque las esmeraldas son como el oro o diamantes en la vida real, una acumulación de mucho dinero, imaginate que para ir a comprar un taro de leche o una funda de doritos tengas que usar diamantes, casi nadie podría comer. Mira ejemplo, Venezuela, la comida cuesta casi como si fuera un lingote de oro real o diamantes, nadie come. Es verdad que en minecraft puedes cazar animales y comer rápido, pero lo que se busca con el mercado, es fomentar el intercambio de comida, suponiendo el caso de que un jugador no sepa como conseguir alimento ya que se dedica a fabricar productos de metales.

Es posible que sea una forma útil: "que la moneda de intercambio sea de fácil acceso para los jugadores al tener libertad de mercado (crear cofres y carteles con madera para un mercado privado) que la armadura prote 1 de fac sea para los chicos de survival, y en facs que empiecen desde 0 o si mismo quieren con armadura de cuero, pero no muy exagerado, con esto quiero decir que haya igualdad de comienzo para todos, no que unos tengan cosas que otros no tienen (al inicio) de allí, si las personas trabajan por tener algo diferente, eso si lo consiguen por ellos mismos, entonces es justo"

**Comment by MithrandirCraft** [comment]
Esto se parece mucho al tema que ya abriste referente a economía, así que voy a tener que cerrarlo como duplicado. Si quieres postealo allí.
