### ISSUE TITLE
Problemas de Conexión.

### ISSUE THREAD

**Issue by Nosekponer** [MithrandirCraft/MithrandirCraft#324]
Buenas :)

Tengo un problema con el servidor, siquiera me establece la conexión antes de entrar y cuando entro me aparece el típico mensaje de " No further information " 

Ya probé cambiándome el nombre miles de veces y con las dos ip :'(

![image](https://user-images.githubusercontent.com/30179036/28214890-6c6cd9ba-6882-11e7-97ba-06d0c556573e.png)

![image](https://user-images.githubusercontent.com/30179036/28214904-788603c0-6882-11e7-8f02-c262b17aca6f.png)

Gracias.

**Comment by MithrandirCraft** [comment]
Quales son las 2 IP's? Solo para estar seguros de que las estas poniendo bien.

**Comment by Nosekponer** [comment]
play.mithrandircraft.es y 213.251.187.7

**Comment by MithrandirCraft** [comment]
Has probado otros servidores, utilizas los clientes indicados en: www.mithrandircraft.es/descargas?

**Comment by Nosekponer** [comment]
Sí, uso el Shiginima launcher en su ultima versión y también me deja jugar algunos otros servidores, he de aclarar que mithrandircraft no es el único que no me deja entrar.

**Comment by MithrandirCraft** [comment]
Hmmm vale, curioso, y esos otros servidores son accesibles a otros imagino.
Usas algún proxy/vpn para conectarte? Sabes si tu IP está baneada en alguna lista negra global?
Probaste reiniciar tu router? Has probado desde otro equipo/red?

**Comment by Nosekponer** [comment]
Que yo sepa no uso ningún proxy ni vpn.
No sé si mi ip esta baneada, ¿Como puedo saberlo?
Desde otro equipo si me lo permite, en la misma red, en otra pc que anda a 5 fps (por eso no la utilizo para entrar.

**Comment by MithrandirCraft** [comment]
Interesante, probaste desactivar tu firewall aver si eso lo soluciona?
Si desactivandolo puedes entrar, significa que hay alguna regla bloqueando el trafico.
Sobretodo manten el firewall encendido, es mas importante que que accedas a nuestro servidor xD Si hay algun problema con ello echale un ojo a las reglas aver si hay algo bloqueando.

Perdona por tardar tanto en contestar.

**Comment by Nosekponer** [comment]
Lo de las reglas ya lo hice :( pero bueno no podré entrar con sta pc :'(

**Comment by MithrandirCraft** [comment]
Prueba desactivar el firewall completamente, como te he sugerido.

**Comment by Nosekponer** [comment]
No funciona :/.

Bueno gracias por su tiempo voy a ver como lo soluciono.
 
Disculpá las molestias :p

**Comment by MithrandirCraft** [comment]
Ya no se que mas decirte xD. Es posible establecer una conexión con nuestra IP, mas allá de eso no veo ninguna otra razón para que no puedas acceder.
Cierro ticket.
