### ISSUE TITLE
Sugerencia de un servidor para beneficio de los jugadores y contribuyentes de igual manera

### ISSUE THREAD

**Issue by alexaviermu** [MithrandirCraft/MithrandirCraft#325]
Dejo esta sugerencia en la búsqueda de una causa común, Mithrandir, sí considera que esta sugerencia es perjudicial, hágase caer todo el peso de la ley, ya que he sido kickeado por ciertas personas al expresar una opinión justa, que no debería confundirse con insultos.
Debes estar consciente de lo que sucede aquí.
Un usuario con rango, y o cualquier cargo superior a los demás no está para kickear a alguien durante un combate para que le roben sus items e invadan su hogar. De lo contrario el jugador se irá del servidor ya que su moral le indica que lo que sucedió no es justo.
Un usuario con rango, y o cualquier cargo superior a los demás no está para insultar a los jugadores creyendo así obtener una victoria, perdonando a sus amigos con cargos altos ante los reclamos de los demás. De lo contrario el jugador se irá del servidor.
Un usuario con rango, y o cualquier cargo superior no está para hacer que lo teman haciendo trampa y corrupción a cada momento porque por encima de su risa, causan disgusto a las personas que de verdad pueden servir de algo, entonces los jugadores se cansan, y se irán del servidor.
Un usuario con rango, y o cualquier cargo superior no está para volar por ahí y destruir viviendas con tnt del inventario creativo. De lo contrario los jugadores se irán del servidor.
Porque tener un cargo o rango no es motivo de beneficio personal, sino es una búsqueda por un bien común, diferente es alguien que quiera ser vip y tenga cositas extra, en comparación a alguien que quiera llegar a un puesto administrativo para poner la ley de cabeza y ser un rey pisando sobre los demás, más aún un gran problema si todo está arreglado para que esto continúe y no estés al tanto, mil perdones, repito, por esta sugerencia.

**Comment by MithrandirCraft** [comment]
No he sido capaz de localizar tu sugerencia en tu texto. Sin embargo, estoy deacuerdo con lo que dices.
No acabo de entenderlo pero, estás quizá reportando un suceso que encaje con precisamente las garantías que reivindicas? Si es así, me gustaría recibir más detalles.
Tal como se establece aquí: www.mithrandircraft.es/normas
Los staff no abusarán de sus poderes en ningún caso ingame. (Y de hecho tienen normas adicionales).
Por lo tanto creo que puedes estar tranquilo.

**Comment by alexaviermu** [comment]
Mith, rafaelox, mickey y rdzperez estan haciendo trampa, y estan haciendo todo eso, ellos tienen rango de Mod o algo asi y matan a traves de las paredes, estan comunicandome eso algunos jugadores, ademas banean cuando ellos les dicen eso y hacen como si con sus cargos pudieran decir que hacer a los demás, como te digo ellos no les importa sacar personas les gusta las cosas sin sentido alguno, obtener cosas y cosas, y no importa lo que hagan, enserio te digo estan tontos, disculpa por la palabra, pero es asi, y esto no es ninguna mentira, aqui tengo unas pocas imagenes de lo que te dicen: a las 19:00 aprox mataron unos perros y a nicogarces a traves de las paredes, hace dias anteriores mataron a un jugador Daniel baneandolo en combate para quitarle sus cosas y su fac con el poder perdido
![12344](https://user-images.githubusercontent.com/30022819/28504422-624fdfb6-6fdc-11e7-870f-ed826bb38400.jpg)

**Comment by MithrandirCraft** [comment]
Voy a investigar estos casos, pero no estás proporcionando suficiente información.
Detecto 2 acusaciones que son preocupantes sobre lo que dices:
- Atacar a través de las paredes (En cuyo caso creo que deberías proporcionar pruebas visuales)
- Banear en meneficio propio (Inflicción de una de las normas de moderación)
En las fotos que nos has pasado solo detecto un montón de amenazas tanto por tu parte como de la suya, y me hace pensar que simplemente estás asustado y no comprendes como funciona el sistema de moderación y el staff en general. Pero por eso estamos aquí para resolverlo, o detectar si realmente se ha incumplido una norma.
Esto es todo lo que necesito para investigar las acusaciones que comentas:
- Hora a la que ocurrió/ocurrieron la/s expulsiones que se aplicaron injustamente y para ventajas en pvp.
- Lista concreta de staff/s acusado/s.
- Evidencia visual de que uno puede atacar por las paredes, o documentación acerca del hack.
- Opcional: Cualquier otra evidencia visual acerca de las expulsiones y/o hacks.

Por cierto, rafaelox24 ya no forma parte del staff, por lo tanto no necesitas incluirle.

**Comment by MithrandirCraft** [comment]
Cerrando ticket. Ha pasado + de 1 semana, y sin respuesta.
