### ISSUE TITLE
Error o bug al querer accesar al server de factions

### ISSUE THREAD

**Issue by blaCkieStar92** [MithrandirCraft/MithrandirCraft#326]
A las 6:00 am hora del servidor me encontraba en warp pvp en la sala 1 luchando contra otro jugador y de pronto el servidor me hecho y cuando quise acceder de nuevo al servidor de factions no me dejo entrar; a lo que procedí a reiniciar el juego, la lap, el modem y me seguía mostrando "conexión perdida con el servidor" o "se ha anulado una conexión establecida por el software en su equipo host" y cabe señalar que esto esta sucediendo solo con mi cuenta Premium que es blaCkieStar92.

Anexo las capturas de los mensajes que aparecen cuando trato de ingresar.
![2017-08-21_10 03 33](https://user-images.githubusercontent.com/31215694/29526624-e2d9d782-865b-11e7-8d19-bc10788bf111.png)
![2017-08-21_10 04 01](https://user-images.githubusercontent.com/31215694/29526629-e903bac4-865b-11e7-9402-bf4a5a0abbc5.png)

**Comment by MithrandirCraft** [comment]
Con que versión te conectas?
Supongo que no puedes loguear desde entonces, no?

**Comment by blaCkieStar92** [comment]
Entró con las version 1.8 y la 1.12.1,  y con ninguna me dejó acceder.

**Comment by MithrandirCraft** [comment]
Vale, intentaste entrar desde 1.8. Pero el problema te surgió estando en 1.12.1?

**Comment by blaCkieStar92** [comment]
No, surgió estando en la 1.8 y posterior trate de entrar con la 1.12.1 y no me dejó

**Comment by MithrandirCraft** [comment]
Exacto... ese es el problema.
Si estás por discord mandame un mensaje para hacer pruebas.
Te ocurre solo en Factions? Puedes entrar a la hub supongo, y a otros servidores?

**Comment by MithrandirCraft** [comment]
Solucionado.
