### ISSUE TITLE
Bug

### ISSUE THREAD

**Issue by PokeFury** [MithrandirCraft/MithrandirCraft#327]
Me mori en el DIRIGIBLE luego fui al SPAWN DE FACTIONS deje mi muñeco ahi y me fui alrededor de 30 min. cuando volvi me saco por inactividad y volvi a entrar, apareci muerto y sin nada . perdi muchas cosas de la nada.

**Comment by MithrandirCraft** [comment]
Hola.
Seguramente te mató un mob. La razón es que los zombies escarlata, esmeralda y cobalto SI aparecen en el spawn de factions, sin respetar la protección.
Esto lleva siendo así un tiempo ya, no podemos restaurar tus cosas, pero hemos decidido bloquear el spawneo de esas entidades. Sin embargo, no es completamente imposible que de algun modo (Por acción de jugadores) se introduzcan mobs al spawn desde el exterior.

De todos modos, no recomiendo que estés 30 minutos afk en el spawn de factions, ya que cualquiera puede empujarte hacia fuera.

**Comment by PokeFury** [comment]
No esperaba recuperar mis cosas, solo reportar el bug jaja pero bueno
gracias!
