### ISSUE TITLE
Mis objetos han desaparecido

### ISSUE THREAD

**Issue by samsaguetti** [MithrandirCraft/MithrandirCraft#328]
al salir de un pvp y teletransportarme al spawn me han desaparecido todos mis objetos tenia pantalones pechera y botas de protección 4 un arco de infinidad poder 4 y llama y una espada con suerte 3 agu 3. Me gustaría recuperar mis cosas lo antes posible

**Comment by MithrandirCraft** [comment]
Lo comentamos en el juego.

**Comment by MithrandirCraft** [comment]
He hecho unos ajustes con los que espero que se detengan futuras iteraciones de este error.
En cuanto a tus items, te he dejado una compensación generica en el enderchest, que espero que sea suficiente.
Si vuelves a reproducir este error. Te pediría que proporciones más detalles la próxima vez, y intentes encontrar el metodo para reproducirlo.
