### ISSUE TITLE
Las 3 entradas en Torre de Babilonia (Siempre abiertas)

### ISSUE THREAD

**Issue by PokeFury** [MithrandirCraft/MithrandirCraft#329]
En la Torre de babilonia tras matar al 2ndo caballero oscuro se abren las 3 compuertas que te llevan a la sima de la torre, pero recientemente no tienes que matar al caballero para que se abran, puesto que permanecen abiertas.

**Comment by MithrandirCraft** [comment]
Hola. Tal como apareció este bug, ha desaparecido. Lo tendré en cuenta como posible fallo ocasional, pero como de momento no está ocurriendo, lo cierro.

Si quieres volver a abrirlo porque ocurre muy a menudo, crea otro ticket, abre este, o solicita su reapertura.
