### ISSUE TITLE
Posible bug de pociones en Factions

### ISSUE THREAD

**Issue by TXJonathanXT** [MithrandirCraft/MithrandirCraft#331]
Nombre: TXJonathanXT

El bug se trata de que no puedo hacer pociones en el servidor de factions, le pregunte a un moderador si es que no se podia, pero el me dijo que era posible hacerlas, el me dijo que grabara y reportara el bug.

https://www.youtube.com/watch?v=FQIO1hhA0vU

**Comment by MithrandirCraft** [comment]
Actualiza a 1.12.2
