### ISSUE TITLE
Desde la misma IP pública

### ISSUE THREAD

**Issue by DMLugh** [MithrandirCraft/MithrandirCraft#332]
Lo primero, mi nick, dentro del juego me llamo DMLugh, pero este error también afecta al usuario Distira.
Es un error persistente que aún esta ocurriendo, por lo que necesitaría ayuda cuando sea posible.
El error consiste en la denegación del acceso al servidor, por mi parte y por la de Distira, ambos nos conectamos desde la misma casa y salimos a internet por la misma IP pública, por lo que el servidor supongo que nos detecta como multicuentas y nos expulsa. Para la demostración de que somos dos personas reales y diferentes os invito a venir a nuestro discord y así demostrar nuestra veracidad.
En su lugar deberíamos poder entrar al mundo de Factions con normalidad y si que nos expulse el servidor al cabo de poco tiempo. También me aparece cada vez que entro al servidor que he iniciado sesión desde 'También has iniciado sesión desde: DMLugh, Distira'
Pido ayuda lo antes posible para solucionar este error que ayer apenas era notable pero que ya se ha vuelto insostenible impidiéndonos el acceso a nuestra faction en la que aún hay más personas esperándonos.

Espero haber hecho este ticket de la mejor forma posible, que sea legible y espero vuestra respuesta.
Un saludo, DMLugh.

PD: Dejo este enlace a nuestro discord que durará solo 24h, escribidme a mi correo si hace falta.
https://discord.gg/79J6ux

**Comment by MithrandirCraft** [comment]
Yo acabo de loguear 2 cuentas (Desde el mismo ordenador), y no he tenido problema.
El limite de cuentas (logueadas) por IP es bastante elevado, así que problemas con eso no deberíais tener. Pero si estais seguros de que ese es el problema, enviadme el mensaje exacto que os aparece.

Una sugerencia tambien: Confirmad que los nombres que usais no son premium (Si no os pertenecen) desde este enlace: https://mcuuid.net/
Si los nombres si os pertenecen, y estais usando el cliente premium normal, no deberíais tener problemas.

**Comment by MithrandirCraft** [comment]
Solucionado. Factions estaba OFF.
