### ISSUE TITLE
Error encontrado en el servidor o en sus interfazes

### ISSUE THREAD

**Issue by maxkillerlol** [MithrandirCraft/MithrandirCraft#333]
-maxkillerlol8309
-12/01/18
-al subirme al caballo y equiparlo con la silla de montar no me deja avanzar.
-Deberia poder hacerlo avanzar.
-El caballo no me deja manejarlo, eh seguido cada paso y nada ocurre, anteriormente ya habia hablado con un (MOD) pero tampoco pudo resolverlo

**Comment by MithrandirCraft** [comment]
Que version utilizas?

**Comment by maxkillerlol** [comment]
Utilizo la version 1.8


________________________________
De: Mithrandir <notifications@github.com>
Enviado: lunes, 15 de enero de 2018 18:53
Para: MithrandirCraft/MithrandirCraft
Cc: maxkillerlol; Author
Asunto: Re: [MithrandirCraft/MithrandirCraft] Error encontrado en el servidor o en sus interfazes (#333)


Que version utilizas?

**Comment by MithrandirCraft** [comment]
Actualiza a 1.12.2
