### ISSUE TITLE
Bug de Dinero en Faction

### ISSUE THREAD

**Issue by frany2002** [MithrandirCraft/MithrandirCraft#334]
Hola este bug ya fue reportado en Discord pero también abro un ticket aquí ya que Mithrandir me dijo que abra un ticket

Mi Nick es frany2002 aunque no dudo que esto le afecto a todo al que juegue en el servidor de Factions
El bug ocurrió hoy (01/02/2018) primero a las 03:00 (En Argentina) donde de la nada a unas 19 personas aumentaron su dinero de manera exagerada y estas personas no se conectan hace días pero eso podría decirse que era el dinero que te da la facc aunque resultase muy exagerado pero el problema fue mas grave cuando a las 22:30 empezó a dar el dinero que da la facc unas 5 veces por segundo y en lo que vi yo gracias a eso gane 500.000 que claramente no me los pensaba quedar así que lo reporte por Discord y se arreglo rápido el problema viene que para sacar el dinero que se gano con ese fallo se restableció el dinero de los jugadores a 10.000 y la mayoría de los jugadores tenían mas de esta cantidad.

El bug ya a sido solucionado lo único que falta es que se restablecer el dinero de los jugadores a como estaba antes,a mi me dijeron que luego me los restablecerá y me imagino que sera a todos.

**Comment by MithrandirCraft** [comment]
Estoy en ello. Gracias por abrir el ticket.
