### ISSUE TITLE
Bug(?) caballo esqueleto (survival)

### ISSUE THREAD

**Issue by Lapis-kun** [MithrandirCraft/MithrandirCraft#335]
Hoy llevé un caballo esqueleto como regalo para una persona y tras dejarlo en su propiedad el destinatario no podía hacer uso de el (podía montarlo pero no dirigirlo, como si no llevara montura).

**Comment by Lapis-kun** [comment]
Actualizacion: a el usuario RomuSad no le deja usar nungun caballo esqueleto ._.

**Comment by MithrandirCraft** [comment]
Solucionado?

**Comment by MithrandirCraft** [comment]
Lo doy por arreglado, puesto que se aplicaron cambios y de momento no veo quejas.
