### ISSUE TITLE
No recuerdo la contraseña

### ISSUE THREAD

**Issue by AndresGatoXD** [MithrandirCraft/MithrandirCraft#337]
Estimados staff, ¿podrían ayudarme con mi problema?
Desde la ultima vez que entre fue hace mucho tiempo y actualmente ya no recuerdo la contraseña, para peor... la cuenta no esta vinculada a mi hotmail. ¿Podrían desloguear la cuenta "AndresGatoXD"? esta cuenta no contiene progreso alguno.

**Comment by MithrandirCraft** [comment]
Hola, puedo ayudarte, si utilizas el medio de reporte correcto establecido en: www.mithrandircraft.es<http://www.mithrandircraft.es>

mithrandircraft.es<http://www.mithrandircraft.es/>
www.mithrandircraft.es
Vota por este servidor! Recibirás una llave dentro del juego, que podrás usar para abrir cofres misteriosos!

Por cierto, si registraste un correo con tu cuenta deberías poder restaurar tu contraseña. Aunque imagino que no lo hiciste verdad?
Ten en cuenta que no responderé mas a tu problema si no utilizas el medio adecuado!


Mithrandir - Administrador global en MithrandirCraft.es



________________________________
De: AndresGatoXD <notifications@github.com>
Enviado: sábado, 30 de junio de 2018 8:33
Para: MithrandirCraft/MithrandirCraft
Cc: Subscribed
Asunto: [MithrandirCraft/MithrandirCraft] No recuerdo la contraseña (#337)


Estimados staff, ¿podrían ayudarme con mi problema?
Desde la ultima vez que entre fue hace mucho tiempo y actualmente ya no recuerdo la contraseña, para peor... la cuenta no esta vinculada a mi hotmail. ¿Podrían desloguear la cuenta "AndresGatoXD"? esta cuenta no contiene progreso alguno.
