### ISSUE TITLE
Contraseña de mi amigo

### ISSUE THREAD

**Issue by Ivanovic24** [MithrandirCraft/MithrandirCraft#34]
Hola, adrinaruto10 un amigo mio que ya no juega al servidor pero que ya quiere volver, no se acuerda de su contraseña. No registro ningun email y dice que era algo de LasPalmeras

**Comment by Ivanovic24** [comment]
Me gustaria saber si pueden decirsela :D

**Comment by MithrandirCraft** [comment]
El sistema de recuperación de contraseñas por email no funciona.

Por lo tanto realizaré comprobaciones para ver si es seguro desregistrar esta cuenta.
En cualquier caso, si és una cuenta inactiva, la desregistraré.

**Comment by MithrandirCraft** [comment]
desregistrada.
