### ISSUE TITLE
Reporte de Usuario bug arnold13

### ISSUE THREAD

**Issue by Ivanovic24** [MithrandirCraft/MithrandirCraft#35]
Hola queria comunicar que el usuario arnold13, segunda cuenta de arnold1516 tiene totalmente bugeado el pvptimer y no se le puede pegar, al parecer es eterno, con ello puede aprovechar mientras luchan la gente fuerte y recojer cosas o ir a sitios con tpakill sin q le maten.
Espero que se solucione.
Un Saludo

**Comment by MithrandirCraft** [comment]
He hecho unos ajustes, reportame si sigue ocurriendo.

**Comment by Ivanovic24** [comment]
Ok Lo comprobare
