### ISSUE TITLE
Robo de cuenta o error

### ISSUE THREAD

**Issue by xMinecon** [MithrandirCraft/MithrandirCraft#36]
Buen@s amig@s de Mithrandircraft . 
Quiero empezar con mi historia , yo era un usuario llamado destruction . Pues yo deje el server como por par de meses no se exactamente. Pues e vuelto y cuando vuelvo mi cuenta estaba desregistrada y cuando la registro tenia saqueado todo todo . Mi fac que me costo mucho ( obsidiana y piedra del fin) un bunker . Tenia baules , biblotecas . Baules de protec Iv espadas OP, picos OP , etc . En fin no quisiera que me devuelvan todo , solo quisiera saber si se puede obtener algo de lo perdido o si hay una solucion que me facilites mith. 
Gracias espero tu respuesta :)

**Comment by MithrandirCraft** [comment]
Hola buenas noches. Me gustaría indicarte que esto no es un foro, sino un sistema de asistencia, por lo que no necesitas más que dirigirte al responsable :) Yo mismo.

Me gustaría conocer un detalle:

Cuanto hace que no te conectas con destruction?

**Comment by xMinecon** [comment]
1 Semana , esque la verdad no encuentro al responsable de esto . Por eso digo esto porque quiero encontrar al culpable :l.

**Comment by xMinecon** [comment]
1 Semana querido mith.

**Comment by MithrandirCraft** [comment]
Sin duda, si tu cuenta fue desregistrada, y no fuiste tu, significa que alguien ha conseguido acceso a tu nombre y contraseña.

Compartiste tu contraseña/nombre con otro jugador?

**Comment by xMinecon** [comment]
Si hace poco , pues no no compartía la cuenta con nadie nadie solo la usaba yo y mi clave nunca se la dije a nadie nadie tampoco. Cosa que me parece raro : lo que creo yo es lo siguiente : se des registro la cuenta porque no me contestaba en meses y me saquearon todo no?

**Comment by MithrandirCraft** [comment]
Hubo una purga de contraseñas hace ya más de un año, que en un principio no debería repetirse.

Creo que lo mejor que podrías hacer si no progresaste mucho en el servidor es comenzar de nuevo.
Sin más detalles no puedo hacer mucho... Es imposible desencriptar una contraseña en MithrandirCraft, sin haber sido victima de algun scam o treta por parte de un "amigo" o haber recibido archivos que comprometan la seguridad en tu ordenador.
