### ISSUE TITLE
Sugerencias (Algunas realmente necesarias)

### ISSUE THREAD

**Issue by Dolwen** [MithrandirCraft/MithrandirCraft#37]
LLevo poco en este servidor, pero la idea con la que fué creada me parece bastante interesante y se le podrá dar un mayor juego a esta misma, con un consecuente aumento de jugadores en este servidor.  Al ser gran cantidad de sugerencias trataré de ser tan detallado y organizado cómo me sea posible.

-Sugerencias necesarias cuanto antes:

****Reducir el lag del servidor: Únicamente con 10 miembros el servidor tiene bastante lag llegando hasta los 5 o 6 fps. Esto se debe a la cantidad de plugins innecesarios y mundos distintos. Este servidor no tiene tantos miembros cómo para que sea necesario un skyblock o hunguer games los cuales sólo consiguen consumir velocidad del servidor innecesariamente. Pudiendo crear la ciudad dentro del propio mapa del juego. El survival y el factons podrían unirse fácilmente para reducir a la mitad el consumo. (Basta con permitir protección a los miembros sin facción no agresivos). 

***Abrir un buzón de sugerencias IN-GAME: Los jugadores del servidor desean mejoras, pero no van a registrarse en un foro externo OFF-GAME para pedirlas. Lo ideal para evitar esto y mantener a los jugadores contentos es introducir el buzón INGAME los jugadores se sentirán más valorados y que contribuyen a mejorar el servidor (algo muy importante si recordamos que el servidor es por y para los jugadores). Es tan sencillo cómo crear un expendedor de libros con pluma y luego lanzarlos dentro de un drop que cae a un baul el cual solo los moderadores y administradores pueden abrir.

Pasaré a crear otro ticket ya que desconozco el máximo de carácteres y no me gustaría volver a escribir todo el texto :p

**Comment by Dolwen** [comment]
Continuo con las sugerencias :D 

Sugerencias de juego: 

****Plugins completamente necesarios en cualquier servidor: Iconomy (y darle uso) Jobs, pets. Estos tres plugins son los que más jugabilidad ofrecen ya que significan UN RETO. Que un personage suba su experiencia y gane dinero o que pueda engtrenar mascotas para que luchen entre ellas. (Negar esto es cómo negar que Pokemon o Skyrim han sido juegos en éxito de ventas). 

****Factions de mayor tamaño: Las factions de 10 miembros son un inconveniente para algunos jugadores (concretamente los que tienen facciones de 10 jugadores). No hace ningún daño a la estabilidad del servdor y muchos jugadores desean este cambio. Aun suponiendo una facción más comprimida para estos debido al tamaño máximo de claim. (No hace daño, algunos miembtros lo quieren, porqué negarse? lo importante es que los jugadores estén contentos :D)

**Comment by Dolwen** [comment]
*****Mejorar foro: ES HORRIBLE! No solo está en inglés, sino que daña a la vista y es realmente complicado de manejar (he administrado 4 o 5 foros de bastante importancia (1000 a 2000 personas) y nunca había visto foro más complejo e incómodo. Os recomiendo que useis otra compañía, ya que esta tiene grandes limitaciones. 

****ESCUCHAD A LOS JUGADORES: Se que parece obvio, se que hacéis un gran trabajo, pero con el tiempo se olvida que estos servidores están hechos para que los jugadores se sientan cómodos y felices y ¡que carajo! también para sacar algo de dinero a ser posible, y eso se consigue con más miembros que a su vez se consiguen con jugadores felices :D cuanto más tiempo e ilusión dediques a un servidor más fácilmente te querrás hacer vip. Así que ahí lo dejo ;) 

*****Felicitaciones: Por último querría felicitar vuestro trabajo, sé que es un coñazo administrar y moderar dia a día un servidor (he sido moderador en muchas ocasiones) y estáis teniendo mucha paciencia con estas situaciones. Dicho esto creo que de momento está todo, si se me olvida alguna sugerencia la comentaré en este mismo post :)

**Comment by MithrandirCraft** [comment]
Saludos. Respondo a tus sugerencias en el mismo orden que las dejas. Y tan solo para orientarme tu nivel de experiencia en MithrandirCraft, me gustaría saber: ¿Cuanto tiempo llevas jugando en este servidor? Intuyo que eres bastante reciente, ya que tus consultas son muy habituales entre los jugadores mas novatos.

Antes que nada, comprendo tu inconformidad con el servidor, pero te avanzo que como comprenderás, no todo el mundo puede quedar siempre contento.

Viendo lo largas que van a ser mis respuestas, voy a aprovechar algunas de ellas para añadirlas a las FAQ's del foro.

Si deseas añadir algo más y responder a alguna de tus sugerencias, responde adjudicando el numero previamente. Si crees que el debate de tu sugerencia se va a alargar, te ruego que consideres abrir otro ticket espeficicamente para ello.

1. Reducir el lag: Te puedo garantizar que por nuestra parte ya hacemos todo lo posible para crear un entorno libre de lag. 
Por lo que me comentas, el lag que estás experimentando es por parte de tu cliente (5-6fps, una tasa que personalmente considero muy baja) el bajo rendimiento de tus frames por segundo puede deberse un 70% a tus condiciones de hardware, y otro 30% al entorno del mapa y la información que recibes desde el servidor (en situaciones normales). 
Si tenemos en cuenta que tu problema reside en lag de fps, no puedo ayudarte mucho con este asunto.
También puedo asegurarte que el tipo de lag afectante no se debe a un exceso de uso de plugins (muy habitual echarle las culpas a lo que se desconoce realmente), Por el hecho de que sugieras los plugins que utilizamos como motivo por el lag que estás teniendo, intuyo que ya tienes alguna experiencia con la administración de servidores. Pero creeme, nada tiene que ver con el lag que estás experimentando, ni el servidor tiene ningún problema de exceso de procesos que pueda derivar en lag por parte de modificaciones. 
Si mas no, el hardware del servidor (Si te diese especificaciones quedarías boquiabierto) esta plenamente capacitado para aguantar los 1000 jugadores de capacidad y a la vez teniendo todos sus modos de juego (2 de los cuales aún permanecen cerrados) plenamente activos y en uso un uso elevado y exigente.
Los TPS del servidor en ningún caso bajan de 18/20, y lo mas habitual es que se mantengan en 20 con pocos y cada vez menos fallos en el rendimiento de procesos, cuya mayoría no tienen porque afectar a tu rendimiento de cliente.
Por otro lado, si es posible que experimentes tirones ocasionales causados por algun plugin. En cuyo caso deberías reportarlo con máximo detalle, para que nosotros podamos identificar la dificil de detectar causa con exactitud, y el fallo de rendimiento será solucionado rápidamente. En cualquier caso estos tirones no son frecuentes y tienden a ser solucionados en cuanto se reportan. En ningún caso estos tirones serán un constante y inaguantable compromiso para el juego.

Debo también decir que actualmente estamos experimentando unos problemas de exceso de consumo de memoria en disco causados por sobrecarga de chunks, que pueden derivar directamente en el lag que experimentas, pero si es así, deberías comenzar a notar resultados positivos debido a ajustes en aproximadamente 6 o 7 días. 

Como puedes ver, los ajustes para combatir el lag son constantes y complejos, y la reciente versión 1.8 de Minecraft bastante famosa por causar todavía más lentitud por parte del cliente del juego no nos ayuda mucho.
Te sugeriría, si no lo haces todavía, descargar e instalar el mod Optifine, que puedes obtener desde nuestros enlaces en: www.mithrandircraft.es/descargas y debería ayudarte mucho a mejorar tu rendimiento.

2. Ya hemos pensado en esto, quizá te parezca fácil, pero en MithrandirCraft somos bastante perfeccionistas, y no nos hace mucha gracia que los jugadores empiecen a tirar basura (que luego nos toca a nosotros clasificar), además de libros con sugerencias.
La solución mas evidente para separar la basura de libros escritos con sugerencias és crear un mecanismo de redstone, que separe libros escritos de todo lo demás.
Pero esto último tampoco és tan fácil, he puesto a prueba personalmente montones de metodos de clasificación de objetos, y ninguno es capaz de separar libros con escrituras del resto del montón.
Asi que si a ti se te ocurre alguno, hazmelo llegar en otro ticket. 
Seguramente dicho mecanismo si sea posible mediante empleo de bloques de comando, pero esto último no es algo que me haga mucha gracia utilizar con exceso en online.

El sistema de tickets está en inglés, si. Y requiere de un registro y mínima atención y compromiso para poder abrir un ticket. Pero precisamente esto es lo que nos permite saber que el jugador que abre un reporte está realmente interesado y comprometido con el servidor para tengamos en cuenta su sugerencia.

3. No es la primera vez que se sugiere esto. Pero seguramente vas a requerir más tiempo de juego para llegar a comprender que la economía del servidor se basa en la Esmeralda, siendo el modo de juego principal Factions, cuya modalidad recibe todos los beneficios de la extensa economía que proporciona el pueblo y los drops de los jefes. Date una vuelta por el pueblo, y te darás cuenta de que muchas de las cosas por las que hay que luchar para obtener, valen Esmeraldas.

Es asi de simple, la economía del servidor se basa en la esmeralda, y eso lo hace distinto y mucho más complejo. No hay lugar para una economía numérica, ni siquiera en Survival. ¿Que porque en survival no? Survival fue incorporado recientemente para que los jugadores mas novatos tuviesen un lugar agradable en el que vivir pacíficamente. Para nada más. Es un mundo aislado que carece de ventajas, y sirve de preparación o descanso de Factions.

Comprendo que estarás acostumbrado a la gran mayoría de servidores, donde toda economía se basa en números, y estos números pueden ser intercambiados en cualquier momento por cualquier bloque existente en el juego, en una tienda muy comprimida donde todo está disponible al alcance de un click. Pero aquí las cosas funcionan de otra manera.

En MithrandirCraft tenemos retos de sobra, tan solo no serán los que estés habituado a alcanzar como niveles o dinero.

4. "Algunos jugadores quieren facciones con capacidad superior a 10 miembros". ¿Estás seguro de esto? Es la primera que veo sugerir un aumento de capacidad de jugadores por facción.

Yo te voy a dar dos motivos por los cuales la capacidad es suficiente actualmente, y tu puedes seguir debatiendolo como te he indicado al inicio de estas respuestas:

- El equilibrio en el servidor si puede verse afectado. Facciones demasiado grandes y con demasiados miembros pueden llegar a superar el actual volumen de trafico en MithrandirCraft.
En ciertos días solo se conecta una media de 10 jugadores, o mucho menos. Aumentar el máximo de jugadores por facción puede afectar negativamente a la generación de nuevas facciones y el desarrollo de pvp entre facciones. Si solo hay una facción con 25 jugadores, y varias más pequeñas con 2 o 3 miembros, las facciones mas pequeñas lo tienen crudo para plantar cara a las grandes, contra mayor es la capacidad, mayor es el desequilibrio en cierta medida.

- Consecuentemente el servidor se beneficiaría mucho más de aumentar la capacidad máxima de jugadores por facción si tuviese un volumen de jugadores mucho más alto.

-  No es necesario tener a 25 miembros en una facción, puedes tener 3 divisiones en facciones distintas, 10 miembros en 2 facciones y 5 en la última (con novatos?). Además, tener a la gente distribuida así puede ayudar mucho para proteger chunks en radio, teniendo la facción central mas importante en el centro, y las menos importantes protegiendo las chunks de los alrededores concentricamente. (Una acción 100% permitida por nuestra normativa: www.mithrandircraft.es/rules). Mientras que una sola facción de 25 miembros es mucho más insegura, y puede ser barrida en un instante.

A pesar de estas contraposiciones que te establezco, no me parecería completamente irrazonable aumentar la capacidad considerablemente. Pero tendrás que convencerme.

5. En cuanto al foro, creo que estás perdido. Como ya he dicho en otras ocasiones, esto no es un foro, es un sistema de tickets. El verdadero foro del servidor es este: www.mithrandircraft.es/foro y se encuentra 100% traducido al español. Los detalles sobre el foro los tienes al pie, por si tienes curiosidad.

5. Siempre estoy al tanto de lo que dicen los jugadores por el chat. De hecho, el servidor es lo que es hoy, puramente basado en comentarios y feedback de los jugadores. Llevamos aproximadamente 3 años ininterrumpidos ON, el servidor ha evolucionado mucho desde sus inicios.
A mi personalmente no me motiva el ánimo de lucro, sinó mis propias ambiciones y perspectivas de futuro para el servidor. Pero considero que lo mejor que puede hacer un jugador para cooperar y ayudar al servidor és donar para mantener sus gastos.

6 Pues nada, muchas gracias. Espero que te hayan servido mis respuestas. Las he creado con mucho cariño para intentar hacerte comprender y darte una nueva perspectiva de como es MithrandirCraft.

**Comment by Dolwen** [comment]
Gracias a ti! No solo me has convencido en algunos aspectos cómo el de la cantidad de gente en la facción. Además me has demostrado el esfuerzo y ganas de trabajar en este server, haciendo dicho sea de paso que me quede permanentemente en él (o hasta que abandone este juego). Ahora trataré de contestar a algunas cosas de las cuales no estoy del todo de acuerdo o tengo alguna duda. (Además añadiré ciertas cuestiones que tengo del juego:

(Acerca del lag):
No soy el único jugador que ha tenido estos problemas, de tenerlo solo yo habría dado por hecho que era problema de mi ordenador :p 

(Sobre iconomy):
Todo lo contrario! Me encanta el sistema de esmeraldas! Pero el iconomy también puede tener distintos usos y lo bueno es que premia el trabajo realizado durante el juego en el campo que a cada uno le gusta. (Cavar, picar...) Se puede usar cómo pago para comprar claim o fundar nuevas facciones. En algunos servidores venía muy bien para comprar una propiedad en la ciudad y poder construir una casa allí donde podía tener un único cofre a salvo del grifeo. 

(Acerca de la clasificación): Normalmente basta con que un conjunto de moderadores administren voluntariamente esos baúles. (Siempre hay voluntarios que quieren colaborar), en caso contrario me ofrezco voluntario (sin necesidad de que se me otorgue moderación). 

(Respecto a las facciones) estoy seguro, Espartanos también me comentaron ese problema. De todos modos me parece buena idea la sugerencia de facciones por capas. Respecto al equilibrio cómo has dicho dependería de la cantidad de gente en el servidor, trataré de contactar con amigos activos para aumentar el índice de conectados. Al mismo tiempo te sugiero que hagas eventos para invitar nuevos miembros. (Premios por padrinazgo por ejemplo). 

(Respecto al foro): Tienes toda la razón, pido perdón :p

(Respecto a pets y factions): No me has ofrecido ninguna premisa para no ponerla así que si quieres dame motivos para convencerme :D 

****Nuevas sugerencias:

> Foros de administradores: Cuando colaboraba en un servidor habían un foro Español únicamente para administradores de servidores de minecraft, donde intercambiaban información y consejos, quizás te pueda ser útil. 

>Las novedades gustan a todos y hacen que los jugadores se sientan atendidos. Siempre que un plugin no de demasiados problemas y aumente la diversidad en un servidor (en mi opinión) no está de mas. Pongo cómo ejemplo de nuevo el pets, no sé si lo conocerás pero permite convocar a una mascota y hacerla luchar con otras subiendo de nivel. Adquiriendo esta nuevas habilidades en cada nuevo nivel. Además que ataca y defiende al jugador. 

>Concurso de construcciones y facciones: Haz concursos para las construcciones más bonitas del server para crear un video y colgarlo en vuestra cuenta de youtube. Para así que los jugadores puedan pasarlo a otras personas para captar nuevos jugadores.

>Eventos grupales: Una vez al mes crea un evento para todo el servidor. (Un boss enorme, un concurso de obstaculos que solo está abierto una vez). Esto lo vi en un server y era realmente entretenido y hacía que los jugadores esperasen con ganas las fechas de cada evento.

Bueno creo que eso es todo. Si se me ocurre algo más crearé un nuevo ticket. Gracias por todo y felicitaciones por vuestro trabajo!

**Comment by MithrandirCraft** [comment]
lag: Desde los inicios del servidor no has sido el único con problemas de lag de fps, es una de las quejas más comunes y que tiendo a filtrar (ignorar) mentalmente, a no ser que sean reportadas aquí. 
Como ya he dicho, este tipo de lag tiende a escapar a lo que nosotros podemos hacer para solucionarlo. En muchos casos, las novedades que traen las nuevas versiones de minecraft son los principales causantes, y en 1.8 tienes 100 motivos más para necesitar hardware más potente y la última versión de java disponible. 
Lo único que puedo decirte es que yo, como residente en España, no he tenido ningún problema de lag de FPS's en el servidor desde hace ya año y medio, y conozco jugadores que jamás han tenido una experiencia negativa en cuanto a FPS en MithrandirCraft. 
En cuanto a velocidad de conexión ya te he mencionado que algunos procesos internos defectuosos pueden causar retrasos en la conexión, pero parece ser que esto no es lo que reportas.
Por si tienes curiosidad, el servidor se encuentra hosteado profesionalmente en Francia.

iconomy: Sinceramente, estuve considerando aplicar una economía en survival, para que los usuarios tuviesen que pagar por reclamar terrenos... Pero creeme, siempre valoro todas las posibilidades y analizo como puede afactar un cambio al resto de elementos del servidor, y llegué a la conclusión de que, para ahorrar en mantenimiento de plugins adicionales (mas que nada), y por el hecho de que solo abrí el mundo survival a petición de los jugadores más novatos que provablemente no estén interesados en factions (todavía), no era conveniente aplicar una economía adicional numerica.
Aplicarla significaría aplicar un nuevo plugin, y aparentemente no te quedas corto sugiriendo "plugins", a pesar de estar en contra del exceso.

sugerencias por libros: Vuelve a pensar en la cantidad de basura que la gente puede llegar a tirar en este sistema, solo para molestar.

facciones: Permiteme ser esceptico acerca de tus posibilidades para aumentar el numero de jugadores. MithrandirCraft dispone de un equipo de Publicismo dedicado que hace todo lo que puede para atraer nuevos jugadores al servidor, pero tan solo alcanzamos el estado actual.
Tu sabrás, todo grano de arena ayuda supongo.

foros de administradores: No estoy muy seguro de que quieres decir con esto. Si crees que quizá necesite alguna ayuda por parte de otros administradores, o apoyo, no es así. Llevo administrando servidores de juegos desde hace ya 6 años y tengo mucha experiencia en ello.
Aún así, cuando se me plantea algo dificil de resolver, acudo a determinados foros de desarrolladores.
Si lo que estás proponiendo (ya que no he terminado de entenderlo) és un nuevo metodo de divulgación/publicidad del servidor, apreciaría que se lo hagas saber a un Publicista (PB), para que lo tenga en cuenta.

pets: Otra vez me estas sugiriendo un plugin, a pesar de estar en contra de sistemas excesivos, y otra vez se trata de un plugin muy solicitado por los novatos que tienden a llegar desde otros servidores.
Aún así, voy a hacerte una pregunta para rebatirte esta cuestión (Y la verdad es que no estoy familiarizado con este plugin. No se puede estarlo con todo.) No crees que las mascotas podrían interferir con la jugabilidad en Factions, y con el sistema de Jefes?

concurso de construcciones: A partir de aquí ya veo que lo que estás sugiriendo es que se realizen más eventos, y de eso te hablaré en el siguiente punto.
Ya se han realizado concursos de construcción con anterioridad. Hubo unos premios dirigidos a las mejores facciones hace varios meses: http://www.mithrandircraft.es/foro/viewtopic.php?f=5&t=6711

eventos grupales: Está previsto aumentar el volumen de eventos, pero aún queda trabajo para que se pueda establecer un sistema de eventos con fechas regulares. Y que puedan ser anunciados estos eventos en la web para que las fechas queden claras.

Finalmente, me gustaría aclararte que soy el único administrador de este servidor. Y seguramente sea así durante mucho tiempo. Apreciaría que no cuestiones esto, ya que el cargo administrativo supone una alta responsabilidad que no estoy dispuesto a compartir con una persona que no conozca personalmente.
Lo que quiero decir con esto es que todas tus ideas las he tenido anteriormente en cuenta, pero no todas puedo aplicarlas. Necesito ahorrarme trabajo para poder mantener lo que de verdad vale la pena con menor esfuerzo.

**Comment by MithrandirCraft** [comment]
Quizá te gustaría aplicar para un rango en www.mithrandircraft.es/normas (lee abajo)

Las aplicaciones están abiertas tanto en Publicismo como Moderación.

**Comment by Dolwen** [comment]
Gracias por todo! Respecto a el foro es simplemente un lugar donde aparte de responder a dudas (algo que por lo que veo no es tu caso) intercambiaban sugerencias y estilos de administración, entre todos sopesaban qué era lo que mejor les funcionaba en cada caso. (Varias cabezas resuelven problemas mejor que una). 

El pets es un plugin basado en sistema de combate de mascotas, la forma de resumirlo sería decir que es un Pokemon de minecraft con los animales del propio juego. 

Ah! Una última cosa! Me he fijado que los moderadores son excesivamente permisivos (en mi opinión) tanto con el spam cómo con los insultos. No había visto servidores donde los jugadores puedan mentar la profesión de sus madres con impunidad :p . De todos modos simplemente lo destaco, me resulta más dañina la mala ortografía o el spam. Simplemente era por si había unas normas sobre el uso del chat en ese sentido reportar que no se están cumpliendo debidamente. 

Eso es todo de momento, gracias por todo!

**Comment by MithrandirCraft** [comment]
/me: Sería preferible no activar este comando ya que entra en conflicto con otras funciones del servidor, y és difícil saber quien está hablando. Fue desactivado por buenas razones.

Esa es la naturaleza de un servidor de Facciones, los insultos y faltas de respeto por parte de jugadores anónimos son gratuitos y surgen fácilmente, en especial tienen más efecto cuando la persona que insulta tiene un nivel de madurez psicológica bajo, o muy bajo, y si la persona que recibe los insultos no utiliza /ignore <jugador> (para que veas que medidas de automoderación hay suficientes, solo hay que buscarlas en /warp comandos) para filtrar toda la basura, y encima el receptor se rebota, puede producirse un ciclo prolongado o sin fin de intercambio de insultos.
Considero que en cierta medida los insultos dan mayor énfasis al juego en el sistema de facciones, pero evidentemente los excesos no son buenos. Por ello los moderadores solo actúan cuando estas situaciones comienzan a volverse repetitivas y afectan al flujo y/o ambiente del chat en gran medida.

Una de las cosas que nos diferencia de otros servidores, especialmente de nuestro tamaño, es nuestra permisividad en cuanto a actitud. Pero quizá veas a algún moderador mas estricto que otro.

Se está valorando aplicar medidas sobre el chat (chat por proximidad/canales/global etc...), en el caso de que la popularidad del servidor aumente. Estas medidas que seguramente no serán aplicadas todavía, deberían contribuir a que se vean todavía menos faltas de respeto anónimas.

**Comment by MithrandirCraft** [comment]
Procedo a cerrar este ticket, abre uno nuevo si tienes algo más que reportar.
