### ISSUE TITLE
Sugerencia

### ISSUE THREAD

**Issue by SnoopDoggES** [MithrandirCraft/MithrandirCraft#38]
Hola a todos, llevo jugando a este servidor una semana más o menos, y veo que tiene mucho potencial, no solo por su comunidad, sino por el servidor en general. Estoy muy satisfecho con él, asi que debo agradecer a Mithrandir que haya hecho posible esto. 

Dicho lo cual, me gustaria proponer un plugin que añade profundidad tanto al PvP Factions como al Survival, y ese es el MCMMO, que consiste básicamente en subir niveles para mejorar nuestras "skills" o habilidades y asi conseguir una serie de mejoras. Creo que pega muy bien con este servidor y por eso lo propongo. Pienso que añadiría un poquito más de profundidad al juego habitual y que podría gustar a muchos usuarios. 

Gracias :)

**Comment by MithrandirCraft** [comment]
Porfavor, revisa las FAQ's en el foro para saber porqué no utilizamos este plugin.

Siento darte una respuesta negativa en este caso.
