### ISSUE TITLE
Imagen Shopkeepers-Logo.png demasiado grande

### ISSUE THREAD

**Issue by BlackBeemo** [MithrandirCraft/MithrandirCraft#39]
![shopkeepers-logo2](https://cloud.githubusercontent.com/assets/5465862/6992875/84aa10d2-dae1-11e4-8d9f-5c47d80b5566.png) 
esta es la imagen redimensionada  al 10%

**Comment by MithrandirCraft** [comment]
Gracias Nadelina. La optimizaré yo mismo, pero no es la única imagen que puede ser optimizada.

Solo la has reducido al 10%?
