### ISSUE TITLE
ha desaparecido mi casa,

### ISSUE THREAD

**Issue by dannvg** [MithrandirCraft/MithrandirCraft#40]

**Comment by dannvg** [comment]
no quela hyan desmontado o alguien me la ha quitado , no esta y con pinta de que nunca hubiera estado

**Comment by MithrandirCraft** [comment]
Porfavor, respondeme a estas 2 cuestiones acerca de la desaparición de tu casa:

 - En que mundo se encontraba tu construcción? (Surival/Factions?)
 - Desapareció la construcción por completo? O solo una o varias secciones/chunks?
 - Reclamaste debidamente el terreno con el metodo correspondiente al mundo en el cuál se 
   encontraba la construcción, tus creaciones?
 - Ves algún indicio de que haya podido ser regenerado el espacio en el que se encontraba tu 
   creación?

Lo mas probable es que tu construcción se haya regenerado al no estar debidamente reclamada. Aún así, para confirmar que se trata de esto, requiero que respondas a las preguntas anteriores.

**Comment by dannvg** [comment]
hola
estaba en survival te envio screenshot donde estaba situada ya lgunas vistas que saque de suerte desaparecida por completo como si no hubiera existido nunca , esta con arboles parte de agua y demas, como podras comprobar si vas a survival a 272 / 43lo reclame con la pala de oro no solo un terreno sino varios unos junto a otroscomo podras comprobar creo que incluso en la ultima vista la casa que se ve con el horno y los cristales tampoco esta 


     El Lunes, 6 de abril, 2015 16:09:19, Mithrandir <notifications@github.com> escribió:
   

 Porfavor, respondeme a estas 2 cuestiones acerca de la desaparición de tu casa:   
   - En que mundo se encontraba tu construcción? (Surival/Factions?)
   - Desapareció la construcción por completo? O solo una o varias secciones/chunks?
   - Reclamaste debidamente el terreno con el metodo correspondiente al mundo en el cuál se encontraba la construcción, tus creaciones?
   - Ves algún indicio de que haya podido ser regenerado el espacio en el que se encontraba tu creación?
Lo mas probable es que tu construcción se haya regenerado al no estar debidamente reclamada. Aún así, para confirmar que se trata de esto, requiero que respondas a las preguntas anteriores.—

**Comment by MithrandirCraft** [comment]
http://i.imgur.com/YCklBnI.jpg

Este es el terreno en cuestión? El reclamo es relativamente pequeño. Toda tu construcción estaba allí dentro?

**Comment by dannvg** [comment]
era eso mas una igual a la izquierda , otra a la derecha y otra por detras

**Comment by dannvg** [comment]
por cierto otra cosa que me he dado cuenta es que cuando haces una mina y empiezas a excavar al cabo del tiempo por donde has venido se cierra y es imposible volver por donde has venido , asi que tienes que salir por donde puedas

**Comment by MithrandirCraft** [comment]
Se cierra probablemente por la regeneración verdad?

**Comment by dannvg** [comment]
Pues no lo sabía

**Comment by MithrandirCraft** [comment]
Visto el pequeño espacio reclamado y tus indicaciones acerca de las construcciones que creaste, intuyo que se encontraban fuera del espacio reclamado, y por ello fueron regeneradas.

Procura proteger debidamente con una pala todas las construcciones que hagas en el mundo Survival.

**Comment by dannvg** [comment]
hahahaha buen admin eres y buena solucion 

 


     El Miércoles, 8 de abril, 2015 14:37:37, Mithrandir <notifications@github.com> escribió:
   

 Closed #40.—
