### ISSUE TITLE
pantalones vitales

### ISSUE THREAD

**Issue by laocraftero** [MithrandirCraft/MithrandirCraft#41]
no me funcionan los pantalones vitales ¿se pueden arreglar o cambiar?
![2015-04-06_18 04 18](https://cloud.githubusercontent.com/assets/11824471/7012486/f02e70ee-dc87-11e4-9c3d-098b1fb0ed2e.png)

**Comment by laocraftero** [comment]
tambbien me pasa con la armadura variada

**Comment by MithrandirCraft** [comment]
Ponlos en tu enderchest y los reemplazaré.
Podrías indicarme, si lo sabes:

  - Posible causa de este error (Reinicio quizá?)
  - La hora a la que se produjo

**Comment by laocraftero** [comment]
la hora no se y la causa es creo que entrar a survival con ellos puesto

**Comment by MithrandirCraft** [comment]
Este error podría reproducirse, procura guardar tus objetos en lugar seguro antes de cambiar entre mundos hasta que lo solucionemos. 

Si puedes confirmar que este error es causado por cambiar de inventarios entre mundos, confirmamelo mediante otro ticket.
