### ISSUE TITLE
mensage de chat

### ISSUE THREAD

**Issue by laocraftero** [MithrandirCraft/MithrandirCraft#42]
no me deja enviar mensajes desde el chat me dice: no se puecde enviar mensaje de chat cuando mando algo que no sea comando o /msg

**Comment by MithrandirCraft** [comment]
Reinicia o deja que pase un tiempo. Si el problema persiste:

Indicarme tu nombre de jugador.
También haz un pantallazo del mensaje y subelo aqui.

**Comment by laocraftero** [comment]
mi nombre es lao y haora quiero poner el captcha en el login que me lo pide y no puedo poner ni el capcha ni el login

**Comment by laocraftero** [comment]
![2015-04-06_18 54 34](https://cloud.githubusercontent.com/assets/11824471/7013318/82f6220e-dc8e-11e4-8308-c9d2e13d0ea5.png)

**Comment by MithrandirCraft** [comment]
Cuando ha comenzado a bloquearte el chat? Puedes darme mas detalles? Alguna explicación?
