### ISSUE TITLE
PvP Camping

### ISSUE THREAD

**Issue by GabbGabb** [MithrandirCraft/MithrandirCraft#43]
No es una queja, aunque pueda parecer lo contrario. El caso es, que hay jugadores "muy valientes" que adoran estar en la zona segura de las salas de /warp pvp con el fin de dar el golpe de gracia a los que combaten en serio. Obviamente, no es que sea algo ilegal, pero si molesto cuando no paran de "farmear" y decir la excusa de ''Es que quiero proteger mis stats".
Y por algún extraño motivo, en la sala 3 (gris) esto no ocurre. 
Y he aquí mi propuesta: Pueden eliminarse las zonas seguras de las salas PvP?
Y de no ser posible, se podría al menos, bloquear la salida a la zona segura una vez se ha entrado en la zona de combate?
Seguro que así, esos jugadores a los que cariñosamente califico como "Buitres y/o Parásitos" se lo piensan antes de entrar a molestar y ser tan arrogantes.

Si hace falta, pondré algunas fotos mas adelante, algunas pueden ser bastante divertidas xD
Un saludo desde Sala Amarilla! o/

**Comment by GabbGabb** [comment]
![2015-04-28_03 10 11](https://cloud.githubusercontent.com/assets/12144547/7405878/4424ff8c-eef9-11e4-9078-6ccc46efd5c1.png)
![2015-04-29_00 48 27](https://cloud.githubusercontent.com/assets/12144547/7405879/442a679c-eef9-11e4-911e-6a7dbe4c8321.png)
![2015-04-30_04 08 17](https://cloud.githubusercontent.com/assets/12144547/7405880/442e330e-eef9-11e4-829f-cd1a6fb56365.png)

**Comment by MithrandirCraft** [comment]
Que es mas molesto? El cumulo de gente? O el hecho de que no existen jugadores con suficiente valor para enfrentarse a ti en condiciones?

Seguramente ya te has dado cuenta, pero en MithrandirCraft hay muchos jugadores muy jovenes...

Consideraré incorporar una función para que no se pueda regresar a zona segura. Podemos probarlo durante un tiempo aver que tal.

**Comment by MithrandirCraft** [comment]
Tras revisar las opciones mas viables, podría hacer que los jugadores que comienzan una pelea, y se encuentren en modo pvp, puedan ser atacados incluso en zonas seguras. 
Pero el modo pvp no se activa en el mundo de Eventos (donde también se encuentran las salas de pvp) el pvp en este mundo funciona de otra manera.

Alternativas que se me ocurren, mucho mas sencillas, pero todavía problemáticas:
 - Eliminar la zona segura. (Pero esto crearía una situación de camping muy abusable)
 - Reducir el espacio de la zona segura (Sigue produciéndose el problema que reportas.)

Alguna otra sugerencia? Seguiré reflexionandolo, pero realmente es necesario deshacerse de una "característica" clásica, en todo servidor de facciones? La gente se amontona en los límites, eso en si forma parte del juego. La cobardía es algo que lleva arraigado desde siempre en Factions, y en cuanto a ello puedo decir que el servidor es bastante tradicional al respeto.

**Comment by GabbGabb** [comment]
Touché...
Es cierto que no se puede hacer nada con la forma de juego de algunos compañeros del servidor.
Pero sigo creyendo que cuando alguien va a /warp PvP es para hacer PvP. 

En cuanto al "camping", en sala gris hay un tiempo de invulnerabilidad al entrar. No sé como funcionan estas cosas, pero si este tiempo puede ser ligeramente aumentado, se podría evitar el problema; son solo suposiciones, no sé mucho sobre servidores y no sé que cosas pueden modificarse y que no.

Y en cuanto al comentario anterior, me gusta combatir en condiciones: si un jugador no puede ponerse a mi nivel, yo me pongo al suyo, incluso a veces he enfrentado a oponentes con mejor equipo. Es simplemente, que el PvP me gusta.

En todo caso, tampoco es algo de vital importancia, supongo que hay otras peticiones y proyectos mucho mejores. Si lo que pido es tan complicado, bueno, puedo entender que esto no se lleve a cabo.

Gracias por la atención!
Un saludo! o/

**Comment by MithrandirCraft** [comment]
Cerraré este ticket cuando haya tomado una decisón.

/warp pvp es un area del servidor en el que caben mejoras.

**Comment by MithrandirCraft** [comment]
Hola gabb. Te aseguro que llevo semanas pensando en esto xD (Porsupuesto no ocupa el 100% de mi tiempo.)

Tras debatirlo con moderadores y publicistas, he llegado a la conclusión de que no voy a hacer ningún cambio en el campeo. Llego a la conclusión de que cualquier ajuste con la mecanica actual tendrá más contras que pros.

Siento rechazar tus sugerencias en este aspecto.
