### ISSUE TITLE
Tormenta de Bugs?

### ISSUE THREAD

**Issue by GabbGabb** [MithrandirCraft/MithrandirCraft#44]
Por lo general, la lluvia no me molesta, pero pasó esto.
![2015-05-11_23 15 14](https://cloud.githubusercontent.com/assets/12144547/7575507/aefaaf7e-f835-11e4-9163-a5a248a5bb28.png)
![2015-05-11_23 17 10](https://cloud.githubusercontent.com/assets/12144547/7575517/bb87d6fe-f835-11e4-939c-872baaa2d39e.png)
Ya se ha solucionado, pero tengo curiosidad en saber como ha ocurrido. xD

**Comment by rafaelox24** [comment]
Loooooooooooooooooooooooooooooooooooooooooooooooool xD!!!!1

**Comment by rafaelox24** [comment]
La vida te odia xD

**Comment by rafaelox24** [comment]
#LebetComprateUnMicroe_e
