### ISSUE TITLE
Mr. Sonrisas

### ISSUE THREAD

**Issue by GabbGabb** [MithrandirCraft/MithrandirCraft#45]
Un "Boss" que he creado offline como buenamente he podido con mis conocimientos en lo que a comandos se refiere.

Mr. Sonrisas! Un conejo con poca vida, pero un considerable ataque y una velocidad comparable con la del conocido Punisher. Drops no se me ocurren muchos: zanahorias doradas... y poco mas.

Para quienes conozcan la existencia de los "Giant", y caballos esqueleto, el conejo zombie no se encuentra en estado natural. (Se puede apreciar, que los ojos son de zombie).

Me haría gracia ver este pequeñín corriendo y saltando por alguna isla de MithrandirCraft algún dia xD

![2015-05-13_11 13 17](https://cloud.githubusercontent.com/assets/12144547/7607383/30f4c06a-f961-11e4-80d3-0b0ed3b17cf1.png)
![2015-05-13_11 13 21](https://cloud.githubusercontent.com/assets/12144547/7607386/35dccd34-f961-11e4-8d32-d308f7535969.png)

Acabo de corregir a Mr.Sonrisas n_n
Además, he añadido un item especial.

Le estoy cogiendo el punto a los comandos... Voy a investigar mas xD

Un saludo a todos! o/

**Comment by MithrandirCraft** [comment]
Hola Gabb.

Yo creo que con un solo minijefe desorbitadamente rápido en el servidor ya bastaría.
De todos modos, no utilizo el mismo metodo que tu para crear los jefes, los bloques de comando pueden estar bastante limitados en bastantes aspectos, por lo que programo todos los jefes en YAML.

Si llego a crear un nuevo jefe que sea tan rápido de nuevo, probablemente sea uno de nivel de dificultad alta y más poderoso.

Ya te ofrecí formar parte del equipo interno como desarrolladora de jefes junto a Mortis, os podría enseñar como crear nuevos jefes a ambos. Pero si te resignas a ello tu información sigue siendo valiosa, puedes dejar todas las propuestas que quieras aquí.

Ten en cuenta pero, que a diferencia del foro, esto es un sistema de reportes.

**Comment by MithrandirCraft** [comment]
Que te parecería un miniboss dificilillo, con un punto débil importante.

Di le das click derecho explota. xD

**Comment by GabbGabb** [comment]
Probaré el YAML. Aunque creo que este sistema no es tan limitado, tal vez, lo adecuado seria "complicado". 

Ese Boss troll...  podría funcionar! 

PD: He creado un palo, sí, un palo, con empuje X. Al que he nombrado humildemente "Bate de béisbol".

Otro saludo! Y intentaré hacer estas aportaciones en el foro de ahora en adelante.
