### ISSUE TITLE
Bug.

### ISSUE THREAD

**Issue by DarkRoi66** [MithrandirCraft/MithrandirCraft#46]
Hola,
Hoy al mediodi estubimos jugando yo y un amigo en el server, y nos fuimos a comer, a la vuelta al entrar en el server, me fijé en que mi inventario habia desaparecido y tenia cosas que no eran mías: guesos, libro del novato, vias de tren... y fui a los cofres y habia tres cofres completamente vacios, y la faction con la que estaba protegida la casa estaba perfecta, nadie al habia robado.
Tengo fotos de algun objecto valioso que ahora no tengo.
En conjunto perdimos: minerales en general, dos kit de armadura de diamante encantados ( no todas las parte) espadas de diamante encantadas de als cuales tengo foto, (al menos de unha de ellas).
Y lo raro esque los otros cofres estan intactos con picos de diamante encantados los cuales no desaparecieron.

**Comment by DarkRoi66** [comment]
Nos podrian ayudar a saber lo que ha pasado??

**Comment by MithrandirCraft** [comment]
Hola buenas tardes, vamos a intentar averiguar que ha ocurrido:

Confirmamos esto:
- Juegas en Factions.
- Tu inventario de Factions sufrió canbios.
- Tus cofres sufrieron cambios.

En nuestro servidor desde hace ya un tiempo, el inventario no va atado al mapa, por lo que si se produce un error, es o de mapa o de inventario. En tu caso estas reportando errores en ambas cosas, lo cuál me tiene perplejo.

Porfavor, respondeme a TODAS estas preguntas:

- Juegas también en Survival? Cambias de mundo a menudo?
- Crees que esos objetos si puedan ser tuyos, pero obtenidos hace ya tiempo? En cuanto al estado 
  de los cofres, es posible que hayan regresado al estado en el que estaban vacíos debido a un 
  error?
- Consecuentemente, crees que pueda haberse producido un rollback?
- Hubo algún reinicio durante el momento en que se produjo el error? Fuiste expulsado del 
  servidor?
- Desde que país te conectas?
- Cuanto tiempo llevas jugando en el servidor?
- A parte de inventario y cofres, notaste algún cambio con los bloques de tu entorno, o alguna 
  irregularidad con las chunks (Factores que determinen que la zona haya podido regresar atrás en 
  el tiempo)?
- Conoces a alguien más que haya sufrido el mismo problema?

También por favor, detallame la hora (Horario Peninsular Español) a la que te fuiste y la hora a la que regresaste y comprobaste el error, además de la posible hora a la que haya podido ocurrir el error.

Como puedes ver, necesito bastantes detalles, si puedes procurarme algo más que pueda ser importante hazlo.

**Comment by DarkRoi66** [comment]
Juego en factions, y voy a dirigible para hacer misiones solamnete.
No hace mucho, empezamos a jugar este mismo fin de semana, y las cosas imp.
son del domingo/lunes mas o menos.
Es imposible que nos hiciesen un rollback, no se puede entrar en casa sin
antes robarnos la faction.
No hubo ningun error, salimos normalmente y tambien entramos normalmente.
Desde España.
Desde este fin e semana.
No, los animales estan todos, los cofres con libros encantados estan todos,
los cultivos estan bien, las pociones tambien.
No, ya que no conozco a nadie en el server, solo a la otra persona que
juega conmigo en mi faction.
La hora la se exactamente por las llamadas de Skype:
15:20 nos fuimos a comer y a las 16 menos veite regresamos.
Lo único que tengo es algunha foto de cosas que tenia, por ejemplo la
espada de diaamnte...

**Comment by MithrandirCraft** [comment]
No implico que os hayan robado.

Os comento que podría tratarse de un rollback (regreso temporal del mapa y inventario)

Lo raro es que se haya producido tanto en tu inventario como en el mapa, por lo que quizá estamos hablando de 2 errores distintos a la vez, posiblemente relacionados.

Por el momento te voy a entregar un par de objetos de ayuda en tu enderchest.

Tengo algunas sospechas acerca de que podría estar causando este error, pero por desgracia no podrá ser solucionado rápidamente. A partir de ahora te aconsejaría que guardes siempre tus objetos en un cofre, pero veo que ni eso lo vas a encontrar seguro.

**Comment by DarkRoi66** [comment]
Lo raro esque me desaparecio el contenido del cofre entero, y otro cofres
con cosas mas reciente como un pico encantado justo antes de que
desaparecieran las cosas estaba en uno de los cofres no afectados. Y los
enderchest no los uso nunca solo uso cofres.
