### ISSUE TITLE
Mith problema con la compra de magias

### ISSUE THREAD

**Issue by escorpivo** [MithrandirCraft/MithrandirCraft#48]
he comprado dos magias /cast mark y /cast recall  y me sale como si no las tuviera ayuda por favor

**Comment by MithrandirCraft** [comment]
Porfavor especifica:
 - Fecha y hora aproximada o exacta de donación
 - Nombre de jugador dentro del juego especificado para recibir los productos comprados durante la 
   compra.
 - Se encontraba el nombre del jugador receptor conectado en el momento de realizar la compra?

En cualquier caso, reinicia tu acceso al servidor y comprueba que no hayas recibido ya las magias, en ocasiones pueden tardar en adjudicarse.

**Comment by escorpivo** [comment]
el 24/5/2015  sobre las 15:00 Horas

Jugador: escorpivo


si, estaba conectado en ese momento

**Comment by escorpivo** [comment]
la hora exacta fue
24/05/2015 
hora  15:56:44

**Comment by MithrandirCraft** [comment]
Deacuerdo, provablemente el comando que se encarga de enseñarte la magia no sea demasiado compatible con el sistema de ventas.

Por lo tanto, cuando te vea en el juego te entregaré las magias personalmente. Habla por helpop para indicarme que estás conectado.

**Comment by MithrandirCraft** [comment]
Solucionado.
