### ISSUE TITLE
Matanza

### ISSUE THREAD

**Issue by tavitoxz** [MithrandirCraft/MithrandirCraft#49]
Estabamos recien empezando a jugar en el servidor y queriamos empezar tranquilamente y como cualquier mapa de facciones obviamente esperamos que nos ataquen y eso, pero el problema es que este no paraba de hacerlo y no nos dejaba en paz y luego hasta reclamo el territorio para molestar solamente ya que no teniamos nada de valor y el lo sabia, por culpa de el podriamos dejar de jugar el servidor nosotros 3
![2015-05-31_01 30 00](https://cloud.githubusercontent.com/assets/12679685/7900542/b5c108f8-0735-11e5-9d2a-e9f1c0e11a42.png)
![2015-05-31_01 30 05](https://cloud.githubusercontent.com/assets/12679685/7900543/b5c202e4-0735-11e5-9e77-a46e5245b962.png)
![2015-05-31_01 30 06](https://cloud.githubusercontent.com/assets/12679685/7900544/b5c29c18-0735-11e5-9366-b988c1f4084f.png)
![2015-05-31_01 30 16](https://cloud.githubusercontent.com/assets/12679685/7900546/b5c3502c-0735-11e5-9214-7a83edcbe661.png)
![2015-05-31_01 30 25](https://cloud.githubusercontent.com/assets/12679685/7900545/b5c31f3a-0735-11e5-9e7c-53487d3813d8.png)
![2015-05-31_01 30 26](https://cloud.githubusercontent.com/assets/12679685/7900547/b5d352f6-0735-11e5-8390-79b44167f2c5.png)
![2015-05-31_01 33 42](https://cloud.githubusercontent.com/assets/12679685/7900548/b5e3e7ce-0735-11e5-8923-5e348a4a9743.png)
![2015-05-31_01 36 40](https://cloud.githubusercontent.com/assets/12679685/7900549/b5e6a8ec-0735-11e5-829e-34cdde7a2acb.png)

**Comment by MithrandirCraft** [comment]
Parece una situación habitual. En factions hay vencedores y hay perdedores. Espero que tu derrota te haya servido de aprendizaje para mejorar en el futuro.

Tu decides lo que haces, comprendo que muchas personas dejan el servidor al ser aplastadas, por ello hemos creado un ambiente pacifico en Survival.

Cuando te recuperes psicologicamente de tu derrota puedes volver a intentarlo.

**Comment by MithrandirCraft** [comment]
En el futuro porfavor coloca tus experiencias en el foro, el sistema de tickets es para reportar errores y jugadores que no cumplen la normativa.

Si puedo ayudarte en algo abre un nuevo ticket.

**Comment by xMineQuinx** [comment]
una cosa, en las rules dice que no se permite hacer matanzas

**Comment by MithrandirCraft** [comment]
@xMineQuinx En la normativa, como cantidad "abusibamente alta" interpretamos el kill spam exagerado en casos donde la expulsión automática de quienes abusan no sea suficiente.
