### ISSUE TITLE
No puedo conseguir aldeanos en survival

### ISSUE THREAD

**Issue by SuperALJ** [MithrandirCraft/MithrandirCraft#50]
Pasa lo siguiente: consigo un zombie aldeano y lo pongo en arena de almas con vallas alrededor. Luego le tiro una poción de debilidad y le doy una manzana dorada. Se pone a temblar y salen burbujas rojas de él, bién. Pero a los 5 minutos, en vez de convertirse en aldeano, desaparece sin más y sin dejar nada. Por cierto, lo hago directamente sobre la rena de almas.
La pregunta, ¿es algo que no hago bién o esque está prohibido tener aldeanos para intercambiar en un servidor como este?

**Comment by MithrandirCraft** [comment]
Estas en lo cierto, Los aldeanos normales están bloqueados. No es ningún error.

La razón por la que bloqueamos aldeanos es porque los intercambios son impredecibles, y pueden salir verdaderas gangas de los intercambios de Minecraft Vanilla.

Para compensar este hecho, MithrandirCraft ha elaborados su propio sistema de economía justo y mucho más interesante que ir resucitando zombies aldeanos.

Con la Esmeralda como moneda del servidor, puedes intercambiar los objetos que necesites en el pueblo (/warp pueblo), o poner a la venta lo que no necesites en (/warp tradeos)

Si tienes alguna sugerencia que hacer al respeto, o quieres más información sobre la economía del servidor, o otras preguntas comunes, visita las FAQ's en este enlace:

http://www.mithrandircraft.es/foro/viewtopic.php?f=4&t=6462

**Comment by SuperALJ** [comment]
He leído el texto de ese link y no viene cómo hacer una tienda en este servidor. Y tengo un apregunta más, ¿las cosas de la tienda no son las del survival, verdad? Si es así ya no he hecho nada :/

**Comment by MithrandirCraft** [comment]
En efecto, survival es un mundo aislado que no recibe los beneficios del pueblo NPC, y de los Jefes.

Aún así, si lo deseas puedes crear una tienda en Survival. Para aprender como crear tiendas, visita /warp tradeos, y lee los carteles a la izquierda, o visita /warp comandos (apartado verde oscuro.)
