### ISSUE TITLE
De las armas, a la magia!

### ISSUE THREAD

**Issue by GabbGabb** [MithrandirCraft/MithrandirCraft#51]
Con las nuevas magias, he cogido interés en estas.
Pero caigo en que la mayoría no funcionan. Ni siquiera las nuevas.

El caso es que siempre deseé que existiese la magia "transform X", en concreto, la de murciélago.
Pero para mi sorpresa no funcionaba. Lo mismo con las de "disguise X".
En cambio, las magias veteranas, funcionan, pero no correctamente, un ejemplo es la magia de "invisibility", estas gastan un uso del pergamino, pero no te hacen invisible.

Por cierto, magias como "Transmute" o "Farm" podrían ser interesantes. Alguna quest complicada para aprenderlas estaría bien, o aunque muchos me odien por la idea, un lvl 15 y 20 del parkour también. xD

Un saludo!  \o/

**Comment by MithrandirCraft** [comment]
Las magias todavía requerirán bastante trabajo para que salgan a flote. Es algo que sigue en mi mente, pero es complicado... Algún día conseguiremos que su uso sea más habitual. (Sin pasarse, las magias son una rareza)

Pensaba que la magia farm estaba disponible, al menos en la tienda vip, no es asi?

Se que las magias de transformación estan bugeadas, esto se debe a que el plugin de magias esta desactualizado, y no existe actualización todavía.

**Comment by xMineQuinx** [comment]
bueno, ya de paso no se si es un bug pero es de las magias... la magia ^repair^ no repara todos los items del todo y para no ser un repair complete pues no deberia valer 9 esmeraldas (1 bloque).

**Comment by MithrandirCraft** [comment]
@xMineQuinx Lee la descripción de la magia repair en: www.mithrandircraft.es/magias
Porfavor, investiga más antes de suponer. El servidor és bastante complejo.

En cuanto al precio, está así porque en un principio es una magia exclusiva y permanente para quienes adquieren el rango vip. El servidor no se paga solo.

**Comment by MithrandirCraft** [comment]
Arreglado.
