### ISSUE TITLE
Recomendacion

### ISSUE THREAD

**Issue by HolguinPROX** [MithrandirCraft/MithrandirCraft#52]
Nombre en el juego:
Holguin

Área de la Recomendacion:
Survival (Supervivencia)

Este servidor lleva 3 años en servicio, pero son muy pocos los jugadores que se encuentran, el motivo más común es por que no les hagrada el echo de que les roben y los maten. En factions esa es la idea, matar y rovar pero, ¿Y en survival? Es claro que no esta permitido rovar pero esto depende del jugar, entonces, si esto depende del jugador, ¿donde queda la autoridad?
Por eso hago este ticket. Propuestas para evitar el griff (rovar) las cuales son muy sencillas:
1.-Que pasa si en survival un jugador quiere hacer una meta ciudad, muchas veces la cantidad de área que se puede claimear es muy pequeña para lo que se tiene planeado hacer, por lo que debe de dejar áreas sin proteger y nunca faltan los "trolls" o mejor dicho rateros, que se aprovechan de la oportunidad así que propongo un sistema de jail (carcel) el plugin es muy fácil de instalar y los comandos lo son haun mas, una ves instalado el plugin y detectado al que infringe una ley se pone /jail (número de la carcel) (tiempo) y al empezar a recibir castigos, los rateros la pensaran dos veces antes de  rovar o trollear, esto haría el server más llamativo para los que no les gusta que les roben.

2.-No se si lo sepan pero queda historial de todo, incluso de los bloques que pisaste, aquí entra en juego el siguiente plugin que les recomiendo, que pasa si un jugador hace una construcción exageradamente grande que no puede protegerla toda, por motivos del destino, un ratero le rompe su construcción, hay un plugin que no recuerdo el nombre pero se los puedo investigar si es que decena ponerlo, en el cual puedes desgrifear (reparar) un área dañada por otro jugador, se pone /co i el cual te pone en modo investigador, le haces click a un bloque y te da historial de quien lo puso o quien lo quito
Después de pone /co (Nick del ratero) r: (radio) t: (tiempo) a: (acción) en esta última, en caso de que a una construcción le quitaran cosas se pone -block y en caso de que le hayan puesto se pone +block
Con este plugin gracias incluso se puede revivir animales, después de reparar lo dañado lo cual no demora ni 3 minutos, se le puede dar jail al que rovo, esto daría más confianza a quien construlle y definitivamente aumentaria la cantidad de usuarios.

3.-Otra propuesta es darle /fly a los moderadores, para que puedan dar un mejor servicio al momento de desgrifear

4.-otra propuesta es remodelar completamente el chat, asiendolo más atractivo usando los colores, ya que al ser a blanco y negro, en muchas ocaciones uno se pierde por el spam.

5.-Los rangos VIP venderlos en dólares y no en otra moneda, en este server juegan mexicanos, españoles, venezolanos, etc etc etc. Cada país usa una moneda distinta así que si uno no conoce la moneda del rango, no va a saber cuanto cuesta en cambio el dólar es universal, así sería más fácil de terminar cuanto cuesta en realidad.

6.-Los rangos VIP venderlos por determinado tiempo, 1 hora, 1 día, 1 semana 1 mes 3 meses, 6 meses y el deporvida, con estos 7 rangos VIP cada uno conforme más caro tendría más cosas, mas área que proteger, los que quieran hacer ciudades tener derecho a un /warp o tele transporte para su ciudad, incluso el de por vida que en 70 dólares se vendería bien pudiera volar, cada rango tenga el nombre de un animal, el más barato podría ser rango calamar y el mas caro rango Ender Dragón y poner ponerte el disfraz del rango que escogiste o compraste, encantos especiales para rangos vip, cavese mencionar que este punto es un poco pesado y llevaría varios días poder tenerlo al 100 por su complejidad pero si necesitan ayuda les puedo dar mas propuestas para este punto, esto definitivamente área más atractivos los rangos y haría que más personas los compraran, esto traería mejores ganancias para el server y se podría comprar mejores hosting para reducir el lag y poder meter mini juegos como war Castell, sky wars, etc.

7.-meter rango al juego, para subir automáticamente de rango seria con el tiempo de juego, eso significa, cuando juntara 3 horas de tiempo game play subo de rango, el último rango podría ser con 1 mes de game play, cada rango tendría un nombre diferente y un color diferente, el plugin y es muy fácil de usar, cada vez que subes de rango tendrías más ventajas, como por ejemplo más haré a de protección etc, el último rango podría incluso ser muy similar al de Ender Dragón la diferencia esque para obtener este rango se necesitaría tener 744 horas de game play ósea, 31 días, 

8.-Otro es meter economías, meter jobs (trabajos) dependiendo el rango es la cantidad de jobs, máximo 3 jobs, esto le permitiría al jugador juntar dinero, poder y vender cosas en shops, así podría medir e las riquezas no solo por recursos y construcciones, sino que también por dinero.

9.-Meter mas rangos staff 
Aspirante.- puede meter a personas en jail, etc, 
Moderador.- puede volar, desgrifear, hereda funciones de aspirante y tiene las mismas ventajas del rango VIP Ender Dragón, incluso podría dar han a ciertos jugadores
Vigilante: usar world edit, creativo, hereda funciones de moderador y aspirante pero no puede usar bloques de comando, el ya tendría que pagar por el hosting del server en caso de que faltase dinero.
Admin: puede hacer de todo

De esta manera estaría más organizado el servidor, habría más control en el server por lo que todos los puntos anteriormente mencionados serían fáciles de cumplir, cavese mencionar que esas ventajas que se le dan a los staff no las usarán para dar ventaja a los que somos normales, a lo que me refiero esque si vigilante ya tiene creativo no esté dando cosas,  claro que esto deveria de ser vigilado por los Admin, y esas ventajas que se le darían serían para su buen trabajo ya que al ser staff dejarían de ser jugadores, haora serían servidores y por ende ellos necesitarían de esas herramientas,

Cavese mencionar que todo lo anteriormente dicho es para el buen funcionamiento del mundo survival, con excepción del de rangos VIP, ese podría tener incluso ventajas en factions
Si decena más ayuda con gusto les digo que mas podrían mejorar y como. Gracias por su atención.

**Comment by Ivanovic24** [comment]
Hmm quieres cambiar completamente al servidor.
1 y 2. Ahora mismo el server no tiene pensado meter mas plugins, por el momento, hasta que no se termine de mejorar los que hay actualmente.
3. A los moderadores no se les pondra /fly, ya que son como unos jugadores normales, exceptuando a que tienen acceso a los comandos basicos de un moderador( /ban, kick, mute) y eso les daria una grandisima ventaja en el juego, tanto en survival como factions.
4. La mayoria de los usuarios sufrimos una gran cantidad de lag, y habilitar el chat, el spam y el flood  seria aun mas molesto y al final con mucho colorido te acabas cansando antes.
5. Si no estoy mal informado el pago por paypal, da igual si son dolares o euros, paypal los pasa automaticamente.
6. Existen rangos vips de un determinado tiempo, y dos tipos (vip y vip +)
7. Haría muy desigual el juego con respecto a los mas veteranos a los mas novatos y podrias granjear ( dejar la cuenta conectada mientras juegas a otra cosa y obtener ventajas por que si)
8. El sistema economico del servidor se basa en esmeraldas, en survival todavia no esta implementado.
9. Por ahora me parece que no hacen falta mas rangos, el problema es la falta de publicidad. Recuerda si subis videos sobre el servidor que ayuden a que entrar

**Comment by MithrandirCraft** [comment]
Buenas tardes Holguin.
Las sugerencias siempre son bienvenidas, y me interesa escuchar las tuyas, pero ten en cuenta que en muchas ocasiones tus ideales pueden entrar en conflicto con los de MithrandirCraft. 
Aún así, si ese es el caso, te explicaré personalmente porqué tu idea no se adecua o no pueda ser incorporada integra o parcialmente según la situación.
Contrariamente si tus ideas son interesantes y se adecuan a la orientación del servidor, puedo tenerlas en cuenta para el futuro del servidor.
Los ideales de MithrandirCraft se fundamentan en lo que se discute internamente entre el staff del servidor, y muy especialmente en lo que el equipo Administrativo cree correcto. Puede sonar egoísta, pero por supuesto nuestra opinión puede cambiar según lo que comentan los jugadores :)

Tu ticket es bastante amplio, como no tenemos saturación de sugerencias, voy a tomarme un tiempo para responderte como mereces. (Voy a leer ahora lo que tienes que decir, y en un rato cuelgo las respuestas punto por punto, como veo que ha hecho Ivanovic aplicando sus propios ideales.)

**Comment by MithrandirCraft** [comment]
Comenzando por tu asunto general que concierne al mundo Survival. Concuerdo con que este mundo tiene muchas carencias, empezando por que se trata de un mundo aislado del resto en cuanto a inventarios y los beneficios recibidos del sistema de Jefes y el pueblo NPC. Por eso me interesa el doble lo que tengas que decir sobre ello, ya que es un mundo al que aún le falta trabajo :)

También es cierto que muchos jugadores abandonan el servidor tras ser barridos en Factions, es por ello que trabajamos en elementos que motiven a los jugadores a quedarse.

En cualquier caso, porfavor lee lo que tenemos que decir en las FAQ's sobre el mundo survival:
http://www.mithrandircraft.es/foro/viewtopic.php?f=4&t=6462

(También encontrarás otras respuestas a preguntas que seguro que te habrás hecho.)

1. Bien, si entiendo bien en este primer punto, lo que expones és en primer lugar una carencia del sistema de protección en Survival. Debo decir que para empezar, la cantidad de terreno que puedes reclamar siendo un novato, es baja, para prevenir el abuso. 
Como el terreno que puede reclamar un novato es bajo, casi siempre terminará por construir fuera de él verdad? Y por ello otros jugadores se dedican a destruir lo que esté fuera del claim.
Si quieres saber la cantidad, y a que ritmo crece el numero de bloques cúbicos puedes reclamar, revisa el apartado de Survival en /warp comandos (Apartado Cián) En general, este apartado deberías revisarlo ya si todavía no lo has hecho, estoy seguro de que hay mucha información que desconoces.
Ya hay cárceles en este servidor, Pero alguien que destruye material no protegido no está infligiendo ninguna norma. (revisa las normas en /rules) También te pido que imagines la cantidad de vigilancia que requeriría estar al tanto de todos los sucesos de greefing fuera de límites. (Nadie nos paga lo suficiente)
Entiendo que quizá haya algo de balanceo en lo que trabajar... quizá el numero de bloques cúbicos reclamables con los que empieza un novato sea muy reducido (A pesar de crecer cada hora), por ello durante el transcurso de este Verano estaremos al tanto para realizar mejoras en Survival.

2. Expones un caso en el que la construcción és demasiado elevada verticalmente como para ser protegida. Esto me sorprende, ya que cuando realizas una protección con nuestro sistema, el área debería quedar completamente protegida en la coordenada cartesiana Z + (Estio significa desde el suelo o punto de reclamo, hasta la altura máxima en el área que hayas reclamado.). En ocasiones lo que reclames no alcanzará los puntos mas bajos del mapa "Z -" para prevenir que jugadores ajenos no puedan ponerse a minar debajo de las construcciones, pero todo lo que se encuentre por encima debería reclamarse.
En todo caso, si hay alguna malfunción con esto, lo revisaremos.
La adición de un nuevo plugin solo para corregir mediante backups en area los destrozos causados por otros jugadores me parece innecesaria... veo más conveniente ir realizando ajustes con nuestro propio sistema hasta que todos estén contentos. Y creeme, con el sistema que utilizamos, és posible prevenir el Greefeo en un 95%, si el jugador sabe lo que hace.
Como comprendemos que muchos jugadores desconocen como funciona el sistema de reclamos, estamos preparando tutoriales visuales que expliquen en mayor medida y detalle como funcionan los reclamos, y las cosas que puedes hacer en Survival.

3. (Disculpame, pero cuando he visto tu tercera sugerencia no he podido evitar reír) En los últimos 3 años hemos recibido varias quejas sobre los moderadores (Todas ellas infundamentadas y generalmente por desconocimiento de sus verdaderas funciones), comentando abusos de poder. 
Dejame decirte que a administración le preocupa mucho que los moderadores no abusen de sus pocos poderes con los que podrían abusar, es por ello que hay intercambios continuos entre administración y moderación para mejorar la formación de los moderadores (que también son jugadores).
El comando fly sería demasiado tentador para ellos, y terminarían realizando acciones cotidianas como volar para colocar bloques en una muralla o llegar antes a una facción enemiga.
Se que mis moderadores son muy responsables, y esto no lo harían, pero de todos modos activar el comando fly és demasiado fácil.
Comprendo que el motivo por el cuál sugieres una función tan genérica para el equipo de moderación, es por que quieres más vigilancia... pero déjame decirte que mas vale prevenir que curar, és mucho más eficaz establecer sistemas para prevenir las acciones contrarias a la normativa que no ir detrás de los jugadores esperando a que hagan algo malo.

4. Es la primera vez que escucho algo asi sobre el chat... Y comprendo que lo estés sugiriendo al haber visto cosas similares en otros servidores.
Pero me temo que no. Nuestro chat és como és. Su sencillez forma parte de los principios del servidor. Lo siento.
Si llega a venir algún ajuste con el chat en el futuro, provablemente sea una divisón por canales para prevenir el spam (chat de comercio, chat de survival, chat de factions...) o una reducción del radio de lectura (mensajes solo visibles cuando el emisor se encuentra a 30 blosuqes, por ejemplo.)
También estoy trabajando personalmente en mejoras anti spam, filtro anti insultos etc...

5. Creo que enjin (el sistema que usamos únicamente para las donaciones) ya se ocupa de mostrar la moneda y conversión correcta según el país. Has visto alguna malfunción con esto? Si es así podría comentarlo con nuestros proveedores.

6. Creo que nuestros rangos ya están bastante bien? Miralos aquí si todavía no lo has hecho:
http://www.mithrandircraft.enjin.com/shop

Nuestros rangos ya incluyen ventajas bastante jugosas y a precios mucho más bajos que en otros servidores, y aún así, aún nos planteamos realizar ajustes para que las recompensas sean más vistosas y atraigan al consumidor.

7. Rangos de juego... bueno, no es una mala idea, pero el servidor no tira por esta vía actualmente. Este tipo de cosas son las que verías en otros servidores, en el nuestro en cambio, verás cosas únicas como los Jefes. los drops con atributos especiales y encantamientos superiores a los límites por defecto, las tiendas ocultas, magias, ranking de pvp... todo esto son cosas que debes descubrir, y intuyo que muchas desconoces como buen jugador novato que debes ser.

8. No voy a responder a esto de nuevo, es otra sugerencia clásica de novato y muy fundamentada en lo que estás acostumbrado a ver en otros servidores. Para recibir una respuesta digna a tu sugerencia, porfavor visita las FAQ's como te he mencionado antes (tu sugerencia sobre jobs ya tiene respuesta allí.)

9. La estructura del staff la realizamos como creemos conveniente nosotros. Me temo que no voy a aceptar sugerencias en este aspecto.

AQUI TERMINAN MIS RESPUESTAS.

En cualquier caso veo que eres una persona a la que le preocupa el correcto desarrollo del servidor, estaré dispuesto a escuchar sugerencias adicionales o tus respuestas a mis contestaciones :P (Si aún te atreves claro, y no te han aplastado mis convincentes respuestas.)

Me gustaría sugerirte que pases más tiempo en el servidor y descubras lo que todavía desconoces... documentate más, visita nuestra web y /warp comandos etc...

**Comment by MithrandirCraft** [comment]
Concuerdo bastante con las respuestas que ha dado Ivanovic.

**Comment by MithrandirCraft** [comment]
Ha pasado ya una semana desde que nos enviaste tus sugerencias @HolguinPROX 

Como no has contestado a este asunto, intuyo que has perdido el interés en el debate que has generado, lo cuál me ha ofendido bastante, especialmente considerando la calidad de respuesta que te he dado.

Procedo a cerrar este tema.
