### ISSUE TITLE
item frame

### ISSUE THREAD

**Issue by legendofdragon** [MithrandirCraft/MithrandirCraft#53]
los item frames que ponemos para nuestro almacen de cofres desaparecen y el item dentro de ellos tambien

**Comment by MithrandirCraft** [comment]
Hola, esto se debe al limitador de entidades por chunk.

Es bastante provable que en la chunk donde situas estos item frames tengas demasiadas entidades, en MithrandirCraft utilizamos un limitador (40 entidades por chunk). Al llegar a sobrepasar este límite, es bastante provable que desaparezcan cosas como Item Frames, Carretillas, Animales, Monstruos etc...

Gracias por sacar a flote este tema, pronto incluiré información sobre el limitador aquí: www.mithrandircraft.es/info

Porfavor, ten en cuenta que esta medida limitadora és una de las más importantes para el servidor, ya que previene gravisimos sucesos de lag y abuso de entidades que pueden llegar a congelar secciones enteras del mapa.
