### ISSUE TITLE
Debate sobre la configuración sistema de Facciones y bugs con Puertas.

### ISSUE THREAD

**Issue by legendofdragon** [MithrandirCraft/MithrandirCraft#54]
llego a mi faccion que esta en uno de los limites del mundo.
abrio las puertas dentro del claim de mi faccion
claimeo encima de mi faccion aun teniendo nosotros suficiente poder
estabamos 6 personas contra 1 y nos mato en apenas un par de golpes
puede golpear atravesando puertas
y tenemos fotos que lo demuestran.
espero que hagas algo mith
acuso tambien a Durantula44 por el mismo motivo que xToCk, este puede que hacks no, pero si aprovecho de bugs y eso deberia estar prohibido

**Comment by legendofdragon** [comment]
![2015-06-12_00 32 35](https://cloud.githubusercontent.com/assets/11568569/8120796/a8e91d06-10a3-11e5-965d-83d411fd3bbe.png)

**Comment by DavidLaCalle5** [comment]
![prueba 1](https://cloud.githubusercontent.com/assets/12852795/8120846/6dd34722-10a4-11e5-9233-5ab58411afb4.png)
![prueba 2](https://cloud.githubusercontent.com/assets/12852795/8120847/6dd479f8-10a4-11e5-8f0f-5aae75c98735.png)
![Uploading prueba 3.png…]()
![Uploading prueba 4.png…]()
![Uploading prueba 5.png…]()
![Uploading prueba 6.png…]()

**Comment by DavidLaCalle5** [comment]
![prueba 6](https://cloud.githubusercontent.com/assets/12852795/8120879/a2590f36-10a4-11e5-8da1-3d509689cb7a.png)
![prueba 1](https://cloud.githubusercontent.com/assets/12852795/8120880/a25b6312-10a4-11e5-9744-584d8d850f21.png)
![prueba 2](https://cloud.githubusercontent.com/assets/12852795/8120881/a25d2daa-10a4-11e5-98a9-a2a7f9750241.png)
![prueba 3](https://cloud.githubusercontent.com/assets/12852795/8120882/a25e0c98-10a4-11e5-8fa5-c70eca2faa31.png)
![prueba 4](https://cloud.githubusercontent.com/assets/12852795/8120883/a26f3a90-10a4-11e5-8cf7-b7e562195e67.png)
![prueba 5](https://cloud.githubusercontent.com/assets/12852795/8120884/a2723178-10a4-11e5-999d-76d50a2bd679.png)

**Comment by MithrandirCraft** [comment]
Si, estuve leyendo esos comentarios en directo.
Pero por lo visto aquí no proporcionas ninguna prueba de hacks, pero si un reporte de abuso de bugs.

Debes tener en cuenta exactamente que estás reportando y detallarlo al máximo para que podamos tomar una decisión sobre si respeta la normativa o no (O incluso si el bug tiene solución o debería pasar a estar permitido por ser un error Vanilla)

Ten en cuenta que existen algunos bugs más que seguro que te harán la vida imposible. Pero és asi la naturaleza de factions, y debes aprender a adaptarte, especialmente al ser un novato.
Ten en cuenta que todo lo que te hacen a ti, puedes hacerselo tu a ellos. No seas mal perdedor.

Si tienes más cosas asi que reportar estaré encantado de leerlas. Respeto a lo de las puertas, investigaré que es exactamente lo que ocurre, pero es evidente que una puerta como bloque semi opaco és mucho menos fiable que un bloque opaco, por ello deberías considerar mejorar la estructura defensiva de tu facción. (Muchos bugs podrás evadirlos así.)

**Comment by legendofdragon** [comment]
llevo mas de 3 años en esto de factions y aun asi el abuso de estos bugs nunca han sido perdonados, almenos en todos los sitios donde he estado, aparte, como demonios pudo encontrar nuestra fac? tu sabes que estabamos en el limite del mundo, es casi imposible que por casualidad desde tan poco pudiera encontrarnos, aunque usara el /f map la casualidad de llegar hasta donde estabamos es 1 entre 100000

**Comment by legendofdragon** [comment]
y la otra cosa es como pudo claimear un chunk que ya estaba claimeado por nosotros? teniamos muchisimo poder. Ya me da igual si hemos perdido casi todo el equipamiento, al fin y al cabo lo podemos volver a conseguir, otra cosa es que ahora sabe donde estamos y nos puede joder infinitamente con el mismo juego sucio

**Comment by legendofdragon** [comment]
ponte en nuestra situacion, queremos formar alianza para ir contra estos abusones pero si siguen jugando asi nos sera imposible, y encima su forma de claimear, se supone que solo puedes claimear donde esta tu claim base, a partir de ahi vas expandiendo, y eso de cambiar todo el rato entre enemigos y luego a neutral como si nada, eso no puede ser tio

**Comment by MithrandirCraft** [comment]
· Reportas que existe un bug con las puertas que permite atacar a través de ellas. Porfavor, detallame si puedes exactamente que armas y elementos pueden atravesar las puertas, y si ocurre con todos los tipos de puertas incluyendo trampillas. Cuando encuentre el momento lo revisaré.
A primera vista, intuyo que este bug provablemente sea un problema de Minecraft Vanilla (Eso complica la solución.) También he oído hablar de este bug con anterioridad, asi que intuyo que puede haber estado presente desde hace ya mucho tiempo.

· En factions el poder funciona de la siguiente manera: 1 integrante = 10 pow, 2 integrantes o + 20 pox (max). 1 pow = 1 terreno reclamable. 20 pow = 20 terrenos (maximo reclamable).
Teniendo esto en cuenta, si tu facción tiene 20 terrenos reclamados, y 19,0 pow, puedes perder uno de tus terrenos si alguien viene y reclama encima de tu chunk reclamada, porque te falta ese 1 de power restante para proteger esa chunk (x1pow = x1 chunk). (Esto es así en MithrandirCraft, y en cualquier otro servidor de facciones, pero las cantidades de poder y terrenos pueden variar.)
La cuestión es que si no tienes suficiente poder para mantener tu cantidad de terrenos, una facción enemiga podrá venir y robarte una chunk (Siempre y cuando esta chunk sea una de las chunks incluídas dentro del radio más exterior de tus reclamos.)
En MithrandirCraft está permitido reclamar terrenos sueltos (El maximo siempre es 20.) Si esto no te agrada, proporcioname más argumentos en contra, y lo debatiré con el resto de staff para ver si esto es correcto. Pero en un principio esta mecanica de juego permite el robo de terrenos, teniendo a la vez terrenos reclamados en lugares lejanos, o incluso la bisección de construcciones reclamadas. Considerando que el maximo de terrenos reclamables es 20 teniendo 2 integrantes o más, personalmente lo encuentro balanceado.

Otra situación completamente distinta, sería el hecho de que hubiesen reclamado una chunk, sobreescribiendo vuestro terreno reclamado, aún teniendo vuestra facción 20/20 pow.
Si realmente es así (Que lo dudo bastante) entonces si podría tratarse de un error. Si es así, porfavor indicamelo.

**Comment by legendofdragon** [comment]
a ver sabiendo que somos 9 personas en mi faccion y cada una tenia el limite de power, pues dudo que una faccion con un par de miembros pudiera claimear encima de algo que estaba en posesion de una fac bastante mas numerosa, a parte de que llego a abrir, poner y romper algunos bloques dentro del claim nuestro casi en el central.
la puerta que abrio es la que mas alejada esta de nosotros, si no me equivoco, tocando una formacion semi-esferica que usariamos para cultivar arboles, y el bug de atacar atravesando puertas pues llego a darnos con su espada y arco desde bastante lejos.
Tambien quiero reportar el cambio de enemigo a neutral entre factions, lo cambiaban cada 2 x 3 para irse y volver y dejar todo lo que nos consiguieron quitar.
tambien me gustaria que incrementarais los claimeos almenos hasta 25 o 30 ya que algunas facciones como la mia buscamos la creacion de ciudades. (somos bastante roleros)

**Comment by MithrandirCraft** [comment]
Debo decir que me he equivocado en varios puntos expuestos en el parrafo anterior (Estaba pensando en como el sistema de facciones estaba diseñado en MithrandirCraft antes de 1.6), por ello voy a corregirlos directamente sobre ese mismo parrafo, por si quieres revisarlo.

En todo caso:

- Sois 9 personas en vuestra facción, y todos teníais el "power" personal a 10/10 en el momento del asalto. El máximo de poder por facción es de 100/100. Siendo el máximo de terrenos reclamables 20. Cuando un jugador se une a una facción, el poder personal se aplica al poder de la facción. También, si un miembro muere, el poder de la facción bajará 4 puntos. No puedo confirmarlo, pero creo que no podrá bajar a más de 10 puntos ya que el poder máximo aportado por miembro es de 10 puntos.

Confirmame lo siguiente:

- El poder de tu facción estaba a más de 95/100 (Una cantidad superior a esta es necesaria para poder mantener 20 terrenos enteros.) Cuando reclamaron encima de uno de vuestros reclamos?

- Tiene tu facción 20 terrenos reclamados?

Conclusiones:

Contra más terrenos tiene tu facción, mejor calidad de poder necesitáis para poderlos mantener. Si tu facción tiene 20 terrenos y 95 de power exactos, alguien podrá robaros uno de los 20 terrenos en el radio exterior de un grupo de reclamos de tu facción.

Como ves, y estoy seguro de que ya sabes, el sistema de facciones és bastante complejo, y aún queda mucho trabajo para refinarlo. Si estás animado, me gustaría que te unieses a mi equipo como consejero para indicarnos que aspectos podemos mejorar del sistema de Facciones, que, a pesar de ser el modo de juego principal en el servidor, seguramente no haya recibido toda la atención que requiere para estar 100% calibrado. (Tan solo indícame tu usuario de skype.)

**Comment by legendofdragon** [comment]
skype: legendofdragon96
claro, me gustaria ayudar y mas a un compañero catalan (nos vemos en el salon de este año en barna), tampoco es que sea un prodigio de la programación pero mis conocimientos tengo xD
aun asi encantado de ayudar, me mola el server, mi gente queria dejar ya el server despues del ataque pero a mi me mola como esta la cosa y le veo futuro, tiene cierta esencia con los antiguos server de la 1.2.5 
cuando quieras hablamos.

**Comment by MithrandirCraft** [comment]
Voy a cerrar este tema, lo discutiremos por skype.
