### ISSUE TITLE
Gambacha falta el respeto

### ISSUE THREAD

**Issue by xMineQuinx** [MithrandirCraft/MithrandirCraft#55]
Gambacha, hoy el dia 13/06/2015 después del torneo (le maté) se puso a decir que no tenía amigos, de que soy un niño rata... etc y lo que pasa es que no sabe perder y cuando pierde se enfada... (uno de esos que no sabe pelear bien/jugar) y el caso es que yo no le dije nada ni insultos aquí les pongo mi captura.
un saludo xMineQuinx .
PD: Para la próxima vez hagan el evento de PvP más pronto, me descalificaron mientras comía
![2015-06-13_22 05 20](https://cloud.githubusercontent.com/assets/12876178/8145864/28df0c6a-121a-11e5-8fd9-2ec84a877db8.png)

**Comment by MithrandirCraft** [comment]
Como he contestado previamente, utiliza /ignore.

Estamos trabajando para mejorar el filtro, pero a gente así es mejor ignorarla.
