### ISSUE TITLE
Dante000 usa anti-knockback...

### ISSUE THREAD

**Issue by xMineQuinx** [MithrandirCraft/MithrandirCraft#56]
hacíamos pvps con Dante000 en warp pvp sala 7 y derrepente ya no se mueve cuando lo golpeo, le doy y no le afecta no se es muy raro, en esta captura no se si se aprecia bien... de verdad no les miento...
![2015-06-14_16 00 23](https://cloud.githubusercontent.com/assets/12876178/8148868/c31b48f8-12af-11e5-9877-d44817749973.png)

**Comment by MithrandirCraft** [comment]
Con esta imagen no puedo determinar nada, proporciona un video como prueba o una cadena de imagenes más convincentes.

Por lo poco que me dices, podría interpretar también que su personaje quedó conectado por mala conexión.

Proporciona más pruebas o cerraré este ticket en 24h.

**Comment by MithrandirCraft** [comment]
Procedo a cerrar este ticket por falta de pruebas.
