### ISSUE TITLE
zudrop insultado a los catalanes, NADIE SABE HABLAR BIEN!?

### ISSUE THREAD

**Issue by xMineQuinx** [MithrandirCraft/MithrandirCraft#57]
bueno este es otro caso del tipico jugador mal hablado, ha insultado a mith y en este caso ami, y a LegendOfWyvern por ser catalanes...
![2015-06-14_17 03 03](https://cloud.githubusercontent.com/assets/12876178/8149057/9ca9f52c-12b7-11e5-8986-bfd41817beb4.png)

**Comment by xMineQuinx** [comment]
tengo mas....
![2015-06-14_17 08 26](https://cloud.githubusercontent.com/assets/12876178/8149084/908cd722-12b8-11e5-9840-f15b9254051c.png)
![2015-06-14_17 09 19](https://cloud.githubusercontent.com/assets/12876178/8149086/909d2924-12b8-11e5-80ae-097e60378c25.png)
![2015-06-14_17 10 53](https://cloud.githubusercontent.com/assets/12876178/8149085/9098f020-12b8-11e5-9d50-af273ca5d4fb.png)

**Comment by legendofdragon** [comment]
por triste que parezca la gente odia a otra gente sin saber los motivos aparentes,
meh, agradeceria una intervencion para evitar este tipo de confrontaciones entre la gente solo por su lugar de origen.

**Comment by MithrandirCraft** [comment]
Porfavor, si te sientes molesto con el lenguaje de otros jugadores hacia ti, utiliza /ignore <jugador>

Si quieres detener el ciclo vicioso de insultos, lo más fácil és no dar motivos para que los insultos sigan.

Personalmente veo la situación muy carente de madurez.

**Comment by Ivanovic24** [comment]
Hmm, /ignore y punto xd; me izo gracia eso de tener metodos para encontrar spawners xd
