### ISSUE TITLE
Hacerse pasar por admins e insultos

### ISSUE THREAD

**Issue by crugo** [MithrandirCraft/MithrandirCraft#58]
Hola, a pesar de parecer un pardillo por confiar en ellos, seanbot y gambacha se hicieron pasar por admins, aprobechando, les consulte que se hacia con la cabeza de murcielago que tenia, ya que los cazadores no me daban esmeraldas por ello. Por los que me la pidieron y yo confiado se las di y ya que estaba 2 cabezas de eskeletos, al descubrir que me estaban tangando les dije que les reportaria y encima se ponen gallos, al cual se suma insultando otro llamado RexFlores.
Entiendo que estafar no es baneable, pero tambien entiendo que si lo es hacerse pasar por admin e insultar...
Lo dejo en vuestras manos y de camino podeis hecharos unas risas a cuenta mia y de mi incredulidad jajaja
![captura de pantalla 11](https://cloud.githubusercontent.com/assets/12899889/8167124/835380c6-139c-11e5-9716-e34fd7989de4.png)
![captura de pantalla 12](https://cloud.githubusercontent.com/assets/12899889/8167144/95b3dc7a-139c-11e5-944c-a84a65b6a839.png)
![captura de pantalla 10](https://cloud.githubusercontent.com/assets/12899889/8167110/69c48cb8-139c-11e5-8ba8-58cd72c0c5a2.png)
![captura de pantalla 13](https://cloud.githubusercontent.com/assets/12899889/8167154/a3d3ea52-139c-11e5-8028-21240eca75b8.png)

y aki los insultos

![captura de pantalla 14](https://cloud.githubusercontent.com/assets/12899889/8167162/b60cae34-139c-11e5-8ec9-86fea9f562e1.png)

muchas gracias

**Comment by Ivanovic24** [comment]
Xd

**Comment by Ivanovic24** [comment]
Es muy normal este tipo de "bromas" por parte de algunos usuarios que no saben jugar y pretende aprovecharse de los mas novatos e inexpertos en el servidor, normalmente los miembros del staff tienen estos prefijos:
[Admin]: Los administradores, tiene un color amarillo anaranjado.
[Mod]: Color verde, son los moderadores
PB: Somos los publicistas, es de color rojo. 
Ademas, los miembros del staff, poseemos /nick, los vip tambien xd, y nos encontraras con nombre en color. Vijila a los usuarios que se hacen pasar por admins, ya que aprovechan el facciones para ponerse de nombre de fac Admin. Se diferencian por el color y que a las facs tienen un prefijo como **Admin, *Admin, +Admin, -Admin. Pero recuerda, timar, robar, estafar, engañar y traicionar, esta permitido; los insultos tienen un cierto limite.

**Comment by MithrandirCraft** [comment]
Gracias por aclarar los detalles técnicos Ivanovic.

@crugo espero que te haya servido de lección, aún así, siento que te haya ocurrido esto, por ello voy a actualizar la motd (mensaje de inicio de acceso al servidor) para que informe de este tipo de fraudes (entre otras advertencias).

(Me hace especial gracia el lenguaje vulgar y vago que emplea SeanBot ._.')
