### ISSUE TITLE
Bug spawner

### ISSUE THREAD

**Issue by pepejunior1** [MithrandirCraft/MithrandirCraft#59]
Yo tengo un spawner en mi casa, al principio cuando llegue a esa zona funcionaba, y ahora que hice una trampa dejo de funcionar. La trampa esta bien estructurada, de hecho, el spawner hace el efecto de invocar zombies, pero no invoca nada. Porfavor, si pueden, solucionenlo cuanto antes.

**Comment by Ivanovic24** [comment]
Puede ser por que as superado el limite de entidades, en que mundo esta el spawner?
Tienes muchos cofres llenos en el mismo chunk?

**Comment by pepejunior1** [comment]
No hay ningun mob, no hay ningun cofre y esta en factions

**Comment by Ivanovic24** [comment]
Tal vez, algunos de tus perros sean demasiados. El spawner es comprado? O encontrado en el mundo

**Comment by MithrandirCraft** [comment]
Hola, esto ya ha ocurrido con anterioridad... las causas por las que no spawnea el mob tienden a ser bastante misteriosas.

No recuerdo como se resolvieron algunos casos, pero una posibilidad es la que ha dicho Ivanovic.

También puede ser que en tu facción (a pesar de estar desactivado por defecto sin posibilidad de cambiarlo) la /f flag para el spawneo de mobs no esté activada. Pero eso querría decir que algo o alguien la habría cambiado después de que encontraseis el spawner.

Porfavor, indicame las coordenadas en las que se encuentra el spawner y lo revisaré.

Sabes si aparece algun otro tipo de mob en la misma zona con un nivel de osucirdad 6 o menor?

**Comment by pepejunior1** [comment]
Aparte a los perros y ya funciona, pero lo del limite de mobs es bajo? porque me para de spawnear enseguida.

**Comment by Ivanovic24** [comment]
Un truco es q los mobs spawneados se pasen a distinto chunk asi podras reservar mobs. Pero el limite es bastante alto si no tienes muchas entidades.

**Comment by Ivanovic24** [comment]
40 entidades si no me equivoco

**Comment by MithrandirCraft** [comment]
Puede que ese sea el problema. Farmear en MithrandirCraft no és tan fácil como en otros servidores.

Aquí tenemos en cuenta el balanceo economico. Por lo que farmear spawners sigue siendo un metodo muy bueno de obtención de dinero y experiencia, pero no va a ser tan OP con en otros sitios. 

Además, el lag derivado del exceso de spawn también nos preocupa, por lo que lo regulamos.

Si este asunto está resuelto, procedo a cerrar el ticket.
