### ISSUE TITLE
Objetos Perdidos...

### ISSUE THREAD

**Issue by iCrazyMadafaka** [MithrandirCraft/MithrandirCraft#60]
Buenas Mithrandircraft, hace ya que no entro al servidor y se reiniciaron los warps, y en este caso, mi tienda, que estaba en /warp este y bueno, quería saber si se puede recuperar las cosas de allí ya que tenia muchas cosas y gran parte de mi facción nada mas e,e chao y saludos c:

**Comment by MithrandirCraft** [comment]
Si sabes en que warp estaba, tendrás que salir por el punto cardinal correspondiente y caminar hasta encontrar tu tienda.
