### ISSUE TITLE
Xrays, pendiente de revaloración.

### ISSUE THREAD

**Issue by legendofdragon** [MithrandirCraft/MithrandirCraft#61]
Me bannean por xray porque me pase una tarde minando con uno de mi faccion en extreme hills que es donde hay mas minerales? venga ya porfavor.
Hay algo conocido como cooperacion en la que mi compañero que lleva el pico de eficiencia 5 pica la cobblestone y yo que tengo el pico con fortuna pico el mineral y por ello me banean?
venga un abruzo, y luego no baneais a los que pueden usar hacks de verdad.

**Comment by MithrandirCraft** [comment]
Minaste en cooperación con otro jugador para sobrepasar el limitador de minería? O ni siquiera te saltó? Si no te saltó el limitador, solo minaste tu?

Minaste en total 150 diamantes en menos de 12 horas. En xtreme hills no aparecen más diamantes que en ningun otro biome.

Dame el nombre del otro jugador para que lo revise.

**Comment by legendofdragon** [comment]
xAndresFTW y si, en extreme hills hay mas minerales que en otros biomas, y no me salio ningun limitador que yo recuerde, no tengo nada que ocultar y si digo que no uso ningun hack es mi palabra, el unico mod que tengo es el minimap que lo pregunte personalmente ya sabes por donde

**Comment by xAndresFTW** [comment]
Buenas Mithrandir, A ver podéis revisar mi ender chest y veras que lo que dice Legend es cierto, mira bien que llevo un pico con "Eficiencia 5" y la verdad el primero que comenzó a minar minerales fui yo y encontré minerales a montón en poco tiempo y te hablo de diamante y oro, pero no logre sacar mucho porque me salto el limitador y ps como mi pico va mas rápido que el de Legend decidí picar yo, mientras el quemaba el hierro y el oro, hice los túneles solamente de dejar que legend pique los minerales, ahora lo que te pregunto yo.    ¿Porque ami si me salto el limitador y a Legend no? No puedes culpar a Legend por un bug en el server porque si vamos al caso no nos percatamos de eso de porque no le saltaba el limitador y si me sales con que igual si fuera sido por culpa de bug y dirás que nos aprovechamos de el, te digo yo donde esta la justicia por xToCk que pegaba atravez de las puerta y demás de cosa? Yo no tengo problema de que le des una semana como mucho, pero un mes de ban? por que el limitador no le dio gana de salir para que legend no picara mas? Por favor, vamos hablar antes de actuar, porque nosotros no tenemos malas mañas de usar programas ilegales, hemos ido un grupo demás de sanos que no gusta diseñar desde castle's y etc de cosas demasiado epicas. 

Al final solo quiero ver una respuesta, no te pido que lo desbanees, solo una corrección del tiempo  baneado, pero por favor hablemos como adultos o seriamente.

**Comment by MithrandirCraft** [comment]
Voy a permitirte lo siguiente @legendofdragon 

He confiscado prácticamente todo lo que había en tu Enderchest. Como hago siempre en casos de Xrays.

Voy a quitar tu expulsión de forma indefinida.
Si @legendofdragon es capaz de reproducir su increhible racha de minería (Que a mi parecer, y al parecer de jugadores experimentados parece completamente imposible en menos de 12h) durante la última sesión de minería, sin uso de Xrays, devolveré todo lo que he confiscado.

Porsupuesto, estaré monitorizandoos de cerca cada vez que minéis.

Intuyo que os parecerá injusto tener que volver a invertir ese numero de horas minando cooperativamente. Porsupuesto, depende de vosotros demostrar la verdad.

Si no veo a "legendofwyvern" en el servidor en los proximos días, volveré a aplicar su expulsión.

Aún así, que no os quede la menor duda de que tengo claro que sois unos tramposos, vuestro caso huele demasiado a centenares de casos ya vistos con anterioridad.

**Comment by legendofdragon** [comment]
hoy estoy de fiesta en san juan asi que dudo que me veas, y ok. ni suerte ni po**** en vinagre, simplemente picamos. Que crees que somos unos tramposos, ok, tu opinion me da mas bien igual si va contra mi palabra, en ningun momento he mentido y la opinion de jugadores experimentados que mas dara? osea, nos pasamos un buen rato minando en extreme hills donde abundan mas minerales como todo jugador de mc sabe y conseguimos lo que picamos, y ya. vigilame lo que te de la gana si a mi me la pela bastante, solo uso minimap como programa externo, marco puntos de interes a mi parecer y veo las cavernas que pueden haber bajo el suelo si estan al mismo nivel que yo, supongo que conoceras el minimap comun y corriente, y si en ningun momento hemos dado indicios de uso de xray por que lo usariamos ahora? solo porque picamos y conseguimos un material que se puede conseguir mas facilmente con cabezas y esmeraldas. Y no es que conseguieramos la gran cantidad de diamantes, tenia un pico con fortuna y me daban 2 diamantes por mena. Pero mira, solo por demostrar mi inocencia frente a una acusacion falsa, nos volveremos a tirar entre 2 o 3 horas en extreme hills picando, no pienso tolerar una acusacion a un jugador con 5 años de antigüedad en minecraft por uso de hacks ya que nunca he usado, puedo haber jugado con mods pero con launchers especiales como FTB o TechnicLauncher, sinceramente nunca consegui instalar mods correctamente asi que opte por launchers ya hechos, y no, no me avergüenzo de nada, digo las verdades a la cara porque no tengo nada que ocultar.

**Comment by legendofdragon** [comment]
![img_24062015_051044](https://cloud.githubusercontent.com/assets/11568569/8322044/95b3764c-1a2f-11e5-8a1e-1b7be82bd932.png)
![img_24062015_051056](https://cloud.githubusercontent.com/assets/11568569/8322048/98a9e25a-1a2f-11e5-8002-1292613faef2.png)
ahi lo tienes. (los carteles los hizo xAndresFTW y la hora es latinoamericana ya que es de Venezuela, la hora española era entre las 3 y las 5 de la madrugada)
Y si te sirve de algo, siento si te di esa impresion pero tanto tu sarcasmo como la acusacion de usar hacks me cabrearon bastante, y no es ser desvergonzado, es como tu dices, dar la impresion. En ningun momento me hice el listillo, si todo lo que has hecho tu en el server dudo que supiera hacerlo yo, pero aun asi mi unica idea era la de ayudar.

**Comment by MithrandirCraft** [comment]
Subís fotos con vuestras coordenadas...(Borro las fotos)

Lo siento pero me lo he perdido... estoy muy ocupado estos días. Parece que os habéis dado prisa en minarlo todo rápido. Me he dado cuenta esta mañana cuando he vuelto a encontrar una desorbitada cantidad de diamantes minados a tu nombre.

El caso sigue oliendo a xrays. Y mucho. Nadie es capaz de minar a vuestra velocidad, ni siquiera cooperativamente. Me estáis diciendo que en 2 horas habéis minado todo eso porque sois 2.

Indices de minería tan altos siempre suelen ser indicadores de xrays.

Habéis demostrado una cosa, y es que al no poder comprobar al 100% que no usais xrays en esta situación, puedo garantizar que aún le queda bastante trabajo a la sección anti xray del servidor.

@legendofdragon Recuerdame lo que había en tu Enderchest y lo reestableceré.

**Comment by legendofdragon** [comment]
ostia mith, no pretendo ser un malcriado ni un un malhablado (puede que un poco tarde no? xD) pero no se que hacer para demostrarte que no usamos xray, si quieres te muestro los tuneles que hicimos, la eficiencia 5 en un pico te permite picar muy rapido tuneles y si te mantienes entre las capas 16 hacia abajo pues es normal encontrar diamantes y con fortuna pues podiamos sacar unos 20 con 2 betas de diamantes, a ver para dejarlo claro, ahora solo somos 2 en mi fac contandome a mi, muchos diamantes no necesitamos, solo fuimos a minar para hierro que no teniamos y de paso pues bajamos y buscamos diamantes picando bastantes tuneles y eso si, aprovechandome de que mi minimap me muestra cavernas si estan cerca del nivel en el que estoy pero es que no usamos otra cosa xD, vigilanos todo lo que quieras pero es que si no, no tengo otra manera de demostrarte que no usamos ningun tipo de hack y creo que no te he mentido en ningun momento, me puedo haber equivocado en muchas cosas, bastante normal en mi, pero yo mentir no lo hago. Nosotros por ahora y normalmente minar no lo hacemos, si salimos a minar nos tiramos los mas grande y aprovechamos el momento para luego poder construir sin necesidad de parar, ¿que nos falta algo? pues volvemos a salir a minar pero no sin antes comprobar lo que nos falta para intentar traer en cantidades industriales lo que necesitamos xd, es trabajo y esfuerzo que dedicamos para poder seguir prosperando, yo de verdad haz lo que creas necesario para vigilarnos o cualquier cosa pero te he dado mi palabra y no es que sea un niño como pueden ser los demas jugadores del servidor o de la mayoria de servers para que engañarnos.
A ver... las cosas que tenia eran unas 2 o 3 armaduras de diamante completas, sin encantar ni nada, que las hice despues del primer ataque de xToCk, teniamos los 22 bloques de diamantes que eso a tu parecer mira, como si nos quieres devolver la mitad xd, 1 stack y 14 bloques de oro creo que eran, 1 stack y pico de bloques de lapislazuli, creo que la redstone tambien la tenia ahi que era un stack de bloques y pico igual, mi chirijiraden que es una espada de diamante afilado 4, empuje 2, esa la tenia incluso antes del primer ataque de xToCk le puedes preguntar a ivan que gracias a el la recupere, y soplo de Ifrit que es otra espada de diamantes que encante hara 2 semanas con afilado 2 y aspecto igneo 1 que era para ir a matar mobs y... creo que ya esta, diria que eso es lo que tenia.
