### ISSUE TITLE
Baneo por que te sale de?...

### ISSUE THREAD

**Issue by crugo** [MithrandirCraft/MithrandirCraft#62]
Hola, mithandir, primero me hechas por suspuesto "Abuso de asistencia", cosa k no me asistes,,,
Entro y me llamas impresentable por decirte precisamente eso, k me kickeas por abuso de asistencia sin recibirla.
Y entonces te pido k me expliques pork me llamas impresentable y me Baneas 3 dias diciendome que "A dormir, que hay que madrugar"... con 2 huevos.
Como ya te dije, VIVO EN ESPAÑA, lo que con la diferencia horaria para k me atienda un ADMIN he tenido k esperar hasta la 1:15... solicito ayuda y me dices pon /helpop, cosa que llevo dias haciendo, consultando que hago para pasar la fact ya que mi lider no conecta y no esta por la labor...
Tu me diras si este trato es normal en el server por parte de los admins, porque entonces empiezo a pensar que es normal que tengas una media de 20 usuarios de 1000 slots...
Con el rollback de 24h que hiciste perdi de todo y no me queje por que entendi que era un error y que fue la unica solucion.
Solo pido que me desbanees ya que considero que no incumplo ninguna norma.
Y no conozco ningun server donde los baneos de "por que no me apetece escucharte" repercuten positivamente al servidor.
Gracias y un saludo

Postdata, sigo teniendo el dichoso Spawner de arañas venenosas BUG.

**Comment by MithrandirCraft** [comment]
Hombre, parece que ahora si te apetece usar este sistema! Me alegra ver eso.

No me apetece ayudar a desagradecidos, te lo has ganado por creer que eres el único que tiene que trabajar. Como si el mundo girase a tu alrededor.

Por mucho trabajo que me de este servidor, siempre habrá algo que no pueda arreglar nunca, y es el factor humano.

Impresentable y desagradecido, ambas cosas eres.
