### ISSUE TITLE
Hacker (Diiego_13)

### ISSUE THREAD

**Issue by JustPvP** [MithrandirCraft/MithrandirCraft#63]
Esta mañana nos hemos conectado yo xX_Madafaka_Xx y vegetagamer9 entonces hemos matado a Diiego_13 con su proteccion 4, entonces nos dijo id a tradeos os doy 15 bloques de esmeraldas, esntonces nosotros dijimos una cosa que el saco que usaba bugs del server, entonces despues fuimos a pvp y se enfdo y se puso su kill aurita, su antinockback, etc...Pruebas:  http://youtu.be/POoFGqjyBjI

**Comment by MithrandirCraft** [comment]
Gracias por reportar esto. A simple vista si puedo observar que hay indicios de Kill Aura en el video que nos mandas. Especialmente notable justo al final.

Pero no es suficiente. Si lo hubieses grabado con mayor detalle lo podría tener más claro, pero con esto no basta. Por ello echaré un ojo al jugador que reportas, pero no garantizo su expulsión.

Si quieres proporcionar más pruebas, el ticket queda abierto un tiempo.

**Comment by JustPvP** [comment]
Hola Mithrandir,

Me gustaria informar al equipo moderador de mithrandircraft que
vegetagamer9 y yo he hemos descubierto que _MOTHERFUCKER_ es multicuenta de
Diiego_13 y tambien usa hacks vegetagamer9 y yo estamos investigando le
vamos echando pvp y se ve.
Intentaremos buscar mas pruebas y abrir un ticket
 El dia 27/06/2015 9:13, "Mithrandir" <notifications@github.com> va
escriure:
