### ISSUE TITLE
Debate sobre la economía numerica. ¿Encaja en MithrandirCraft? (Jobs? Comenta aquí)

### ISSUE THREAD

**Issue by xDarkSoul** [MithrandirCraft/MithrandirCraft#64]
Buenas , me gustaría proponer una forma de que las esmeraldas fuesen un poco mas fácil de conseguir , ya que los jugadores nuevos , ven muy difícil conseguir esmeraldas , me gustaría proponer.
Que se instalara el /jobs , y que por 3000(solo un ejemplo) se canjeara una esmeralda , así , los nuevos jugadores estarán mas entretenidos , minando , cultivando o realizando otras tareas  para conseguir las esmeraldas , ya que la verdad es que me parece muy difícil empezar en este servidor sobre todo si acabas de empezar a jugar.

me gustaría que lo pensaras bastante , ya que lo veo bastante asequible , porque el /jobs premia el trabajo con niveles , haciendo mas fácil conseguir dinero , y en un tiempo estimado , reiniciar los niveles para evitar una farmeo excesivo 

Espero que al menos te parezca interesante la propuesta ^^

**Comment by MithrandirCraft** [comment]
Bueno ya es como la vigesima vez que llega una sugerencia de economía numerica a mis oídos.

Llevo ya tiempo considerando la inclusión de una economía numerica en el servidor.

Lo que dices es interesante, pero depende de muchas otras cosas. Lo consideraré.

**Comment by MithrandirCraft** [comment]
Dejemoslo abierto hasta que tome una decisión.

**Comment by MithrandirCraft** [comment]
@xDarkSoul Hola.

He estado revisando y valorando esta sugerencia, y me estoy decantando por no incorporarla.

Motivos por los cuales me decanto por no incorporar este sistema:

 - Requerirá el uso de plugins adicionales. Puedo confirmar que como mínimo 2 más: uno para hacer que la economía numerica funcione, y otro para que puedan realizarse compras con el balance economico, mediante tiendas u otros metodos. Añadir más plugins tiene diversas consecuencias: Más dedicación para su mantenimiento, más posibles errores, y más procesos que consumen el hardware de nuestro host.
 - En MithrandirCraft ya existen diversas formas originales de conseguir dinero, entre ellas: Vender cabezas de Monstruos, Intercambiar objetos en tiendas administrativas especificas, Vender tus objetos mediante NPC privado. No vamos a quedarnos allí, una buena idea va a ser incorporar esmeraldas directas como drop por matar a jefes en islas, e idear nuevas formas de conseguir esmeraldas mediante NPC's
-Los resultados de establecer una economía numérica basada en la obtención de esmeraldas mediante crédito numérico, que a su vez puede ser obtenido vendiendo cualquier objeto del juego, son inciertos. No es tan fácil calibrar la cantidad de esmeraldas que recibirán los jugadores a cambio de vender cualquier cosa, por no mencionar que establecer un sistema así sería bastante complejo.
-Algunos jugadores ya crean inflación en el servidor fácilmente, sin necesidad de tener montones de métodos para la obtención de esmeraldas. Puedo imaginar que este nuevo sistema solo empeoraría la inflación.

En cualquier caso, las razones de mayor peso por las cuales no considero adecuado incorporar un sistem así, son las primeras que te he comentado.

Personalmente creo que cada vez que un jugador pide el establecimiento de este tipo de economía se debe a que este está acostumbrado al funcionamiento simple de compra y venta centralizada y inflada en otros servidores.
Aún así, si tanta gente sigue insistiendo en que al servidor le faltan "jobs" y economía numérica, puede que haya alguna razón oculta que escape a mi entendimiento, si es así, y aún hay más razones que no me hayas explicado, me gustaría que tu, y cualquier otro jugador interesado expongáis todos los motivos por los cuales debería considerarlo, en este mismo ticket que permanecerá abierto un tiempo.

**Comment by Mataleno990907** [comment]
Mith la verdad me parece que la idea que plantea xdarksoul es muy buena, y quisiera que lo volvieras a pensar, entiendo lo de los plugins pero mejoraria la forma de avanzar para muchos en factions, o que polo menos puedas ponerlo en un futuro muy sercano.

**Comment by xDarkSoul** [comment]
mith , con lo de los plugin me as dicho todo , veo al server muy cargado ya sea de plugin o por que el host de problemas , no quiero que metas mas plugin sobre todo si incrementa el lag ya que si se incrementa mas lag ya no me quiero imaginar xD pero cuando se solucione el lag en mithrandircraft ,  me gustaría que mi idea pase por tu cabeza , respecto a la inflación , no lo había  pensado , solo pensé una idea de mantener al player mas tiempo conectado minando o haciendo cualquier otra cosa para conseguir sus esmeraldas y así no se si aumentaría el numero de jugadores , pero si se quedarían mas tiempo.

**Comment by MithrandirCraft** [comment]
@xDarkSoul El verdadero problema no es la cantidad de plugins, sino el Hardware del host.

Siento decir esto, pero la única causa de que no se esté mejorando el hardware és la ausencia de aportaciones economicas por parte de los jugadores. Si hubiese más donaciones podríamos mejorar la calidad de juego.

La cantidad de plugins está bastante bien hoy día. No tengo intención de añadir más.

@Mataleno990907 

Te parece bien su idea, pero no me proporciones más motivos. Asi que reitero en lo mismo que ya he dicho en mi posterior comentario.

**Comment by MithrandirCraft** [comment]
Cierro tema. Consideraremos aplicar economía numerica en el futuro si conseguimos darle un uso convincente y paralelo a la economía actual, basada en esmeraldas.
