### ISSUE TITLE
Recomendación de drop

### ISSUE THREAD

**Issue by colo997** [MithrandirCraft/MithrandirCraft#65]
ya que se pueden conseguir muchos encantamientos superiores a los posibles en vanila me pareceria cuerente que alguno de los bosses del server dropeo una looting V ya que me parece el encantamiento mas importante para cualquier tipo de factions y lo veo como un gran ahorro de tiempo y una muy buena manera para q los nuevos consigan fortalecerse mas rapido que al igual que los q ya llevan su tiempo en el server tengan la posibilidad de granjear cosas aplicando menos tiempo, logrando una mayor divercion. gracias anticipadas y perdon por los errores de ortografia

**Comment by MithrandirCraft** [comment]
Looting V? Creo que ya hay algun objeto con este encantamiento previsto, si no recuerdo mal puede que sea una espada en desarrollo llamada "Espada del rey ladrón"

En todo caso, al sistema de jefes aún le queda trabajo, estamos en ello, pero nuestra fijación principal por el momento és reducir el consumo de procesos en el servidor y controlar el exceso de chunks y entidades para mejorar el rendimiento.

Cuando terminemos con esto, podremos volver al tema de los jefes y drops :)
