### ISSUE TITLE
Recomendaciónes

### ISSUE THREAD

**Issue by colo997** [MithrandirCraft/MithrandirCraft#66]
Queria pedir si se podria implementar en en la tienda donde estan los NPC de cabezas que se agrege uno de lepizma y guardianes y que tengan un precio mas elevado que el de los demas mobs ya que la dificultad para conseguir estas cabezas es bastante mas superior

**Comment by MithrandirCraft** [comment]
Este ticket contiene una duplicación de: https://github.com/MithrandirCraft/MithrandirCraft/issues/65
Porfavor, procura respetar las normas de apertura de tickets en el siguiente archivo readme:
https://github.com/MithrandirCraft/MithrandirCraft
-------------------------------------------------------------------------------------------------------------------------------

Seguramente lleguen mas cabezas en el futuro, aunque de momento la prioridad es hacer que no se bugueen tanto al intentar venderlas.
