### ISSUE TITLE
Bug de spawners bloqueados (Has tenido este problema desde el 09/07/2015? Reportalo aquí.)

### ISSUE THREAD

**Issue by crugo** [MithrandirCraft/MithrandirCraft#67]
Hola, tengo un spawner de arañas de la cueva BUG, salen cada 40 min o asi, FChao, me lo miro y dijo k sabia cual era el problema, pero yo no me acuerdo de lo que me dijo.
El caso esque hace como que va a spawnear un mob pero no sale nada.
Aclarar que esta todo a oscuras, esta en el aire y con 4 bloques de separacion a las paredes...
Si me lo pueden arreglar seria un detalle, sino, me conformo con que me pongan uno de algun otro tipo que funcione, eskeltos, zombies o algo.

**Comment by MithrandirCraft** [comment]
Es posible que no podamos arreglar el "spawner" aunque podemos probar sustituirlo.

Lo mas seguro es que algo este jugando con los spawns y irregularizando el spawneo. Es un error que ya ha sido reportado varias veces antes.

Dame las coordenadas y lo investigaremos.

**Comment by crugo** [comment]
Hola Mithrandir, hoy he encontrado otro spawner de arañas de cueva, y esta igual que el mio... por lo que entiendo que no se debe al numero de mobs en el chunck( como he comprobado hoy una vez hablado con Deidei) No he podido coincidir contigo para darte las coords, aver si veo conectado a Fchao que el sabe cual es el problema y puede ayudarnos.
Un saludo.

**Comment by MithrandirCraft** [comment]
Si te refieres a ChaoFM, él cree saber que lo causa, pero está equivocado.

Todavía no me has dado las coordenadas :/ asi no puedo hacer nada.

**Comment by crugo** [comment]
Esta noche si estás conectado te la doy, que si la pongo aqui todos sabran
donde esta mi faccion... Jajaja

**Comment by MithrandirCraft** [comment]
Bueno, le he echado un vistazo y lo he sustituido.
No se si será por haber colocado uno nuevo, pero han comenzado a aparecer arañas de cueva.

Dime si el problema esta resuelto, o si al menos está algo mejor. Podría ser que esas arañas simplemente estén spawneando muy lentamente?

**Comment by MithrandirCraft** [comment]
Parche aplicado. Si alguien vuelve a tener este problema, porfavor lo cominique en este mismo ticket.
