### ISSUE TITLE
acusasion 

### ISSUE THREAD

**Issue by xXJOSEXx** [MithrandirCraft/MithrandirCraft#68]
estaba en mi fac y llego duran y nos mato a todos ami y a dos amigos mas y volvi a ver si ya se abian ido y apareci hay yo y un amigo y duran se fue por mi amigo cuando mire en el chat que decia que duran abia muerto y mire sus cosas en el piso y fui por ellas, y su amigo me amenaso que yo abia echo kill aurora y en luego de un rato me amenaso que iva a subir un video que donde se miraba que use hacks, yo despues de dejar las cosas en el eder chest dije mejor no me las llevo puestas me comi una manzande de bloques y un pocion de fuerza y me mato de un golpe

**Comment by Ivanovic24** [comment]
Sin pruebas fotograficas o un video, no se puede hacer nada

**Comment by BlackBeemo** [comment]
lo cierro por falta de prubas
