### ISSUE TITLE
Clipping facilitado por el sistema de contraseñas (arreglar)

### ISSUE THREAD

**Issue by Mataleno990907** [MithrandirCraft/MithrandirCraft#69]
Este bug es algo molesto y quisiera que lo solucionaras si es posible mith.
Invadir un FAC es muy fácil gracias a esto, y consiste en lanzar dos ender pearl a la ves y así atraviesas cualquier pared y puerta sin ningún problema, seré muy breve quisiera que arreglaras eso lo mas rápido posible, espero que la comunidad de mithrandircraft y tu entiendan mi petición.

**Comment by Ivanovic24** [comment]
Ninguna base es totalmente segura, puedes probar ha hacer dos capas de pared, o usar puertas de valla que solucionan un poco el bug, pero el bug de las enderpearls no es del servidor, si no de minecraft y se remonta a su aparicion, lo que se puede considerar una utilidad mas de las enderpearls

**Comment by Mataleno990907** [comment]
La verdad gracias por el consejo y se que ninguna FAC es 100% segura pero puede hacercarse a esos parámetros de seguridad, y pues tu mismo dijiste, es un bug por lo tanto es un error y si es un error no puede considerarse una utilidad legal de las ender pearls.
GRACIAS POR TU CONSEJO.

**Comment by Ivanovic24** [comment]
No es considerado un bug, si no ya hubiera sido solucionado.

**Comment by Mataleno990907** [comment]
sabemos que minecraft es un juego todavía en perfección como gran parte de los juegos que nos divierten, y que al pasar de sus años a tenido muchísimos bugs.
como por ejemplo el de la redstone que provocaba obsidiana o el bug de los diamantes infinitos.
bug que ya fueron solucionados.
tal vez pronto ese bug pronto sea solucionado, recuerda que estamos en la versión 1.8.7.
pero por otro lado se que hay programas que pueden modificar el minecraft, tal vez mith pueda solucionarlo.

**Comment by BlackBeemo** [comment]
Es un glich de esos que se transforman en funcionalidad, lo único que puedes hacer es buscar formas de como dificultar su uso.

Algunas formas de prevenir:
1.- Situa tu faccion en contacto con el bedrock 
2.- Crafting tables fuerzan al que lanza la enderperl a usar shift si no lo hace no puede traspasar el bloque.
3.- No uses materiales que cuenten como transparentes; escalones, cristal, puertas, media piedra...
4.- Si tu facc esta en el aire deja como mínimo 30 bloques desde el suelo.

**Comment by MithrandirCraft** [comment]
Hola. La verdad, creo que esto és efectivamente un error. Pero no estoy seguro de ello, por tanto hay que confirmarlo. Mi pregunta és:

* ¿Realmente és posible atravesar manteles de bloques horizontales tan solo utilizando enderpearls?

¿Porque pregunto esto?: Básicamente porque actualmente la persona a la que más he visto hacer esto és Ivanovic24, y siento revelar las intricacias de este glitch, pero en MithrandirCraft és necesario desconectarse al spamear enderpearls para poder abusar del error.

Creo que el denominado bug de "clipping" con enderpearls está ya parcheado, pero nuestro sistema de contraseñas en el estado actual lo está volviendo a hacer emerger. Por tanto, si se contesta a mi pregunta de si és posible reproducir este bug sin realizar un /logout o desconexión, únicamente empleando el uso de enderpearls, me estaréis aportando información valiosa para la solución de este error.

**Comment by MithrandirCraft** [comment]
Os recuerdo que actualmente tal como está establecido en el foro, este error es 100% legal hasta que sea arreglado.

**Comment by Mataleno990907** [comment]
Te diré lo que se, puedes atravesar bloques horizontal y verticalmente con solo lan vender pearls. Y que es un logout y clipping?

**Comment by Ivanovic24** [comment]
Me cago en to' dijieron mis secretos u.u xd.

Si tiras enderpearl hacia arriba cuando esto es una superficie de un bloque de espesor o de una losa, spammendo enderpearls claro xd. Logras atravesar el techo y quedarte arriba, lo que es bug/glitch de toda la vida en minecraft.

**Comment by MithrandirCraft** [comment]
Ok, por confirmamos que es posible reproducir este bug sin deslogueos, pero és mas potente al desloguear.

**Comment by Ivanovic24** [comment]
Exacto, con deslogueos puedes traspasar la cantidad de capas de suelo que quieras, siempre y cuando no haya cavernas depormedio y sea desde abajo. Sin deslogueo solo se pueden atravesar 1 losa, un bloque, una losa y un bloque, y en casos extraños 2 bloques.

**Comment by MithrandirCraft** [comment]
Por tanto va a seguir tratandose de un error de Minecraft Vanilla, accentuable gracias al sistema de contraseñas.

Intentaré reducir la facilidad de reproducrir este bug gracias al sistema de contraseñas, pero en cuanto al clipping normal, esto es algo que Mojang va a tener que arreglar, veré si les abro un ticket.

**Comment by MithrandirCraft** [comment]
Porfavor, confirmen que este error sigue siendo posible de ejecutar con facilidad mediante deslogueo.

**Comment by Ivanovic24** [comment]
Sigue funcionando, lo he probado

**Comment by MithrandirCraft** [comment]
Puede alguien confirmar que "Clippear" siga siendo posible?

**Comment by Ivanovic24** [comment]
Ya no es posible...
