### ISSUE TITLE
bug  con los dispensadores D:

### ISSUE THREAD

**Issue by sadow2811** [MithrandirCraft/MithrandirCraft#70]
mithr, hay un bug un tanto extraño en el que al crear una graja de plantas solo un dispensador puede aplicar polvo de hueso a un bloque de tierra, si pones mas aunque estén conectados  a la redestone estos no aplican el polvo de hueso hasta que se le agota al primero y me es un gran inconveniente para algunas construcciones que quería hacer. me gustaría saber si modificaste algo en relación al comportamiento de los dispensadores y si no es así intentar buscar el motivo del bug

**Comment by Nepo23** [comment]
Te apoyo porque igual me pasa pero creo que es la redstone porque solo activa a un dispensador los demas o el que sigue no es activado, pasa con mis cañones y no me gusta

**Comment by Ivanovic24** [comment]
A mi me paso con unos pistones. U.u

**Comment by MithrandirCraft** [comment]
No creo que sea un bug, sino algo intencionado.
Aplico muchas medidas para reducir los procesos del servidor que puedan causar lag por parte de los jugadores. No recuerdo si habré bloqueado el uso excesivo de dispensadores (seguramente si).
Estas medidas son necesarias, pero lo revisaré por si se trata de un error.

**Comment by MithrandirCraft** [comment]
Etiqueta provisional*

**Comment by MithrandirCraft** [comment]
Ciertamente, este filtro lo apliqué yo hace ya años, y és necesario para mejorar el rendimiento del servidor.

No voy a arreglarlo, pero lo tendré en cuenta en el futuro, y quizá lo haga más permisivo.
