### ISSUE TITLE
El abuso de asesinatos, mejoras y permisividad - Debate abierto (comenta aquí)

### ISSUE THREAD

**Issue by Nepo23** [MithrandirCraft/MithrandirCraft#71]
Bueno asi en peso todo:
Estaba buscando arcilla ya sabes por ahi y tambien buscando fortalezas para esponjas, cuando encontre una fac llamada Genocide.
Como es faccion le rrompi la pared era muy facil, ademas uno de los miembros entro y enpeso la pelea, lo mate pero el siguio llegando al home me acorde del console que no puedo matarlo muchas veces seguidas por lo que llame a zirix ( Relevo zirix), y pss lo mate por 5a vez entonses consola me expulso ok de acuerdo asepto que es una proteccion para los nobatos, pero al regresar al server ya pasando el tiempo de penalizacion, entre sin inventario y marcaba que el 50% habia sido recuperado pero al loguearme se perdio todo eso. Zirix estaba conectado y recogio cosas mias pero perdi la mitada de mi armadura, arco y espada. Me parese que es un bug que consola elimine mi inventario.
Ademas zirix igual seguia peliando con el tipo de la faccion asi que igual fue expulsado por consola ademas de que murio tirando sus cosas, lo mismo paso perdio la mitad de su inventario solo pude recoger su espada y basura que el tipo habia tirado.
Y soy claro quiero mis cosas y que se rrepare este bug horrible, las cosas de zirix igual,ademas sugiero aumentar el liminte porque 5 muertes es muy poco.

**Comment by sadow2811** [comment]
en mi opinión 5 también son muy pocas :S ¿eso significa que si asaltas una fac tienes que llegar al punto de tener que ignorar a los miembros de la fac para que no te maten por lo del console?

**Comment by xDarkSoul** [comment]
yo creo que se tendria que quitar ese plugin , ¿para que tenerlo si no respawnean en su casa? , ademas es factions es normal el spawnkill... y si van es por que quieren morir.. xD

**Comment by BlackBeemo** [comment]
Dudo que sea un bug. Esto supongo que es debido a que hay dos funcionalidades del server que no se entienden demasiado bien.
- Si te deslogueas en combate pierdes parte de tu inventario.
- Si matas a alguien mas de 5 veces seguidas te echa del server.

Algo abra que configurar supongo o eliminar una de las dos funcionalidades.

**Comment by Ivanovic24** [comment]
La 2. Si eliminas la 1 es una cagada

**Comment by Nepo23** [comment]
Es interesante pero cuando hablas de perdir deveria ser tirar tus objetos no?
O cuando hablas de perder es de borrar parte de tu inventario mas ademas tirar los objetos?

**Comment by MithrandirCraft** [comment]
@Nepo23 
> "y marcaba que el 50% había sido recuperado pero al loguearme se perdio todo eso.":
Este mensaje és el único "error" en lo que has experimentado. Se trata de un problema de compatibilidad (No tengo demasiado interés en arreglarlo, ya que se trata de una norma que tu has violado y como tal se ha aplicado la penalización automatica independiente de la recuperación de inventario que debería aplicarse en esta situación). 
Tu, al ser Moderador recuperas un 50% de objetos al morir, pero de esto se encarga un sistema que no tiene nada que ver con el proceso de dropear tus objetos (todos) al abusar de asesinatos.

> "Zirix estaba conectado y recogio cosas mias pero perdi la mitada de mi armadura, arco y espada.":
Es posible que antes en skype me dijiste que la consola había eliminado todo? Pero según me dices aquí, zirix recogió tus drops, por tanto se aplicó la acción correcta de dropear los objetos al desaparecer en PvP. La desaparición en pvp o sistema anticobardes se aplica igualmente aunque tu no hayas causado esa desaparición, és una consecuencia que tu debes acarrear por burlar una norma, como moderador deberías estar avergonzado >:l (Es broma, és una norma leve, pero debes admitir que te lo has buscado.)
Parece ser que no dropeaste algunas cosas, por lo que se eliminaron? Eso si que és un verdadero misterio... Y dices que a Zirix le ha ocurrido lo mismo.

>"sugiero aumentar el liminte porque 5 muertes es muy poco.":
El sistema de kicks por asesinato és bastante flexible. Si lo has activado és porque esas 5 muertes han sido bastante seguidas. (Sin duda te estabas abusando de asesinatos, y esto floodea el chat además de ser una acción muy abusable para aumentar tu posición en el ranking de pvp.) 

Conclusión, en este caso se produce 1 error que no me apetece arreglar, y un error de veracidad inconcluida:

* El mensaje de 50% de recuperación de inventario es incorrecto, porque el drop de inventarios sobreescribe la recuperación.
* Algunos objetos no son dropeados y son eliminados al desaparecer en combate.

Igualmente, en unos días revisaré de nuevo este caso y veré si puedo hacer más permisivo y menos agresivo en cuanto al inventario al sistema.

**Comment by Nepo23** [comment]
Ok entonses haber si entendi.
1) Al matar 5 veces a un jugador el servidor me kickea (ok es clara esa parte y siempre la e entendido).
2) Un porcentaje no se cual sea cae para ser dropeado por jugadores (en este caso zirix lo recogio porque lo mato, grasias zirix)?
3) Luego ademas un porcentaje que en este caso como ser vip+ deveria quedar en mi inventario, pero que se sobrescribe y en ves de recuperar o quedar en el inventario se elimina y no se activara para el drop?

**Comment by MithrandirCraft** [comment]
* 1.Al matar 5 veces lo suficientemente seguidas a un jugador, eres expulsado durante 1 minuto (si no recuerdo mal.) Se trata de abusar de asesinatos, no de matar a alguien 5 veces. Como ya he dicho, és bastante flexible y nos aseguramos de que no sean simples asesinatos sino un abuso.

* 2.Todavía no me estás confirmando si el resto del % que no detallas és eliminado sin dejar rastro.

* 4.Efectivamente

No has contestado a algunas de mis preguntas.

**Comment by Nepo23** [comment]
2 Efectivamente un % del inventario se elimino sin dejar rastro.

**Comment by MithrandirCraft** [comment]
Parece un caso puntual, a saber que ha podido ocurrir con esos objetos podrían haber caído en un bloque que los destruya, o ser recogidos por cualquier persona. Una vez los objetos caen al suelo su futuro és dificil de predecir.

Creo que podemos estar deacuerdo en que ahora que te ha ocurrido esto, intentarás no realizar asesinatos tan seguidos sobre el mismo jugador.

También por otro lado, considero que el jugador que se deja hacer eso no toma la mejor decisión, ya que tiene tiempo suficiente para regresar al spawn y prevenir el spawnkill. Aunque comprendo que no quiera abandonar su facción.

**Comment by Ivanovic24** [comment]
A mi hace mucho me ocurrio una cosa parecida, al morir perdi una parte de mis objetos, cai en un agujero de 1x1 y al recojer mis objetos faltaban cosas, en ese momento pense: "habra sido que se han bugueado en la pared o algo e.e" y le di poca importancia...  Pero veo que tal vez no fuera eso.

**Comment by Nepo23** [comment]
Pss por el momento la solucion es esa no matar demasiado rrapido pero igual, si se eliminan cosas, porque como dije zirix igual le paso, yo recogi algunas cosa, pero eran muy pocas me pedia cosas que no tenia como casco. Pero ok igual espero no me pase otra vez. Aunque si es un error eliminar objetos

**Comment by MithrandirCraft** [comment]
@Nepo23 

Vamos a dejar este ticket abierto, y quien tenga que aportar una valoración similar sobre el mismo tema que lo haga aquí.

**Comment by Ivanovic24** [comment]
Pienso que, deberia ampliarse a 10 asesinatos seguidos, ya que un usuario tiene 10 de power y se pierde alrededor de 2 de power por muerte, lo que hace que con 10 asesinatos no sea necesario matarlo mas, sería mas facil bajar el power para conquistar una faccion y el spawnkill abusivo se sigue pudiendo disminuir.

**Comment by MithrandirCraft** [comment]
@Ivanovic24 
Detalles sobre el funcionamiento de la expulsión automática por abuso de asesinatos:
Asesinatos máximos: 5
Limite de tiempo: 240 segundos = 4 minutos. Este es el tiempo tras el cuál al asesinar a alguien se cuenta el siguiente asesinato como un asesinato posiblemente abusivo, al llegar a 5 se aplica el castigo, pero si evitas realizar un asesinato al mismo jugador en este periodo de tiempo tras el último asesinato, evitas el castigo por abuso.
Castigo: expulsión del servidor de 1 minuto y consecuencias adicionales.
Protección del jugador que recibe la paliza al reaparecer: 8 segundos (Suficiente para largarse.)

Como ves, el sistema és bastante flexible. Ya se encuentra perfectamente configurado, por lo que aumentar el máximo de asesinatos tan solo fomentaría el spam de spawn kills.

**Comment by Nepo23** [comment]
Bueno pruebas de que se puede repetir...
1)
![2015-07-10_20 27 21](https://cloud.githubusercontent.com/assets/8717280/8631768/a531fe5e-2745-11e5-90ad-7076f0ec6f43.jpg)

Aca muestro los objetos que tenia inventario lleno, luego de esto enpese a matarlo
2)
![2015-07-10_20 32 31](https://cloud.githubusercontent.com/assets/8717280/8631772/b891a63e-2745-11e5-834e-5c37fc8ffd3a.jpg)
Ya lo e matado 5 veces pero observa el mensaje 50% recuperado xD
3)
![2015-07-10_20 31 33](https://cloud.githubusercontent.com/assets/8717280/8631785/1c5f274a-2746-11e5-9e7a-d31b78c8d44b.jpg)
Aca muestro los objetos que quedaron al personaje.
4)
![2015-07-10_20 34 12](https://cloud.githubusercontent.com/assets/8717280/8631788/350892f4-2746-11e5-85e8-11dbb8cc910a.jpg)
Esto es lo que termino quedando en mi personaje sumando lo del personaje que mate varias veces.
Y lo demas!!!?
Se lo llevo el aire jajajaja

.

**Comment by xDarkSoul** [comment]
Mith creo deberías pensar en el plugin , si antes no teníamos castigo por spawn kill  y reaparecíamos en el f home , no entiendo la decisión de ponerlo ahora , cuando reaparecemos en /spawn y tu eres el que decide si vas o no vas , e incluso hay una zona de enderchest , los cuales pueden facilitar que el jugador que este siendo raideado pueda coger una armadura si la guarda previamente , porque si pones un limite tan bajo es casi imposible raidear una fac por power ya que aveces solo basta con matar al único jugador que este activo en la fac y con 5 kill no da para nada.
creo que tendrías que replantear el retirar este plugin por que lo único que hace es complicar la vida a los que atacan, nosotros no tenemos culpa de que no se queden en el spawn y vallan sin ninguna armoradura a intentar defender , la decisión es suya...

**Comment by MithrandirCraft** [comment]
@xDarkSoul Esta medida lleva en el servidor desde hace más de 8 meses.

Pero tienes buenos argumentos.

He hecho más permisivo el sistema. Pero tened en cuenta que muchos jugadores podrían aprovechar para abusar y ascender en el ranking.

**Comment by xDarkSoul** [comment]
si ocho meses pero la ultima vez que raidee por pow estaba a 10 o asi no a 5 xD de todas formas no podrías bloquear las kills solo para el ranking? en plan como el castigo pero a partir de 5 kills el mismo player que no te cuenten para el ranking . respecto a lo de abusar se puede hacer con o sin el plugin pidiendo a players nuevos cambiar kills por esmeraldas

**Comment by MithrandirCraft** [comment]
@xDarkSoul Siempre ha funcionado de la misma manera el limitador de asesinatos.

Esta es la primera vez que lo cambio.
