### ISSUE TITLE
Tnt No Rompe Menas

### ISSUE THREAD

**Issue by Nepo23** [MithrandirCraft/MithrandirCraft#72]
Bueno esto no se a que se deva pero la tnt por mas que explote o ponga no rrompio estas menas:
Caños de todos los tipos y estas menas son inmortales.
Sugerencia revisar la tnt tiene suficiente potencia?
O has protegido las menas contra la tnt?
Si las has protegido todos a poner menas en ves de obsi parese mas economico XD.
![2015-07-03_22 54 35](https://cloud.githubusercontent.com/assets/8717280/8506389/ddaeb7b4-21d6-11e5-9f6e-c1f19be749eb.png)
![2015-07-03_22 54 23](https://cloud.githubusercontent.com/assets/8717280/8506391/f7c17df8-21d6-11e5-8275-d1dde9fba817.png)

**Comment by sadow2811** [comment]
a mi también me pasaba pero solo en terrenos no claimeados que yo recuerde

**Comment by Ivanovic24** [comment]
A mi me pasa pero en carbon

**Comment by Nepo23** [comment]
Chicos A mi me pasa?
SI ha pasado anteriormente porque no lo mencionan?
Ayuden al servidor y cuando encuentren bugs o cosas que anteriormente no pasaban mencionenlas en este apartado no se adapten a estas rarezas.

**Comment by MithrandirCraft** [comment]
Interesante, lo revisaré pronto :)

Cualquier detalle adicional es bienvenido, haced caso a @Nepo23 :+1:

**Comment by MithrandirCraft** [comment]
Hola. Hay algo de progreso en este caso. He encontrado exactamente lo que lo está causando, y se trata un error relacionado con el limitador de minería.

He reducido un poco la facilidad de abusar de este bug, pero aún queda trabajo.
