### ISSUE TITLE
Crash sistema de contraseñas

### ISSUE THREAD

**Issue by Nepo23** [MithrandirCraft/MithrandirCraft#73]
Bueno el servidor ya nos va sacando por segunda vez o talvez an pasado mas veses pero esto es lo que tome fotos.
No se que pase pero aca pruebas.
![2015-07-04_21 03 01](https://cloud.githubusercontent.com/assets/8717280/8510017/9e39defa-2290-11e5-8de3-4f1de148993f.png)
![2015-07-04_21 02 45](https://cloud.githubusercontent.com/assets/8717280/8510019/b50ea0f2-2290-11e5-964f-7eb9d183d37d.png)

**Comment by Ivanovic24** [comment]
Hubiera molado q la foto hubiera sido con F3 xd.
No entiendo lo que reportas u.u

**Comment by Nepo23** [comment]
Reporto que el servidos va sacando a los jugadores, varias veses, Indico que no ha mencionado reinicio o algo por el estilo, ademas que antes da un lag tremendo y saca a las personas de su faccion por unos pequeños segundos.
Problemas como este pueden llegar a mas, si no se observa las causas.

**Comment by MithrandirCraft** [comment]
@Nepo23 El servidor kickea a los jugadores del servidor o los expulsa de la facción unos segundos y regresan a la facción transcurridos unos instantes?

Si se trata de perdidas de conexión, kicks, o crashes... Estoy bastante seguro de que esto lo causa un defecto con el sistema de contraseñas que ya estoy intentando arreglar desde hace mucho tiempo, recientemente hay progreso en el asunto. Solo el tiempo podrá solucionarlo, eventualmente dejará de ocurrir cuando lo arregle.

**Comment by Nepo23** [comment]
El orden es:
1)  lag no se pueden habrir cofres pero se puede hablar por chat.
2) Expulsa a los jugadores de la faccion durante como mucho 2 segundos.
3) Al pasar dos segundos el servidor expulsa a los jugadores. (Parese que se reinicia no se que haga).
4) Tras pasar un tiempo no me fije cuanto fue el servidor esta online, pero ya todo normal estamos en las facciones como si no pasara.
La duracion de esto es como mucho 15 segundos segun mi criterio porque platica un poco antes de que me sacara.

**Comment by MithrandirCraft** [comment]
Es un crash causado por el sistema de contraseñas. Este ticket permanecerá abierto hasta que se resuelva el error.

**Comment by vegetagamer9** [comment]
Mith cual sera la IP no la encuentro en el facebook

**Comment by MithrandirCraft** [comment]
Arreglado. Porfavor reabre este ticket si el problema reemerge.
