### ISSUE TITLE
Me mutearon

### ISSUE THREAD

**Issue by byDave2** [MithrandirCraft/MithrandirCraft#74]
Me mutearon sin motivo, estuve spameando eso para que me echaran a ver si se daban cuenta y suicidandome para llamar la atencion

**Comment by Nepo23** [comment]
Eres muy grocero ya te lo habia advertido ademas te kickee varias veces y no te calmabas no se quien te muteo pero sin razon dudo que fuera. El mute se termina en un tiempo asi que a comportace y dejar de ser tan grocero con todas las personas

**Comment by MithrandirCraft** [comment]
@byDave2 Porfavor respeta la normativa. Leela en /rules o www.mithrandircraft.es/normas

Recuerda que realizar esta acción al entrar al servidor és obligatorio.
