### ISSUE TITLE
Kickeo en combate

### ISSUE THREAD

**Issue by iKaooXx** [MithrandirCraft/MithrandirCraft#75]
Estaba en la fac de yolista24 con iKaooXx y el server me kickeo en combate por lo que perdi las cosas y quiero recuperlarla debido a que fue fallo del servidor 
![2015-07-16_14 10 15](https://cloud.githubusercontent.com/assets/13365332/8722573/41f41f86-2bc6-11e5-86d3-0434a8ef0f78.png)

**Comment by Ivanovic24** [comment]
Podrias escribir la hora exacta sobre la que ha ocurrido? Esto podria deberse al anti spamkill, que esta habiendo problemas con el.

**Comment by MithrandirCraft** [comment]
@Ivanovic24 Podría deberse a eso y a 100 motivos más. Pero es bastante probable que tengas razón y sea esto.

@iKaooXx Sin la hora y sin mensaje de expulsión no puedo hacer mucho. Si por lo contrario fuiste Expulsado durante 1 minuto y no kickeado, és bastante probable que hayas sido castigado por abuso de asesinatos. Esta medida lleva ya bastante tiempo en el servidor, me sorprende que la gente empiece a notar los efectos ahora.

También veo que en la imagen que proporcionas sacas una foto del chat donde bernaldito16 es castigado por escapar de un combate. Es este tu personaje? O se trata de otro jugador a quien le ha ocurrido lo mismo?

Porfavor, proporciona los datos que te he pedido. Procura incluir mas detalles en futuros tickets.

**Comment by Nepo23** [comment]
1) La informacion que proporcionas no esta completa.
Falta: 
a) Fecha
b) Que hacias antes del kick
c) Te desconectaste en combate?
d) Cuanto duro el kick?
e) Cuantos jugadores estaban el el suceso
procura dar detalles y mencionar claramente cada uno

**Comment by vegetagamer9** [comment]
yo lo vi y era injusto porque yolista24  iba todas las veces que podia aproposito para que le kickearan a bernaldito16 perdio una p4 injustamente hagan algo

**Comment by vegetagamer9** [comment]
yo intento trollearlo para devolverle su p4 y sus cosas

**Comment by MithrandirCraft** [comment]
Estoy seguro de bernaldito irá con mas cuidado en el futuro.

**Comment by vegetagamer9** [comment]
y ... yolista24 es hacker y motherfucker
 porque me enfrente a _motherfucker_  me ponia f5 y me pegaba de espaldas yolista24 bernaldito16 dice que es hacker tmb los quiero baneenlo durante unos dias

**Comment by vegetagamer9** [comment]
es mother_;fu:;^cker

**Comment by MithrandirCraft** [comment]
Si quieren seguir comentando sobre el sistema anti abusos de asesinatos, haganlo en este ticket, que al fin y al cabo es el pertinente: https://github.com/MithrandirCraft/MithrandirCraft/issues/71

**Comment by vegetagamer9** [comment]
mith quiero ser moderador

**Comment by vegetagamer9** [comment]
¿como seria?

**Comment by vegetagamer9** [comment]
mith como puedo ser moderador

**Comment by MithrandirCraft** [comment]
@vegetagamer9 Comentarios eliminados. No tienen nada que ver con el hilo de este tema, visita las faq's: www.mithrandircraft.es/faq, tienes toda la información que necesites en la web.

El hecho de que hagas preguntas por aquí demuestra que no tienes las suficientes ganas como para investigar.

**Comment by bernaldito16** [comment]
era yo bernaldito16 y la tia me dejo encerrada em su fac (encima es hacker) y no paraba de venir la consola me kickeo y mori creo q fue sobre las 2 no se la hora exacta

**Comment by MithrandirCraft** [comment]
Comprendo... te quedaste atrapado dentro de una facción. Pero cuando tomaste la decisión de entrar en esa facción tomaste ese riesgo. Tu eres el responsable de esas consecuencias.

Aún asi voy a intentar tomar unas medidas para mejorar la experiencia en este tipo de situaciones.

**Comment by bernaldito16** [comment]
lol pero que dices macho el spamkill nunca te mataba y ahora por culpa de una hacker lo pierdo to y ensima dises q es culpa mia que el este bug el spamkill y no me des mis cosas

**Comment by MithrandirCraft** [comment]
Como he dicho, me miraré este asunto. Algo tiene que mejorar, no es cohincidencia que no seas la única persona en mencionar este asunto.

Para futuros comentarios sobre esto, porvavor dirigete al ticket #71
