### ISSUE TITLE
Sistema de subastas en Mithrandir (Participación Libre)

### ISSUE THREAD

**Issue by JC1609** [MithrandirCraft/MithrandirCraft#77]
Mi Nick name es JC1609_ en el servidor..
Quiero proponer que en el servidor de Mithrandir Craft se comienze a usar el plugin Auction o subasta por chat...Para que este plugin funcione se necesita money (pluggin de economia) para conseguir money se requieren Jobs (trabajos)... Seria un problema poner estos plugins porque Mithrandir Craft tiene el sistema de tradeos directos con NPC´s por medio de esmeraldas, pero yo tengo la solucion; el sistema de tradeos por esmeraldas no se tocara para nada, el dinero solo se utilizara para las subastas por chat, y como conseguiremos el dinero? con Jobs todos los trabajos normales exepto enchanter y repair, Porque son propensos a ser glitcheados y conseguir money infinita (experiencia propia) bueno el plugin de subastas funciona de la siguiente manera: El vendedor pone su Producto a subastar con un precio inicial ej Producto:Pico de diamante (encantado) (gastado) inicia:100$
como sabremos que encantamientos y que tan gastado el pico este? con /auc info o /auc i
y saldrá: Pico de diamante (Eficiencia 2 - Durabilidad 2) (230 - 1500) usos..
las subastas duraran de 30 segs a 5 mins.
Y que pasa si varias personas a la vez quieren subastar?
Habrá un sistema de subasta en Cola por ejemplo uno subasta un pico y otro 64 diamantes
cuando termine la subasta del pico habrá un mensaje en el chat: en un minuto comienza la siguiente subasta.
No sera obligatorio participar, el vendedor tendrá que poner un precio inicial de 50 para arriba
y podrá quitar la subasta cuando lo desee si no esta de acuerdo con el precio o si se arrepiente.
y con respecto a los jobs solo podrás estar en un solo trabajo a la vez. muchas gracias

**Comment by MithrandirCraft** [comment]
Hola. Tener subastas no es una mala idea, pero añadir más complejidad al servidor significa lo siguiente:

+ Plugins = + Procesos para nuestra pobre CPU que ya sufre + Posibles errores, y + necesidad de Mantenimiento.

Incluir una economía numérica es algo que se ha sugerido centenares de veces, pero si lo vieseis desde mi lugar, llegaríais a la misma conclusión desde un punto de vista interno, no es conveniente a pesar de que sea una idea agradable.

Se que es un poco rudimentario, pero como alternativa tienes el chat del servidor (que si algún día llega a llenarse de spam puedo regularlo por canales.) y el apartado de Comercio en el foro, donde está 100% permitido realizar subastas.

También ten en cuenta de que aunque en nuestro servidor no se produzcan subastas tan molonas como en otros servidores, tenemos muchisimos elementos que hacen único al servidor.

Te sugiero que si todavía no lo has hecho, visites /warp tradeos, donde encontrarás montones de tiendas establecidas por otros jugadores.

**Comment by JC1609** [comment]
La verdad es que no había pensado en eso...
Ya visite /warp tradeos y soy un cliente activo, pero note que solo la fila de adelante son tiendas y también que solo venden siempre los mismos usuarios, debieran buscar una solución a eso..
Próximamente estaré dando mas ideas y propuestas pero esta vez los pensare e investigare un poco mas..
Igualmente gracias :)

**Comment by Ivanovic24** [comment]
Las filas de atras tambien se pueden poner tiendas.
