### ISSUE TITLE
\* Bug sistema de contraseñas.

### ISSUE THREAD

**Issue by GabbGabb** [MithrandirCraft/MithrandirCraft#78]
Ya he pasado por bugs que me han limpiado o estropeado el inventario en mas de una ocasión, pero esta vez, han sido dos seguidas y las perdidas han sido muy altas. Los dos bugs han ocurrido técnicamente la misma semana, pero han sido diferentes.
Por ejemplo, mirad la "Bara Incandescente" tras los dos bugs.
![2015-07-25_20 47 36](https://cloud.githubusercontent.com/assets/12144547/8890820/e74a8de0-330e-11e5-8718-a4e660297e85.png) El primer bug solo conservó los efectos mágicos predeterminados.
![2015-07-25_20 47 38](https://cloud.githubusercontent.com/assets/12144547/8890821/e7506ce2-330e-11e5-97d3-4f13eec3c7ae.png) Y el segundo, ocurrido el 25/07 bugeó el nombre, los efectos mágicos. pero conservó el texto (también bugeado).

También items normales como armaduras de hierro se han visto doblemente bugeadas.
Con el primer bug se veía el típico simbolo de este fallo: /* (pero con la barra inversa)

Pero estos items se vieron doblemente bugeados, siendo ahora así:
![2015-07-25_20 47 57](https://cloud.githubusercontent.com/assets/12144547/8890834/b727bcd6-330f-11e5-9fe2-28200728dcca.png)
![2015-07-25_20 47 59](https://cloud.githubusercontent.com/assets/12144547/8890835/b729fcda-330f-11e5-86e6-bd9189a9c5d6.png)

Normalmente no me quejaría por algo como esto, pues ya ha ocurrido antes y es algo que supongo que es impredecible, pero cuando solo ocurre a ciertas personas ya es algo irritante, pués hasta la fecha, no me he librado de estos bugs, como el de los HG...

Y esta vez ha dolido bastante porque los 2 sets de equipo que me han dado estos días para reponer las perdidas han sido bugeados otra vez, y en un tiempo récord.
Un ejemplo es el arco OP que me dió Dei para sustituir mi Ballesta Sintética:
![2015-07-25_20 47 42](https://cloud.githubusercontent.com/assets/12144547/8890848/97283a68-3310-11e5-845b-dc6399752148.png)

Diablos! Si en el primer bug de la semana perdí todo por conectarme a los 10 segundos de un kick masivo o algo!
Esta vez son muchas cosas perdidas que me gustaría recuperar.

Voy a desahogarme...
Me atrevería a decir incluso, que soy de las pocas personas que se han visto afectadas por todos los bugs que han ido afectando el tema inventarios.
Incluso cuando se recortó el mapa del survival perdí todo (casa incluida)
![2015-06-23_00 24 02](https://cloud.githubusercontent.com/assets/12144547/8890882/c0250724-3311-11e5-8923-a03ab7121e2a.png)
Aquí había una bonita casa... cuando hice /home pasó esto...

Si puedo recuperar esta vez las cosas, bien, si no... comenzaré a pensar que hay un complot contra mi persona ò_ó

**Comment by ModFarmex** [comment]
Esta solía ser la bonita casa (Nuestro hogar en survival u.u).
Parte interior:
![casa interior](https://cloud.githubusercontent.com/assets/12589956/8891131/321c6ffa-32e2-11e5-9732-6e92ac597894.png)

Aquí la parte de arriba:
![2015-05-05_18 45 33](https://cloud.githubusercontent.com/assets/12589956/8891137/7b1e22ac-32e2-11e5-8ffc-99807e521eb6.png)

**Comment by MithrandirCraft** [comment]
Lo siento.

Se exactamente lo que esta causando ese famoso error. Se llama \* y lo llevo arreglando desde hará unos 6 meses.

Cada vez estamos mas cerca de arreglarlo, solo puedo decir que estamos en ello, y que este error, además del lag, y los crashes que se producen en el servidor, todo se debe al mismo error.

Espero poder arreglarlo cuanto antes, y hacer que se dejen de producir estos problemas.

**Comment by MithrandirCraft** [comment]
El ticket permanecerá abierto hasta que el error sea erradicado.

**Comment by MithrandirCraft** [comment]
Recuerda que el lugar mas seguro para tus objetos es siempre el Enderchest.

**Comment by GabbGabb** [comment]
Cambio de imagen por un caso en exceso extraño y paranormal del github donde ciertas personas, veían cosas raras donde otros veían un libro bugeado.

Esto es también algo reportable? xD

**Comment by MithrandirCraft** [comment]
@GabbGabb no.

**Comment by MithrandirCraft** [comment]
Arreglado. Porfavor reabre este ticket si el problema sigue emergiendo.
