### ISSUE TITLE
No recibo el mail de recuperacion de contraseña

### ISSUE THREAD

**Issue by TheXapurri** [MithrandirCraft/MithrandirCraft#79]
He olvidado la contraseña con la que entro en el server, y he hecho lo de mail recovery poniendo el mail con el que me registre, aun sigo sin recibir el mensaje con mi nueva pass.
Saludos

**Comment by MithrandirCraft** [comment]
Hola. Siento que hayas tenido este problema, a pesar de que hay un cartel en la zona de logueo indicando que el sistema de e-mail está en mantenimiento, y estoy al corriente de que hay malfunciones con el sistema de recuperación por e-mail.

Es por ello que hoy se ha realizado un mantenimiento para intentar solucionar este error, y varios otros con el sistema de contraseñas que llevan afectando al servidor toda esta semana.

Para reestablecer tu contraseña haremos lo siguiente:

- Indicanos tu e-mail, y enviaremos una contraseña manualmente.

Tras el mantenimiento que acabamos de realizar, se espera que este problema se resuelva, pero todavía hará falta comprobarlo. Espero que no se queden clavadas asi las contraseñas de más jugadores.

**Comment by MithrandirCraft** [comment]
Si no nos indicas tu e-mail en 3 días, procederé a cerrar este ticket.
