### ISSUE TITLE
Increible y asqueroso bug

### ISSUE THREAD

**Issue by Ivanovic24** [MithrandirCraft/MithrandirCraft#8]
Hola, bueno hoy un dia como otro cualquiera me entran ganas de entrar al servidor y al entrar me encuentro con una ''agradable'' sorpresa :c:
Todo mi inventario se le cambia el nombre de los objetos por estos simbolos: \* ; y los q ya tenian nombre como mi espada y mi arcose pone asi: Nombredelarma\*. Ahora subo las fotos:
http://imgur.com/8UpxqzY,Y8Fv9Uy,yA4Baer,6X3cmxW,PfFOx7U,HuUez6U,LcpqXg7
Y no solo eso, si no que los encantamientos de las armas se han borrado tambien.

Lo curioso es que esto no ha ocurrido con las armaduras.

Un Saludo.

**Comment by Ivanovic24** [comment]
Los encantamientos de las armas eran:
Espada: SandaiKitetsu: Agu 5, Irrom 3 empuje 2 , botin 3.
Arco: Arco De Fuego: Poder 5, irrom 3, fuego 1 y infinidad 1

Lo ocurrido fue entrando sin mas no ice otra cosa

**Comment by MithrandirCraft** [comment]
Hola. Hace 2 días hubo un fallo del servidor que causó rollback de inventario y mapa (rollback de aproximadamente 3h máx).

Esto podría haber sido suficiente para corromper tu inventario.

Me gustaría saber 2 cosas:
  - Tu arma y equipo son creadas y encantadas recientemente?
  - Las armas y armaduras adectadas son modificadas/obtenidas de drops de Jefe?

**Comment by Ivanovic24** [comment]
las armas y armaduras son totalmente del survival normal sin jefes y ademas son bastante antiguas y anteriores a la actualizacion del servidor

**Comment by MithrandirCraft** [comment]
Coloca tus objetos corruptos en el inventario, y me encargaré de sustituirlos por sus originales.

**Comment by Ivanovic24** [comment]
OK TARDO NADA

**Comment by Ivanovic24** [comment]
Gracias!
