### ISSUE TITLE
Desaparición de armadura causada por el sistema de contraseñas (#Parche 2 - ¿A alguien ocurre esto desde el 21/09/2015? ¡Comenta aquí!)

### ISSUE THREAD

**Issue by Adrinaruto10** [MithrandirCraft/MithrandirCraft#81]
cuando me logeado en el servidor a las 20:00 me di cuenta de que mi armadura me había desaparecido

**Comment by MithrandirCraft** [comment]
Hola, porfavor, responde a las siguientes preguntas:
-Recuerdas si apareciste en el "Limbo" de logueo al descubrir que tu inventario había desaparecido?
-En que mundo deslogueaste?

Ya estamos al corriente de estos sucesos y estamos arreglandolos. Este ticket permanecerá abierto hasta que el asunto se solucione.

**Comment by Adrinaruto10** [comment]
No aparecí en el limbo, pero se me puso como si me hubiera logeado en el servidor de cubecraft.
Me desconecte en el spawn.

**Comment by Ivanovic24** [comment]
Lobezno me a dicho que le a desaparecido una armadura de diamante

**Comment by unicorn4771** [comment]
Hola mith al día después de la desaparición de mi armadura, volví a perder no cosas de gran valor pero si desaparecieron cosas del  inventario.

**Comment by MithrandirCraft** [comment]
Parche aplicado el día 16/09/2015 a las 6:00h A.M. para remediar la perdida de inventarios causada por el sistema de contraseñas

Pregunta:
¿Alguien más se ha desconectado desde hoy (dicha fecha) a las 6:00h A.M. con su inventario en perfectas condiciones, y se ha reconectado rato después para comprobar que su inventario había desaparecido?

**Comment by villamusta** [comment]
Hola no se si sea exactamente el mismo busg, pero ya me a pasado dos veces.. la primera entre mi ultimo log del dia lunes y apareci sin nada en el inventario el dia de ayer y nuevamente me a vuelto a pasar el dia de hoy en la tarde. la primera vez estaba en mi casa de faction y al reloguear apareci donde mismo habia dejado el pj y la segunda vez en un sector del mundo de faction en el norte

**Comment by caler1234** [comment]
admin ami se me bugio todo lo del survival y ya puse todo lo que perdi y a que hora solamente quiera pregunta que si me lo podian devolver

**Comment by AwesomeDenis** [comment]
A mí me pasó ayer en /warp factions. D:

**Comment by MithrandirCraft** [comment]
Aplicado segundo parche. Si a alguien le sigue ocurriendo, porfavor comuniquenmelo :)
Porsupuesto, el reset que realizamos ayer lo doy por evidente e irrelevante a este tema.

**Comment by MithrandirCraft** [comment]
Voy a dar este bug por arreglado. Si alguien sigue teniendo este problema, quizá vuelva a abrir este ticket.
