### ISSUE TITLE
Ville_Y4 robando con kill aura

### ISSUE THREAD

**Issue by vegetagamer** [MithrandirCraft/MithrandirCraft#82]
Ville_Y4 aprovecha cuando no hay Moderadores ni Admins para robar cosas y tiene kill aura me pega de espaldas

**Comment by vegetagamer** [comment]
y se hace tp a todas las facs para matarlos con el kill aura y a mi amigo lobezno02 le quito una agudeza 5

**Comment by JoseVille** [comment]
Ja ja ja argumentos te faltan amigo tienes alguna prueba de que uso algun tipo de hacks mas bien deberias tu sentirte mal que tu eres el que los usa como me voy a hacer tp a las facs sin permiso ademas si fuera a las facs no los podria matar porque tienen esa zona claimeada ustedes me matarian a mi buscate otro argumento lo que dices no tiene sentido. GRACIAS

**Comment by vegetagamer** [comment]
tienes kill aura y vas por ahi cogiendo cosas

**Comment by vegetagamer** [comment]
y si le pones enemy les puedes pegar no te hagas el tonto ;)

**Comment by JoseVille** [comment]
jajaja yo no soy tu enemy y si soy tu enemy es porque tu me pusiste lloron ademas como les voy a matar si ustedes van todo chetados

**Comment by vegetagamer** [comment]
matas a los que no van chetados

**Comment by JoseVille** [comment]
Ahh y por cierto chetados de cosas robadas a la mayoria  del server les consta que ustedes roban para tener lo que tienen ;)

**Comment by vegetagamer** [comment]
no

**Comment by vegetagamer** [comment]
nos los conseguimos nosotros

**Comment by vegetagamer** [comment]
matando gente legal

**Comment by JoseVille** [comment]
jajajaja claro robando

**Comment by JoseVille** [comment]
Amigo la verdad duele

**Comment by vegetagamer** [comment]
si la verdad duele para ti

**Comment by vegetagamer** [comment]
hacker

**Comment by vegetagamer** [comment]
con kill aura pegando de espaldas

**Comment by JoseVille** [comment]
tienes algo grabado o fotos que lo comprueben ademas, todo esto inventas por tu amigo que me regalo la espada y ahora esta arrepentido que conste que tu amigo iba proteccion 4 y yo con nada apenas con la espada que me dio como lo podia matar hablas sin argumentos

**Comment by vegetagamer** [comment]
no pero las conseguire

**Comment by vegetagamer** [comment]
me voy

**Comment by JoseVille** [comment]
jajajajajajajaajaja buscate otra escusa para que me baneen sin haber echo nada chau espero encuentres algo aunque creo que no porque eres falso

**Comment by MithrandirCraft** [comment]
Menudo espectaculo.

@vegetagamer porfavor proporciona pruebas visuales (video o fotos) para acompañar a futuros reportes.
