### ISSUE TITLE
Uso de Rayos X

### ISSUE THREAD

**Issue by Pepelu1234** [MithrandirCraft/MithrandirCraft#83]
Hola, vengo para realizar una queja, ya que una gente del servidor de facciones, ha usado el HACK de los Rayos X para encontrarnos y destruirnos, estos estaban picados con nosotros, porque anteriormente estabamos en su facción pero tras una discusión por una tonteria nos separamos y por eso sabemos que esta facción, Trynda, tienen dicho hack para poder encontrarnos y vengarse, y sabemos que lo han usado porque era muy dificil encontrarnos ya que los que nos fuimos estuvimos media hora corriendo y navegando para estar lo mas lejos posible. Queremos que estos sean castigados de alguna manera, por favor pedimos ayuda. 

Un saludo y gracias por su atencion.

**Comment by usuariosequeja** [comment]
Pertenecía a un clan con Pepelu1234 y doy crédito de sus palabras.

**Comment by Ivanovic24** [comment]
Quiero que decirles que, como ya sabran, existe un comando llamado /F map con el que puedes ver todos los claims de facciones que hay en la zona. Ademas con la nueva modificacion del sistema de contraseñas, al intentar loguear, apareces en el ultimo punto de desconexion con lo que pueden haber hecho el intento de loguear con alguna cuenta perteneciente a algun miembro de tu faccion y haber cojido coordenadas, esto tambien es ilegal. Igualmente no se puede descartar el uso de xrays si vuestra faccion se situa bajo tierra, si no es el caso, y se encuentra en la superficie o en el cielo, es muy sencillo encontrarla. 

Sin pruebas sobre sus delitos no podemos hacer nada, como mucho esperar, si enrealidad si son hackers, tarde o temprano seran descubiertos y sancionados.

**Comment by MithrandirCraft** [comment]
Como ya ha dicho @Ivanovic24 
Y añado varios puntos cruciales.

*Según la normativa vigente del servidor, el uso de Xrays Overworld está permitido (Uso de xrays en cualquier situación fuera de minería.).
*Según la normativa vigente, el uso de tracers y minimapas está permitido.

Con alguna de las 2 anteriores tecnicas es posible detectaros en cercanías 100% legalmente en MithrandirCraft.

"¿Pero mith, entonces eso significa que yo tambien puedo ponerme a usar xrays?"

La respuesta es si, siempre y cuando no los utilizes para minar.

**Comment by MithrandirCraft** [comment]
Por tanto este caso no viola ninguna normativa ni en el supuesto de que sea información veraz.

En futuros tickets por favor proporcionad información visual complementaria (Imagenes < Videos).
