### ISSUE TITLE
Eliminar apartado blog (Web)

### ISSUE THREAD

**Issue by MithrandirCraft** [MithrandirCraft/MithrandirCraft#84]
En el apartado "Blog" el desplegable (incorrectamente distribuído) aparecen por debajo de las entradas de blog.
![screenshot_2](https://cloud.githubusercontent.com/assets/6623704/9429545/10ded39c-49d4-11e5-8d3c-820bfad8790c.png)

Los apartados no estan divididos de la misma forma que como se visualiza desde cualquier otro apartado, siendo los desplegables correspondientes: Información> Info, Staff, Normas y Catalogos > Comandos, Magias, Jefes.

**Comment by Ivanovic24** [comment]
Vaya webmaster, madre mia..... Nope xd.

**Comment by MithrandirCraft** [comment]
Este ticket puede cerrarlo @BlackBeemo cuando quiera.

Hemos acordado que el apartado Blog se va.
