### ISSUE TITLE
Bug Que Te conectas sin lo que tenias del inv 

### ISSUE THREAD

**Issue by vegetagamer** [MithrandirCraft/MithrandirCraft#85]

**Comment by vegetagamer** [comment]
a colo997 acaba de decirme que perdio todo su inv es la 4 vez que le pasa :/

**Comment by vegetagamer** [comment]
Mithrandir haber si puedes poner el SV en arreglar ese bug cuando tengas tiempo

**Comment by vegetagamer** [comment]
Aunque tengas que poner el sv en mantenimiento

**Comment by MithrandirCraft** [comment]
Replica de #81
