### ISSUE TITLE
adquisición de ts una posible propaganda para el servidor

### ISSUE THREAD

**Issue by xDarkSoul** [MithrandirCraft/MithrandirCraft#86]
Buenas hace poco me entere de que mithrandir tiene ts y me parece un gran avance pero hay otras comunidades mas aya de factions que buscan ts . aquí se podría hacer cierta publicidad a parte de añadir salas de lol y counter strike. Aquí viene mi propuesta que es dedicar un cierto espacio a los team de oc.tc . esta comunidad esta siempre entrenando pera los torneos del servidor en el que juegan y la gran mayoría de teams por no decir todos usan ts ya que es mejor que skype para estas de 6 personas en adelante en una conversación , al dejar un apartado para ellos , como también les gusta todo lo que tenga que ver con el pvp pues lo mas seguro es que jugasen un tiempo si les gusta el servidor. 

-Espero que te parezca interesante mi propuesta ^^

**Comment by MithrandirCraft** [comment]
Se lo he comentado a los responsables del TS. Dependerá de su decisión.
También puedes entrar tu mismo al TS y comentarselo.

**Comment by RufiRufil** [comment]
Hola xDarkSoul, ya he visto que has entrado al ts3 pero te contesto ahora porque antes no pude. Quería decirte que si que haremos lo de oc.tc pero estaría bien hacerlo con un equipo, ya que si lo hacemos y nadie entra sera un poco inútil, pero seguramente lo aremos. Gracias por la propuesta.
