### ISSUE TITLE
Desaparición de la armadura 

### ISSUE THREAD

**Issue by unicorn4771** [MithrandirCraft/MithrandirCraft#87]
Hola, hoy entre al server, luego de un rato el servidor me saco y cuando volví a entrar mi armadura había desaparecido. Perdí el armor y eso que la tenia puesta..
A alguien mas ya pasado por este error? 
Mith  se puede recuperar las cosas que se pierden?
Mi nombre es unicorn4711, el dia de la desaparicion fue el 01/09 en la noche

**Comment by MithrandirCraft** [comment]
Lo siento, pero esto le ocurre a varios jugadores, y no puedo reestablecer con ningun grado de detalle los objetos perdidos.

Estamos trabajando para procurar tener backups mas regulares para que si a alguien le ocurre esto en el futuro podamos reestablecer un backup del inventario.

**Comment by MithrandirCraft** [comment]
Perdiste algo mas a parte de la armadura?

**Comment by MithrandirCraft** [comment]
Replica de #81 Porfavor continua el tema allí.
