### ISSUE TITLE
Se bugean algunas cosillas.

### ISSUE THREAD

**Issue by krazlas** [MithrandirCraft/MithrandirCraft#89]
Esto ya me ha sucedido varias veces, pasa que te desconectas y cuando te conectas luego lo que tenias en el inventario se bugea, como libros encantados o espadas con acentos y nombres con símbolos o las magias de pergaminos. Esto es bastante molesto porque no se puede estar perdiendo cosas asi como asi, mas si son magias, ya que cuestan mucho dinero dentro del juego :(!

**Comment by MithrandirCraft** [comment]
No creo que ocurra con las magias. Creo que solo ocurre con objetos encantados.

Puedes sacar una foto de tu inventario bugeado porfavor?

**Comment by krazlas** [comment]
Aqui tengo algunos pergaminos y libros bug.
![Uploading Sin s.jpg…]()

**Comment by MithrandirCraft** [comment]
Ocurre cada vez que te desconectas? Ea, ya has cerrado el ticket? Bueno, tengo este problema en mi lista...

**Comment by krazlas** [comment]
Perdon por cerrarle, no he leido lo que decia el boton. Pero aqui te mando una captura por Gyazo, no es virus ni nada es una captura de pantalla que se envia por link https://gyazo.com/58cee9b0128489c58bb467a33ba14415
