### ISSUE TITLE
Fallo En los HG

### ISSUE THREAD

**Issue by Ivanovic24** [MithrandirCraft/MithrandirCraft#9]
Bueno el caso es que cuando comienza una partida de los hg, los objetos que se soltaron al morir los jugadores de la partida anterior siguen en la arena en la partida siguiente. Probablemente ya estes informado.

**Comment by MithrandirCraft** [comment]
Si, estoy informado, y no és el único error. De todos modos este ticket queda abierto hasta que sea solucionado.

**Comment by Ivanovic24** [comment]
E encontrado un agujero en el mapa: lunar
Si no lo an visto ya, mañana subire unas fotos de la localizacion de este agujero q permite salirse del mapa y volver a entrar si uno quiere

**Comment by MithrandirCraft** [comment]
Cierro esto. Las arenas serán restauradas.
