### ISSUE TITLE
Se bugean pergaminos y libros (#Parche 1 ¿A alguien le ocurre esto desde el 22/09/2015? ¡Comenta aquí!)

### ISSUE THREAD

**Issue by krazlas** [MithrandirCraft/MithrandirCraft#90]
Bueno, este post ya lo había abierto hace poco pero lo he borrado sin querer. El punto es que aveces cuando te desconectas con Libros Encantados en el inventario o Magias de pergamino se bugean y luego no funcionan. Aqui les dejo unas fotos.

https://gyazo.com/e540d81570722455c37396b9d6ebbaff

https://gyazo.com/e540d81570722455c37396b9d6ebbaff

**Comment by MithrandirCraft** [comment]
Deacuerdo. Este ticket quedará abierto hasta que este error sea solucionado.

Esta bastante claro que por el momento una solución es no dejar este tipo de objetos en el inventario.
El enderchest siempre és un lugar seguro, considera utilizarlo alternativamente como soporte.

**Comment by MithrandirCraft** [comment]
¿Sigue ocurriendo esto?

**Comment by MithrandirCraft** [comment]
Cierro ticket. Aparentemente no se ha vuelto a producir este error en un tiempo.
