### ISSUE TITLE
hola queria informarles que se me bugio lo que tenia en el inventario y que si me lo podia dar devuelta :D

### ISSUE THREAD

**Issue by caler1234** [MithrandirCraft/MithrandirCraft#91]
tenia las cosas el dia 15/09/15 a las 19:15 por hay y cuando entre el dia 16/09/15 no tenia nada y perdi todo lo que tenia en el inventario que eran
toda una armor con proteccion 4
una espada con filo 5 aspecto ardiente y otro encantamiento mas pero no me acuerdo xd
un pico con eficiencia 3 y fortuna
y algunas que otras potis 
todo esto lo perdi en el survival y las horas que dije fueron horas argentina

**Comment by Razelo** [comment]
Yo tambien perdi mis cosas las tenia el dia 15/09/15 a las 02:00 y al otro dia cuando entre el 16/09/15 a las 12:55 no tenia nada, tenia p4 entera con espinas 2 en el pecho y unas botas p4 caida de pluma 3 mas el p4 que lo tenia toda la armor tenia una espada de diamante con filo 5 aspecto ardiente 2 y durabilidad 2 pico de diamante fortuna 2 eficiencia 4 y durabilidad 3 y tenia 2 stacks y medio de obsi, eso es de lo que mas me preocupa, despues tenia comida algunos materiales y flechas

**Comment by Razelo** [comment]
las horas que puse en post anterior son de uruguay

**Comment by MithrandirCraft** [comment]
Hola buenas tardes.

Porfavor lean el último comentario y continúen este debate en el siguiente ticket:
https://github.com/MithrandirCraft/MithrandirCraft/issues/81

Procuren referirse al horario del servidor (visible en www.mithrandircraft.es)
