### ISSUE TITLE
Regresar al metodo de logueo en spawn normal para solucionar robo de coordenadas

### ISSUE THREAD

**Issue by krazlas** [MithrandirCraft/MithrandirCraft#92]
Hola, quiero reportar al jugador MoscaDopada por entrar con mi cuenta sin mi consentimiento y ver mis coordenadas, ha hecho una trampa en el lugar que yo estaba y he muerto a culpa de eso. Si pudieran solucionar el logeo en el lugar que estas a la brevedad posible seria perfecto. (Tambien debo destacar que he tenido parte de culpabilidad en no deslogear en el /spawn, pero de todas formas no es lo ideal.) Gracias por la atención. 

Att kraz1234

**Comment by MithrandirCraft** [comment]
Saludos.

Es cierto que es posible loguear en otras cuentas para coger las coordenadas de una facción, y llevamos sabiendolo desde el momento en que decidimos cambiar el punto de logueo al mismo punto de deslogueo.

El problema es que no podemos solucionar esto sin causar otros errores que hemos conseguido evadir con este metodo provisional.

La acción que describes está completamente prohibida actualmente, y puede ser castigada con una expulsión, el problema es que no nos estás proporcionando ninguna prueba sobre la infracción.

Por el momento te recomendaría que desloguees siempre en un lugar lejano a tu facción, para que no sepan donde se encuentra.

Cuando consigamos evadir estas situaciones por medio del metodo de logueo normal, este ticket será cerrado.

**Comment by krazlas** [comment]
Yo particularmente puedo descartar cualquier otra opción que halla podido tomar el player MoscaDopada para conseguir mis coordenadas exáctas de deslogeo, mas en un lugar tan remoto he inhóspito como en el que me encontraba. No he perdido nada sumamente importante, pero si me he enfadado un poco. Comprendo que ustedes han de tener problemas alternos a este que deben ser solucionados, ya sean mas importantes o de mayor gravedad etc. Bueno, gracias por responder.

**Comment by MithrandirCraft** [comment]
Los jugadores que realicen estas acciones recibirán su castigo pertinente.

**Comment by PandaGTA** [comment]
Mosca siempre hace eso ya se lo comentamos a los moderadores dentro el juego pero no hacen nada y ya de plano nos ignoran, la semana pasada estubo haciendo eso con el otro miembro de su fac. cambiamos de lugar la fac como 5 veses pero el siempre en menos de media hora la encontraba. entraba mataba y robaba, ademas de que cuando es muy tarde, altas horas de la noche se pone a estafar gente en tradeos. y hay muchos que ya lo reportaron pero los moderadores dicen que no tienen pruevas, hay 5 personas afirmando que mosca es asi y los moderadores no hacen nada?.

**Comment by MoscaDopada** [comment]
Me baneasteis, aún no ví pruebas. NP .

**Comment by MithrandirCraft** [comment]
Arreglado. Reabe este ticket si se vuelve a producir.
