### ISSUE TITLE
Mi baneo de 10 Días exijo explicación

### ISSUE THREAD

**Issue by MoscaDopada** [MithrandirCraft/MithrandirCraft#93]
Buenas me gustaria una explicación breve de porque me baneasteis 10 días sin tener pruebas de que yo no hice nada, ya que siempre que le pregunto al Mod (NADELINA) me dice regla numero 14 , la cual es la siguiente " Cualquier actitud que un administrador o moderador considere perjudicial para el ambiente de juego o el servidor en general. Me gustaría saber que hice mal para que mi actitud sea perjudicial para el ambiente de juego, ya que ella Nade, me baneo por la regla 14, pero Krazz por otra parte me dijo que me banearon por tenderle una trampa ya que segun el "me meti en su cuenta" y le puse un trampa donde deslogeo, cuando es todo falso. Esta claro que Krazz le dijo a Nade que me baneara pero como estan escasos nulos de pruebas, me banearon por la regla 14 "Por que sí" y cuando pido explicación no me dan ninguna, Aquí quiero que me digais el por qué y las pruebas, si teneis pruebas "no se de que" asumire . Por cierto a otro de mi fac, la banearon tambien (asdfghjk) cuando es una chica de 10 años que lleva jugando 5 días, todo por "XRAY", Ya van 2, Nadelina esta en Asgard nuestro principal enemigo, y tambien esta dentro Krazz el cual esta "muy cabreado" conmigo despues de millones de insultos ayer, por eso, me encuentro esto hoy, "sin motivo" , ¿Casualidad? ¿Corrupción de los Mods? , Necesito Respuestas a todo esto, y quiero que me responda Mith ya que los demas Mods también son enemigos y van por la misma rama que nade, Mith es el único que se podría encangar de este tema 100%, Gracias por su atención. Gracias. Espero respuestas pronto.

PD: tengo grabada conversación ( Mensajes ) Con nade, la cual me ignora mientras le pido explicaciones, mientras que me dice solo "Regla 14" a la misma vez krazz diciendome lo de la trampa en su cuenta. No concuerda nada, para mi es todo obra del "porque me caes mal" , Además un mod no puede tener esa actitud.

**Comment by MoscaDopada** [comment]
14 Horas, Sigo esperando, ¿No teneis puebas y estáis buscando alguna excusa fiable?, En fin...

**Comment by MoscaDopada** [comment]
20 Horas, Baneo sin pruebas, y nadie hace nada.

**Comment by BlackBeemo** [comment]
Se te a baneado por: Mutlicuenta, xray
No baneamos porque nos da la gana. El server dispone de plugins para detectar infractores y tu sales en ellos. 
El ban fue ordenado por el administrador principal y por eso voy a dejar el ticket un rato mas abierto.

**Comment by MoscaDopada** [comment]
Y porque, ¿Me dijistes norma 14? , No hice nada de eso, ya te estas inventando cosas ? , Eso es impresionante Mod Corruptos.

**Comment by BlackBeemo** [comment]
cierro el ticket por es poco constructivo. Y si estas baneado por la norma 14

**Comment by MoscaDopada** [comment]
Lo acabas de cerrar porque si, Dios mio pero por favor otro admin que se de cuenta de que este MOD es corrupto

**Comment by MoscaDopada** [comment]
WTF Pero me dices que por Xray y ahora por norma 14 !! pero por favor que este MOD esta loco mirarlo...

**Comment by MoscaDopada** [comment]
Aún no vi ni 1 Prueba de mis infracciones, todas mentiras, Me banearon por que el Jugador Kraz1234 se lo dijo a beemo que lo hiciera ya que su ticket contra mi no surgio resultado.

**Comment by MoscaDopada** [comment]
Exijo que otro mod o un admin observe el ticket vera que este mod es corrupto por favor. Gracias.

**Comment by MithrandirCraft** [comment]
@MoscaDopada 

Nadelina no es una persona corrupta. Simplemente hace lo que cree que tiene que hacer.

Si quieres ahorrarte estar en situaciones así en el futuro, procura dejarnos bien claro que eres un jugador ejemplar y no te hagas un mal nombre. 
He de decir que llevo tiempo observandote, y podría haber llegado a la misma conclusión que Nadelina sobre ti.
