### ISSUE TITLE
Martinetx entro con mi cuenta

### ISSUE THREAD

**Issue by vegetagamer9** [MithrandirCraft/MithrandirCraft#94]
Martinetx entro con mi cuenta y me puso ungister y tengo pruebas

**Comment by Nepo23** [comment]
Coloca las pruebas no las digas nada mas....

**Comment by vegetagamer9** [comment]
las pruebas se me borraron con la reforma de mi pc

**Comment by vegetagamer9** [comment]
pero tengo otras pruebas de que usa un mod que hace saber los corazones

**Comment by vegetagamer9** [comment]
= a hack

**Comment by vegetagamer9** [comment]
bueno no se poner fotos

**Comment by vegetagamer9** [comment]
![2015-09-19_15 31 47](https://cloud.githubusercontent.com/assets/12957778/9976610/ec7d01ba-5ee9-11e5-8067-d964e91144df.png)
![2015-09-19_15 32 08](https://cloud.githubusercontent.com/assets/12957778/9976611/ec7fc6b6-5ee9-11e5-9f8f-8e0dbe8f0c15.png)
![2015-09-19_15 33 44](https://cloud.githubusercontent.com/assets/12957778/9976612/ec877708-5ee9-11e5-873c-4175491729d9.png)

**Comment by vegetagamer9** [comment]
la que vale es la de Mario

**Comment by vegetagamer9** [comment]
antes

**Comment by vegetagamer9** [comment]
le dige a Martin que si usaba hacks

**Comment by vegetagamer9** [comment]
yo dige =hacks

**Comment by vegetagamer9** [comment]
y me dijo Si

**Comment by BlackBeemo** [comment]
esto no es ningun chat reporta bien

**Comment by vegetagamer9** [comment]
es motivo de ban

**Comment by vegetagamer9** [comment]
e.e

**Comment by vegetagamer9** [comment]
e.e

**Comment by BlackBeemo** [comment]
para de usar esto como si fuese un chat, redita tu reporte correctamente y lo abro
