### ISSUE TITLE
PORQUE CERRAIS MI TICKET SOBRE MI BANEO

### ISSUE THREAD

**Issue by MoscaDopada** [MithrandirCraft/MithrandirCraft#95]
BEEMO ES UN MOD CORRUPTO, NECESITO HABLAR CON UN ADMIN NO CON ELLA POR AQUI, ELLA SOLO SABE DECIR LA MISMA TONTERIA SIN SENTIDO Y CERRAR EL TICKET!!

**Comment by BlackBeemo** [comment]
Te recuerdo como lo hice en el otro ticket que fuiste baneado por petición de Mithrandir el admin y propietario del server.
ticket duplicado. Dirígete al ticket original, si sigues abriendo tickets de este tipo se te baneara de esta pagina.
