### ISSUE TITLE
multicuentas crickettv,mythicalmidget,meepmurp,witch_dr

### ISSUE THREAD

**Issue by BlackBeemo** [MithrandirCraft/MithrandirCraft#96]
El limite esta a 3 cuentas, te desbaneo las que me digas.

crickettv,mythicalmidget,meepmurp,witch_dr

**Comment by CricketTV** [comment]
Hola nadelina estas cometiendo un error, te explico somos 4 hermanas y todas tenemos turno para jugar en el server son diferentes personas y no me parece justo que nos baneen solo por tener una pc donde jugar

**Comment by CricketTV** [comment]
No es multicuenta y podemos demostrar que somos diferentes personas, creo que sea correcto que nos baneen, quiere decir que no podemos jugar en el server, desde una misma pc porq creeran que somos las mismas, las personas que nos conocen del server saben que somos hermanas y no estamos faltando ninguna regla ni cometiendo ilegalidades, por favor no nos baneen y demnos la posibilidad de demostrar que no somos la misma persona

**Comment by BlackBeemo** [comment]
te desbaneo crickettv,mythicalmidget,meepmurp la 4 cuenta queda baneada asta que lo demuestres

**Comment by CricketTV** [comment]
Mith ya he explicado la situación y el error que estan cometiendo no es justo por favor, haran  algo?

**Comment by CricketTV** [comment]
como te lo demuestro? me agregas a skype para que nos conoscas? yo soy la mayor tengo 18 años, estoy en la univarsidad y soy responsable de cricketTV, mi hermana la siguiente se llama indiana y tiene 12 años ella maneja la cuenta de witch_dr, la siguiente se llama adais tiene 11 y ella siempre a manejado laa cuenta de mythicalmidget desde antes que eliminaran todo y la ultima mi hermana menor se llama ariadna ella maneja meep murp en  facebook puedes encontrarlas

**Comment by MithrandirCraft** [comment]
@CricketTV Espero que no tengas la poca verguenza de estar mintiendo en esta situación.

Tendremos en cuenta que haya familias enteras jugando a partir de ahora xD

Procurad no excederos de esos 4 nombres.

@BlackBeemo puedes desbanearles.

**Comment by CricketTV** [comment]
si en verdad hay duda podemos demostrarlo por skype, no mentimos, y me atrevo a decir que empece a jugar en el server  por ellas:(
