### ISSUE TITLE
multicuenta [luigi,mario,lolo,sanic,herobrine]

### ISSUE THREAD

**Issue by BlackBeemo** [MithrandirCraft/MithrandirCraft#98]
El limite de cuentas esta en 3. Las siguientes cuentas fueron baneadas por sobrepasarlo luigi,mario,lolo,sanic,herobrine

Puedo desbanear a peticion las que indiques

**Comment by MithrandirCraft** [comment]
No banees. Desregistra. Si el exceso se repite con las mismas cuentas/IP/Jugador, aplica expulsión.
